function out = model(inputGain,coupling,horizonSec,timeStepSec,targetPositionM)
%MODEL Expose two-state controllability with exact held-input arithmetic.
arguments
    inputGain (1,1) double {mustBeReal,mustBeFinite,mustBeNonnegative} = 1
    coupling (1,1) double {mustBeReal,mustBeFinite,mustBeNonnegative} = 1
    horizonSec (1,1) double {mustBeReal,mustBeFinite,mustBePositive} = 2
    timeStepSec (1,1) double {mustBeReal,mustBeFinite,mustBePositive} = 0.05
    targetPositionM (1,1) double {mustBeReal,mustBeFinite,mustBePositive} = 1
end

minimumNonzeroGain = 0.05;
minimumNonzeroCoupling = 0.05;
maximumInputGain = 2;
maximumCoupling = 2;
minimumHorizonSec = 0.5;
maximumHorizonSec = 5;
maximumTimeStepSec = 0.1;
maximumStepCount = 5000;
maximumCommandMagnitude = 100;
if inputGain > maximumInputGain || ...
        (inputGain > 0 && inputGain < minimumNonzeroGain)
    error('P13:InputGainRange', ...
        'Input gain must be zero or between 0.05 and 2 (m/s^2)/command.');
end
if coupling > maximumCoupling || ...
        (coupling > 0 && coupling < minimumNonzeroCoupling)
    error('P13:CouplingRange', ...
        'Coupling must be zero or between 0.05 and 2.');
end
if horizonSec < minimumHorizonSec || horizonSec > maximumHorizonSec
    error('P13:HorizonRange','Maneuver time must be between 0.5 and 5 s.');
end
if timeStepSec > maximumTimeStepSec
    error('P13:DisplayResolution', ...
        'The held-command interval must not exceed 0.1 s.');
end
if targetPositionM < 0.1 || targetPositionM > 2
    error('P13:TargetRange','Target position must be between 0.1 and 2 m.');
end
stepRatio = horizonSec/timeStepSec;
if isinf(stepRatio)
    error('P13:TooManySteps', ...
        'Requested grid exceeds the 5000 held-command-step resource bound.');
end
stepCount = round(stepRatio);
alignmentTolerance = 64*eps(max(1,abs(stepRatio)));
if abs(stepRatio-stepCount) > alignmentTolerance
    error('P13:GridAlignment', ...
        'Maneuver time must be an integer multiple of the held-command interval.');
end
if stepCount > maximumStepCount
    error('P13:TooManySteps', ...
        'Requested grid exceeds the 5000 held-command-step resource bound.');
end

dampingPerSec = 0.5;
positionScaleM = 1;
rateScaleMPerSec = 1;
stateScaling = diag([1/positionScaleM 1/rateScaleMPerSec]);
continuousA = [0 coupling;0 -dampingPerSec];
continuousB = [0;inputGain];
continuousControllabilityMatrix = [continuousB continuousA*continuousB];
continuousControllabilityDeterminant = ...
    -coupling*inputGain*inputGain;

decay = exp(-dampingPerSec*timeStepSec);
rateFromRate = decay;
positionFromRate = coupling*(1-decay)/dampingPerSec;
rateFromCommand = inputGain*(1-decay)/dampingPerSec;
positionFromCommand = coupling*inputGain/dampingPerSec*( ...
    timeStepSec-(1-decay)/dampingPerSec);
discreteA = [1 positionFromRate;0 rateFromRate];
discreteB = [positionFromCommand;rateFromCommand];

reachabilityMatrix = zeros(2,stepCount);
reachabilityMatrix(:,stepCount) = discreteB;
for k = stepCount-1:-1:1
    reachabilityMatrix(:,k) = discreteA*reachabilityMatrix(:,k+1);
end
scaledReachabilityMatrix = stateScaling*reachabilityMatrix;
gramian = scaledReachabilityMatrix*scaledReachabilityMatrix.';
g11 = gramian(1,1);
g12 = gramian(1,2);
g22 = gramian(2,2);
gramianTrace = g11+g22;
gramianDeterminant = g11*g22-g12*g12;
eigenvalueSpread = hypot(g11-g22,2*g12);
lambdaMaximum = max(0,0.5*(gramianTrace+eigenvalueSpread));
lambdaMinimum = max(0,0.5*(gramianTrace-eigenvalueSpread));
singularValues = [sqrt(lambdaMaximum);sqrt(lambdaMinimum)];
rankTolerance = 128*eps(max(gramianTrace,1));
if lambdaMaximum <= rankTolerance
    controllabilityRank = 0;
elseif lambdaMinimum <= rankTolerance
    controllabilityRank = 1;
else
    controllabilityRank = 2;
end
if singularValues(2) == 0
    reachabilityConditionNumber = Inf;
else
    reachabilityConditionNumber = singularValues(1)/singularValues(2);
end

desiredPhysicalState = [targetPositionM;0];
desiredScaledState = stateScaling*desiredPhysicalState;
if controllabilityRank == 2
    dualState = [ ...
        (g22*desiredScaledState(1)-g12*desiredScaledState(2))/ ...
        gramianDeterminant; ...
        (-g12*desiredScaledState(1)+g11*desiredScaledState(2))/ ...
        gramianDeterminant];
    minimumEnergyCommand = scaledReachabilityMatrix.'*dualState;
    transferCommand = minimumEnergyCommand;
    targetReachable = true;
else
    % The requested full-state equality is infeasible. A zero command is
    % retained only as a visible failed transfer attempt, never as an optimum.
    dualState = [NaN;NaN];
    minimumEnergyCommand = NaN(stepCount,1);
    transferCommand = zeros(stepCount,1);
    targetReachable = false;
end

timeSec = (0:stepCount)'*timeStepSec;
commandTimeSec = timeSec(1:end-1);
stateTrajectory = simulateHeldCommand(transferCommand,discreteA,discreteB);
terminalState = stateTrajectory(:,end);
terminalResidual = desiredPhysicalState-terminalState;
terminalScaledResidual = desiredScaledState-stateScaling*terminalState;
if targetReachable
    commandEnergy = timeStepSec*sum(minimumEnergyCommand.^2);
    peakCommandMagnitude = max(abs(minimumEnergyCommand));
else
    commandEnergy = Inf;
    peakCommandMagnitude = Inf;
end
if targetReachable && peakCommandMagnitude > maximumCommandMagnitude
    error('P13:CommandBound', ...
        'Required command exceeds the 100-command retained-view bound.');
end

probeCommand = zeros(stepCount,1);
probeStepCount = max(1,round(0.25*stepCount));
probeCommand(1:probeStepCount) = 1;
probeStateTrajectory = simulateHeldCommand(probeCommand,discreteA,discreteB);

out = struct( ...
    'inputGainMPerSec2PerCommand',inputGain, ...
    'coupling',coupling, ...
    'dampingPerSec',dampingPerSec, ...
    'horizonSec',horizonSec, ...
    'timeStepSec',timeStepSec, ...
    'targetPositionM',targetPositionM, ...
    'positionScaleM',positionScaleM, ...
    'rateScaleMPerSec',rateScaleMPerSec, ...
    'stateScaling',stateScaling, ...
    'continuousA',continuousA, ...
    'continuousB',continuousB, ...
    'continuousControllabilityMatrix',continuousControllabilityMatrix, ...
    'continuousControllabilityDeterminant', ...
    continuousControllabilityDeterminant, ...
    'discreteA',discreteA, ...
    'discreteB',discreteB, ...
    'reachabilityMatrix',reachabilityMatrix, ...
    'scaledReachabilityMatrix',scaledReachabilityMatrix, ...
    'gramian',gramian, ...
    'gramianTrace',gramianTrace, ...
    'gramianDeterminant',gramianDeterminant, ...
    'singularValues',singularValues, ...
    'minimumSingularValue',singularValues(2), ...
    'reachabilityConditionNumber',reachabilityConditionNumber, ...
    'rankTolerance',rankTolerance, ...
    'controllabilityRank',controllabilityRank, ...
    'targetReachable',targetReachable, ...
    'desiredPhysicalState',desiredPhysicalState, ...
    'desiredScaledState',desiredScaledState, ...
    'dualState',dualState, ...
    'minimumEnergyCommand',minimumEnergyCommand, ...
    'transferCommand',transferCommand, ...
    'stateTrajectory',stateTrajectory, ...
    'terminalState',terminalState, ...
    'terminalResidual',terminalResidual, ...
    'terminalScaledResidual',terminalScaledResidual, ...
    'terminalResidualNorm',hypot(terminalScaledResidual(1), ...
    terminalScaledResidual(2)), ...
    'commandEnergyCommand2Sec',commandEnergy, ...
    'peakCommandMagnitude',peakCommandMagnitude, ...
    'probeCommand',probeCommand, ...
    'probeStateTrajectory',probeStateTrajectory, ...
    'probeStepCount',probeStepCount, ...
    'timeSec',timeSec, ...
    'commandTimeSec',commandTimeSec, ...
    'stepCount',stepCount, ...
    'maximumStepCount',maximumStepCount, ...
    'maximumCommandMagnitude',maximumCommandMagnitude);
end

function stateTrajectory = simulateHeldCommand(command,discreteA,discreteB)
stepCount = numel(command);
stateTrajectory = zeros(2,stepCount+1);
for k = 1:stepCount
    stateTrajectory(:,k+1) = discreteA*stateTrajectory(:,k)+ ...
        discreteB*command(k);
end
end
