function run_checks
%RUN_CHECKS Independent controllability identities, limits, and recovery.
tolerance = 5e-11;

baselineA = model(1,1,2,0.05);
baselineB = model(1,1,2,0.05);
expectedStateScaling = eye(2);
assert(isequaln(baselineA,baselineB), ...
    'Identical inputs must produce identical matrices, commands, and states.');
assert(baselineA.dampingPerSec == 0.5 && ...
    baselineA.positionScaleM == 1 && ...
    baselineA.rateScaleMPerSec == 1 && ...
    max(abs(baselineA.stateScaling(:)-expectedStateScaling(:))) == 0 && ...
    baselineA.targetPositionM == 1, ...
    'The damping, normalized state scales, and target must stay explicit.');

expectedA = [0 1;0 -0.5];
expectedB = [0;1];
expectedContinuousColumns = [expectedB expectedA*expectedB];
assert(max(abs(baselineA.continuousA(:)-expectedA(:))) == 0 && ...
    max(abs(baselineA.continuousB-expectedB)) == 0 && ...
    max(abs(baselineA.continuousControllabilityMatrix(:)- ...
    expectedContinuousColumns(:))) == 0 && ...
    baselineA.continuousControllabilityDeterminant == -1, ...
    'The continuous input direction and its propagated direction must be visible.');

decay = exp(-0.5*0.05);
expectedAd = [1 2*(1-decay);0 decay];
expectedBd = [2*(0.05-2*(1-decay));2*(1-decay)];
assert(max(abs(baselineA.discreteA(:)-expectedAd(:))) < tolerance && ...
    max(abs(baselineA.discreteB-expectedBd)) < tolerance, ...
    'Exact zero-order-held matrices must match independent scalar formulas.');

reachability = baselineA.reachabilityMatrix;
assert(max(abs(reachability(:,end)-baselineA.discreteB)) == 0, ...
    'The newest command column must equal Bd.');
for k = 1:baselineA.stepCount-1
    assert(max(abs(reachability(:,k)- ...
        baselineA.discreteA*reachability(:,k+1))) < tolerance, ...
        'Each earlier reachability column must propagate once through Ad.');
end
for k = 1:baselineA.stepCount
    propagationCount = baselineA.stepCount-k;
    expectedRateEffect = 2*(1-decay)*decay^propagationCount;
    expectedPositionEffect = 4*(0.5*0.05- ...
        decay^propagationCount*(1-decay));
    assert(abs(reachability(1,k)-expectedPositionEffect) < tolerance && ...
        abs(reachability(2,k)-expectedRateEffect) < tolerance, ...
        'Every reachability column must match the independent closed form.');
end
expectedGramian = baselineA.scaledReachabilityMatrix* ...
    baselineA.scaledReachabilityMatrix.';
assert(max(abs(baselineA.gramian(:)-expectedGramian(:))) < tolerance && ...
    baselineA.gramianDeterminant > 0 && ...
    baselineA.minimumSingularValue > 0 && ...
    baselineA.controllabilityRank == 2, ...
    'The baseline reachability Gramian must span both scaled state directions.');

reconstructedTarget = baselineA.scaledReachabilityMatrix* ...
    baselineA.minimumEnergyCommand;
assert(max(abs(reconstructedTarget-baselineA.desiredScaledState)) < tolerance && ...
    baselineA.targetReachable && ...
    baselineA.terminalResidualNorm < tolerance, ...
    'The transparent minimum-energy command must reconstruct the target.');
for k = 1:baselineA.stepCount
    expectedNextState = baselineA.discreteA* ...
        baselineA.stateTrajectory(:,k)+baselineA.discreteB* ...
        baselineA.minimumEnergyCommand(k);
    assert(max(abs(baselineA.stateTrajectory(:,k+1)- ...
        expectedNextState)) < tolerance, ...
        'Every state sample must satisfy the exact held-command recurrence.');
end
nullCommand = zeros(baselineA.stepCount,1);
column1 = baselineA.scaledReachabilityMatrix(:,1);
column2 = baselineA.scaledReachabilityMatrix(:,2);
column3 = baselineA.scaledReachabilityMatrix(:,3);
nullCommand(1) = column2(1)*column3(2)-column2(2)*column3(1);
nullCommand(2) = column3(1)*column1(2)-column3(2)*column1(1);
nullCommand(3) = column1(1)*column2(2)-column1(2)*column2(1);
nullCommand = nullCommand/norm(nullCommand);
perturbedCommand = baselineA.minimumEnergyCommand+nullCommand;
assert(max(abs(baselineA.scaledReachabilityMatrix*nullCommand)) < tolerance && ...
    abs(baselineA.minimumEnergyCommand.'*nullCommand) < tolerance && ...
    0.05*sum(perturbedCommand.^2) > ...
    baselineA.commandEnergyCommand2Sec+0.04, ...
    'The target command must be orthogonal to a reachable-matrix null direction.');
assert(abs(baselineA.commandEnergyCommand2Sec-1.65087224848343) < 1e-10 && ...
    abs(baselineA.peakCommandMagnitude-1.50331356506878) < 1e-10 && ...
    abs(baselineA.minimumSingularValue-0.116210035070149) < 1e-11, ...
    'Baseline effort and scaled reachability metrics must stay deterministic.');

inputGains = [0.25 0.5 1 1.5 2];
gainSingularValues = zeros(size(inputGains));
gainEnergies = zeros(size(inputGains));
gainPeaks = zeros(size(inputGains));
for k = 1:numel(inputGains)
    changed = model(inputGains(k),1,2,0.05);
    gainSingularValues(k) = changed.minimumSingularValue;
    gainEnergies(k) = changed.commandEnergyCommand2Sec;
    gainPeaks(k) = changed.peakCommandMagnitude;
    assert(changed.controllabilityRank == 2 && ...
        changed.coupling == 1 && changed.horizonSec == 2 && ...
        changed.timeStepSec == 0.05, ...
        'The input-gain sweep must preserve coupling, time, and rank.');
    assert(abs(gainSingularValues(k)-inputGains(k)* ...
        baselineA.minimumSingularValue) < tolerance && ...
        abs(gainEnergies(k)-baselineA.commandEnergyCommand2Sec/ ...
        inputGains(k)^2) < tolerance && ...
        abs(gainPeaks(k)-baselineA.peakCommandMagnitude/ ...
        inputGains(k)) < tolerance, ...
        'Input gain must scale reachability, energy, and peak command independently.');
end
assert(all(diff(gainSingularValues) > 0) && ...
    all(diff(gainEnergies) < 0) && all(diff(gainPeaks) < 0), ...
    'More actuator effectiveness must improve scaled reach and reduce effort.');

maneuverTimesSec = [0.5 1 2 3 4];
timeSingularValues = zeros(size(maneuverTimesSec));
timeEnergies = zeros(size(maneuverTimesSec));
timePeaks = zeros(size(maneuverTimesSec));
for k = 1:numel(maneuverTimesSec)
    changed = model(1,1,maneuverTimesSec(k),0.05);
    timeSingularValues(k) = changed.minimumSingularValue;
    timeEnergies(k) = changed.commandEnergyCommand2Sec;
    timePeaks(k) = changed.peakCommandMagnitude;
    assert(changed.inputGainMPerSec2PerCommand == 1 && ...
        changed.coupling == 1 && changed.dampingPerSec == 0.5 && ...
        changed.timeStepSec == 0.05 && changed.targetPositionM == 1 && ...
        changed.controllabilityRank == 2, ...
        'The time sweep must preserve model, input, interval, target, and rank.');
end
assert(all(diff(timeSingularValues) > 0) && ...
    all(diff(timeEnergies) < 0) && all(diff(timePeaks) < 0) && ...
    timeEnergies(1) > 50*timeEnergies(3), ...
    'More maneuver time must strengthen reachability and reduce effort.');

broken = model(1,0,2,0.05);
recovered = model(1,1,2,0.05);
assert(broken.controllabilityRank == 1 && ...
    ~broken.targetReachable && ...
    broken.continuousControllabilityDeterminant == 0 && ...
    broken.minimumSingularValue == 0 && ...
    isinf(broken.reachabilityConditionNumber), ...
    'Disconnected coupling must remove exactly one reachable direction.');
assert(max(abs(broken.probeStateTrajectory(1,:))) == 0 && ...
    max(abs(broken.probeStateTrajectory(2,:)- ...
    recovered.probeStateTrajectory(2,:))) == 0 && ...
    max(abs(recovered.probeStateTrajectory(1,:))) > 0.1, ...
    'The broken probe must retain rate response while freezing position.');
assert(all(isnan(broken.minimumEnergyCommand)) && ...
    max(abs(broken.transferCommand)) == 0 && ...
    isinf(broken.commandEnergyCommand2Sec) && ...
    isinf(broken.peakCommandMagnitude) && ...
    broken.terminalResidual(1) == 1 && ...
    recovered.targetReachable && ...
    recovered.controllabilityRank == 2 && ...
    recovered.terminalResidualNorm < tolerance, ...
    'Restoring coupling must recover the position target from a fresh call.');

noActuator = model(0,1,2,0.05);
assert(noActuator.controllabilityRank == 0 && ...
    ~noActuator.targetReachable && ...
    max(abs(noActuator.reachabilityMatrix(:))) == 0 && ...
    max(abs(noActuator.probeStateTrajectory(:))) == 0 && ...
    noActuator.terminalResidualNorm == 1, ...
    'Zero input effectiveness must be the rank-zero limiting case.');

assertAnyError(@() model(NaN,1,2,0.05), ...
    'A nonfinite input gain must be rejected.');
assertAnyError(@() model([1 2],1,2,0.05), ...
    'A nonscalar input gain must be rejected.');
assertAnyError(@() model(-1,1,2,0.05), ...
    'A negative input gain must be rejected.');
assertAnyError(@() model(1,Inf,2,0.05), ...
    'A nonfinite coupling must be rejected.');
assertAnyError(@() model(1,1+1i,2,0.05), ...
    'A complex coupling must be rejected.');
assertAnyError(@() model(1,1,NaN,0.05), ...
    'A nonfinite maneuver time must be rejected.');
assertAnyError(@() model(1,1,2,Inf), ...
    'A nonfinite held-command interval must be rejected.');
assertAnyError(@() model(1,1,2,0), ...
    'A zero held-command interval must be rejected.');
assertAnyError(@() model(1,1,2,0.05,1+1i), ...
    'A complex target must be rejected.');
assertErrorId(@() model(2.1,1,2,0.05), ...
    'P13:InputGainRange','Excessive input gain must be rejected.');
assertErrorId(@() model(0.01,1,2,0.05), ...
    'P13:InputGainRange','A numerically misleading tiny gain must be rejected.');
assertErrorId(@() model(1,2.1,2,0.05), ...
    'P13:CouplingRange','Excessive coupling must be rejected.');
assertErrorId(@() model(1,0.01,2,0.05), ...
    'P13:CouplingRange','A numerically misleading tiny coupling must be rejected.');
assertErrorId(@() model(1,1,0.49,0.05), ...
    'P13:HorizonRange','A too-short maneuver must be rejected.');
assertErrorId(@() model(1,1,5.1,0.05), ...
    'P13:HorizonRange','An excessive maneuver must be rejected.');
assertErrorId(@() model(1,1,2,0.11), ...
    'P13:DisplayResolution','An under-resolved interval must be rejected.');
assertErrorId(@() model(1,1,2,0.03), ...
    'P13:GridAlignment','A partial held-command interval must be rejected.');
assertErrorId(@() model(1,1,2,0.05,0.09), ...
    'P13:TargetRange','An undersized target must be rejected.');
assertErrorId(@() model(1,1,2,0.05,2.1), ...
    'P13:TargetRange','An excessive target must be rejected.');
assertErrorId(@() model(1,1,5,1e-6), ...
    'P13:TooManySteps','An oversized grid must be rejected before allocation.');
assertErrorId(@() model(0.05,1,0.5,0.05), ...
    'P13:CommandBound','An excessive reconstructed command must be bounded.');
boundedGrid = model(1,1,5,0.001);
assert(boundedGrid.stepCount == 5000 && ...
    all(isfinite(boundedGrid.stateTrajectory(:))) && ...
    boundedGrid.terminalResidualNorm < tolerance, ...
    'The largest accepted grid must remain finite and reconstruct the target.');

disp(['P13 checks passed: exact reachability columns, two isolated ' ...
    'levers, broken coupling, recovery, malformed inputs, and bounds.']);
end

function assertAnyError(operation,message)
didError = false;
try
    operation();
catch
    didError = true;
end
assert(didError,message);
end

function assertErrorId(operation,expectedIdentifier,message)
actualIdentifier = '';
try
    operation();
catch exception
    actualIdentifier = exception.identifier;
end
assert(strcmp(actualIdentifier,expectedIdentifier),message);
end
