function run_checks
%RUN_CHECKS Independent proportional-loop invariants, limits, and recovery.
tolerance = 2e-12;

baselineA = model(2,1,1,1,0,-1,5,0.01);
baselineB = model(2,1,1,1,0,-1,5,0.01);
assert(isequaln(baselineA,baselineB), ...
    'Identical inputs must produce identical deterministic outputs.');
assert(baselineA.outputM(1) == 0 && baselineA.trackingErrorM(1) == 1 && ...
    baselineA.controlCommand(1) == 2, ...
    'The baseline must preserve its initial output, error, and command.');

expectedPole = -(1+1*2)/1;
expectedTimeConstant = 1/3;
expectedSteadyOutput = 2/3;
expectedSteadyError = 1/3;
assert(abs(baselineA.closedLoopPolePerSec-expectedPole) < tolerance, ...
    'Negative feedback must move the pole to -(1+G*Kp)/tau.');
assert(abs(baselineA.closedLoopTimeConstantSec-expectedTimeConstant) < tolerance, ...
    'Closed-loop time constant must equal tau/(1+G*Kp).');
assert(abs(baselineA.predictedSteadyStateOutputM-expectedSteadyOutput) < tolerance && ...
    abs(baselineA.predictedSteadyStateErrorM-expectedSteadyError) < tolerance, ...
    'Steady output and error must independently satisfy the feedback balance.');
assert(abs(expectedSteadyOutput- ...
    baselineA.plantGainMPerCommand*baselineA.proportionalGain* ...
    expectedSteadyError) < tolerance, ...
    'At steady state, plant output must equal G*Kp times residual error.');
assert(abs(baselineA.initialOutputRateMPerSec-2) < tolerance, ...
    'The initial plant rate must equal (-y0+G*Kp*(r-y0))/tau.');

expectedBaseline = expectedSteadyOutput + ...
    (0-expectedSteadyOutput)*exp(expectedPole*baselineA.t);
assert(max(abs(baselineA.outputM-expectedBaseline)) < tolerance, ...
    'Every baseline sample must match the independent closed-form response.');
oneTimeConstant = model(2,1,1,1,0,-1,expectedTimeConstant,0.001);
expectedOneTimeConstantOutput = expectedSteadyOutput*(1-exp(-1));
assert(abs(oneTimeConstant.outputM(end)-expectedOneTimeConstantOutput) < tolerance, ...
    'One closed-loop time constant must traverse exactly 1-exp(-1) of the change.');

initializedAtReference = model(2,1,1,1,1,-1,1,0.01);
expectedInitializedOutput = expectedSteadyOutput + ...
    (1-expectedSteadyOutput)*exp(expectedPole*initializedAtReference.t);
assert(max(abs(initializedAtReference.outputM-expectedInitializedOutput)) < tolerance && ...
    initializedAtReference.initialControlCommand == 0 && ...
    abs(initializedAtReference.initialOutputRateMPerSec+1) < tolerance, ...
    ['A nonzero initial output and constant reference must retain both the ' ...
    'homogeneous response and the forced closed-loop response.']);

lowGain = model(0.5,1,1,1,0,-1,5,0.005);
highGain = model(8,1,1,1,0,-1,5,0.005);
assert(highGain.closedLoopTimeConstantSec < lowGain.closedLoopTimeConstantSec && ...
    highGain.predictedSteadyStateErrorM < lowGain.predictedSteadyStateErrorM, ...
    'Moving only Kp upward must speed response and reduce proportional offset.');
assert(highGain.initialControlCommand > lowGain.initialControlCommand, ...
    'The same Kp change must increase initial control effort.');
assert(highGain.plantTimeConstantSec == lowGain.plantTimeConstantSec && ...
    highGain.referenceM == lowGain.referenceM && ...
    highGain.maxInterval == lowGain.maxInterval, ...
    'The gain lever must preserve plant time constant, reference, and interval.');

fastPlant = model(2,0.25,1,1,0,-1,5,0.005);
slowPlant = model(2,3,1,1,0,-1,5,0.005);
assert(abs(slowPlant.closedLoopTimeConstantSec/ ...
    fastPlant.closedLoopTimeConstantSec-12) < tolerance, ...
    'Increasing only tau by twelve must stretch closed-loop time by twelve.');
assert(abs(slowPlant.predictedSteadyStateOutputM- ...
    fastPlant.predictedSteadyStateOutputM) < tolerance && ...
    slowPlant.initialControlCommand == fastPlant.initialControlCommand, ...
    'The tau lever must preserve steady output and initial command.');
assert(slowPlant.proportionalGain == fastPlant.proportionalGain && ...
    slowPlant.referenceM == fastPlant.referenceM && ...
    slowPlant.maxInterval == fastPlant.maxInterval, ...
    'The time-constant lever must preserve gain, reference, and interval.');

zeroGain = model(0,1,1,1,0,-1,3,0.01);
assert(all(zeroGain.outputM == 0) && all(zeroGain.controlCommand == 0) && ...
    all(zeroGain.trackingErrorM == 1), ...
    'Zero proportional gain must leave a zero-state plant uncommanded.');
zeroState = model(5,2,1,0,0,-1,3,0.01);
assert(all(zeroState.outputM == 0) && all(zeroState.controlCommand == 0), ...
    'Zero reference and zero output must remain at equilibrium.');
decay = model(0,2,1,0,1,-1,2,0.01);
assert(abs(decay.outputM(end)-exp(-1)) < tolerance, ...
    'With Kp=0, a nonzero initial state must decay with the open-loop tau.');
positiveReference = model(2,1,1,1,0,-1,3,0.01);
negativeReference = model(2,1,1,-1,0,-1,3,0.01);
assert(max(abs(positiveReference.outputM+negativeReference.outputM)) < tolerance && ...
    max(abs(positiveReference.controlCommand+ ...
    negativeReference.controlCommand)) < tolerance, ...
    'The linear loop must preserve reference-sign symmetry.');

marginal = model(1,1,1,1,0,1,2,0.01);
assert(marginal.closedLoopPolePerSec == 0 && ...
    max(abs(marginal.outputM-marginal.t)) < tolerance && ...
    isinf(marginal.closedLoopTimeConstantSec), ...
    'At reversed-sign G*Kp=1, the zero-pole boundary must produce a ramp.');
nearMarginal = model(1+1e-10,1,1,1,0,1,2,0.01);
expectedNearMarginalEnd = (1+1e-10)* ...
    expm1(nearMarginal.closedLoopPolePerSec*2)/ ...
    nearMarginal.closedLoopPolePerSec;
assert(isfinite(nearMarginal.outputM(end)) && ...
    abs(nearMarginal.outputM(end)-expectedNearMarginalEnd) < 1e-10, ...
    'Near the zero-pole boundary, propagation must avoid equilibrium cancellation.');
aboveMarginal = model(1+eps,1,1,1,0,1,1,0.01);
belowMarginal = model(1-eps,1,1,1,0,1,1,0.01);
expectedAboveEnd = (1+eps)*expm1(aboveMarginal.closedLoopPolePerSec)/ ...
    aboveMarginal.closedLoopPolePerSec;
expectedBelowEnd = (1-eps)*expm1(belowMarginal.closedLoopPolePerSec)/ ...
    belowMarginal.closedLoopPolePerSec;
assert(abs(aboveMarginal.outputM(end)-expectedAboveEnd) < 1e-12 && ...
    abs(belowMarginal.outputM(end)-expectedBelowEnd) < 1e-12, ...
    'The nearest floating-point poles on both sides of zero must remain continuous.');
broken = model(2,1,1,1,0,1,4,0.01);
recovered = model(2,1,1,1,0,-1,4,0.01);
assert(~broken.closedLoopStable && broken.closedLoopPolePerSec == 1 && ...
    broken.outputM(end) > 100, ...
    'Adding measurement with G*Kp>1 must expose positive-pole growth.');
assert(max(abs(broken.controlCommand-2*(1+broken.outputM))) < tolerance, ...
    'The broken polarity must command Kp*(r+y) across the trajectory.');
brokenPlantResidual = broken.plantTimeConstantSec*broken.outputRateMPerSec - ...
    (-broken.outputM+broken.plantGainMPerCommand*broken.controlCommand);
assert(max(abs(brokenPlantResidual)) < tolerance, ...
    'Reported rates must satisfy tau*y'' = -y+G*u across the trajectory.');
assert(recovered.closedLoopStable && recovered.closedLoopPolePerSec == -3 && ...
    recovered.maxAbsOutputM < 1 && recovered.finalTrackingErrorM > 0, ...
    'Restoring measurement subtraction must recover bounded P-only tracking.');

assertAnyError(@() model(NaN,1,1,1,0,-1,5,0.01), ...
    'A nonfinite proportional gain must be rejected.');
assertAnyError(@() model(2,Inf,1,1,0,-1,5,0.01), ...
    'A nonfinite time constant must be rejected.');
assertAnyError(@() model(2,1,1+1i,1,0,-1,5,0.01), ...
    'A nonreal plant gain must be rejected.');
assertAnyError(@() model(2,1,1,[1 2],0,-1,5,0.01), ...
    'A nonscalar reference must be rejected.');
assertAnyError(@() model(-1,1,1,1,0,-1,5,0.01), ...
    'A negative proportional gain must be rejected.');
assertAnyError(@() model(2,1,1,1,0,-1,0,0.01), ...
    'A nonpositive duration must be rejected.');
assertAnyError(@() model(2,1,1,1,0,-1,5,0), ...
    'A nonpositive interval must be rejected.');
assertErrorId(@() model(51,1,1,1,0,-1,5,0.001), ...
    'P05:GainRange','An out-of-contract proportional gain must be rejected.');
assertErrorId(@() model(2,0.01,1,1,0,-1,1,0.001), ...
    'P05:TimeConstantRange','An out-of-contract time constant must be rejected.');
assertErrorId(@() model(2,1,0.01,1,0,-1,5,0.01), ...
    'P05:PlantGainRange','An out-of-contract plant gain must be rejected.');
assertErrorId(@() model(2,1,1,101,0,-1,5,0.01), ...
    'P05:SignalRange','An out-of-contract reference must be rejected.');
assertErrorId(@() model(2,1,1,1,0,0,5,0.01), ...
    'P05:FeedbackSign','An ambiguous feedback sign must be rejected.');
assertErrorId(@() model(2,1,1,1,0,-1,101,0.01), ...
    'P05:HorizonRange','An excessive horizon must be rejected.');
assertErrorId(@() model(8,0.25,1,1,0,-1,2,0.01), ...
    'P05:TimeResolution','An under-resolved visible transient must be rejected.');
assertErrorId(@() model(50,0.05,10,1,0,1,1,0.0001), ...
    'P05:ResponseBound','An excessive positive-feedback exponent must be rejected.');

acceptedResolution = model(8,0.25,1,1,0,-1,1,0.0027);
assert(abs(acceptedResolution.closedLoopPolePerSec)* ...
    acceptedResolution.maxInterval < 0.1 && ...
    max(abs(acceptedResolution.outputM- ...
    acceptedResolution.predictedSteadyStateOutputM*(1- ...
    exp(acceptedResolution.closedLoopPolePerSec*acceptedResolution.t)))) < tolerance, ...
    'The accepted display-resolution boundary must retain exact response samples.');
nonIntegerGrid = model(2,1,1,1,0,-1,0.033,0.011);
assert(nonIntegerGrid.sampleCount == 4 && ...
    all(diff(nonIntegerGrid.t) > 0) && nonIntegerGrid.t(end) == 0.033, ...
    'An integer interval ratio must not create a duplicate final timestamp.');
shortHorizon = model(2,1,1,1,0,-1,0.02,2);
assert(shortHorizon.sampleCount == 2 && ...
    abs(shortHorizon.maxInterval-0.02) < tolerance, ...
    'A clipped endpoint interval must report the interval actually used.');
atResourceLimit = model(2,1,1,1,0,-1,20,0.001);
assert(atResourceLimit.sampleCount == 20001, ...
    'The declared maximum calculation grid must remain accepted.');
assertErrorId(@() model(2,1,1,1,0,-1,20.001,0.001), ...
    'P05:TooManySamples','An excessive calculation grid must be rejected.');

disp('P05 checks passed: loop invariants, levers, limits, sign recovery, and bounds.');
end

function assertAnyError(operation,message)
didError = false;
try
    operation();
catch
    didError = true;
end
assert(didError,message);
end

function assertErrorId(operation,expectedIdentifier,message)
actualIdentifier = '';
try
    operation();
catch exception
    actualIdentifier = exception.identifier;
end
assert(strcmp(actualIdentifier,expectedIdentifier),message);
end
