function out = model(assumedPositionNoiseStdM, ...
    assumedProcessAccelerationStdMPerSec2,positionOutlierM,noiseSeed, ...
    simulationDurationSec,timeStepSec)
%MODEL Fuse two noisy position sensors with a transparent Kalman filter.
arguments
    assumedPositionNoiseStdM (1,1) double ...
        {mustBeReal,mustBeFinite,mustBePositive} = 0.35
    assumedProcessAccelerationStdMPerSec2 (1,1) double ...
        {mustBeReal,mustBeFinite,mustBePositive} = 0.08
    positionOutlierM (1,1) double ...
        {mustBeReal,mustBeFinite,mustBeNonnegative} = 0
    noiseSeed (1,1) double ...
        {mustBeReal,mustBeFinite,mustBeInteger,mustBePositive} = 1601
    simulationDurationSec (1,1) double ...
        {mustBeReal,mustBeFinite,mustBePositive} = 20
    timeStepSec (1,1) double ...
        {mustBeReal,mustBeFinite,mustBePositive} = 0.05
end

minimumPositionNoiseStdM = 0.1;
maximumPositionNoiseStdM = 0.9;
minimumProcessAccelerationStdMPerSec2 = 0.01;
maximumProcessAccelerationStdMPerSec2 = 0.5;
maximumPositionOutlierM = 4;
maximumNoiseSeed = 1000000;
minimumSimulationDurationSec = 15;
maximumSimulationDurationSec = 30;
maximumTimeStepSec = 0.1;
maximumStepCount = 5000;
if assumedPositionNoiseStdM < minimumPositionNoiseStdM || ...
        assumedPositionNoiseStdM > maximumPositionNoiseStdM
    error('P16:PositionNoiseRange', ...
        'Assumed position-sensor noise must be between 0.1 and 0.9 m.');
end
if assumedProcessAccelerationStdMPerSec2 < ...
        minimumProcessAccelerationStdMPerSec2 || ...
        assumedProcessAccelerationStdMPerSec2 > ...
        maximumProcessAccelerationStdMPerSec2
    error('P16:ProcessNoiseRange', ...
        'Assumed process-acceleration noise must be between 0.01 and 0.5 m/s^2.');
end
if positionOutlierM > maximumPositionOutlierM
    error('P16:OutlierRange', ...
        'Position-sensor outlier magnitude must be between 0 and 4 m.');
end
if noiseSeed > maximumNoiseSeed
    error('P16:SeedRange', ...
        'Noise seed must be an integer between 1 and 1000000.');
end
if simulationDurationSec < minimumSimulationDurationSec || ...
        simulationDurationSec > maximumSimulationDurationSec
    error('P16:DurationRange', ...
        'Simulation duration must be between 15 and 30 s.');
end
if timeStepSec > maximumTimeStepSec
    error('P16:DisplayResolution', ...
        'The sample interval must not exceed 0.1 s.');
end

stepRatio = simulationDurationSec/timeStepSec;
if isinf(stepRatio)
    error('P16:TooManySteps', ...
        'Requested grid exceeds the 5000-step resource bound.');
end
stepCount = round(stepRatio);
alignmentTolerance = 64*eps(max(1,abs(stepRatio)));
if abs(stepRatio-stepCount) > alignmentTolerance
    error('P16:GridAlignment', ...
        'Simulation duration must be an integer multiple of the sample interval.');
end
if stepCount > maximumStepCount
    error('P16:TooManySteps', ...
        'Requested grid exceeds the 5000-step resource bound.');
end

% Retain the exact sampled P15 cart: p_dot=v, v_dot=-d*v+u.
dampingPerSec = 0.5;
decay = exp(-dampingPerSec*timeStepSec);
positionFromRateSec = (1-decay)/dampingPerSec;
positionFromAccelerationSec2 = ...
    (timeStepSec-positionFromRateSec)/dampingPerSec;
discreteA = [1 positionFromRateSec;0 decay];
accelerationColumn = ...
    [positionFromAccelerationSec2;positionFromRateSec];
discreteB = accelerationColumn;
measurementMatrix = [1 0;1 0];
identityState = eye(2);
actualPositionNoiseStdM = 0.35;
actualBackupPositionNoiseStdM = 0.8;
actualProcessAccelerationStdMPerSec2 = 0.08;
assumedBackupPositionNoiseStdM = actualBackupPositionNoiseStdM;
processCovariance = accelerationColumn*accelerationColumn.'* ...
    assumedProcessAccelerationStdMPerSec2^2;
measurementCovariance = diag([assumedPositionNoiseStdM^2, ...
    assumedBackupPositionNoiseStdM^2]);

sampleCount = stepCount+1;
timeSec = (0:stepCount)*timeStepSec;
commandAccelerationMPerSec2 = zeros(1,sampleCount);
commandAccelerationMPerSec2(timeSec >= 2 & timeSec < 6) = 0.3;
commandAccelerationMPerSec2(timeSec >= 10 & timeSec < 14) = -0.2;
processNoiseShape = deterministicNormal(stepCount,noiseSeed);
primaryNoiseShape = deterministicNormal(sampleCount,noiseSeed+1);
backupNoiseShape = deterministicNormal(sampleCount,noiseSeed+2);
actualProcessAccelerationNoiseMPerSec2 = ...
    actualProcessAccelerationStdMPerSec2*processNoiseShape;
actualPrimaryPositionNoiseM = actualPositionNoiseStdM*primaryNoiseShape;
actualBackupPositionNoiseM = ...
    actualBackupPositionNoiseStdM*backupNoiseShape;
outlierNominalTimeSec = 12;
outlierIndex = round(outlierNominalTimeSec/timeStepSec)+1;
outlierTimeSec = timeSec(outlierIndex);
outlierSequenceM = zeros(1,sampleCount);
outlierSequenceM(outlierIndex) = positionOutlierM;

trueState = zeros(2,sampleCount);
priorEstimate = zeros(2,sampleCount);
posteriorEstimate = zeros(2,sampleCount);
measurement = zeros(2,sampleCount);
innovation = zeros(2,sampleCount);
innovationCovariance = zeros(2,2,sampleCount);
kalmanGain = zeros(2,2,sampleCount);
priorCovariance = zeros(2,2,sampleCount);
posteriorCovariance = zeros(2,2,sampleCount);
normalizedInnovationSquared = zeros(1,sampleCount);
trueState(:,1) = [0;0];
priorEstimate(:,1) = [-0.8;0.8];
priorCovariance(:,:,1) = diag([1.5^2,0.8^2]);

for k = 1:sampleCount
    measurement(:,k) = measurementMatrix*trueState(:,k)+ ...
        [actualPrimaryPositionNoiseM(k)+outlierSequenceM(k); ...
        actualBackupPositionNoiseM(k)];
    innovation(:,k) = measurement(:,k)- ...
        measurementMatrix*priorEstimate(:,k);
    innovationCovariance(:,:,k) = ...
        measurementMatrix*priorCovariance(:,:,k)*measurementMatrix.'+ ...
        measurementCovariance;
    innovationCovarianceInverse = ...
        inverseSymmetricTwoByTwo(innovationCovariance(:,:,k));
    kalmanGain(:,:,k) = priorCovariance(:,:,k)* ...
        measurementMatrix.'*innovationCovarianceInverse;
    posteriorEstimate(:,k) = priorEstimate(:,k)+ ...
        kalmanGain(:,:,k)*innovation(:,k);
    covarianceCorrection = identityState- ...
        kalmanGain(:,:,k)*measurementMatrix;
    posteriorCovariance(:,:,k) = ...
        covarianceCorrection*priorCovariance(:,:,k)* ...
        covarianceCorrection.'+kalmanGain(:,:,k)* ...
        measurementCovariance*kalmanGain(:,:,k).';
    normalizedInnovationSquared(k) = innovation(:,k).'* ...
        innovationCovarianceInverse*innovation(:,k);
    if k <= stepCount
        trueState(:,k+1) = discreteA*trueState(:,k)+ ...
            discreteB*commandAccelerationMPerSec2(k)+ ...
            accelerationColumn*actualProcessAccelerationNoiseMPerSec2(k);
        priorEstimate(:,k+1) = discreteA*posteriorEstimate(:,k)+ ...
            discreteB*commandAccelerationMPerSec2(k);
        priorCovariance(:,:,k+1) = discreteA* ...
            posteriorCovariance(:,:,k)*discreteA.'+processCovariance;
    end
end

estimationError = trueState-posteriorEstimate;
posteriorPositionStdM = ...
    sqrt(reshape(posteriorCovariance(1,1,:),1,sampleCount));
posteriorRateStdMPerSec = ...
    sqrt(reshape(posteriorCovariance(2,2,:),1,sampleCount));
tailMask = timeSec >= simulationDurationSec-5;
positionErrorRmsTailM = sqrt(mean(estimationError(1,tailMask).^2));
rateErrorRmsTailMPerSec = sqrt(mean(estimationError(2,tailMask).^2));
meanNormalizedInnovationSquaredTail = ...
    mean(normalizedInnovationSquared(tailMask));
steadyPrimaryPositionGain = kalmanGain(1,1,end);
steadyBackupPositionGain = kalmanGain(1,2,end);
steadyRateGainFromPrimaryPerSec = kalmanGain(2,1,end);

out = struct( ...
    'assumedPositionNoiseStdM',assumedPositionNoiseStdM, ...
    'assumedProcessAccelerationStdMPerSec2', ...
    assumedProcessAccelerationStdMPerSec2, ...
    'positionOutlierM',positionOutlierM, ...
    'noiseSeed',noiseSeed, ...
    'simulationDurationSec',simulationDurationSec, ...
    'timeStepSec',timeStepSec, ...
    'actualPositionNoiseStdM',actualPositionNoiseStdM, ...
    'actualBackupPositionNoiseStdM',actualBackupPositionNoiseStdM, ...
    'actualProcessAccelerationStdMPerSec2', ...
    actualProcessAccelerationStdMPerSec2, ...
    'assumedBackupPositionNoiseStdM',assumedBackupPositionNoiseStdM, ...
    'dampingPerSec',dampingPerSec, ...
    'decay',decay, ...
    'positionFromRateSec',positionFromRateSec, ...
    'positionFromAccelerationSec2',positionFromAccelerationSec2, ...
    'discreteA',discreteA, ...
    'discreteB',discreteB, ...
    'accelerationColumn',accelerationColumn, ...
    'measurementMatrix',measurementMatrix, ...
    'processCovariance',processCovariance, ...
    'measurementCovariance',measurementCovariance, ...
    'timeSec',timeSec, ...
    'commandAccelerationMPerSec2',commandAccelerationMPerSec2, ...
    'processNoiseShape',processNoiseShape, ...
    'primaryNoiseShape',primaryNoiseShape, ...
    'backupNoiseShape',backupNoiseShape, ...
    'actualProcessAccelerationNoiseMPerSec2', ...
    actualProcessAccelerationNoiseMPerSec2, ...
    'actualPrimaryPositionNoiseM',actualPrimaryPositionNoiseM, ...
    'actualBackupPositionNoiseM',actualBackupPositionNoiseM, ...
    'outlierSequenceM',outlierSequenceM, ...
    'outlierIndex',outlierIndex, ...
    'outlierTimeSec',outlierTimeSec, ...
    'trueState',trueState, ...
    'priorEstimate',priorEstimate, ...
    'posteriorEstimate',posteriorEstimate, ...
    'measurement',measurement, ...
    'innovation',innovation, ...
    'innovationCovariance',innovationCovariance, ...
    'kalmanGain',kalmanGain, ...
    'priorCovariance',priorCovariance, ...
    'posteriorCovariance',posteriorCovariance, ...
    'normalizedInnovationSquared',normalizedInnovationSquared, ...
    'estimationError',estimationError, ...
    'posteriorPositionStdM',posteriorPositionStdM, ...
    'posteriorRateStdMPerSec',posteriorRateStdMPerSec, ...
    'positionErrorRmsTailM',positionErrorRmsTailM, ...
    'rateErrorRmsTailMPerSec',rateErrorRmsTailMPerSec, ...
    'meanNormalizedInnovationSquaredTail', ...
    meanNormalizedInnovationSquaredTail, ...
    'peakNormalizedInnovationSquared', ...
    max(normalizedInnovationSquared), ...
    'steadyPrimaryPositionGain',steadyPrimaryPositionGain, ...
    'steadyBackupPositionGain',steadyBackupPositionGain, ...
    'steadyRateGainFromPrimaryPerSec',steadyRateGainFromPrimaryPerSec, ...
    'stepCount',stepCount, ...
    'sampleCount',sampleCount, ...
    'maximumStepCount',maximumStepCount);
end

function inverseMatrix = inverseSymmetricTwoByTwo(matrix)
determinant = matrix(1,1)*matrix(2,2)-matrix(1,2)*matrix(2,1);
if determinant <= 0
    error('P16:InnovationCovariance', ...
        'Innovation covariance must remain positive definite.');
end
inverseMatrix = [matrix(2,2) -matrix(1,2); ...
    -matrix(2,1) matrix(1,1)]/determinant;
end

function values = deterministicNormal(valueCount,seed)
% Local Park-Miller and Box-Muller arithmetic avoids global RNG state.
modulus = 2147483647;
multiplier = 16807;
state = seed;
values = zeros(1,valueCount);
writeIndex = 1;
while writeIndex <= valueCount
    state = mod(multiplier*state,modulus);
    uniformOne = max(state/modulus,1e-12);
    state = mod(multiplier*state,modulus);
    uniformTwo = state/modulus;
    magnitude = sqrt(-2*log(uniformOne));
    values(writeIndex) = magnitude*cos(2*pi*uniformTwo);
    if writeIndex+1 <= valueCount
        values(writeIndex+1) = magnitude*sin(2*pi*uniformTwo);
    end
    writeIndex = writeIndex+2;
end
end
