function run_checks
%RUN_CHECKS Verify P16 Kalman-filter invariants without presentation code.
tolerance = 5e-11;
baselineA = model(0.35,0.08,0,1601,20,0.05);
baselineB = model(0.35,0.08,0,1601,20,0.05);
assert(isequaln(baselineA,baselineB), ...
    'The deterministic seeded baseline must repeat exactly.');

expectedDecay = exp(-0.5*0.05);
expectedPositionFromRate = (1-expectedDecay)/0.5;
expectedPositionFromAcceleration = ...
    (0.05-expectedPositionFromRate)/0.5;
expectedA = [1 expectedPositionFromRate;0 expectedDecay];
expectedB = [expectedPositionFromAcceleration;expectedPositionFromRate];
expectedC = [1 0;1 0];
expectedQ = expectedB*expectedB.'*0.08^2;
expectedR = diag([0.35^2 0.8^2]);
assert(max(abs(baselineA.discreteA(:)-expectedA(:))) < tolerance && ...
    max(abs(baselineA.discreteB(:)-expectedB(:))) < tolerance, ...
    'The exact P15 plant matrices must match independent formulas.');
assert(max(abs(baselineA.measurementMatrix(:)-expectedC(:))) == 0 && ...
    max(abs(baselineA.processCovariance(:)-expectedQ(:))) < tolerance && ...
    max(abs(baselineA.measurementCovariance(:)-expectedR(:))) < tolerance, ...
    'C, Q, and R must match the visible covariance definitions.');
assert(max(abs(baselineA.processNoiseShape(1:4)- ...
    [-2.478763417543018 -1.617092513460249 ...
    -0.242817572814180 0.765920120581528])) < 2e-12 && ...
    max(abs(baselineA.primaryNoiseShape(1:4)- ...
    [-0.489807081574456 -2.918577816474157 ...
    0.057181930085679 -1.210706371278562])) < 2e-12 && ...
    max(abs(baselineA.backupNoiseShape(1:4)- ...
    [1.814796402487107 -2.337364630418819 ...
    0.358944768387307 1.662732412598177])) < 2e-12, ...
    'The local seeded generator must retain its independent reference sequence.');

identityState = eye(2);
for k = 1:baselineA.sampleCount
    expectedMeasurement = expectedC*baselineA.trueState(:,k)+ ...
        [baselineA.actualPrimaryPositionNoiseM(k); ...
        baselineA.actualBackupPositionNoiseM(k)];
    expectedInnovation = expectedMeasurement- ...
        expectedC*baselineA.priorEstimate(:,k);
    expectedS = expectedC*baselineA.priorCovariance(:,:,k)*expectedC.'+ ...
        expectedR;
    expectedDeterminant = expectedS(1,1)*expectedS(2,2)- ...
        expectedS(1,2)*expectedS(2,1);
    expectedSInverse = [expectedS(2,2) -expectedS(1,2); ...
        -expectedS(2,1) expectedS(1,1)]/expectedDeterminant;
    expectedGain = baselineA.priorCovariance(:,:,k)*expectedC.'* ...
        expectedSInverse;
    expectedPosterior = baselineA.priorEstimate(:,k)+ ...
        expectedGain*expectedInnovation;
    covarianceCorrection = identityState-expectedGain*expectedC;
    expectedPosteriorCovariance = covarianceCorrection* ...
        baselineA.priorCovariance(:,:,k)*covarianceCorrection.'+ ...
        expectedGain*expectedR*expectedGain.';
    expectedNis = expectedInnovation.'*expectedSInverse*expectedInnovation;
    [forwardSequentialEstimate,forwardSequentialCovariance] = ...
        sequentialSensorUpdate(baselineA.priorEstimate(:,k), ...
        baselineA.priorCovariance(:,:,k),expectedMeasurement,expectedR,[1 2]);
    [reverseSequentialEstimate,reverseSequentialCovariance] = ...
        sequentialSensorUpdate(baselineA.priorEstimate(:,k), ...
        baselineA.priorCovariance(:,:,k),expectedMeasurement,expectedR,[2 1]);
    assert(max(abs(baselineA.measurement(:,k)-expectedMeasurement)) < tolerance && ...
        max(abs(baselineA.innovation(:,k)-expectedInnovation)) < tolerance, ...
        'Every measurement and innovation must follow the declared sensors.');
    assert(max(abs(baselineA.innovationCovariance(:,:,k)-expectedS),[],'all') < ...
        tolerance && max(abs(baselineA.kalmanGain(:,:,k)-expectedGain),[],'all') < ...
        tolerance, ...
        'Every innovation covariance and gain must follow P, C, and R.');
    assert(max(abs(baselineA.posteriorEstimate(:,k)-expectedPosterior)) < ...
        tolerance && max(abs(baselineA.posteriorCovariance(:,:,k)- ...
        expectedPosteriorCovariance),[],'all') < tolerance, ...
        'Every state and Joseph covariance update must match the equations.');
    assert(max(abs(forwardSequentialEstimate-expectedPosterior)) < tolerance && ...
        max(abs(reverseSequentialEstimate-expectedPosterior)) < tolerance && ...
        max(abs(forwardSequentialCovariance- ...
        expectedPosteriorCovariance),[],'all') < tolerance && ...
        max(abs(reverseSequentialCovariance- ...
        expectedPosteriorCovariance),[],'all') < tolerance, ...
        ['Independent sensor updates in either order must equal the ' ...
        'simultaneous two-sensor correction.']);
    assert(abs(baselineA.normalizedInnovationSquared(k)-expectedNis) < ...
        tolerance, ...
        'Every NIS value must use the same visible innovation covariance.');
    covariance = baselineA.posteriorCovariance(:,:,k);
    covarianceDeterminant = covariance(1,1)*covariance(2,2)- ...
        covariance(1,2)*covariance(2,1);
    assert(abs(covariance(1,2)-covariance(2,1)) < tolerance && ...
        covariance(1,1) > 0 && covariance(2,2) > 0 && ...
        covarianceDeterminant > 0, ...
        'Posterior covariance must stay symmetric and positive definite.');
    if k <= baselineA.stepCount
        expectedTrue = expectedA*baselineA.trueState(:,k)+ ...
            expectedB*baselineA.commandAccelerationMPerSec2(k)+ ...
            expectedB*baselineA.actualProcessAccelerationNoiseMPerSec2(k);
        expectedPrior = expectedA*baselineA.posteriorEstimate(:,k)+ ...
            expectedB*baselineA.commandAccelerationMPerSec2(k);
        expectedPriorCovariance = expectedA* ...
            baselineA.posteriorCovariance(:,:,k)*expectedA.'+expectedQ;
        assert(max(abs(baselineA.trueState(:,k+1)-expectedTrue)) < tolerance && ...
            max(abs(baselineA.priorEstimate(:,k+1)-expectedPrior)) < tolerance && ...
            max(abs(baselineA.priorCovariance(:,:,k+1)- ...
            expectedPriorCovariance),[],'all') < tolerance, ...
            'Truth, state prediction, and covariance prediction must recur exactly.');
    end
end
assert(baselineA.positionErrorRmsTailM < 0.1 && ...
    baselineA.rateErrorRmsTailMPerSec < 0.02 && ...
    baselineA.meanNormalizedInnovationSquaredTail > 1 && ...
    baselineA.meanNormalizedInnovationSquaredTail < 3 && ...
    baselineA.posteriorPositionStdM(end) < 0.05 && ...
    baselineA.posteriorRateStdMPerSec(end) < 0.02, ...
    'The matched seeded baseline must remain bounded with plausible NIS.');

assumedPositionNoiseStdValuesM = [0.1 0.2 0.35 0.6 0.9];
primaryPositionGains = zeros(size(assumedPositionNoiseStdValuesM));
backupPositionGains = zeros(size(assumedPositionNoiseStdValuesM));
meanTailNis = zeros(size(assumedPositionNoiseStdValuesM));
sensorRuns = cell(size(assumedPositionNoiseStdValuesM));
for k = 1:numel(assumedPositionNoiseStdValuesM)
    sensorRuns{k} = model(assumedPositionNoiseStdValuesM(k), ...
        0.08,0,1601,20,0.05);
    changed = sensorRuns{k};
    primaryPositionGains(k) = changed.steadyPrimaryPositionGain;
    backupPositionGains(k) = changed.steadyBackupPositionGain;
    meanTailNis(k) = changed.meanNormalizedInnovationSquaredTail;
    assert(changed.assumedProcessAccelerationStdMPerSec2 == 0.08 && ...
        changed.positionOutlierM == 0 && changed.noiseSeed == 1601 && ...
        max(abs(changed.trueState(:)-baselineA.trueState(:))) == 0 && ...
        max(abs(changed.measurement(:)-baselineA.measurement(:))) == 0, ...
        'The sensor-noise sweep must preserve truth, data, and all other inputs.');
end
assert(all(diff(primaryPositionGains) < 0) && ...
    all(diff(backupPositionGains) > 0) && all(diff(meanTailNis) < 0), ...
    'Higher reported sensor A noise must lower its gain and reallocate trust.');

equalReportedSensors = model(0.8,0.08,0,1601,20,0.05);
equalGainDifference = equalReportedSensors.kalmanGain(:,1,:)- ...
    equalReportedSensors.kalmanGain(:,2,:);
assert(equalReportedSensors.measurementCovariance(1,1) == ...
    equalReportedSensors.measurementCovariance(2,2) && ...
    max(abs(equalGainDifference(:))) < tolerance, ...
    'Equal C rows and equal reported variances must produce equal gain columns.');

assumedProcessNoiseStdValuesMPerSec2 = [0.01 0.04 0.08 0.2 0.5];
rateGainsPerSec = zeros(size(assumedProcessNoiseStdValuesMPerSec2));
reportedRateStdMPerSec = zeros(size(assumedProcessNoiseStdValuesMPerSec2));
for k = 1:numel(assumedProcessNoiseStdValuesMPerSec2)
    changed = model(0.35,assumedProcessNoiseStdValuesMPerSec2(k), ...
        0,1601,20,0.05);
    rateGainsPerSec(k) = changed.steadyRateGainFromPrimaryPerSec;
    reportedRateStdMPerSec(k) = changed.posteriorRateStdMPerSec(end);
    assert(changed.assumedPositionNoiseStdM == 0.35 && ...
        changed.positionOutlierM == 0 && changed.noiseSeed == 1601 && ...
        max(abs(changed.trueState(:)-baselineA.trueState(:))) == 0 && ...
        max(abs(changed.measurement(:)-baselineA.measurement(:))) == 0, ...
        'The process-noise sweep must preserve truth, data, and all other inputs.');
end
assert(all(diff(rateGainsPerSec) > 0) && ...
    all(diff(reportedRateStdMPerSec) > 0), ...
    'Higher Q must increase rate correction gain and reported rate uncertainty.');

broken = model(0.35,0.08,4,1601,20,0.05);
recovered = model(0.35,0.08,0,1601,20,0.05);
measurementDelta = broken.measurement-recovered.measurement;
expectedMeasurementDelta = zeros(size(measurementDelta));
expectedMeasurementDelta(1,broken.outlierIndex) = 4;
assert(max(abs(broken.trueState(:)-recovered.trueState(:))) == 0 && ...
    max(abs(broken.kalmanGain(:)-recovered.kalmanGain(:))) == 0 && ...
    max(abs(broken.posteriorCovariance(:)- ...
    recovered.posteriorCovariance(:))) == 0 && ...
    max(abs(measurementDelta(:)-expectedMeasurementDelta(:))) < tolerance, ...
    'The broken case must alter exactly one sensor sample, not truth or covariance.');
expectedOutlierCorrection = ...
    recovered.kalmanGain(:,1,broken.outlierIndex)*4;
actualOutlierCorrection = broken.posteriorEstimate(:,broken.outlierIndex)- ...
    recovered.posteriorEstimate(:,recovered.outlierIndex);
assert(max(abs(actualOutlierCorrection-expectedOutlierCorrection)) < tolerance && ...
    broken.normalizedInnovationSquared(broken.outlierIndex) > 50 && ...
    recovered.normalizedInnovationSquared(recovered.outlierIndex) < 10, ...
    'The outlier must receive the unchanged gain and cause a visible NIS spike.');
assert(isequaln(recovered,baselineA), ...
    'A fresh zero-outlier call must recover the exact baseline.');

alternateSeed = model(0.35,0.08,0,1701,20,0.05);
assert(max(abs(alternateSeed.measurement(:)-baselineA.measurement(:))) > 0.1 && ...
    max(abs(alternateSeed.trueState(:)-baselineA.trueState(:))) > 1e-4 && ...
    max(abs(alternateSeed.kalmanGain(:)-baselineA.kalmanGain(:))) == 0 && ...
    max(abs(alternateSeed.posteriorCovariance(:)- ...
    baselineA.posteriorCovariance(:))) == 0, ...
    'Seeded realizations must be isolated while covariance remains data-independent.');

assertAnyError(@() model(NaN,0.08,0,1601,20,0.05), ...
    'A nonfinite sensor-noise setting must be rejected.');
assertAnyError(@() model([0.2 0.3],0.08,0,1601,20,0.05), ...
    'A nonscalar sensor-noise setting must be rejected.');
assertAnyError(@() model(0.35,0.08+1i,0,1601,20,0.05), ...
    'A complex process-noise setting must be rejected.');
assertAnyError(@() model(0.35,-0.08,0,1601,20,0.05), ...
    'A negative process-noise setting must be rejected.');
assertAnyError(@() model(0.35,0.08,-1,1601,20,0.05), ...
    'A negative outlier magnitude must be rejected.');
assertAnyError(@() model(0.35,0.08,0,1601.5,20,0.05), ...
    'A noninteger seed must be rejected.');
assertErrorId(@() model(0.09,0.08,0,1601,20,0.05), ...
    'P16:PositionNoiseRange','Too-small sensor noise must be rejected.');
assertErrorId(@() model(0.91,0.08,0,1601,20,0.05), ...
    'P16:PositionNoiseRange','Excessive sensor noise must be rejected.');
assertErrorId(@() model(0.35,0.009,0,1601,20,0.05), ...
    'P16:ProcessNoiseRange','Too-small process noise must be rejected.');
assertErrorId(@() model(0.35,0.51,0,1601,20,0.05), ...
    'P16:ProcessNoiseRange','Excessive process noise must be rejected.');
assertErrorId(@() model(0.35,0.08,4.01,1601,20,0.05), ...
    'P16:OutlierRange','Excessive outlier magnitude must be rejected.');
assertErrorId(@() model(0.35,0.08,0,1000001,20,0.05), ...
    'P16:SeedRange','Excessive seed must be rejected.');
assertErrorId(@() model(0.35,0.08,0,1601,14.9,0.05), ...
    'P16:DurationRange','A too-short duration must be rejected.');
assertErrorId(@() model(0.35,0.08,0,1601,30.1,0.05), ...
    'P16:DurationRange','An excessive duration must be rejected.');
assertErrorId(@() model(0.35,0.08,0,1601,20,0.101), ...
    'P16:DisplayResolution','An under-resolved interval must be rejected.');
assertErrorId(@() model(0.35,0.08,0,1601,20,0.03), ...
    'P16:GridAlignment','A partial final sample must be rejected.');
assertErrorId(@() model(0.35,0.08,0,1601,30,0.005), ...
    'P16:TooManySteps','An oversized grid must be rejected before allocation.');
boundedGrid = model(0.35,0.08,0,1601,30,0.006);
assert(boundedGrid.stepCount == 5000 && boundedGrid.sampleCount == 5001 && ...
    all(isfinite(boundedGrid.trueState(:))) && ...
    all(isfinite(boundedGrid.posteriorEstimate(:))) && ...
    all(isfinite(boundedGrid.posteriorCovariance(:))) && ...
    all(isfinite(boundedGrid.normalizedInnovationSquared)), ...
    'The largest accepted grid must contain only finite retained outputs.');

disp(['P16 checks passed: seeded sensor fusion, covariance recurrences, ' ...
    'two isolated levers, outlier recovery, malformed inputs, and bounds.']);
end

function assertAnyError(operation,message)
didError = false;
try
    operation();
catch
    didError = true;
end
assert(didError,message);
end

function [estimate,covariance] = sequentialSensorUpdate( ...
    priorEstimate,priorCovariance,measurement,measurementCovariance,order)
% Fuse independent scalar sensors one at a time as a batch-update oracle.
measurementRow = [1 0];
identityState = eye(2);
estimate = priorEstimate;
covariance = priorCovariance;
for sensorIndex = order
    innovation = measurement(sensorIndex)-measurementRow*estimate;
    innovationVariance = measurementRow*covariance*measurementRow.'+ ...
        measurementCovariance(sensorIndex,sensorIndex);
    gain = covariance*measurementRow.'/innovationVariance;
    estimate = estimate+gain*innovation;
    covarianceCorrection = identityState-gain*measurementRow;
    covariance = covarianceCorrection*covariance*covarianceCorrection.'+ ...
        gain*measurementCovariance(sensorIndex,sensorIndex)*gain.';
end
end

function assertErrorId(operation,expectedIdentifier,message)
actualIdentifier = '';
try
    operation();
catch exception
    actualIdentifier = exception.identifier;
end
assert(strcmp(actualIdentifier,expectedIdentifier),message);
end
