function interactive
%INTERACTIVE Explore P20's declared nominal-versus-robust tradeoff.
modelFunction = @model;

window = uifigure('Name','P20 - Nominal versus robust designs', ...
    'Position',[100 100 1120 740]);
speedAxes = uiaxes(window,'Position',[55 390 670 300]);
commandAxes = uiaxes(window,'Position',[55 75 670 255]);

uilabel(window,'Position',[765 665 300 22], ...
    'Text','Actuator gain ratio (actual / nominal)');
gainSlider = uislider(window,'Position',[770 645 285 3], ...
    'Limits',[0.5 1.5],'Value',1, ...
    'MajorTicks',[0.5 0.75 1 1.25 1.5]);

uilabel(window,'Position',[765 590 300 22], ...
    'Text','Drag ratio (actual / nominal)');
dragSlider = uislider(window,'Position',[770 570 285 3], ...
    'Limits',[0.5 2],'Value',1, ...
    'MajorTicks',[0.5 1 1.5 2]);

uilabel(window,'Position',[765 515 210 22], ...
    'Text','Reference speed (m/s; 1 used for design)');
referenceSpinner = uispinner(window,'Position',[955 515 100 22], ...
    'Limits',[0 2],'Step',0.1,'Value',1);

uilabel(window,'Position',[765 465 160 22], ...
    'Text','Actuator polarity');
signDropdown = uidropdown(window,'Position',[900 465 155 22], ...
    'Items',{'Positive sign','Reversed (broken)'}, ...
    'Value','Positive sign');

resetButton = uibutton(window,'push','Text','Reset matched baseline', ...
    'Position',[765 410 290 30]);
statusLabel = uilabel(window,'Position',[765 85 315 295], ...
    'VerticalAlignment','top','WordWrap','on','Text','');

gainSlider.ValueChangingFcn = @(~,event) redraw(event.Value, ...
    dragSlider.Value,referenceSpinner.Value,signDropdown.Value);
gainSlider.ValueChangedFcn = @(~,~) redraw(gainSlider.Value, ...
    dragSlider.Value,referenceSpinner.Value,signDropdown.Value);
dragSlider.ValueChangingFcn = @(~,event) redraw(gainSlider.Value, ...
    event.Value,referenceSpinner.Value,signDropdown.Value);
dragSlider.ValueChangedFcn = @(~,~) redraw(gainSlider.Value, ...
    dragSlider.Value,referenceSpinner.Value,signDropdown.Value);
referenceSpinner.ValueChangedFcn = @(~,~) redraw(gainSlider.Value, ...
    dragSlider.Value,referenceSpinner.Value,signDropdown.Value);
signDropdown.ValueChangedFcn = @(~,~) redraw(gainSlider.Value, ...
    dragSlider.Value,referenceSpinner.Value,signDropdown.Value);
resetButton.ButtonPushedFcn = @(~,~) resetBaseline();

redraw(1,1,1,'Positive sign');

function resetBaseline
    gainSlider.Value = 1;
    dragSlider.Value = 1;
    referenceSpinner.Value = 1;
    signDropdown.Value = 'Positive sign';
    redraw(1,1,1,'Positive sign');
end

function redraw(gainRatio,dragRatio,referenceSpeed,signChoice)
    if strcmp(signChoice,'Positive sign')
        actuatorSign = 1;
    else
        actuatorSign = -1;
    end
    result = modelFunction(gainRatio,dragRatio,actuatorSign, ...
        referenceSpeed,12,0.02);

    cla(speedAxes);
    plot(speedAxes,result.timeSec,result.referenceSpeed,'k:', ...
        'LineWidth',1.4,'DisplayName','Reference');
    hold(speedAxes,'on');
    plot(speedAxes,result.timeSec,result.nominal.speedMPerSec,'b-', ...
        'LineWidth',1.7,'DisplayName','Nominal design');
    plot(speedAxes,result.timeSec,result.robust.speedMPerSec,'m--', ...
        'LineWidth',1.7,'DisplayName','Robust design');
    hold(speedAxes,'off'); grid(speedAxes,'on');
    xlabel(speedAxes,'Time (s)'); ylabel(speedAxes,'Speed (m/s)');
    title(speedAxes,'Same plant, different design objective');
    legend(speedAxes,'Location','best');

    cla(commandAxes);
    plot(commandAxes,result.timeSec, ...
        result.nominal.totalCommandMPerSec2,'b-', ...
        'LineWidth',1.7,'DisplayName','Nominal command');
    hold(commandAxes,'on');
    plot(commandAxes,result.timeSec, ...
        result.robust.totalCommandMPerSec2,'m--', ...
        'LineWidth',1.7,'DisplayName','Robust command');
    hold(commandAxes,'off'); grid(commandAxes,'on');
    xlabel(commandAxes,'Time (s)');
    ylabel(commandAxes,'Acceleration command (m/s^2)');
    title(commandAxes,'Command effort is part of the tradeoff');
    legend(commandAxes,'Location','best');

    if referenceSpeed == 0
        interpretation = ['zero reference: both designs remain at rest; ' ...
            'choose a positive reference to expose the tracking tradeoff'];
    elseif actuatorSign < 0
        interpretation = ['broken: negative actuator effectiveness lies ' ...
            'outside the positive design grid'];
    elseif gainRatio == 1 && dragRatio == 1
        interpretation = ['matched point: nominal wins tracking ISE; ' ...
            'robustness is judged over the declared grid'];
    elseif result.robust.trackingIntegralM2PerSec < ...
            result.nominal.trackingIntegralM2PerSec
        interpretation = ['changed plant: robust PI has lower finite-time ' ...
            'tracking ISE on this scenario'];
    else
        interpretation = ['changed plant: nominal still has lower ISE here; ' ...
            'worst-case improvement is not pointwise dominance'];
    end
    statusLabel.Text = sprintf([ ...
        'gain ratio: %.2f\ndrag ratio: %.2f\n' ...
        'selected robust Kp/Ki: %.1f 1/s / %.1f 1/s^2\n' ...
        'design conditions: 1 m/s, 12 s, dt=0.02 s\n\n' ...
        'nominal ISE: %.4f m^2/s\nrobust ISE: %.4f m^2/s\n' ...
        'nominal effort: %.3f m^2/s^3\nrobust effort: %.3f m^2/s^3\n' ...
        'nominal/robust pole magnitude: %.4f / %.4f\n' ...
        'nominal/robust final error: %.4f / %.4f m/s\n\n%s'], ...
        gainRatio,dragRatio,result.robustProportionalGainPerSec, ...
        result.robustIntegralGainPerSec2, ...
        result.nominal.trackingIntegralM2PerSec, ...
        result.robust.trackingIntegralM2PerSec, ...
        result.nominal.commandEffortIntegralM2PerSec3, ...
        result.robust.commandEffortIntegralM2PerSec3, ...
        result.nominal.closedLoopPoleMagnitude, ...
        result.robust.closedLoopPoleMagnitude, ...
        result.nominal.finalAbsoluteTrackingErrorMPerSec, ...
        result.robust.finalAbsoluteTrackingErrorMPerSec,interpretation);
end
end
