function result = model(actuatorGainRatio,dragRatio,actuatorSign, ...
    referenceSpeedMPerSec,simulationDurationSec,timeStepSec)
%MODEL Compare a nominal controller with a design chosen over uncertainty.
arguments
    actuatorGainRatio (1,1) double ...
        {mustBeReal,mustBeFinite,mustBePositive} = 1
    dragRatio (1,1) double {mustBeReal,mustBeFinite,mustBePositive} = 1
    actuatorSign (1,1) double {mustBeReal,mustBeFinite} = 1
    referenceSpeedMPerSec (1,1) double ...
        {mustBeReal,mustBeFinite,mustBeNonnegative} = 1
    simulationDurationSec (1,1) double ...
        {mustBeReal,mustBeFinite,mustBePositive} = 12
    timeStepSec (1,1) double ...
        {mustBeReal,mustBeFinite,mustBePositive} = 0.02
end

if actuatorGainRatio < 0.5 || actuatorGainRatio > 1.5
    error('P20:ActuatorGainRatioRange', ...
        'Actuator gain ratio must be between 0.5 and 1.5.');
end
if dragRatio < 0.5 || dragRatio > 2
    error('P20:DragRatioRange', ...
        'Drag ratio must be between 0.5 and 2.');
end
if actuatorSign ~= 1 && actuatorSign ~= -1
    error('P20:ActuatorSign', ...
        'Actuator sign must be exactly +1 or -1.');
end
if referenceSpeedMPerSec > 2
    error('P20:ReferenceSpeedRange', ...
        'Reference speed must be between 0 and 2 m/s.');
end
if simulationDurationSec < 6 || simulationDurationSec > 20
    error('P20:DurationRange', ...
        'Simulation duration must be between 6 and 20 seconds.');
end
if timeStepSec > 0.05
    error('P20:DisplayResolution', ...
        'Time step must be at most 0.05 seconds.');
end

maximumStepCount = 5000;
rawStepCount = simulationDurationSec/timeStepSec;
if ~isfinite(rawStepCount) || rawStepCount > maximumStepCount+0.5
    error('P20:TooManySteps', ...
        'The requested time grid exceeds 5000 state transitions.');
end
stepCount = round(rawStepCount);
if abs(rawStepCount-stepCount) > 1e-10*max(1,rawStepCount)
    error('P20:GridAlignment', ...
        'Duration must contain an integer number of time steps.');
end
referenceStepSec = 1;
eventRatio = referenceStepSec/timeStepSec;
if abs(eventRatio-round(eventRatio)) > 1e-10*max(1,eventRatio)
    error('P20:EventAlignment', ...
        'The 1 s reference event must lie on the time grid.');
end

% P19's actual plant remains explicit:
%   dv/dt = -a*v + b*u
%   v[k+1] = alpha*v[k] + beta*u[k].
% The nominal design retains P19's model-matched feedforward plus P gain.
% The robust design is a PI candidate selected by finite minimax enumeration.
nominalDragPerSec = 1;
nominalActuatorGain = 1;
nominalFeedforwardGainPerSec = nominalDragPerSec/nominalActuatorGain;
actualDragPerSec = dragRatio*nominalDragPerSec;
actualActuatorGain = actuatorSign*actuatorGainRatio* ...
    nominalActuatorGain;
actualDecay = exp(-actualDragPerSec*timeStepSec);
actualInputCoefficient = actualActuatorGain/actualDragPerSec* ...
    (1-actualDecay);
nominalProportionalGainPerSec = 1.5;

selection = selectRobustDesign();
robustProportionalGainPerSec = selection.selectedProportionalGainPerSec;
robustIntegralGainPerSec2 = selection.selectedIntegralGainPerSec2;

sampleCount = stepCount+1;
timeSec = (0:stepCount)*timeStepSec;
referenceSpeed = zeros(1,sampleCount);
referenceSpeed(timeSec >= referenceStepSec) = referenceSpeedMPerSec;
divergenceLimitMPerSec = 1000;

nominal = simulateNominal(actualDecay,actualInputCoefficient, ...
    nominalFeedforwardGainPerSec,nominalProportionalGainPerSec, ...
    referenceSpeed,timeSec,timeStepSec,divergenceLimitMPerSec, ...
    actualDragPerSec,actualActuatorGain);
robust = simulateRobust(actualDecay,actualInputCoefficient, ...
    robustProportionalGainPerSec,robustIntegralGainPerSec2, ...
    referenceSpeed,timeSec,timeStepSec,divergenceLimitMPerSec, ...
    actualDragPerSec,actualActuatorGain);

result = struct( ...
    'actuatorGainRatio',actuatorGainRatio, ...
    'dragRatio',dragRatio, ...
    'actuatorSign',actuatorSign, ...
    'referenceSpeedMPerSec',referenceSpeedMPerSec, ...
    'simulationDurationSec',simulationDurationSec, ...
    'timeStepSec',timeStepSec, ...
    'referenceStepSec',referenceStepSec, ...
    'maximumStepCount',maximumStepCount, ...
    'stepCount',stepCount, ...
    'sampleCount',sampleCount, ...
    'nominalDragPerSec',nominalDragPerSec, ...
    'nominalActuatorGain',nominalActuatorGain, ...
    'nominalFeedforwardGainPerSec',nominalFeedforwardGainPerSec, ...
    'actualDragPerSec',actualDragPerSec, ...
    'actualActuatorGain',actualActuatorGain, ...
    'actualDecay',actualDecay, ...
    'actualInputCoefficient',actualInputCoefficient, ...
    'nominalProportionalGainPerSec',nominalProportionalGainPerSec, ...
    'robustProportionalGainPerSec',robustProportionalGainPerSec, ...
    'robustIntegralGainPerSec2',robustIntegralGainPerSec2, ...
    'divergenceLimitMPerSec',divergenceLimitMPerSec, ...
    'timeSec',timeSec, ...
    'referenceSpeed',referenceSpeed, ...
    'designSelection',selection, ...
    'nominal',nominal, ...
    'robust',robust);
end

function selection = selectRobustDesign()
% Select a transparent PI candidate against a declared 25-point grid.
proportionalGainCandidatesPerSec = [0.5 1 1.5 2];
integralGainCandidatesPerSec2 = [0.4 0.8 1.2];
designActuatorGainRatios = [0.5 0.75 1 1.25 1.5];
designDragRatios = [0.5 0.75 1 1.5 2];
designDurationSec = 12;
designTimeStepSec = 0.02;
commandEffortLimitM2PerSec3 = 90;
designStepCount = round(designDurationSec/designTimeStepSec);
candidateCount = numel(proportionalGainCandidatesPerSec)* ...
    numel(integralGainCandidatesPerSec2);
scenarioCount = numel(designActuatorGainRatios)* ...
    numel(designDragRatios);
maximumDesignTransitionCount = candidateCount*scenarioCount* ...
    designStepCount;

worstTrackingIntegralM2PerSec = inf(numel(proportionalGainCandidatesPerSec), ...
    numel(integralGainCandidatesPerSec2));
worstCommandEffortIntegralM2PerSec3 = ...
    inf(size(worstTrackingIntegralM2PerSec));
stableAcrossGrid = false(size(worstTrackingIntegralM2PerSec));
feasible = false(size(worstTrackingIntegralM2PerSec));
selectedScore = Inf;
selectedProportionalGainPerSec = NaN;
selectedIntegralGainPerSec2 = NaN;

for proportionalIndex = 1:numel(proportionalGainCandidatesPerSec)
    proportionalGainPerSec = ...
        proportionalGainCandidatesPerSec(proportionalIndex);
    for integralIndex = 1:numel(integralGainCandidatesPerSec2)
        integralGainPerSec2 = ...
            integralGainCandidatesPerSec2(integralIndex);
        candidateWorstTracking = 0;
        candidateWorstEffort = 0;
        candidateStable = true;
        for gainRatio = designActuatorGainRatios
            for dragRatio = designDragRatios
                [trackingIntegral,commandEffort,poleMagnitude] = ...
                    evaluateRobustCandidate(gainRatio,dragRatio, ...
                    proportionalGainPerSec,integralGainPerSec2, ...
                    designDurationSec,designTimeStepSec);
                candidateWorstTracking = max(candidateWorstTracking, ...
                    trackingIntegral);
                candidateWorstEffort = max(candidateWorstEffort, ...
                    commandEffort);
                candidateStable = candidateStable && poleMagnitude < 1;
            end
        end
        worstTrackingIntegralM2PerSec(proportionalIndex,integralIndex) = ...
            candidateWorstTracking;
        worstCommandEffortIntegralM2PerSec3( ...
            proportionalIndex,integralIndex) = candidateWorstEffort;
        stableAcrossGrid(proportionalIndex,integralIndex) = ...
            candidateStable;
        candidateFeasible = candidateStable && ...
            candidateWorstEffort <= commandEffortLimitM2PerSec3;
        feasible(proportionalIndex,integralIndex) = candidateFeasible;
        % Strict comparison plus loop order gives the documented tie rule:
        % first lower Kp, then lower Ki for exactly equal worst-case ISE.
        if candidateFeasible && candidateWorstTracking < selectedScore
            selectedScore = candidateWorstTracking;
            selectedProportionalGainPerSec = proportionalGainPerSec;
            selectedIntegralGainPerSec2 = integralGainPerSec2;
        end
    end
end
if ~isfinite(selectedScore)
    error('P20:NoFeasibleRobustDesign', ...
        'The declared finite candidate set has no feasible robust design.');
end

selection = struct( ...
    'proportionalGainCandidatesPerSec', ...
    proportionalGainCandidatesPerSec, ...
    'integralGainCandidatesPerSec2',integralGainCandidatesPerSec2, ...
    'designActuatorGainRatios',designActuatorGainRatios, ...
    'designDragRatios',designDragRatios, ...
    'designDurationSec',designDurationSec, ...
    'designTimeStepSec',designTimeStepSec, ...
    'commandEffortLimitM2PerSec3',commandEffortLimitM2PerSec3, ...
    'candidateCount',candidateCount, ...
    'scenarioCount',scenarioCount, ...
    'maximumDesignTransitionCount',maximumDesignTransitionCount, ...
    'worstTrackingIntegralM2PerSec',worstTrackingIntegralM2PerSec, ...
    'worstCommandEffortIntegralM2PerSec3', ...
    worstCommandEffortIntegralM2PerSec3, ...
    'stableAcrossGrid',stableAcrossGrid, ...
    'feasible',feasible, ...
    'selectedWorstTrackingIntegralM2PerSec',selectedScore, ...
    'selectedProportionalGainPerSec',selectedProportionalGainPerSec, ...
    'selectedIntegralGainPerSec2',selectedIntegralGainPerSec2);
end

function [trackingIntegral,commandEffort,poleMagnitude] = ...
    evaluateRobustCandidate(gainRatio,dragRatio,proportionalGainPerSec, ...
    integralGainPerSec2,durationSec,timeStepSec)
decay = exp(-dragRatio*timeStepSec);
inputCoefficient = gainRatio/dragRatio*(1-decay);
stepCount = round(durationSec/timeStepSec);
speedMPerSec = 0;
errorIntegralM = 0;
trackingIntegral = 0;
commandEffort = 0;
for k = 1:stepCount
    timeSec = (k-1)*timeStepSec;
    referenceSpeed = double(timeSec >= 1);
    trackingError = referenceSpeed-speedMPerSec;
    commandMPerSec2 = proportionalGainPerSec*trackingError+ ...
        integralGainPerSec2*errorIntegralM;
    trackingIntegral = trackingIntegral+ ...
        timeStepSec*trackingError^2;
    commandEffort = commandEffort+timeStepSec*commandMPerSec2^2;
    speedMPerSec = decay*speedMPerSec+ ...
        inputCoefficient*commandMPerSec2;
    errorIntegralM = errorIntegralM+timeStepSec*trackingError;
end
[~,~,poleMagnitude] = robustPoles(decay,inputCoefficient, ...
    proportionalGainPerSec,integralGainPerSec2,timeStepSec);
end

function output = simulateNominal(decay,inputCoefficient, ...
    feedforwardGainPerSec,proportionalGainPerSec,referenceSpeed,timeSec, ...
    timeStepSec,divergenceLimitMPerSec,actualDragPerSec,actualActuatorGain)
sampleCount = numel(timeSec);
speedMPerSec = zeros(1,sampleCount);
feedbackCommandMPerSec2 = nan(1,sampleCount);
totalCommandMPerSec2 = nan(1,sampleCount);
terminatedEarly = false;
terminationIndex = NaN;
for k = 1:sampleCount
    if terminatedEarly
        break;
    end
    trackingError = referenceSpeed(k)-speedMPerSec(k);
    feedbackCommandMPerSec2(k) = proportionalGainPerSec*trackingError;
    totalCommandMPerSec2(k) = feedforwardGainPerSec*referenceSpeed(k)+ ...
        feedbackCommandMPerSec2(k);
    if k < sampleCount
        nextSpeed = decay*speedMPerSec(k)+ ...
            inputCoefficient*totalCommandMPerSec2(k);
        speedMPerSec(k+1) = nextSpeed;
        if ~isfinite(nextSpeed) || abs(nextSpeed) > divergenceLimitMPerSec
            terminatedEarly = true;
            terminationIndex = k+1;
            if k+1 < sampleCount
                speedMPerSec(k+2:end) = NaN;
            end
        end
    end
end
closedLoopPole = decay-inputCoefficient*proportionalGainPerSec;
stable = abs(closedLoopPole) < 1;
if stable
    steadyStateSpeedMPerSec = actualActuatorGain* ...
        (feedforwardGainPerSec+proportionalGainPerSec)* ...
        referenceSpeed(end)/ ...
        (actualDragPerSec+actualActuatorGain*proportionalGainPerSec);
else
    steadyStateSpeedMPerSec = NaN;
end
output = finishMetrics(speedMPerSec,feedbackCommandMPerSec2, ...
    totalCommandMPerSec2,referenceSpeed,timeSec,timeStepSec, ...
    terminatedEarly,terminationIndex,stable,abs(closedLoopPole), ...
    closedLoopPole,NaN,steadyStateSpeedMPerSec,NaN, ...
    proportionalGainPerSec,0,'nominal feedforward plus P');
output.recurrenceResidualMPerSec = recurrenceResidual(speedMPerSec, ...
    totalCommandMPerSec2,decay,inputCoefficient);
end

function output = simulateRobust(decay,inputCoefficient, ...
    proportionalGainPerSec,integralGainPerSec2,referenceSpeed,timeSec, ...
    timeStepSec,divergenceLimitMPerSec,actualDragPerSec, ...
    actualActuatorGain)
sampleCount = numel(timeSec);
speedMPerSec = zeros(1,sampleCount);
errorIntegralM = zeros(1,sampleCount);
feedbackCommandMPerSec2 = nan(1,sampleCount);
totalCommandMPerSec2 = nan(1,sampleCount);
terminatedEarly = false;
terminationIndex = NaN;
for k = 1:sampleCount
    if terminatedEarly
        break;
    end
    trackingError = referenceSpeed(k)-speedMPerSec(k);
    feedbackCommandMPerSec2(k) = proportionalGainPerSec*trackingError;
    totalCommandMPerSec2(k) = feedbackCommandMPerSec2(k)+ ...
        integralGainPerSec2*errorIntegralM(k);
    if k < sampleCount
        nextSpeed = decay*speedMPerSec(k)+ ...
            inputCoefficient*totalCommandMPerSec2(k);
        nextIntegral = errorIntegralM(k)+timeStepSec*trackingError;
        speedMPerSec(k+1) = nextSpeed;
        errorIntegralM(k+1) = nextIntegral;
        if ~isfinite(nextSpeed) || ~isfinite(nextIntegral) || ...
                abs(nextSpeed) > divergenceLimitMPerSec
            terminatedEarly = true;
            terminationIndex = k+1;
            if k+1 < sampleCount
                speedMPerSec(k+2:end) = NaN;
                errorIntegralM(k+2:end) = NaN;
            end
        end
    end
end
[pole1,pole2,poleMagnitude] = robustPoles(decay,inputCoefficient, ...
    proportionalGainPerSec,integralGainPerSec2,timeStepSec);
stable = poleMagnitude < 1;
if stable && actualActuatorGain > 0
    steadyStateSpeedMPerSec = referenceSpeed(end);
    steadyStateCommandMPerSec2 = actualDragPerSec/ ...
        actualActuatorGain*referenceSpeed(end);
else
    steadyStateSpeedMPerSec = NaN;
    steadyStateCommandMPerSec2 = NaN;
end
output = finishMetrics(speedMPerSec,feedbackCommandMPerSec2, ...
    totalCommandMPerSec2,referenceSpeed,timeSec,timeStepSec, ...
    terminatedEarly,terminationIndex,stable,poleMagnitude,pole1,pole2, ...
    steadyStateSpeedMPerSec,steadyStateCommandMPerSec2, ...
    proportionalGainPerSec,integralGainPerSec2,'robust PI');
output.errorIntegralM = errorIntegralM;
output.recurrenceResidualMPerSec = recurrenceResidual(speedMPerSec, ...
    totalCommandMPerSec2,decay,inputCoefficient);
output.integralRecurrenceResidualM = integralRecurrenceResidual( ...
    errorIntegralM,speedMPerSec,referenceSpeed,timeStepSec);
end

function output = finishMetrics(speedMPerSec,feedbackCommandMPerSec2, ...
    totalCommandMPerSec2,referenceSpeed,timeSec,timeStepSec, ...
    terminatedEarly,terminationIndex,stable,poleMagnitude,pole1,pole2, ...
    steadyStateSpeedMPerSec,steadyStateCommandMPerSec2, ...
    proportionalGainPerSec,integralGainPerSec2,designName)
trackingErrorMPerSec = referenceSpeed-speedMPerSec;
validTransitions = isfinite(trackingErrorMPerSec(1:end-1)) & ...
    isfinite(totalCommandMPerSec2(1:end-1));
validSamples = isfinite(speedMPerSec);
trackingIntegralM2PerSec = timeStepSec*sum( ...
    trackingErrorMPerSec(find(validTransitions)).^2);
commandEffortIntegralM2PerSec3 = timeStepSec*sum( ...
    totalCommandMPerSec2(find(validTransitions)).^2);
peakAbsoluteSpeedMPerSec = max(abs(speedMPerSec(find(validSamples))));
peakAbsoluteCommandMPerSec2 = max(abs( ...
    totalCommandMPerSec2(find(isfinite(totalCommandMPerSec2)))));
validPerformance = stable && ~terminatedEarly;
if validPerformance
    comparisonCostM2PerSec = trackingIntegralM2PerSec;
    finalAbsoluteTrackingErrorMPerSec = ...
        abs(trackingErrorMPerSec(end));
    terminationTimeSec = NaN;
else
    comparisonCostM2PerSec = Inf;
    finalAbsoluteTrackingErrorMPerSec = NaN;
    if terminatedEarly
        terminationTimeSec = timeSec(terminationIndex);
    else
        terminationTimeSec = NaN;
    end
end
output = struct( ...
    'designName',designName, ...
    'proportionalGainPerSec',proportionalGainPerSec, ...
    'integralGainPerSec2',integralGainPerSec2, ...
    'speedMPerSec',speedMPerSec, ...
    'trackingErrorMPerSec',trackingErrorMPerSec, ...
    'feedbackCommandMPerSec2',feedbackCommandMPerSec2, ...
    'totalCommandMPerSec2',totalCommandMPerSec2, ...
    'trackingIntegralM2PerSec',trackingIntegralM2PerSec, ...
    'commandEffortIntegralM2PerSec3', ...
    commandEffortIntegralM2PerSec3, ...
    'peakAbsoluteSpeedMPerSec',peakAbsoluteSpeedMPerSec, ...
    'peakAbsoluteCommandMPerSec2',peakAbsoluteCommandMPerSec2, ...
    'finalAbsoluteTrackingErrorMPerSec', ...
    finalAbsoluteTrackingErrorMPerSec, ...
    'comparisonCostM2PerSec',comparisonCostM2PerSec, ...
    'stable',stable, ...
    'closedLoopPoleMagnitude',poleMagnitude, ...
    'closedLoopPole1',pole1, ...
    'closedLoopPole2',pole2, ...
    'steadyStateSpeedMPerSec',steadyStateSpeedMPerSec, ...
    'steadyStateCommandMPerSec2',steadyStateCommandMPerSec2, ...
    'validPerformance',validPerformance, ...
    'terminatedEarly',terminatedEarly, ...
    'terminationIndex',terminationIndex, ...
    'terminationTimeSec',terminationTimeSec);
end

function [pole1,pole2,poleMagnitude] = robustPoles(decay, ...
    inputCoefficient,proportionalGainPerSec,integralGainPerSec2,timeStepSec)
traceValue = decay-inputCoefficient*proportionalGainPerSec+1;
determinantValue = decay-inputCoefficient*proportionalGainPerSec+ ...
    inputCoefficient*integralGainPerSec2*timeStepSec;
discriminant = traceValue^2-4*determinantValue;
squareRoot = sqrt(complex(discriminant,0));
pole1 = (traceValue+squareRoot)/2;
pole2 = (traceValue-squareRoot)/2;
poleMagnitude = max(abs([pole1 pole2]));
end

function residual = recurrenceResidual(speedMPerSec,commandMPerSec2, ...
    decay,inputCoefficient)
residual = 0;
for k = 1:numel(speedMPerSec)-1
    if ~isfinite(speedMPerSec(k+1)) || ~isfinite(commandMPerSec2(k))
        break;
    end
    expectedNext = decay*speedMPerSec(k)+ ...
        inputCoefficient*commandMPerSec2(k);
    residual = max(residual,abs(speedMPerSec(k+1)-expectedNext));
end
end

function residual = integralRecurrenceResidual(errorIntegralM, ...
    speedMPerSec,referenceSpeed,timeStepSec)
residual = 0;
for k = 1:numel(errorIntegralM)-1
    if ~isfinite(errorIntegralM(k+1)) || ~isfinite(speedMPerSec(k))
        break;
    end
    expectedNext = errorIntegralM(k)+ ...
        timeStepSec*(referenceSpeed(k)-speedMPerSec(k));
    residual = max(residual,abs(errorIntegralM(k+1)-expectedNext));
end
end
