function run_checks
%RUN_CHECKS Verify P20 arithmetic, design selection, limits, and failures.
tolerance = 2e-12;
baselineA = model(1,1,1,1,12,0.02);
baselineB = model(1,1,1,1,12,0.02);
assert(isequaln(baselineA,baselineB), ...
    'Repeated baseline calls must be exactly deterministic.');

% Independent baseline oracle: recompute held coefficients, controller
% commands, every recurrence, and both integral metrics from retained inputs.
expectedDecay = exp(-0.02);
expectedInput = 1-expectedDecay;
assert(abs(baselineA.actualDecay-expectedDecay) < tolerance && ...
    abs(baselineA.actualInputCoefficient-expectedInput) < tolerance, ...
    'Baseline held-input coefficients must follow the plant equation.');
assert(baselineA.nominalProportionalGainPerSec == 1.5 && ...
    baselineA.nominalFeedforwardGainPerSec == 1 && ...
    baselineA.robustProportionalGainPerSec == 2 && ...
    baselineA.robustIntegralGainPerSec2 == 0.8, ...
    'The declared nominal gain and selected robust gains must be retained.');

expectedNominalSpeed = zeros(size(baselineA.timeSec));
expectedRobustSpeed = zeros(size(baselineA.timeSec));
expectedRobustIntegral = zeros(size(baselineA.timeSec));
expectedNominalCommand = zeros(size(baselineA.timeSec));
expectedRobustCommand = zeros(size(baselineA.timeSec));
for k = 1:baselineA.sampleCount
    referenceSpeed = double(baselineA.timeSec(k) >= 1);
    nominalError = referenceSpeed-expectedNominalSpeed(k);
    robustError = referenceSpeed-expectedRobustSpeed(k);
    expectedNominalCommand(k) = ...
        baselineA.nominalFeedforwardGainPerSec*referenceSpeed+ ...
        1.5*nominalError;
    expectedRobustCommand(k) = 2*robustError+ ...
        0.8*expectedRobustIntegral(k);
    if k <= baselineA.stepCount
        expectedNominalSpeed(k+1) = expectedDecay* ...
            expectedNominalSpeed(k)+expectedInput* ...
            expectedNominalCommand(k);
        expectedRobustSpeed(k+1) = expectedDecay* ...
            expectedRobustSpeed(k)+expectedInput*expectedRobustCommand(k);
        expectedRobustIntegral(k+1) = expectedRobustIntegral(k)+ ...
            0.02*robustError;
    end
end
assert(max(abs(baselineA.nominal.speedMPerSec- ...
    expectedNominalSpeed)) < tolerance && ...
    max(abs(baselineA.robust.speedMPerSec-expectedRobustSpeed)) < ...
    tolerance, ...
    'Both baseline histories must follow independently propagated states.');
assert(max(abs(baselineA.nominal.totalCommandMPerSec2- ...
    expectedNominalCommand)) < tolerance && ...
    max(abs(baselineA.robust.totalCommandMPerSec2- ...
    expectedRobustCommand)) < tolerance && ...
    max(abs(baselineA.robust.errorIntegralM- ...
    expectedRobustIntegral)) < tolerance, ...
    'Both command laws and the PI integral state must match definitions.');
expectedNominalIse = 0.02*sum((baselineA.referenceSpeed(1:end-1)- ...
    expectedNominalSpeed(1:end-1)).^2);
expectedRobustIse = 0.02*sum((baselineA.referenceSpeed(1:end-1)- ...
    expectedRobustSpeed(1:end-1)).^2);
expectedNominalEffort = 0.02*sum(expectedNominalCommand(1:end-1).^2);
expectedRobustEffort = 0.02*sum(expectedRobustCommand(1:end-1).^2);
assert(abs(baselineA.nominal.trackingIntegralM2PerSec- ...
    expectedNominalIse) < tolerance && ...
    abs(baselineA.robust.trackingIntegralM2PerSec-expectedRobustIse) < ...
    tolerance && ...
    abs(baselineA.nominal.commandEffortIntegralM2PerSec3- ...
    expectedNominalEffort) < tolerance && ...
    abs(baselineA.robust.commandEffortIntegralM2PerSec3- ...
    expectedRobustEffort) < tolerance, ...
    'Reported ISE and command effort must be direct history integrals.');
assert(abs(baselineA.nominal.trackingIntegralM2PerSec- ...
    0.20713356588115908) < 5e-13 && ...
    abs(baselineA.robust.trackingIntegralM2PerSec- ...
    0.38021285022257995) < 5e-13 && ...
    baselineA.nominal.trackingIntegralM2PerSec < ...
    baselineA.robust.trackingIntegralM2PerSec, ...
    'The nominal design must win the declared matched-plant ISE comparison.');
assert(baselineA.nominal.recurrenceResidualMPerSec < tolerance && ...
    baselineA.robust.recurrenceResidualMPerSec < tolerance && ...
    baselineA.robust.integralRecurrenceResidualM < tolerance, ...
    'Retained recurrence residuals must remain at arithmetic roundoff.');

% Independently repeat all 300 bounded candidate/scenario evaluations.
selection = baselineA.designSelection;
assert(selection.candidateCount == 12 && selection.scenarioCount == 25 && ...
    selection.maximumDesignTransitionCount == 180000 && ...
    selection.commandEffortLimitM2PerSec3 == 90, ...
    'The finite design search must retain exact resource and effort bounds.');
independentWorstIse = zeros(4,3);
independentWorstEffort = zeros(4,3);
independentStable = true(4,3);
independentFeasible = false(4,3);
independentSelectedScore = Inf;
independentSelectedKp = NaN;
independentSelectedKi = NaN;
for proportionalIndex = 1:4
    proportionalGain = ...
        selection.proportionalGainCandidatesPerSec(proportionalIndex);
    for integralIndex = 1:3
        integralGain = ...
            selection.integralGainCandidatesPerSec2(integralIndex);
        for gainRatio = selection.designActuatorGainRatios
            for dragRatio = selection.designDragRatios
                [scenarioIse,scenarioEffort,scenarioPoleMagnitude] = ...
                    independentCandidate(gainRatio,dragRatio, ...
                    proportionalGain,integralGain);
                independentWorstIse(proportionalIndex,integralIndex) = ...
                    max(independentWorstIse(proportionalIndex, ...
                    integralIndex),scenarioIse);
                independentWorstEffort(proportionalIndex,integralIndex) = ...
                    max(independentWorstEffort(proportionalIndex, ...
                    integralIndex),scenarioEffort);
                independentStable(proportionalIndex,integralIndex) = ...
                    independentStable(proportionalIndex,integralIndex) && ...
                    scenarioPoleMagnitude < 1;
            end
        end
        independentFeasible(proportionalIndex,integralIndex) = ...
            independentStable(proportionalIndex,integralIndex) && ...
            independentWorstEffort(proportionalIndex,integralIndex) <= 90;
        if independentFeasible(proportionalIndex,integralIndex) && ...
                independentWorstIse(proportionalIndex,integralIndex) < ...
                independentSelectedScore
            independentSelectedScore = ...
                independentWorstIse(proportionalIndex,integralIndex);
            independentSelectedKp = proportionalGain;
            independentSelectedKi = integralGain;
        end
    end
end
assert(max(abs(independentWorstIse(:)- ...
    selection.worstTrackingIntegralM2PerSec(:))) < 5e-12 && ...
    max(abs(independentWorstEffort(:)- ...
    selection.worstCommandEffortIntegralM2PerSec3(:))) < 5e-11 && ...
    isequal(independentStable,selection.stableAcrossGrid) && ...
    isequal(independentFeasible,selection.feasible), ...
    'Retained design tables must match independent finite enumeration.');
assert(independentSelectedKp == 2 && independentSelectedKi == 0.8 && ...
    selection.selectedProportionalGainPerSec == independentSelectedKp && ...
    selection.selectedIntegralGainPerSec2 == independentSelectedKi && ...
    abs(selection.selectedWorstTrackingIntegralM2PerSec- ...
    1.76331826901075) < 5e-12 && ...
    abs(independentSelectedScore- ...
    selection.selectedWorstTrackingIntegralM2PerSec) < 5e-12, ...
    'The minimax rule and deterministic tie order must select Kp=2, Ki=0.8.');

% Declared worst corner: robust improves ISE, but spends more command effort.
worstCorner = model(0.5,2,1,1,12,0.02);
assert(abs(worstCorner.nominal.trackingIntegralM2PerSec- ...
    3.4960569186739505) < 5e-12 && ...
    abs(worstCorner.robust.trackingIntegralM2PerSec- ...
    1.76331826901075) < 5e-12 && ...
    worstCorner.robust.trackingIntegralM2PerSec < ...
    worstCorner.nominal.trackingIntegralM2PerSec && ...
    worstCorner.robust.commandEffortIntegralM2PerSec3 > ...
    worstCorner.nominal.commandEffortIntegralM2PerSec3 && ...
    worstCorner.robust.commandEffortIntegralM2PerSec3 < 90, ...
    'Worst-grid improvement must retain the visible effort tradeoff.');
assert(abs(worstCorner.nominal.steadyStateSpeedMPerSec-5/11) < ...
    tolerance && worstCorner.robust.steadyStateSpeedMPerSec == 1 && ...
    worstCorner.robust.steadyStateCommandMPerSec2 == 4 && ...
    worstCorner.robust.finalAbsoluteTrackingErrorMPerSec > 0.14, ...
    'Equilibrium limits must be distinct from the finite-horizon final error.');

% Sweep 1: actuator gain only; compare independent reference endpoints.
actuatorGainRatioValues = [0.5 0.75 1 1.25 1.5];
expectedNominalActuatorIse = [1.2833666492520681 ...
    0.4399312062186439 0.20713356588115908 ...
    0.23038033093398774 0.36377707627192346];
expectedRobustActuatorIse = [0.8772224328727535 ...
    0.5382819766662711 0.38021285022257995 ...
    0.2909418147631757 0.23438217453580218];
for k = 1:numel(actuatorGainRatioValues)
    changed = model(actuatorGainRatioValues(k),1,1,1,12,0.02);
    assert(changed.dragRatio == 1 && changed.actuatorSign == 1 && ...
        changed.referenceSpeedMPerSec == 1 && ...
        changed.simulationDurationSec == 12 && ...
        changed.timeStepSec == 0.02, ...
        'The actuator sweep must reset all non-swept inputs.');
    assert(abs(changed.nominal.trackingIntegralM2PerSec- ...
        expectedNominalActuatorIse(k)) < 5e-12 && ...
        abs(changed.robust.trackingIntegralM2PerSec- ...
        expectedRobustActuatorIse(k)) < 5e-12, ...
        'Actuator-sweep metrics must match independent propagation.');
end
assert(expectedNominalActuatorIse(3) < expectedRobustActuatorIse(3) && ...
    expectedNominalActuatorIse(1) > expectedRobustActuatorIse(1) && ...
    expectedNominalActuatorIse(5) > expectedRobustActuatorIse(5), ...
    'Actuator sweep must show matched advantage without pointwise dominance.');

% Sweep 2: drag only; endpoint ISE and steady command have visible meaning.
dragRatioValues = [0.5 0.75 1 1.5 2];
expectedNominalDragIse = [0.7739874042026641 ...
    0.3079630177147654 0.20713356588115908 ...
    0.5206074807863013 1.093920564426119];
expectedRobustDragIse = [0.2682821088938651 ...
    0.31515116473170596 0.38021285022257995 ...
    0.5485197951430376 0.7499735115322869];
for k = 1:numel(dragRatioValues)
    changed = model(1,dragRatioValues(k),1,1,12,0.02);
    assert(changed.actuatorGainRatio == 1 && ...
        changed.actuatorSign == 1 && ...
        changed.referenceSpeedMPerSec == 1 && ...
        changed.simulationDurationSec == 12 && ...
        changed.timeStepSec == 0.02, ...
        'The drag sweep must reset all non-swept inputs.');
    assert(abs(changed.nominal.trackingIntegralM2PerSec- ...
        expectedNominalDragIse(k)) < 5e-12 && ...
        abs(changed.robust.trackingIntegralM2PerSec- ...
        expectedRobustDragIse(k)) < 5e-12 && ...
        abs(changed.robust.steadyStateCommandMPerSec2- ...
        dragRatioValues(k)) < tolerance, ...
        'Drag-sweep metrics and required steady command must match limits.');
end

% Limiting cases, broken structure, stateless recovery, malformed inputs.
matchedRatio = model(0.5,0.5,1,1,12,0.02);
assert(abs(matchedRatio.nominal.steadyStateSpeedMPerSec-1) < ...
    tolerance && matchedRatio.robust.steadyStateSpeedMPerSec == 1, ...
    'Equal actuator and drag ratios preserve the nominal feedforward ratio.');
zeroReference = model(1.5,2,1,0,12,0.02);
assert(max(abs(zeroReference.referenceSpeed)) == 0 && ...
    max(abs(zeroReference.nominal.speedMPerSec)) == 0 && ...
    max(abs(zeroReference.robust.speedMPerSec)) == 0 && ...
    max(abs(zeroReference.nominal.totalCommandMPerSec2)) == 0 && ...
    max(abs(zeroReference.robust.totalCommandMPerSec2)) == 0 && ...
    zeroReference.nominal.trackingIntegralM2PerSec == 0 && ...
    zeroReference.robust.trackingIntegralM2PerSec == 0, ...
    'Zero reference from rest must be an exact equilibrium.');
broken = model(1,1,-1,1,12,0.02);
recovered = model(1,1,1,1,12,0.02);
assert(~broken.nominal.stable && ~broken.robust.stable && ...
    broken.nominal.closedLoopPoleMagnitude > 1 && ...
    broken.robust.closedLoopPoleMagnitude > 1 && ...
    broken.nominal.terminatedEarly && broken.robust.terminatedEarly && ...
    ~broken.nominal.validPerformance && ~broken.robust.validPerformance && ...
    isinf(broken.nominal.comparisonCostM2PerSec) && ...
    isinf(broken.robust.comparisonCostM2PerSec), ...
    'Reversed polarity must fail both stability checks and bounded traces.');
assert(isequaln(recovered,baselineA), ...
    'A fresh positive-polarity call must recover the exact baseline.');

assertAnyError(@() model(NaN,1,1,1,12,0.02), ...
    'A nonfinite actuator ratio must be rejected.');
assertAnyError(@() model([1 1],1,1,1,12,0.02), ...
    'A nonscalar actuator ratio must be rejected.');
assertAnyError(@() model(1,1+1i,1,1,12,0.02), ...
    'A complex drag ratio must be rejected.');
assertAnyError(@() model(-1,1,1,1,12,0.02), ...
    'A negative actuator ratio must be rejected.');
assertAnyError(@() model(1,-1,1,1,12,0.02), ...
    'A negative drag ratio must be rejected.');
assertAnyError(@() model(1,1,1,-1,12,0.02), ...
    'A negative reference speed must be rejected.');
assertAnyError(@() model(1,1,1,1,-12,0.02), ...
    'A negative duration must be rejected.');
assertAnyError(@() model(1,1,1,1,12,-0.02), ...
    'A negative time step must be rejected.');
assertErrorId(@() model(0.49,1,1,1,12,0.02), ...
    'P20:ActuatorGainRatioRange','Too-small actuator ratio must fail.');
assertErrorId(@() model(1.51,1,1,1,12,0.02), ...
    'P20:ActuatorGainRatioRange','Excessive actuator ratio must fail.');
assertErrorId(@() model(1,0.49,1,1,12,0.02), ...
    'P20:DragRatioRange','Too-small drag ratio must fail.');
assertErrorId(@() model(1,2.01,1,1,12,0.02), ...
    'P20:DragRatioRange','Excessive drag ratio must fail.');
assertErrorId(@() model(1,1,0,1,12,0.02), ...
    'P20:ActuatorSign','Malformed actuator sign must fail.');
assertErrorId(@() model(1,1,1,2.01,12,0.02), ...
    'P20:ReferenceSpeedRange','Excessive reference speed must fail.');
assertErrorId(@() model(1,1,1,1,5.99,0.02), ...
    'P20:DurationRange','Too-short duration must fail.');
assertErrorId(@() model(1,1,1,1,20.01,0.02), ...
    'P20:DurationRange','Excessive duration must fail.');
assertErrorId(@() model(1,1,1,1,12,0.051), ...
    'P20:DisplayResolution','Under-resolved time step must fail.');
assertErrorId(@() model(1,1,1,1,12,0.032), ...
    'P20:GridAlignment','Partial final sample must fail.');
assertErrorId(@() model(1,1,1,1,12,0.024), ...
    'P20:EventAlignment','Off-grid reference event must fail.');
assertErrorId(@() model(1,1,1,1,20,0.003), ...
    'P20:TooManySteps','Oversized grid must fail before allocation.');
assertErrorId(@() model(1,1,1,1,20,realmin), ...
    'P20:TooManySteps','Overflowing grid ratio must fail before allocation.');

boundedGrid = model(1.5,2,1,2,20,0.004);
assert(boundedGrid.stepCount == 5000 && ...
    boundedGrid.sampleCount == 5001 && ...
    all(isfinite(boundedGrid.nominal.speedMPerSec)) && ...
    all(isfinite(boundedGrid.robust.speedMPerSec)) && ...
    all(isfinite(boundedGrid.nominal.totalCommandMPerSec2)) && ...
    all(isfinite(boundedGrid.robust.totalCommandMPerSec2)) && ...
    boundedGrid.nominal.validPerformance && ...
    boundedGrid.robust.validPerformance && ...
    boundedGrid.designSelection.maximumDesignTransitionCount == 180000, ...
    'The largest accepted grid and fixed design search must remain bounded.');

disp(['P20 checks passed: deterministic recurrences, finite minimax ' ...
    'selection, matched/worst tradeoffs, two isolated sweeps, polarity ' ...
    'recovery, malformed inputs, and resource bounds.']);
end

function [trackingIntegral,commandEffort,poleMagnitude] = ...
    independentCandidate(gainRatio,dragRatio,proportionalGain,integralGain)
timeStepSec = 0.02;
stepCount = 600;
decay = exp(-dragRatio*timeStepSec);
inputCoefficient = gainRatio/dragRatio*(1-decay);
speed = 0;
integralState = 0;
trackingIntegral = 0;
commandEffort = 0;
for k = 1:stepCount
    referenceSpeed = double((k-1)*timeStepSec >= 1);
    trackingError = referenceSpeed-speed;
    command = proportionalGain*trackingError+integralGain*integralState;
    trackingIntegral = trackingIntegral+timeStepSec*trackingError^2;
    commandEffort = commandEffort+timeStepSec*command^2;
    speed = decay*speed+inputCoefficient*command;
    integralState = integralState+timeStepSec*trackingError;
end
traceValue = decay-inputCoefficient*proportionalGain+1;
determinantValue = decay-inputCoefficient*proportionalGain+ ...
    inputCoefficient*integralGain*timeStepSec;
squareRoot = sqrt(complex(traceValue^2-4*determinantValue,0));
pole1 = (traceValue+squareRoot)/2;
pole2 = (traceValue-squareRoot)/2;
poleMagnitude = max(abs([pole1 pole2]));
end

function assertAnyError(operation,message)
didError = false;
try
    operation();
catch
    didError = true;
end
assert(didError,message);
end

function assertErrorId(operation,expectedIdentifier,message)
actualIdentifier = '';
try
    operation();
catch exception
    actualIdentifier = exception.identifier;
end
assert(strcmp(actualIdentifier,expectedIdentifier),message);
end
