function interactive
%INTERACTIVE Explore P23 sensor and actuator dynamics one lever at a time.
modelFunction = @model;

window = uifigure('Name','P23 - Sensor and actuator dynamics', ...
    'Position',[70 70 1240 780]);
chainAxes = uiaxes(window,'Position',[45 430 750 300]);
errorAxes = uiaxes(window,'Position',[45 65 750 300]);

uilabel(window,'Position',[835 700 330 22], ...
    'Text','Actuator time constant (s)');
actuatorTauSlider = uislider(window,'Position',[840 680 330 3], ...
    'Limits',[0 1.5],'Value',0.2, ...
    'MajorTicks',[0 0.2 0.4 0.8 1.2 1.5]);

uilabel(window,'Position',[835 625 330 22], ...
    'Text','Sensor time constant (s)');
sensorTauSlider = uislider(window,'Position',[840 605 330 3], ...
    'Limits',[0 1.5],'Value',0.1, ...
    'MajorTicks',[0 0.2 0.4 0.8 1.2 1.5]);

uilabel(window,'Position',[835 545 225 22], ...
    'Text','Command half-period (s)');
halfPeriodSpinner = uispinner(window,'Position',[1065 545 105 22], ...
    'Limits',[0.1 4],'Step',0.1,'Value',2);

uilabel(window,'Position',[835 495 225 22], ...
    'Text','Actuator limit (m/s^2)');
limitSpinner = uispinner(window,'Position',[1065 495 105 22], ...
    'Limits',[5 100],'Step',5,'Value',30);

uilabel(window,'Position',[835 445 225 22], ...
    'Text','Sensor bias (m/s^2)');
biasSpinner = uispinner(window,'Position',[1065 445 105 22], ...
    'Limits',[-20 20],'Step',1,'Value',0);

resetButton = uibutton(window,'push','Text','Reset P23 baseline', ...
    'Position',[835 390 335 30]);
statusLabel = uilabel(window,'Position',[835 60 350 300], ...
    'VerticalAlignment','top','WordWrap','on','Text','');

actuatorTauSlider.ValueChangingFcn = @(~,event) redraw(event.Value, ...
    sensorTauSlider.Value,halfPeriodSpinner.Value,limitSpinner.Value, ...
    biasSpinner.Value);
actuatorTauSlider.ValueChangedFcn = @(~,~) redraw( ...
    actuatorTauSlider.Value,sensorTauSlider.Value, ...
    halfPeriodSpinner.Value,limitSpinner.Value,biasSpinner.Value);
sensorTauSlider.ValueChangingFcn = @(~,event) redraw( ...
    actuatorTauSlider.Value,event.Value,halfPeriodSpinner.Value, ...
    limitSpinner.Value,biasSpinner.Value);
sensorTauSlider.ValueChangedFcn = @(~,~) redraw( ...
    actuatorTauSlider.Value,sensorTauSlider.Value, ...
    halfPeriodSpinner.Value,limitSpinner.Value,biasSpinner.Value);
halfPeriodSpinner.ValueChangedFcn = @(~,~) redraw( ...
    actuatorTauSlider.Value,sensorTauSlider.Value, ...
    halfPeriodSpinner.Value,limitSpinner.Value,biasSpinner.Value);
limitSpinner.ValueChangedFcn = @(~,~) redraw( ...
    actuatorTauSlider.Value,sensorTauSlider.Value, ...
    halfPeriodSpinner.Value,limitSpinner.Value,biasSpinner.Value);
biasSpinner.ValueChangedFcn = @(~,~) redraw( ...
    actuatorTauSlider.Value,sensorTauSlider.Value, ...
    halfPeriodSpinner.Value,limitSpinner.Value,biasSpinner.Value);
resetButton.ButtonPushedFcn = @(~,~) resetBaseline();

redraw(0.2,0.1,2,30,0);

function resetBaseline
    actuatorTauSlider.Value = 0.2;
    sensorTauSlider.Value = 0.1;
    halfPeriodSpinner.Value = 2;
    limitSpinner.Value = 30;
    biasSpinner.Value = 0;
    redraw(0.2,0.1,2,30,0);
end

function redraw(actuatorTau,sensorTau,halfPeriod,actuatorLimit,sensorBias)
    result = modelFunction(actuatorTau,sensorTau,halfPeriod,20, ...
        actuatorLimit,sensorBias,0.02,8);

    cla(chainAxes);
    plot(chainAxes,result.timeSec, ...
        result.requestedAccelerationMPerSec2,'k--','LineWidth',1.3, ...
        'DisplayName','Requested acceleration');
    hold(chainAxes,'on');
    plot(chainAxes,result.timeSec,result.actualAccelerationMPerSec2, ...
        'b-','LineWidth',1.8,'DisplayName','Applied acceleration');
    plot(chainAxes,result.timeSec,result.measuredAccelerationMPerSec2, ...
        'm-','LineWidth',1.6,'DisplayName','Measured acceleration');
    yline(chainAxes,actuatorLimit,'r:','Positive actuator limit');
    yline(chainAxes,-actuatorLimit,'r:','Negative actuator limit');
    hold(chainAxes,'off'); grid(chainAxes,'on');
    xlabel(chainAxes,'Time (s)');
    ylabel(chainAxes,'Lateral acceleration (m/s^2)');
    title(chainAxes,'Request, physical actuator, and sensor report');
    legend(chainAxes,'Location','best');

    cla(errorAxes);
    plot(errorAxes,result.timeSec, ...
        result.actuatorTrackingErrorMPerSec2,'b-', ...
        'LineWidth',1.7,'DisplayName','Request - applied');
    hold(errorAxes,'on');
    plot(errorAxes,result.timeSec,result.sensorDynamicErrorMPerSec2, ...
        'm-','LineWidth',1.7,'DisplayName','Applied - sensor state');
    plot(errorAxes,result.timeSec, ...
        result.reportedMeasurementErrorMPerSec2,'c--', ...
        'LineWidth',1.4,'DisplayName','Applied - reported');
    hold(errorAxes,'off'); grid(errorAxes,'on');
    xlabel(errorAxes,'Time (s)');
    ylabel(errorAxes,'Acceleration error (m/s^2)');
    title(errorAxes,'Separate dynamic lag from declared sensor bias');
    legend(errorAxes,'Location','best');

    if result.saturationDurationSec > 0
        interpretation = ['magnitude-limited: the request exceeds actuator ' ...
            'authority before either dynamic state responds'];
    elseif abs(sensorBias) > 0
        interpretation = ['biased measurement: the reported curve includes ' ...
            'a declared static offset in addition to dynamic lag'];
    elseif halfPeriod < 3*max(actuatorTau,sensorTau)
        interpretation = ['bandwidth separation is weak: reversals arrive ' ...
            'before stored actuator and sensor states can settle'];
    else
        interpretation = ['bandwidth separation is visible: applied motion ' ...
            'leads the sensor report after each reversal'];
    end
    statusLabel.Text = sprintf([ ...
        'Actuator tau: %.3f s\nSensor tau: %.3f s\n' ...
        'Command half-period: %.2f s\nCommand amplitude: 20.0 m/s^2\n' ...
        'Actuator limit: %.1f m/s^2\nSensor bias: %.1f m/s^2\n\n' ...
        'Actuator RMS error: %.3f m/s^2\n' ...
        'Sensor dynamic RMS error: %.3f m/s^2\n' ...
        'Reported measurement RMS error: %.3f m/s^2\n' ...
        'Peak applied: %.3f m/s^2\nPeak measured: %.3f m/s^2\n' ...
        'Opposite-sign time: %.3f s\nSaturation time: %.3f s\n\n%s'], ...
        actuatorTau,sensorTau,halfPeriod,actuatorLimit,sensorBias, ...
        result.actuatorTrackingRmsMPerSec2, ...
        result.sensorDynamicRmsMPerSec2, ...
        result.reportedMeasurementRmsMPerSec2, ...
        result.peakActualAccelerationMPerSec2, ...
        result.peakMeasuredAccelerationMPerSec2, ...
        result.oppositeSignDurationSec,result.saturationDurationSec, ...
        interpretation);
end
end
