function result = model(actuatorTimeConstantSec,sensorTimeConstantSec, ...
    commandHalfPeriodSec,commandAmplitudeMPerSec2, ...
    actuatorLimitMPerSec2,sensorBiasMPerSec2,timeStepSec,durationSec)
%MODEL Simulate an exact discrete first-order actuator and sensor cascade.
arguments
    actuatorTimeConstantSec (1,1) double {mustBeReal,mustBeFinite} = 0.2
    sensorTimeConstantSec (1,1) double {mustBeReal,mustBeFinite} = 0.1
    commandHalfPeriodSec (1,1) double ...
        {mustBeReal,mustBeFinite,mustBePositive} = 2
    commandAmplitudeMPerSec2 (1,1) double ...
        {mustBeReal,mustBeFinite,mustBePositive} = 20
    actuatorLimitMPerSec2 (1,1) double ...
        {mustBeReal,mustBeFinite,mustBePositive} = 30
    sensorBiasMPerSec2 (1,1) double {mustBeReal,mustBeFinite} = 0
    timeStepSec (1,1) double ...
        {mustBeReal,mustBeFinite,mustBePositive} = 0.02
    durationSec (1,1) double ...
        {mustBeReal,mustBeFinite,mustBePositive} = 8
end

if actuatorTimeConstantSec < 0 || actuatorTimeConstantSec > 1.5
    error('P23:ActuatorTimeConstantRange', ...
        'Actuator time constant must be between 0 and 1.5 seconds.');
end
if sensorTimeConstantSec < 0 || sensorTimeConstantSec > 1.5
    error('P23:SensorTimeConstantRange', ...
        'Sensor time constant must be between 0 and 1.5 seconds.');
end
if commandHalfPeriodSec < 0.1 || commandHalfPeriodSec > 4
    error('P23:CommandHalfPeriodRange', ...
        'Command half-period must be between 0.1 and 4 seconds.');
end
if commandAmplitudeMPerSec2 < 1 || commandAmplitudeMPerSec2 > 80
    error('P23:CommandAmplitudeRange', ...
        'Command amplitude must be between 1 and 80 m/s^2.');
end
if actuatorLimitMPerSec2 < 5 || actuatorLimitMPerSec2 > 100
    error('P23:ActuatorLimitRange', ...
        'Actuator limit must be between 5 and 100 m/s^2.');
end
if abs(sensorBiasMPerSec2) > 20
    error('P23:SensorBiasRange', ...
        'Sensor bias magnitude must not exceed 20 m/s^2.');
end
if timeStepSec < 0.002 || timeStepSec > 0.05
    error('P23:TimeStepRange', ...
        'Time step must be between 0.002 and 0.05 seconds.');
end
if durationSec < 4 || durationSec > 20
    error('P23:DurationRange', ...
        'Duration must be between 4 and 20 seconds.');
end

durationRatio = durationSec/timeStepSec;
roundedDurationRatio = round(durationRatio);
gridTolerance = 64*eps(max(1,abs(durationRatio)));
if abs(durationRatio-roundedDurationRatio) > gridTolerance
    error('P23:TimeGridMismatch', ...
        'Duration must be an integer multiple of the time step.');
end
halfPeriodRatio = commandHalfPeriodSec/timeStepSec;
samplesPerHalfPeriod = round(halfPeriodRatio);
halfPeriodTolerance = 64*eps(max(1,abs(halfPeriodRatio)));
if abs(halfPeriodRatio-samplesPerHalfPeriod) > halfPeriodTolerance
    error('P23:CommandGridMismatch', ...
        'Command half-period must be an integer multiple of the time step.');
end
minimumStepCount = 81;
maximumStepCount = 5001;
allocatedStepCount = roundedDurationRatio+1;
if allocatedStepCount < minimumStepCount || ...
        allocatedStepCount > maximumStepCount
    error('P23:StepCountRange', ...
        'The derived history must contain between 81 and 5001 samples.');
end

% All resource checks run before histories are allocated. The square-wave
% request stands in for the bounded lateral-acceleration request from P22.
timeSec = (0:roundedDurationRatio)*timeStepSec;
sampleIndex = 0:roundedDurationRatio;
commandSign = 1-2*mod(floor(sampleIndex/samplesPerHalfPeriod),2);
requestedAccelerationMPerSec2 = commandAmplitudeMPerSec2*commandSign;
limitedCommandMPerSec2 = min(max(requestedAccelerationMPerSec2, ...
    -actuatorLimitMPerSec2),actuatorLimitMPerSec2);
actualAccelerationMPerSec2 = zeros(1,allocatedStepCount);
sensorDynamicMPerSec2 = zeros(1,allocatedStepCount);

if actuatorTimeConstantSec == 0
    actuatorDecay = 0;
    actualAccelerationMPerSec2(1) = limitedCommandMPerSec2(1);
else
    actuatorDecay = exp(-timeStepSec/actuatorTimeConstantSec);
end
if sensorTimeConstantSec == 0
    sensorDecay = 0;
    sensorDynamicMPerSec2(1) = actualAccelerationMPerSec2(1);
else
    sensorDecay = exp(-timeStepSec/sensorTimeConstantSec);
end

% Exact zero-order-hold recurrence for
%   tau_a*a_dot+a=u, tau_s*y_dot+y=a.
% The equal-time-constant branch is the finite repeated-pole limit.
for k = 2:allocatedStepCount
    previousIntervalCommandMPerSec2 = limitedCommandMPerSec2(k-1);
    currentCommandMPerSec2 = limitedCommandMPerSec2(k);
    previousActualMPerSec2 = actualAccelerationMPerSec2(k-1);
    previousSensorDynamicMPerSec2 = sensorDynamicMPerSec2(k-1);
    if actuatorTimeConstantSec == 0
        % An ideal actuator can jump with the right-continuous current input.
        actualAccelerationMPerSec2(k) = currentCommandMPerSec2;
    else
        actualAccelerationMPerSec2(k) = actuatorDecay* ...
            previousActualMPerSec2+(1-actuatorDecay)* ...
            previousIntervalCommandMPerSec2;
    end

    if sensorTimeConstantSec == 0
        sensorDynamicMPerSec2(k) = actualAccelerationMPerSec2(k);
    elseif actuatorTimeConstantSec == 0
        % A dynamic sensor integrates the actuator value held over the
        % preceding interval; it cannot anticipate the endpoint jump.
        sensorDynamicMPerSec2(k) = sensorDecay* ...
            previousSensorDynamicMPerSec2+(1-sensorDecay)* ...
            previousIntervalCommandMPerSec2;
    else
        timeConstantDifferenceSec = actuatorTimeConstantSec- ...
            sensorTimeConstantSec;
        equalityTolerance = sqrt(eps)*max([1 actuatorTimeConstantSec ...
            sensorTimeConstantSec]);
        if timeConstantDifferenceSec == 0
            % The mathematical x*exp(-x) limit is zero when an accepted
            % positive tau is so small that x=dt/tau overflows.
            if actuatorDecay == 0
                cascadeCoefficient = 0;
            else
                cascadeCoefficient = ...
                    (timeStepSec/actuatorTimeConstantSec)*actuatorDecay;
            end
        elseif abs(timeConstantDifferenceSec) <= equalityTolerance
            % Evaluate the unequal near-repeated-pole coefficient with
            % expm1 so close decays are not subtracted catastrophically.
            % If both decays underflow, their finite coefficient limit is 0.
            if actuatorDecay == 0 && sensorDecay == 0
                cascadeCoefficient = 0;
            else
                decayExponentDifference = ...
                    (timeStepSec/sensorTimeConstantSec)* ...
                    (timeConstantDifferenceSec/actuatorTimeConstantSec);
                cascadeCoefficient = ...
                    (timeStepSec/sensorTimeConstantSec)*actuatorDecay* ...
                    (-expm1(-decayExponentDifference)/ ...
                    decayExponentDifference);
            end
        else
            cascadeCoefficient = actuatorTimeConstantSec/ ...
                timeConstantDifferenceSec* ...
                (actuatorDecay-sensorDecay);
        end
        sensorDynamicMPerSec2(k) = sensorDecay* ...
            previousSensorDynamicMPerSec2+(1-sensorDecay)* ...
            previousIntervalCommandMPerSec2+cascadeCoefficient* ...
            (previousActualMPerSec2-previousIntervalCommandMPerSec2);
    end
end

measuredAccelerationMPerSec2 = ...
    sensorDynamicMPerSec2+sensorBiasMPerSec2;
saturationTolerance = 64*eps(max([1 commandAmplitudeMPerSec2 ...
    actuatorLimitMPerSec2]));
saturated = abs(requestedAccelerationMPerSec2) > ...
    actuatorLimitMPerSec2+saturationTolerance;
actuatorTrackingErrorMPerSec2 = ...
    requestedAccelerationMPerSec2-actualAccelerationMPerSec2;
sensorDynamicErrorMPerSec2 = ...
    actualAccelerationMPerSec2-sensorDynamicMPerSec2;
reportedMeasurementErrorMPerSec2 = ...
    actualAccelerationMPerSec2-measuredAccelerationMPerSec2;
oppositeSign = requestedAccelerationMPerSec2.* ...
    sensorDynamicMPerSec2 < 0 & ...
    abs(sensorDynamicMPerSec2) > 0.01*commandAmplitudeMPerSec2;

actuatorTrackingRmsMPerSec2 = sqrt(mean( ...
    actuatorTrackingErrorMPerSec2.^2));
sensorDynamicRmsMPerSec2 = sqrt(mean(sensorDynamicErrorMPerSec2.^2));
reportedMeasurementRmsMPerSec2 = sqrt(mean( ...
    reportedMeasurementErrorMPerSec2.^2));
saturationDurationSec = sum(saturated(1:end-1))*timeStepSec;
oppositeSignDurationSec = sum(oppositeSign(1:end-1))*timeStepSec;
firstPlateauLastIndex = min(samplesPerHalfPeriod,allocatedStepCount);

result = struct( ...
    'actuatorTimeConstantSec',actuatorTimeConstantSec, ...
    'sensorTimeConstantSec',sensorTimeConstantSec, ...
    'commandHalfPeriodSec',commandHalfPeriodSec, ...
    'commandAmplitudeMPerSec2',commandAmplitudeMPerSec2, ...
    'actuatorLimitMPerSec2',actuatorLimitMPerSec2, ...
    'sensorBiasMPerSec2',sensorBiasMPerSec2, ...
    'timeStepSec',timeStepSec, ...
    'durationSec',durationSec, ...
    'minimumStepCount',minimumStepCount, ...
    'maximumStepCount',maximumStepCount, ...
    'allocatedStepCount',allocatedStepCount, ...
    'samplesPerHalfPeriod',samplesPerHalfPeriod, ...
    'actuatorDecay',actuatorDecay, ...
    'sensorDecay',sensorDecay, ...
    'timeSec',timeSec, ...
    'requestedAccelerationMPerSec2',requestedAccelerationMPerSec2, ...
    'limitedCommandMPerSec2',limitedCommandMPerSec2, ...
    'actualAccelerationMPerSec2',actualAccelerationMPerSec2, ...
    'sensorDynamicMPerSec2',sensorDynamicMPerSec2, ...
    'measuredAccelerationMPerSec2',measuredAccelerationMPerSec2, ...
    'actuatorTrackingErrorMPerSec2', ...
    actuatorTrackingErrorMPerSec2, ...
    'sensorDynamicErrorMPerSec2',sensorDynamicErrorMPerSec2, ...
    'reportedMeasurementErrorMPerSec2', ...
    reportedMeasurementErrorMPerSec2, ...
    'saturated',saturated, ...
    'oppositeSign',oppositeSign, ...
    'actuatorTrackingRmsMPerSec2',actuatorTrackingRmsMPerSec2, ...
    'sensorDynamicRmsMPerSec2',sensorDynamicRmsMPerSec2, ...
    'reportedMeasurementRmsMPerSec2', ...
    reportedMeasurementRmsMPerSec2, ...
    'saturationDurationSec',saturationDurationSec, ...
    'oppositeSignDurationSec',oppositeSignDurationSec, ...
    'peakActualAccelerationMPerSec2', ...
    max(abs(actualAccelerationMPerSec2)), ...
    'peakMeasuredAccelerationMPerSec2', ...
    max(abs(measuredAccelerationMPerSec2)), ...
    'firstPlateauActualMPerSec2', ...
    actualAccelerationMPerSec2(firstPlateauLastIndex), ...
    'firstPlateauMeasuredMPerSec2', ...
    measuredAccelerationMPerSec2(firstPlateauLastIndex));
end
