function run_checks
%RUN_CHECKS Verify P23 dynamics, limits, failures, and bounded execution.
tolerance = 2e-10;
baselineA = model(0.2,0.1,2,20,30,0,0.02,8);
baselineB = model(0.2,0.1,2,20,30,0,0.02,8);
assert(isequaln(baselineA,baselineB), ...
    'Repeated baseline calls must be exactly deterministic.');

% Reconstruct the command schedule and clipping independently.
sampleIndex = 0:baselineA.allocatedStepCount-1;
expectedSign = 1-2*mod(floor( ...
    sampleIndex/baselineA.samplesPerHalfPeriod),2);
expectedRequest = baselineA.commandAmplitudeMPerSec2*expectedSign;
expectedLimited = min(max(expectedRequest, ...
    -baselineA.actuatorLimitMPerSec2), ...
    baselineA.actuatorLimitMPerSec2);
assert(isequal(baselineA.requestedAccelerationMPerSec2,expectedRequest) && ...
    isequal(baselineA.limitedCommandMPerSec2,expectedLimited), ...
    'The square-wave request and signed magnitude limit must be exact.');

% Reconstruct every exact zero-order-hold state update from the preceding
% states. This check does not trust the model summary metrics.
actuatorDecay = exp(-baselineA.timeStepSec/ ...
    baselineA.actuatorTimeConstantSec);
sensorDecay = exp(-baselineA.timeStepSec/ ...
    baselineA.sensorTimeConstantSec);
cascadeCoefficient = baselineA.actuatorTimeConstantSec/ ...
    (baselineA.actuatorTimeConstantSec- ...
    baselineA.sensorTimeConstantSec)*(actuatorDecay-sensorDecay);
for k = 2:baselineA.allocatedStepCount
    intervalCommand = expectedLimited(k-1);
    expectedActual = actuatorDecay* ...
        baselineA.actualAccelerationMPerSec2(k-1)+ ...
        (1-actuatorDecay)*intervalCommand;
    expectedSensor = sensorDecay* ...
        baselineA.sensorDynamicMPerSec2(k-1)+ ...
        (1-sensorDecay)*intervalCommand+cascadeCoefficient* ...
        (baselineA.actualAccelerationMPerSec2(k-1)-intervalCommand);
    assert(abs(baselineA.actualAccelerationMPerSec2(k)- ...
        expectedActual) < tolerance && ...
        abs(baselineA.sensorDynamicMPerSec2(k)- ...
        expectedSensor) < tolerance, ...
        'Actuator and sensor states must match the exact recurrence.');
end
firstReversalIndex = baselineA.samplesPerHalfPeriod+1;
expectedBoundaryActual = 20*(1-exp(-2/0.2));
expectedBoundarySensor = 20*(1-(0.2*exp(-2/0.2)- ...
    0.1*exp(-2/0.1))/(0.2-0.1));
assert(expectedRequest(firstReversalIndex) == -20 && ...
    abs(baselineA.actualAccelerationMPerSec2(firstReversalIndex)- ...
    expectedBoundaryActual) < tolerance && ...
    abs(baselineA.sensorDynamicMPerSec2(firstReversalIndex)- ...
    expectedBoundarySensor) < tolerance && ...
    baselineA.actualAccelerationMPerSec2(firstReversalIndex) > ...
    baselineA.actualAccelerationMPerSec2(firstReversalIndex-1) && ...
    baselineA.sensorDynamicMPerSec2(firstReversalIndex) > ...
    baselineA.sensorDynamicMPerSec2(firstReversalIndex-1) && ...
    baselineA.actualAccelerationMPerSec2(firstReversalIndex+1) < ...
    baselineA.actualAccelerationMPerSec2(firstReversalIndex), ...
    ['Positive-time-constant states must finish the preceding positive ' ...
    'hold before reacting to the reversal at its timestamp.']);
assert(max(abs(baselineA.measuredAccelerationMPerSec2- ...
    baselineA.sensorDynamicMPerSec2)) == 0, ...
    'A zero-bias sensor report must equal its dynamic state.');
assert(max(abs(baselineA.actualAccelerationMPerSec2)) <= 30 && ...
    max(abs(baselineA.sensorDynamicMPerSec2)) <= 30, ...
    'Stable first-order states must stay inside the bounded input envelope.');

% Independent constant-step formulas at the last sample before reversal.
firstPlateauTimeSec = ...
    (baselineA.samplesPerHalfPeriod-1)*baselineA.timeStepSec;
expectedFirstActuator = 20*(1-exp( ...
    -firstPlateauTimeSec/baselineA.actuatorTimeConstantSec));
expectedFirstSensor = 20*(1-( ...
    baselineA.actuatorTimeConstantSec*exp( ...
    -firstPlateauTimeSec/baselineA.actuatorTimeConstantSec)- ...
    baselineA.sensorTimeConstantSec*exp( ...
    -firstPlateauTimeSec/baselineA.sensorTimeConstantSec))/ ...
    (baselineA.actuatorTimeConstantSec- ...
    baselineA.sensorTimeConstantSec));
assert(abs(baselineA.firstPlateauActualMPerSec2- ...
    expectedFirstActuator) < tolerance && ...
    abs(baselineA.firstPlateauMeasuredMPerSec2- ...
    expectedFirstSensor) < tolerance, ...
    'First-plateau states must match independent analytic step responses.');
assert(abs(baselineA.firstPlateauActualMPerSec2- ...
    19.99899650635887) < tolerance && ...
    abs(baselineA.firstPlateauMeasuredMPerSec2- ...
    19.997993063067714) < tolerance && ...
    abs(baselineA.actuatorTrackingRmsMPerSec2- ...
    8.690359273336114) < tolerance && ...
    abs(baselineA.sensorDynamicRmsMPerSec2- ...
    3.287018981667333) < tolerance && ...
    abs(baselineA.oppositeSignDurationSec-0.78) < tolerance && ...
    baselineA.saturationDurationSec == 0, ...
    'Baseline retained metrics must remain deterministic.');

% Sensor sweep changes no upstream value and increases dynamic mismatch.
sensorTimeConstantValuesSec = [0 0.02 0.05 0.1 0.2 0.4];
sensorRmsError = zeros(size(sensorTimeConstantValuesSec));
for k = 1:numel(sensorTimeConstantValuesSec)
    changed = model(0.2,sensorTimeConstantValuesSec(k), ...
        2,20,30,0,0.02,8);
    assert(changed.actuatorTimeConstantSec == 0.2 && ...
        changed.commandHalfPeriodSec == 2 && ...
        changed.commandAmplitudeMPerSec2 == 20 && ...
        changed.actuatorLimitMPerSec2 == 30 && ...
        changed.sensorBiasMPerSec2 == 0 && ...
        changed.timeStepSec == 0.02 && changed.durationSec == 8, ...
        'Sensor sweep must reset every non-swept input.');
    assert(isequal(changed.requestedAccelerationMPerSec2, ...
        baselineA.requestedAccelerationMPerSec2) && ...
        isequal(changed.actualAccelerationMPerSec2, ...
        baselineA.actualAccelerationMPerSec2), ...
        'Sensor time constant must not alter command or actuator history.');
    sensorRmsError(k) = changed.sensorDynamicRmsMPerSec2;
end
assert(sensorRmsError(1) == 0 && all(diff(sensorRmsError) > 0), ...
    'Sensor lag error must grow across the isolated sweep.');

% Actuator sweep changes no request and increases request-to-motion error.
actuatorTimeConstantValuesSec = [0 0.05 0.1 0.2 0.4 0.8];
actuatorRmsError = zeros(size(actuatorTimeConstantValuesSec));
for k = 1:numel(actuatorTimeConstantValuesSec)
    changed = model(actuatorTimeConstantValuesSec(k),0.1, ...
        2,20,30,0,0.02,8);
    assert(changed.sensorTimeConstantSec == 0.1 && ...
        changed.commandHalfPeriodSec == 2 && ...
        changed.commandAmplitudeMPerSec2 == 20 && ...
        changed.actuatorLimitMPerSec2 == 30 && ...
        changed.sensorBiasMPerSec2 == 0 && ...
        changed.timeStepSec == 0.02 && changed.durationSec == 8, ...
        'Actuator sweep must reset every non-swept input.');
    assert(isequal(changed.requestedAccelerationMPerSec2, ...
        baselineA.requestedAccelerationMPerSec2), ...
        'Actuator time constant must not alter the request.');
    actuatorRmsError(k) = changed.actuatorTrackingRmsMPerSec2;
end
assert(actuatorRmsError(1) == 0 && all(diff(actuatorRmsError) > 0), ...
    'Actuator lag error must grow across the isolated sweep.');

% Ideal limits and the equal-time-constant repeated-pole branch.
ideal = model(0,0,2,20,30,0,0.02,8);
assert(isequal(ideal.actualAccelerationMPerSec2, ...
    ideal.limitedCommandMPerSec2) && ...
    isequal(ideal.sensorDynamicMPerSec2, ...
    ideal.actualAccelerationMPerSec2) && ...
    ideal.actuatorTrackingRmsMPerSec2 == 0 && ...
    ideal.sensorDynamicRmsMPerSec2 == 0, ...
    'Zero time constants must reduce to the ideal static chain.');
equalTau = model(0.2,0.2,2,20,30,0,0.02,8);
nearEqualTau = model(0.2,0.2+1e-10,2,20,30,0,0.02,8);
equalDecay = exp(-0.02/0.2);
equalCoefficient = (0.02/0.2)*equalDecay;
expectedEqualFirstStep = (1-equalDecay)*20+ ...
    equalCoefficient*(0-20);
assert(all(isfinite(equalTau.sensorDynamicMPerSec2)) && ...
    abs(equalTau.sensorDynamicMPerSec2(2)- ...
    expectedEqualFirstStep) < tolerance && ...
    all(isfinite(nearEqualTau.sensorDynamicMPerSec2)) && ...
    max(abs(nearEqualTau.sensorDynamicMPerSec2- ...
    equalTau.sensorDynamicMPerSec2)) < 2e-8, ...
    'Equal time constants must use the finite repeated-pole limit.');
smallestPositiveTimeConstantSec = realmin*eps;
smallPositiveTau = model(smallestPositiveTimeConstantSec, ...
    smallestPositiveTimeConstantSec,2,20,30,0,0.02,8);
assert(smallestPositiveTimeConstantSec > 0 && ...
    all(isfinite(smallPositiveTau.actualAccelerationMPerSec2)) && ...
    all(isfinite(smallPositiveTau.sensorDynamicMPerSec2)) && ...
    isequal(smallPositiveTau.actualAccelerationMPerSec2, ...
    smallPositiveTau.sensorDynamicMPerSec2) && ...
    smallPositiveTau.actualAccelerationMPerSec2(2) == 20, ...
    ['Accepted positive time constants below the exponential underflow ' ...
    'scale must approach the ideal-device limit without NaN histories.']);

% Signed saturation and bias remain separate from dynamic lag.
saturated = model(0.2,0.1,2,50,15,0,0.02,8);
assert(all(abs(saturated.limitedCommandMPerSec2) == 15) && ...
    max(abs(saturated.actualAccelerationMPerSec2)) <= 15 && ...
    max(abs(saturated.sensorDynamicMPerSec2)) <= 15 && ...
    saturated.saturationDurationSec == 8, ...
    'Magnitude limiting must clip both command signs before dynamics.');
biased = model(0.2,0.1,2,20,30,5,0.02,8);
assert(isequal(biased.actualAccelerationMPerSec2, ...
    baselineA.actualAccelerationMPerSec2) && ...
    isequal(biased.sensorDynamicMPerSec2, ...
    baselineA.sensorDynamicMPerSec2) && ...
    max(abs((biased.measuredAccelerationMPerSec2- ...
    biased.sensorDynamicMPerSec2)-5)) < tolerance && ...
    max(abs((biased.reportedMeasurementErrorMPerSec2- ...
    baselineA.reportedMeasurementErrorMPerSec2)+5)) < tolerance, ...
    'Static sensor bias must shift only the reported measurement.');

% Broken bandwidth separation, bounded duration, and exact recovery.
broken = model(0.8,0.6,0.1,20,30,0,0.01,4);
bandwidthRecovered = model(0.8,0.6,4,20,30,0,0.01,4);
shortDuration = model(0.2,0.1,2,20,30,0,0.05,4);
recovered = model(0.2,0.1,2,20,30,0,0.02,8);
assert(broken.peakActualAccelerationMPerSec2 < 3 && ...
    broken.peakMeasuredAccelerationMPerSec2 < 1 && ...
    broken.oppositeSignDurationSec > 0.5, ...
    'Fast reversals must expose the broken bandwidth assumption.');
assert(bandwidthRecovered.peakActualAccelerationMPerSec2 > 19 && ...
    bandwidthRecovered.peakMeasuredAccelerationMPerSec2 > 19 && ...
    bandwidthRecovered.oppositeSignDurationSec == 0, ...
    ['Changing only the command half-period must restore bandwidth ' ...
    'separation for the same slow devices and grid.']);
assert(shortDuration.timeSec(end) == 4 && ...
    shortDuration.allocatedStepCount == 81, ...
    'The minimum accepted history must stop at its bounded duration.');
assert(isequaln(recovered,baselineA), ...
    'A fresh valid call must recover after broken and bounded cases.');

% Malformed inputs and resource bounds fail before history allocation.
assertAnyError(@() model(NaN,0.1,2,20,30,0,0.02,8), ...
    'A nonfinite actuator time constant must be rejected.');
assertAnyError(@() model(0.2,[0.1 0.2],2,20,30,0,0.02,8), ...
    'A nonscalar sensor time constant must be rejected.');
assertAnyError(@() model(0.2,0.1,2+1i,20,30,0,0.02,8), ...
    'A complex command half-period must be rejected.');
assertAnyError(@() model(0.2,0.1,2,Inf,30,0,0.02,8), ...
    'A nonfinite amplitude must be rejected.');
assertAnyError(@() model(0.2,0.1,2,20,30,NaN,0.02,8), ...
    'A nonfinite sensor bias must be rejected.');
assertErrorId(@() model(-0.01,0.1,2,20,30,0,0.02,8), ...
    'P23:ActuatorTimeConstantRange','Negative actuator tau must fail.');
assertErrorId(@() model(1.51,0.1,2,20,30,0,0.02,8), ...
    'P23:ActuatorTimeConstantRange','Excessive actuator tau must fail.');
assertErrorId(@() model(0.2,-0.01,2,20,30,0,0.02,8), ...
    'P23:SensorTimeConstantRange','Negative sensor tau must fail.');
assertErrorId(@() model(0.2,1.51,2,20,30,0,0.02,8), ...
    'P23:SensorTimeConstantRange','Excessive sensor tau must fail.');
assertErrorId(@() model(0.2,0.1,0.09,20,30,0,0.01,8), ...
    'P23:CommandHalfPeriodRange','Too-fast command must fail.');
assertErrorId(@() model(0.2,0.1,4.01,20,30,0,0.01,8), ...
    'P23:CommandHalfPeriodRange','Too-slow command must fail.');
assertErrorId(@() model(0.2,0.1,2,0.99,30,0,0.02,8), ...
    'P23:CommandAmplitudeRange','Too-small amplitude must fail.');
assertErrorId(@() model(0.2,0.1,2,80.01,30,0,0.02,8), ...
    'P23:CommandAmplitudeRange','Excessive amplitude must fail.');
assertErrorId(@() model(0.2,0.1,2,20,4.99,0,0.02,8), ...
    'P23:ActuatorLimitRange','Too-small limit must fail.');
assertErrorId(@() model(0.2,0.1,2,20,100.01,0,0.02,8), ...
    'P23:ActuatorLimitRange','Excessive limit must fail.');
assertErrorId(@() model(0.2,0.1,2,20,30,20.01,0.02,8), ...
    'P23:SensorBiasRange','Excessive positive bias must fail.');
assertErrorId(@() model(0.2,0.1,2,20,30,-20.01,0.02,8), ...
    'P23:SensorBiasRange','Excessive negative bias must fail.');
assertErrorId(@() model(0.2,0.1,2,20,30,0,0.0019,8), ...
    'P23:TimeStepRange','Too-small step must fail.');
assertErrorId(@() model(0.2,0.1,2,20,30,0,0.0501,8), ...
    'P23:TimeStepRange','Too-large step must fail.');
assertErrorId(@() model(0.2,0.1,2,20,30,0,0.02,3.99), ...
    'P23:DurationRange','Too-short duration must fail.');
assertErrorId(@() model(0.2,0.1,2,20,30,0,0.02,20.01), ...
    'P23:DurationRange','Too-long duration must fail.');
assertErrorId(@() model(0.2,0.1,2,20,30,0,0.03,8), ...
    'P23:TimeGridMismatch','A fractional duration grid must fail.');
assertErrorId(@() model(0.2,0.1,0.11,20,30,0,0.02,8), ...
    'P23:CommandGridMismatch','A fractional command grid must fail.');
assertErrorId(@() model(0.2,0.1,0.2,20,30,0,0.002,20), ...
    'P23:StepCountRange','Oversized history must fail before allocation.');

boundedHistory = model(1.5,1.5,0.2,80,100,20,0.004,20);
afterBoundedHistory = model(0.2,0.1,2,20,30,0,0.02,8);
assert(boundedHistory.allocatedStepCount == 5001 && ...
    numel(boundedHistory.timeSec) == 5001 && ...
    all(isfinite(boundedHistory.actualAccelerationMPerSec2)) && ...
    all(isfinite(boundedHistory.measuredAccelerationMPerSec2)) && ...
    max(abs(boundedHistory.actualAccelerationMPerSec2)) <= 80 && ...
    max(abs(boundedHistory.measuredAccelerationMPerSec2)) <= 100, ...
    'The largest accepted history must remain finite and bounded.');
assert(isequaln(afterBoundedHistory,baselineA), ...
    'Maximum-history execution must not leak state into a fresh baseline.');

disp(['P23 checks passed: exact first-order states, independent step ' ...
    'limits, two isolated sweeps, saturation, bias, broken bandwidth, ' ...
    'bounded duration, recovery, malformed inputs, and resource bounds.']);
end

function assertAnyError(operation,message)
didError = false;
try
    operation();
catch
    didError = true;
end
assert(didError,message);
end

function assertErrorId(operation,expectedIdentifier,message)
actualIdentifier = '';
try
    operation();
catch exception
    actualIdentifier = exception.identifier;
end
assert(strcmp(actualIdentifier,expectedIdentifier),message);
end
