function out = model(positionErrorWeight,controlEffortWeight, ...
    actuatorEffectiveness,initialPositionM,simulationDurationSec,timeStepSec)
%MODEL Regulate a damped cart with a transparent discrete LQR design.
arguments
    positionErrorWeight (1,1) double ...
        {mustBeReal,mustBeFinite,mustBeNonnegative} = 4
    controlEffortWeight (1,1) double ...
        {mustBeReal,mustBeFinite,mustBePositive} = 1
    actuatorEffectiveness (1,1) double ...
        {mustBeReal,mustBeFinite,mustBeNonnegative} = 1
    initialPositionM (1,1) double ...
        {mustBeReal,mustBeFinite} = 1
    simulationDurationSec (1,1) double ...
        {mustBeReal,mustBeFinite,mustBePositive} = 12
    timeStepSec (1,1) double ...
        {mustBeReal,mustBeFinite,mustBePositive} = 0.02
end

maximumPositionErrorWeight = 25;
minimumPositivePositionErrorWeight = 0.25;
minimumControlEffortWeight = 0.05;
maximumControlEffortWeight = 20;
maximumInitialPositionM = 2;
minimumSimulationDurationSec = 8;
maximumSimulationDurationSec = 20;
maximumTimeStepSec = 0.05;
maximumStepCount = 5000;
if (positionErrorWeight > 0 && ...
        positionErrorWeight < minimumPositivePositionErrorWeight) || ...
        positionErrorWeight > maximumPositionErrorWeight
    error('P17:PositionWeightRange', ...
        'Position-error weight must be zero or between 0.25 and 25.');
end
if controlEffortWeight < minimumControlEffortWeight || ...
        controlEffortWeight > maximumControlEffortWeight
    error('P17:EffortWeightRange', ...
        'Control-effort weight must be between 0.05 and 20.');
end
if actuatorEffectiveness > 1
    error('P17:ActuatorEffectivenessRange', ...
        'Actuator effectiveness must be between 0 and 1.');
end
if abs(initialPositionM) > maximumInitialPositionM
    error('P17:InitialPositionRange', ...
        'Initial position magnitude must not exceed 2 m.');
end
if simulationDurationSec < minimumSimulationDurationSec || ...
        simulationDurationSec > maximumSimulationDurationSec
    error('P17:DurationRange', ...
        'Simulation duration must be between 8 and 20 s.');
end
if timeStepSec > maximumTimeStepSec
    error('P17:DisplayResolution', ...
        'The sample interval must not exceed 0.05 s.');
end

stepRatio = simulationDurationSec/timeStepSec;
if isinf(stepRatio)
    error('P17:TooManySteps', ...
        'Requested grid exceeds the 5000-step resource bound.');
end
stepCount = round(stepRatio);
alignmentTolerance = 64*eps(max(1,abs(stepRatio)));
if abs(stepRatio-stepCount) > alignmentTolerance
    error('P17:GridAlignment', ...
        'Simulation duration must be an integer multiple of the sample interval.');
end
if stepCount > maximumStepCount
    error('P17:TooManySteps', ...
        'Requested grid exceeds the 5000-step resource bound.');
end

% Retain P16's known damped cart: p_dot=v, v_dot=-d*v+u.
dampingPerSec = 0.5;
decay = exp(-dampingPerSec*timeStepSec);
positionFromRateSec = (1-decay)/dampingPerSec;
positionFromAccelerationSec2 = ...
    (timeStepSec-positionFromRateSec)/dampingPerSec;
discreteA = [1 positionFromRateSec;0 decay];
discreteB = [positionFromAccelerationSec2;positionFromRateSec];

% Each cost integrand is dimensionless because p, v, and u are divided by
% 1-unit scales. Time integration gives the retained score units of seconds.
positionScaleM = 1;
rateScaleMPerSec = 1;
accelerationScaleMPerSec2 = 1;
rateErrorWeight = 1;
stateCost = diag([positionErrorWeight/positionScaleM^2, ...
    rateErrorWeight/rateScaleMPerSec^2]);
inputCost = controlEffortWeight/accelerationScaleMPerSec2^2;

% Solve the infinite-horizon discrete Riccati equation by visible iteration.
% This is the operation hidden by lqr/dare toolbox calls.
riccatiMatrix = stateCost;
riccatiTolerance = 1e-12;
maximumRiccatiIterations = 40000;
riccatiConverged = false;
for riccatiIterationCount = 1:maximumRiccatiIterations
    controlCurvature = inputCost+ ...
        discreteB.'*riccatiMatrix*discreteB;
    if controlCurvature <= 0
        error('P17:ControlCurvature', ...
            'The one-step control cost must remain positive.');
    end
    trialGain = (discreteB.'*riccatiMatrix*discreteA)/ ...
        controlCurvature;
    nextRiccatiMatrix = stateCost+ ...
        discreteA.'*riccatiMatrix*discreteA- ...
        discreteA.'*riccatiMatrix*discreteB*trialGain;
    nextRiccatiMatrix = ...
        (nextRiccatiMatrix+nextRiccatiMatrix.')/2;
    riccatiDelta = max(abs(nextRiccatiMatrix(:)-riccatiMatrix(:)));
    riccatiScale = max(1,max(abs(nextRiccatiMatrix(:))));
    riccatiMatrix = nextRiccatiMatrix;
    if riccatiDelta <= riccatiTolerance*riccatiScale
        riccatiConverged = true;
        break
    end
end
if ~riccatiConverged
    error('P17:RiccatiConvergence', ...
        'Transparent Riccati iteration did not converge within its fixed bound.');
end
controlCurvature = inputCost+discreteB.'*riccatiMatrix*discreteB;
feedbackGain = (discreteB.'*riccatiMatrix*discreteA)/controlCurvature;
riccatiRightHandSide = stateCost+ ...
    discreteA.'*riccatiMatrix*discreteA- ...
    discreteA.'*riccatiMatrix*discreteB*feedbackGain;
riccatiResidual = riccatiMatrix-riccatiRightHandSide;

nominalClosedLoopA = discreteA-discreteB*feedbackGain;
closedLoopTrace = nominalClosedLoopA(1,1)+nominalClosedLoopA(2,2);
closedLoopDeterminant = nominalClosedLoopA(1,1)* ...
    nominalClosedLoopA(2,2)-nominalClosedLoopA(1,2)* ...
    nominalClosedLoopA(2,1);
closedLoopDiscriminant = closedLoopTrace^2-4*closedLoopDeterminant;
closedLoopRoot = sqrt(complex(closedLoopDiscriminant,0));
nominalClosedLoopPoles = ...
    [(closedLoopTrace+closedLoopRoot)/2; ...
    (closedLoopTrace-closedLoopRoot)/2];
nominalSpectralRadius = max(abs(nominalClosedLoopPoles));
actualClosedLoopA = discreteA-actuatorEffectiveness*discreteB*feedbackGain;
actualClosedLoopTrace = actualClosedLoopA(1,1)+actualClosedLoopA(2,2);
actualClosedLoopDeterminant = actualClosedLoopA(1,1)* ...
    actualClosedLoopA(2,2)-actualClosedLoopA(1,2)*actualClosedLoopA(2,1);
actualClosedLoopDiscriminant = ...
    actualClosedLoopTrace^2-4*actualClosedLoopDeterminant;
actualClosedLoopRoot = sqrt(complex(actualClosedLoopDiscriminant,0));
actualClosedLoopPoles = ...
    [(actualClosedLoopTrace+actualClosedLoopRoot)/2; ...
    (actualClosedLoopTrace-actualClosedLoopRoot)/2];
actualSpectralRadius = max(abs(actualClosedLoopPoles));

sampleCount = stepCount+1;
timeSec = (0:stepCount)*timeStepSec;
state = zeros(2,sampleCount);
commandedAccelerationMPerSec2 = zeros(1,sampleCount);
appliedAccelerationMPerSec2 = zeros(1,sampleCount);
state(:,1) = [initialPositionM;0];
for k = 1:sampleCount
    commandedAccelerationMPerSec2(k) = -feedbackGain*state(:,k);
    appliedAccelerationMPerSec2(k) = ...
        actuatorEffectiveness*commandedAccelerationMPerSec2(k);
    if k <= stepCount
        state(:,k+1) = discreteA*state(:,k)+ ...
            discreteB*appliedAccelerationMPerSec2(k);
    end
end

positionErrorM = state(1,:);
rateErrorMPerSec = state(2,:);
positionIntegralSquaredM2Sec = timeStepSec* ...
    sum(positionErrorM(1:end-1).^2);
rateIntegralSquaredM2PerSec = timeStepSec* ...
    sum(rateErrorMPerSec(1:end-1).^2);
commandedEffortIntegralM2PerSec3 = timeStepSec* ...
    sum(commandedAccelerationMPerSec2(1:end-1).^2);
appliedEffortIntegralM2PerSec3 = timeStepSec* ...
    sum(appliedAccelerationMPerSec2(1:end-1).^2);
normalizedStateCostIntegralSec = positionErrorWeight* ...
    positionIntegralSquaredM2Sec/positionScaleM^2+ ...
    rateErrorWeight*rateIntegralSquaredM2PerSec/ ...
    rateScaleMPerSec^2;
normalizedControlCostIntegralSec = controlEffortWeight* ...
    commandedEffortIntegralM2PerSec3/accelerationScaleMPerSec2^2;
normalizedRunningCostIntegralSec = normalizedStateCostIntegralSec+ ...
    normalizedControlCostIntegralSec;
normalizedTerminalCostSec = timeStepSec*state(:,end).'* ...
    riccatiMatrix*state(:,end);
normalizedCostWithTerminalSec = normalizedRunningCostIntegralSec+ ...
    normalizedTerminalCostSec;
normalizedInitialValueSec = timeStepSec*state(:,1).'* ...
    riccatiMatrix*state(:,1);
positionToleranceM = 0.02*abs(initialPositionM);
rateToleranceMPerSec = 0.02;
outsideSettlingBand = abs(positionErrorM) > positionToleranceM | ...
    abs(rateErrorMPerSec) > rateToleranceMPerSec;
lastOutsideIndex = find(outsideSettlingBand,1,'last');
if isempty(lastOutsideIndex)
    settlingTimeSec = 0;
elseif lastOutsideIndex == sampleCount
    settlingTimeSec = Inf;
else
    settlingTimeSec = timeSec(lastOutsideIndex+1);
end
settledByEnd = isfinite(settlingTimeSec);

out = struct( ...
    'positionErrorWeight',positionErrorWeight, ...
    'rateErrorWeight',rateErrorWeight, ...
    'controlEffortWeight',controlEffortWeight, ...
    'actuatorEffectiveness',actuatorEffectiveness, ...
    'initialPositionM',initialPositionM, ...
    'simulationDurationSec',simulationDurationSec, ...
    'timeStepSec',timeStepSec, ...
    'dampingPerSec',dampingPerSec, ...
    'decay',decay, ...
    'positionFromRateSec',positionFromRateSec, ...
    'positionFromAccelerationSec2',positionFromAccelerationSec2, ...
    'discreteA',discreteA, ...
    'discreteB',discreteB, ...
    'positionScaleM',positionScaleM, ...
    'rateScaleMPerSec',rateScaleMPerSec, ...
    'accelerationScaleMPerSec2',accelerationScaleMPerSec2, ...
    'stateCost',stateCost, ...
    'inputCost',inputCost, ...
    'riccatiMatrix',riccatiMatrix, ...
    'riccatiResidual',riccatiResidual, ...
    'riccatiIterationCount',riccatiIterationCount, ...
    'maximumRiccatiIterations',maximumRiccatiIterations, ...
    'feedbackGain',feedbackGain, ...
    'positionFeedbackGainPerSec2',feedbackGain(1), ...
    'rateFeedbackGainPerSec',feedbackGain(2), ...
    'controlCurvature',controlCurvature, ...
    'nominalClosedLoopA',nominalClosedLoopA, ...
    'nominalClosedLoopPoles',nominalClosedLoopPoles, ...
    'nominalSpectralRadius',nominalSpectralRadius, ...
    'actualClosedLoopA',actualClosedLoopA, ...
    'actualClosedLoopPoles',actualClosedLoopPoles, ...
    'actualSpectralRadius',actualSpectralRadius, ...
    'timeSec',timeSec, ...
    'state',state, ...
    'positionErrorM',positionErrorM, ...
    'rateErrorMPerSec',rateErrorMPerSec, ...
    'commandedAccelerationMPerSec2',commandedAccelerationMPerSec2, ...
    'appliedAccelerationMPerSec2',appliedAccelerationMPerSec2, ...
    'positionIntegralSquaredM2Sec',positionIntegralSquaredM2Sec, ...
    'rateIntegralSquaredM2PerSec',rateIntegralSquaredM2PerSec, ...
    'commandedEffortIntegralM2PerSec3', ...
    commandedEffortIntegralM2PerSec3, ...
    'appliedEffortIntegralM2PerSec3',appliedEffortIntegralM2PerSec3, ...
    'normalizedStateCostIntegralSec',normalizedStateCostIntegralSec, ...
    'normalizedControlCostIntegralSec', ...
    normalizedControlCostIntegralSec, ...
    'normalizedRunningCostIntegralSec',normalizedRunningCostIntegralSec, ...
    'normalizedTerminalCostSec',normalizedTerminalCostSec, ...
    'normalizedCostWithTerminalSec',normalizedCostWithTerminalSec, ...
    'normalizedInitialValueSec',normalizedInitialValueSec, ...
    'peakCommandedAccelerationMPerSec2', ...
    max(abs(commandedAccelerationMPerSec2)), ...
    'peakAppliedAccelerationMPerSec2', ...
    max(abs(appliedAccelerationMPerSec2)), ...
    'settlingTimeSec',settlingTimeSec, ...
    'settledByEnd',settledByEnd, ...
    'positionToleranceM',positionToleranceM, ...
    'rateToleranceMPerSec',rateToleranceMPerSec, ...
    'stepCount',stepCount, ...
    'sampleCount',sampleCount, ...
    'maximumStepCount',maximumStepCount);
end
