function run_checks
%RUN_CHECKS Verify P17 LQR invariants without presentation code.
tolerance = 5e-10;
baselineA = model(4,1,1,1,12,0.02);
baselineB = model(4,1,1,1,12,0.02);
assert(isequaln(baselineA,baselineB), ...
    'The deterministic baseline must repeat exactly.');

expectedDecay = exp(-0.5*0.02);
expectedPositionFromRate = (1-expectedDecay)/0.5;
expectedPositionFromAcceleration = ...
    (0.02-expectedPositionFromRate)/0.5;
expectedA = [1 expectedPositionFromRate;0 expectedDecay];
expectedB = [expectedPositionFromAcceleration;expectedPositionFromRate];
expectedQ = diag([4 1]);
expectedR = 1;
assert(max(abs(baselineA.discreteA(:)-expectedA(:))) < tolerance && ...
    max(abs(baselineA.discreteB(:)-expectedB(:))) < tolerance, ...
    'The exact P16 zero-order-hold plant matrices must be retained.');
assert(max(abs(baselineA.stateCost(:)-expectedQ(:))) == 0 && ...
    baselineA.inputCost == expectedR && ...
    baselineA.positionScaleM == 1 && baselineA.rateScaleMPerSec == 1 && ...
    baselineA.accelerationScaleMPerSec2 == 1, ...
    'Q and R must follow the visible normalized cost definitions.');

P = baselineA.riccatiMatrix;
expectedControlCurvature = expectedR+expectedB.'*P*expectedB;
expectedGain = (expectedB.'*P*expectedA)/expectedControlCurvature;
expectedRiccatiRight = expectedQ+expectedA.'*P*expectedA- ...
    expectedA.'*P*expectedB*expectedGain;
assert(max(abs(baselineA.feedbackGain-expectedGain)) < tolerance && ...
    abs(baselineA.controlCurvature-expectedControlCurvature) < tolerance, ...
    'The gain must minimize the visible scalar quadratic control choice.');
assert(max(abs(P(:)-expectedRiccatiRight(:))) < 2e-8 && ...
    max(abs(baselineA.riccatiResidual(:))) < 2e-8 && ...
    baselineA.riccatiIterationCount < baselineA.maximumRiccatiIterations, ...
    'The retained P must satisfy the algebraic Riccati fixed point.');
riccatiDeterminant = P(1,1)*P(2,2)-P(1,2)*P(2,1);
assert(abs(P(1,2)-P(2,1)) < tolerance && P(1,1) > 0 && ...
    P(2,2) > 0 && riccatiDeterminant > 0, ...
    'The baseline future-cost matrix must be symmetric positive definite.');
assert(abs(baselineA.feedbackGain(1)-1.9644942427723904) < 2e-10 && ...
    abs(baselineA.feedbackGain(2)-1.7703588392280174) < 2e-10, ...
    'The baseline gain must match independent reference arithmetic.');

expectedClosedLoop = expectedA-expectedB*expectedGain;
expectedTrace = expectedClosedLoop(1,1)+expectedClosedLoop(2,2);
expectedDeterminant = expectedClosedLoop(1,1)*expectedClosedLoop(2,2)- ...
    expectedClosedLoop(1,2)*expectedClosedLoop(2,1);
for pole = baselineA.nominalClosedLoopPoles.'
    characteristicResidual = pole^2-expectedTrace*pole+expectedDeterminant;
    assert(abs(characteristicResidual) < tolerance, ...
        'Each reported pole must satisfy the two-state characteristic equation.');
end
assert(max(abs(baselineA.nominalClosedLoopA(:)-expectedClosedLoop(:))) < ...
    tolerance && baselineA.nominalSpectralRadius < 1, ...
    'The nominal feedback model must be asymptotically stable.');

for k = 1:baselineA.stepCount
    expectedCommand = -expectedGain*baselineA.state(:,k);
    expectedNext = expectedA*baselineA.state(:,k)+expectedB*expectedCommand;
    assert(abs(baselineA.commandedAccelerationMPerSec2(k)- ...
        expectedCommand) < tolerance && ...
        abs(baselineA.appliedAccelerationMPerSec2(k)- ...
        expectedCommand) < tolerance, ...
        'Every nominal command and applied input must follow u=-K*x.');
    assert(max(abs(baselineA.state(:,k+1)-expectedNext)) < tolerance, ...
        'Every state sample must follow the declared closed-loop recurrence.');
end
expectedPositionIntegral = 0.02*sum(baselineA.positionErrorM(1:end-1).^2);
expectedRateIntegral = 0.02*sum(baselineA.rateErrorMPerSec(1:end-1).^2);
expectedCommandEnergy = 0.02*sum( ...
    baselineA.commandedAccelerationMPerSec2(1:end-1).^2);
expectedTotalCost = 4*expectedPositionIntegral+ ...
    expectedRateIntegral+expectedCommandEnergy;
assert(abs(baselineA.positionIntegralSquaredM2Sec- ...
    expectedPositionIntegral) < tolerance && ...
    abs(baselineA.rateIntegralSquaredM2PerSec-expectedRateIntegral) < ...
    tolerance && abs(baselineA.commandedEffortIntegralM2PerSec3- ...
    expectedCommandEnergy) < tolerance && ...
    abs(baselineA.normalizedRunningCostIntegralSec-expectedTotalCost) < ...
    tolerance, ...
    'All retained metrics must be independent sums of the state history.');
assert(abs(baselineA.normalizedCostWithTerminalSec- ...
    baselineA.normalizedInitialValueSec) < 2e-8, ...
    'Running plus terminal cost must equal the Riccati value identity.');
assert(baselineA.settlingTimeSec > 3 && baselineA.settlingTimeSec < 4 && ...
    baselineA.positionIntegralSquaredM2Sec > 0.7 && ...
    baselineA.positionIntegralSquaredM2Sec < 0.9 && ...
    baselineA.commandedEffortIntegralM2PerSec3 > 0.9 && ...
    baselineA.commandedEffortIntegralM2PerSec3 < 1.1 && ...
    abs(baselineA.positionErrorM(end)) < 1e-5, ...
    'The nominal baseline must remain bounded and settle on this fixed grid.');

% Independent one-step optimality: the derivative of the cost-to-go is zero.
trialState = [0.7;-0.25];
optimalCommand = -expectedGain*trialState;
costDerivative = 2*expectedR*optimalCommand+ ...
    2*expectedB.'*P*(expectedA*trialState+expectedB*optimalCommand);
assert(abs(costDerivative) < tolerance, ...
    'The feedback command must make the one-step quadratic derivative zero.');

% Behavioral optimum: nearby fixed gains must cost more on the same plant,
% initial state, horizon, running cost, and Riccati terminal cost.
gainPerturbations = [0.2 0;-0.2 0;0 0.2;0 -0.2];
perturbedCostValues = zeros(size(gainPerturbations,1),1);
for candidateIndex = 1:size(gainPerturbations,1)
    candidateGain = expectedGain+gainPerturbations(candidateIndex,:);
    candidateState = baselineA.state(:,1);
    candidateRunningCost = 0;
    for k = 1:baselineA.stepCount
        candidateCommand = -candidateGain*candidateState;
        candidateRunningCost = candidateRunningCost+0.02*( ...
            candidateState.'*expectedQ*candidateState+ ...
            expectedR*candidateCommand^2);
        candidateState = expectedA*candidateState+expectedB*candidateCommand;
    end
    candidateTerminalCost = 0.02*candidateState.'*P*candidateState;
    perturbedCostValues(candidateIndex) = ...
        candidateRunningCost+candidateTerminalCost;
end
assert(all(perturbedCostValues > baselineA.normalizedInitialValueSec+0.01), ...
    ['The retained LQR gain must beat nearby feedback gains on the same ' ...
    'closed-loop cost experiment.']);

positionErrorWeightValues = [0 0.25 1 4 16];
positionGains = zeros(size(positionErrorWeightValues));
positionIntegralValues = zeros(size(positionErrorWeightValues));
commandEnergyValues = zeros(size(positionErrorWeightValues));
positionRuns = cell(size(positionErrorWeightValues));
for k = 1:numel(positionErrorWeightValues)
    positionRuns{k} = model(positionErrorWeightValues(k),1,1,1,12,0.02);
    changed = positionRuns{k};
    positionGains(k) = changed.feedbackGain(1);
    positionIntegralValues(k) = changed.positionIntegralSquaredM2Sec;
    commandEnergyValues(k) = changed.commandedEffortIntegralM2PerSec3;
    assert(changed.controlEffortWeight == 1 && ...
        changed.actuatorEffectiveness == 1 && ...
        changed.initialPositionM == 1 && ...
        changed.simulationDurationSec == 12 && changed.timeStepSec == 0.02 && ...
        max(abs(changed.discreteA(:)-baselineA.discreteA(:))) == 0, ...
        'The position-weight sweep must reset every non-swept input.');
end
assert(all(diff(positionGains) > 0) && ...
    all(diff(positionIntegralValues) < 0) && ...
    all(diff(commandEnergyValues) > 0), ...
    'Higher q_p must buy less position error with more command effort.');
zeroPositionWeight = positionRuns{1};
assert(zeroPositionWeight.feedbackGain(1) == 0 && ...
    max(abs(zeroPositionWeight.positionErrorM-1)) == 0 && ...
    max(abs(zeroPositionWeight.rateErrorMPerSec)) == 0 && ...
    max(abs(zeroPositionWeight.commandedAccelerationMPerSec2)) == 0 && ...
    zeroPositionWeight.positionIntegralSquaredM2Sec == 12, ...
    'With q_p=0, a stationary position offset must be an exact zero-input limit.');

controlEffortWeightValues = [0.1 0.25 1 4 10];
peakCommandValues = zeros(size(controlEffortWeightValues));
settlingValues = zeros(size(controlEffortWeightValues));
effortEnergyValues = zeros(size(controlEffortWeightValues));
for k = 1:numel(controlEffortWeightValues)
    changed = model(4,controlEffortWeightValues(k),1,1,12,0.02);
    peakCommandValues(k) = changed.peakCommandedAccelerationMPerSec2;
    settlingValues(k) = changed.settlingTimeSec;
    effortEnergyValues(k) = changed.commandedEffortIntegralM2PerSec3;
    assert(changed.positionErrorWeight == 4 && ...
        changed.actuatorEffectiveness == 1 && ...
        changed.initialPositionM == 1 && ...
        changed.simulationDurationSec == 12 && changed.timeStepSec == 0.02 && ...
        max(abs(changed.discreteB(:)-baselineA.discreteB(:))) == 0, ...
        'The effort-weight sweep must reset every non-swept input.');
end
assert(all(diff(peakCommandValues) < 0) && ...
    all(diff(settlingValues) > 0) && all(diff(effortEnergyValues) < 0), ...
    'Higher r must reduce command magnitude and effort while slowing settling.');

broken = model(4,1,0,1,12,0.02);
recovered = model(4,1,1,1,12,0.02);
assert(max(abs(broken.feedbackGain-baselineA.feedbackGain)) == 0 && ...
    max(abs(broken.riccatiMatrix(:)-baselineA.riccatiMatrix(:))) == 0 && ...
    max(abs(broken.positionErrorM-1)) == 0 && ...
    max(abs(broken.rateErrorMPerSec)) == 0 && ...
    max(abs(broken.appliedAccelerationMPerSec2)) == 0 && ...
    broken.commandedEffortIntegralM2PerSec3 > 40 && ...
    isinf(broken.settlingTimeSec) && ~broken.settledByEnd && ...
    abs(broken.actualSpectralRadius-1) < tolerance, ...
    'A disconnected actuator must retain the design but lose all authority.');
assert(isequaln(recovered,baselineA), ...
    'A fresh full-authority call must recover the exact baseline.');

negativeInitialState = model(4,1,1,-1,12,0.02);
assert(max(abs(negativeInitialState.state(:)+baselineA.state(:))) < ...
    tolerance && max(abs(negativeInitialState.commandedAccelerationMPerSec2+ ...
    baselineA.commandedAccelerationMPerSec2)) < tolerance && ...
    negativeInitialState.positionIntegralSquaredM2Sec == ...
    baselineA.positionIntegralSquaredM2Sec && ...
    negativeInitialState.commandedEffortIntegralM2PerSec3 == ...
    baselineA.commandedEffortIntegralM2PerSec3, ...
    'The linear regulator must preserve sign symmetry and quadratic metrics.');

assertAnyError(@() model(NaN,1,1,1,12,0.02), ...
    'A nonfinite position weight must be rejected.');
assertAnyError(@() model([1 2],1,1,1,12,0.02), ...
    'A nonscalar position weight must be rejected.');
assertAnyError(@() model(4,1+1i,1,1,12,0.02), ...
    'A complex effort weight must be rejected.');
assertAnyError(@() model(-1,1,1,1,12,0.02), ...
    'A negative position weight must be rejected.');
assertAnyError(@() model(4,0,1,1,12,0.02), ...
    'A zero effort weight must be rejected.');
assertAnyError(@() model(4,1,-0.1,1,12,0.02), ...
    'A negative actuator effectiveness must be rejected.');
assertErrorId(@() model(25.01,1,1,1,12,0.02), ...
    'P17:PositionWeightRange','Excessive position weight must be rejected.');
assertErrorId(@() model(0.1,1,1,1,12,0.02), ...
    'P17:PositionWeightRange','Tiny positive position weight must be rejected.');
assertErrorId(@() model(4,0.049,1,1,12,0.02), ...
    'P17:EffortWeightRange','Too-small effort weight must be rejected.');
assertErrorId(@() model(4,20.01,1,1,12,0.02), ...
    'P17:EffortWeightRange','Excessive effort weight must be rejected.');
assertErrorId(@() model(4,1,1.01,1,12,0.02), ...
    'P17:ActuatorEffectivenessRange', ...
    'Excessive actuator effectiveness must be rejected.');
zeroInitialState = model(4,1,1,0,12,0.02);
assert(max(abs(zeroInitialState.state(:))) == 0 && ...
    max(abs(zeroInitialState.commandedAccelerationMPerSec2)) == 0 && ...
    zeroInitialState.settlingTimeSec == 0 && zeroInitialState.settledByEnd, ...
    'The zero initial state must remain an exact equilibrium limit.');
assertErrorId(@() model(4,1,1,2.01,12,0.02), ...
    'P17:InitialPositionRange','Excessive initial position must be rejected.');
assertErrorId(@() model(4,1,1,1,7.99,0.02), ...
    'P17:DurationRange','A too-short duration must be rejected.');
assertErrorId(@() model(4,1,1,1,20.01,0.02), ...
    'P17:DurationRange','An excessive duration must be rejected.');
assertErrorId(@() model(4,1,1,1,12,0.051), ...
    'P17:DisplayResolution','An under-resolved interval must be rejected.');
assertErrorId(@() model(4,1,1,1,12,0.031), ...
    'P17:GridAlignment','A partial final sample must be rejected.');
assertErrorId(@() model(4,1,1,1,20,0.003), ...
    'P17:GridAlignment','A misaligned oversized grid must fail alignment first.');
assertErrorId(@() model(4,1,1,1,20,0.002), ...
    'P17:TooManySteps','An oversized grid must be rejected before allocation.');
assertErrorId(@() model(4,1,1,1,20,realmin), ...
    'P17:TooManySteps','An overflowing grid ratio must be rejected.');
boundedGrid = model(4,1,1,1,20,0.004);
assert(boundedGrid.stepCount == 5000 && boundedGrid.sampleCount == 5001 && ...
    all(isfinite(boundedGrid.state(:))) && ...
    all(isfinite(boundedGrid.commandedAccelerationMPerSec2)) && ...
    all(isfinite(boundedGrid.appliedAccelerationMPerSec2)) && ...
    all(isfinite(boundedGrid.riccatiMatrix(:))), ...
    'The largest accepted grid must contain only finite retained outputs.');
worstRiccati = model(0.25,20,1,1,8,0.0016);
assert(worstRiccati.stepCount == 5000 && ...
    worstRiccati.riccatiIterationCount > 30000 && ...
    worstRiccati.riccatiIterationCount < ...
    worstRiccati.maximumRiccatiIterations && ...
    worstRiccati.nominalSpectralRadius < 1, ...
    'The slowest accepted Riccati case must converge within its fixed bound.');

disp(['P17 checks passed: Riccati optimum, deterministic regulation, ' ...
    'two isolated weights, actuator recovery, malformed inputs, and bounds.']);
end

function assertAnyError(operation,message)
didError = false;
try
    operation();
catch
    didError = true;
end
assert(didError,message);
end

function assertErrorId(operation,expectedIdentifier,message)
actualIdentifier = '';
try
    operation();
catch exception
    actualIdentifier = exception.identifier;
end
assert(strcmp(actualIdentifier,expectedIdentifier),message);
end
