function interactive
%INTERACTIVE Explore the P24 virtual HIL-shaped boundary one lever at a time.
modelFunction = @model;

window = uifigure('Name','P24 - Virtual controller/plant boundary', ...
    'Position',[60 60 1280 800]);
positionAxes = uiaxes(window,'Position',[45 430 770 315]);
protocolAxes = uiaxes(window,'Position',[45 70 770 295]);

uilabel(window,'Position',[850 715 205 22], ...
    'Text','Controller period (s)');
periodControl = uidropdown(window,'Position',[1060 715 135 22], ...
    'Items',{'0.02','0.04','0.05','0.10','0.20'},'Value','0.05');

uilabel(window,'Position',[850 665 205 22], ...
    'Text','One-way latency (s)');
latencyControl = uidropdown(window,'Position',[1060 665 135 22], ...
    'Items',{'0','0.01','0.02','0.04','0.06','0.08'}, ...
    'Value','0.01');

uilabel(window,'Position',[850 615 205 22], ...
    'Text','Watchdog timeout (s)');
watchdogControl = uidropdown(window,'Position',[1060 615 135 22], ...
    'Items',{'0.05','0.10','0.12','0.20','0.50'},'Value','0.20');

uilabel(window,'Position',[850 565 205 22], ...
    'Text','Drop every Nth command');
dropControl = uispinner(window,'Position',[1060 565 135 22], ...
    'Limits',[0 20],'Step',1,'Value',0);

uilabel(window,'Position',[850 515 205 22], ...
    'Text','Plant mass (kg)');
massControl = uislider(window,'Position',[855 490 335 3], ...
    'Limits',[0.5 5],'Value',1.5, ...
    'MajorTicks',[0.5 1.5 2.5 3.5 5]);

uilabel(window,'Position',[850 440 205 22], ...
    'Text','Simulated cancellation');
cancelControl = uidropdown(window,'Position',[1060 440 135 22], ...
    'Items',{'Disabled','At 4.01 s'},'Value','Disabled');

resetButton = uibutton(window,'push','Text','Reset P24 baseline', ...
    'Position',[850 390 345 30]);
statusLabel = uilabel(window,'Position',[850 55 365 310], ...
    'VerticalAlignment','top','WordWrap','on','Text','');

periodControl.ValueChangedFcn = @(~,~) redrawFromControls();
latencyControl.ValueChangedFcn = @(~,~) redrawFromControls();
watchdogControl.ValueChangedFcn = @(~,~) redrawFromControls();
dropControl.ValueChangedFcn = @(~,~) redrawFromControls();
massControl.ValueChangingFcn = @(~,event) redraw( ...
    str2double(periodControl.Value),str2double(latencyControl.Value), ...
    str2double(watchdogControl.Value),dropControl.Value,event.Value, ...
    cancellationValue());
massControl.ValueChangedFcn = @(~,~) redrawFromControls();
cancelControl.ValueChangedFcn = @(~,~) redrawFromControls();
resetButton.ButtonPushedFcn = @(~,~) resetBaseline();

redraw(0.05,0.01,0.2,0,1.5,Inf);

function resetBaseline
    periodControl.Value = '0.05';
    latencyControl.Value = '0.01';
    watchdogControl.Value = '0.20';
    dropControl.Value = 0;
    massControl.Value = 1.5;
    cancelControl.Value = 'Disabled';
    redraw(0.05,0.01,0.2,0,1.5,Inf);
end

function redrawFromControls
    redraw(str2double(periodControl.Value), ...
        str2double(latencyControl.Value), ...
        str2double(watchdogControl.Value),dropControl.Value, ...
        massControl.Value,cancellationValue());
end

function cancelAtSec = cancellationValue
    if strcmp(cancelControl.Value,'At 4.01 s')
        cancelAtSec = 4.01;
    else
        cancelAtSec = Inf;
    end
end

function redraw(controllerPeriod,latency,watchdog,dropEvery,mass,cancelAt)
    try
        result = modelFunction(controllerPeriod,latency,watchdog, ...
            dropEvery,cancelAt,mass,0.01,8);
    catch exception
        cla(positionAxes);
        cla(protocolAxes);
        title(positionAxes,'Rejected bounded-model input');
        title(protocolAxes,'No virtual command history produced');
        statusLabel.Text = sprintf(['Input combination rejected by the ' ...
            'bounded virtual model.\n\n%s\n\nNo hardware command was sent.'], ...
            exception.message);
        return;
    end

    cla(positionAxes);
    plot(positionAxes,result.timeSec,result.referencePositionM,'k--', ...
        'LineWidth',1.3,'DisplayName','Reference position');
    hold(positionAxes,'on');
    plot(positionAxes,result.timeSec,result.positionM,'b-', ...
        'LineWidth',1.8,'DisplayName','Virtual plant position');
    plot(positionAxes,result.timeSec,result.lastMeasuredPositionM,'m:', ...
        'LineWidth',1.5,'DisplayName','Last delivered measurement');
    hold(positionAxes,'off'); grid(positionAxes,'on');
    xlabel(positionAxes,'Virtual time (s)');
    ylabel(positionAxes,'Position (m)');
    title(positionAxes,'Reference, plant state, and delivered measurement');
    legend(positionAxes,'Location','best');

    cla(protocolAxes);
    plot(protocolAxes,result.timeSec,result.controllerForceN,'c--', ...
        'LineWidth',1.3,'DisplayName','Controller request');
    hold(protocolAxes,'on');
    plot(protocolAxes,result.timeSec,result.appliedForceN,'b-', ...
        'LineWidth',1.7,'DisplayName','Plant-applied force');
    stairs(protocolAxes,result.timeSec,double(result.watchdogTimedOut)* ...
        result.forceLimitN,'r:','LineWidth',1.4, ...
        'DisplayName','Watchdog active (scaled)');
    hold(protocolAxes,'off'); grid(protocolAxes,'on');
    xlabel(protocolAxes,'Virtual time (s)');
    ylabel(protocolAxes,'Force (N)');
    title(protocolAxes,'Transport and safe-zero watchdog boundary');
    legend(protocolAxes,'Location','best');

    if isfinite(cancelAt)
        interpretation = ['simulated cancellation wins delivery ties, ' ...
            'purges queued commands, and holds applied force at zero'];
    elseif any(result.watchdogTimedOut)
        interpretation = ['command continuity failed: stale held force ' ...
            'was replaced by watchdog safe zero'];
    elseif latency >= controllerPeriod
        interpretation = ['transport latency is at least one controller ' ...
            'period, so feedback uses an older plant state'];
    else
        interpretation = ['packets remain fresh enough for this bounded ' ...
            'virtual loop; plant motion follows delivered commands'];
    end
    statusLabel.Text = sprintf([ ...
        'Controller period: %.3f s\nOne-way latency: %.3f s\n' ...
        'Round trip: %.3f s\nWatchdog timeout: %.3f s\n' ...
        'Drop every Nth command: %d\nPlant mass: %.2f kg\n\n' ...
        'Tracking RMS: %.4f m\nIntegral absolute error: %.4f m*s\n' ...
        'Maximum measurement age: %.3f s\n' ...
        'Commands sent / dropped / delivered: %d / %d / %d\n' ...
        'Watchdog duration: %.3f s\nCancellation duration: %.3f s\n\n' ...
        '%s\n\nVirtual-time simulation only; no physical HIL ran.'], ...
        controllerPeriod,latency,2*latency,watchdog,dropEvery,mass, ...
        result.trackingRmsM,result.integratedAbsoluteErrorMSec, ...
        result.maximumMeasurementAgeSec,result.commandPacketSentCount, ...
        result.commandPacketDroppedCount, ...
        result.commandPacketDeliveredCount,result.watchdogDurationSec, ...
        result.cancellationDurationSec,interpretation);
end
end
