function result = model(controllerPeriodSec,oneWayLatencySec, ...
    watchdogTimeoutSec,commandDropEveryN,cancelAtSec,plantMassKg, ...
    timeStepSec,durationSec)
%MODEL Emulate a timestamped controller-to-plant protocol deterministically.
%   This is a software model of virtual-time packet exchange, not a hardware
%   driver or evidence that a physical HIL loop ran.
arguments
    controllerPeriodSec (1,1) double ...
        {mustBeReal,mustBeFinite,mustBePositive} = 0.05
    oneWayLatencySec (1,1) double ...
        {mustBeReal,mustBeFinite,mustBeNonnegative} = 0.01
    watchdogTimeoutSec (1,1) double ...
        {mustBeReal,mustBeFinite,mustBePositive} = 0.2
    commandDropEveryN (1,1) double ...
        {mustBeReal,mustBeFinite,mustBeInteger,mustBeNonnegative} = 0
    cancelAtSec (1,1) double {mustBeReal} = Inf
    plantMassKg (1,1) double ...
        {mustBeReal,mustBeFinite,mustBePositive} = 1.5
    timeStepSec (1,1) double ...
        {mustBeReal,mustBeFinite,mustBePositive} = 0.01
    durationSec (1,1) double ...
        {mustBeReal,mustBeFinite,mustBePositive} = 8
end

if controllerPeriodSec < 0.02 || controllerPeriodSec > 0.2
    error('P24:ControllerPeriodRange', ...
        'Controller period must be between 0.02 and 0.2 seconds.');
end
if oneWayLatencySec < 0 || oneWayLatencySec > 0.2
    error('P24:LatencyRange', ...
        'One-way latency must be between 0 and 0.2 seconds.');
end
if watchdogTimeoutSec < 0.05 || watchdogTimeoutSec > 1
    error('P24:WatchdogRange', ...
        'Watchdog timeout must be between 0.05 and 1 second.');
end
if commandDropEveryN < 0 || commandDropEveryN > 20
    error('P24:DropScheduleRange', ...
        'Drop cadence must be zero or an integer from 1 through 20.');
end
if ~(isinf(cancelAtSec) && cancelAtSec > 0) && ...
        (~isfinite(cancelAtSec) || cancelAtSec < 0 || ...
        cancelAtSec > durationSec)
    error('P24:CancellationRange', ...
        'Cancellation time must be within the run or positive infinity.');
end
if plantMassKg < 0.5 || plantMassKg > 5
    error('P24:PlantMassRange', ...
        'Plant mass must be between 0.5 and 5 kilograms.');
end
if timeStepSec < 0.005 || timeStepSec > 0.02
    error('P24:TimeStepRange', ...
        'Plant time step must be between 0.005 and 0.02 seconds.');
end
if durationSec < 4 || durationSec > 20
    error('P24:DurationRange', ...
        'Duration must be between 4 and 20 seconds.');
end

durationRatio = durationSec/timeStepSec;
durationTickCount = round(durationRatio);
controllerRatio = controllerPeriodSec/timeStepSec;
controllerPeriodTicks = round(controllerRatio);
latencyRatio = oneWayLatencySec/timeStepSec;
oneWayLatencyTicks = round(latencyRatio);
watchdogRatio = watchdogTimeoutSec/timeStepSec;
watchdogTimeoutTicks = round(watchdogRatio);
gridTolerance = 64*eps(max([1 abs(durationRatio) ...
    abs(controllerRatio) abs(latencyRatio) abs(watchdogRatio)]));
if abs(durationRatio-durationTickCount) > gridTolerance
    error('P24:DurationGridMismatch', ...
        'Duration must be an integer multiple of the plant time step.');
end
if abs(controllerRatio-controllerPeriodTicks) > gridTolerance
    error('P24:ControllerGridMismatch', ...
        'Controller period must be an integer multiple of the plant time step.');
end
if abs(latencyRatio-oneWayLatencyTicks) > gridTolerance
    error('P24:LatencyGridMismatch', ...
        'One-way latency must be an integer multiple of the plant time step.');
end
if abs(watchdogRatio-watchdogTimeoutTicks) > gridTolerance
    error('P24:WatchdogGridMismatch', ...
        'Watchdog timeout must be an integer multiple of the plant time step.');
end
if mod(durationTickCount,2) ~= 0
    error('P24:ReferenceGridMismatch', ...
        'Duration must place the reference reversal on a plant tick.');
end
if isfinite(cancelAtSec)
    cancellationRatio = cancelAtSec/timeStepSec;
    cancellationTick = round(cancellationRatio);
    cancellationTolerance = 64*eps(max(1,abs(cancellationRatio)));
    if abs(cancellationRatio-cancellationTick) > cancellationTolerance
        error('P24:CancellationGridMismatch', ...
            'Cancellation time must lie on a plant tick.');
    end
else
    cancellationTick = Inf;
end

minimumStepCount = 201;
maximumStepCount = 4001;
allocatedStepCount = durationTickCount+1;
if allocatedStepCount < minimumStepCount || ...
        allocatedStepCount > maximumStepCount
    error('P24:StepCountRange', ...
        'The derived history must contain between 201 and 4001 samples.');
end

% Fixed controller and plant properties keep the two timing levers isolated.
positionGainNPerM = 18;
velocityGainNPerMPerSec = 8;
forceLimitN = 30;
plantDampingNPerMPerSec = 1.2;
positionBoundM = 10;
velocityBoundMPerSec = 30;

% Exact constant-force transition for m*x_ddot+c*x_dot=u over one tick.
velocityDecay = exp(-plantDampingNPerMPerSec*timeStepSec/plantMassKg);
velocityFromForce = (1-velocityDecay)/plantDampingNPerMPerSec;
positionFromVelocity = plantMassKg/plantDampingNPerMPerSec* ...
    (1-velocityDecay);
positionFromForce = timeStepSec/plantDampingNPerMPerSec- ...
    plantMassKg/plantDampingNPerMPerSec^2*(1-velocityDecay);

% Resource checks finish before any history or packet queue is allocated.
timeSec = (0:durationTickCount)*timeStepSec;
referencePositionM = ones(1,allocatedStepCount);
referencePositionM(timeSec >= durationSec/2) = -0.5;
positionM = zeros(1,allocatedStepCount);
velocityMPerSec = zeros(1,allocatedStepCount);
controllerForceN = zeros(1,allocatedStepCount);
appliedForceN = zeros(1,allocatedStepCount);
lastMeasuredPositionM = NaN(1,allocatedStepCount);
lastMeasuredVelocityMPerSec = NaN(1,allocatedStepCount);
measurementAgeSec = NaN(1,allocatedStepCount);
commandAgeSec = NaN(1,allocatedStepCount);
commandSourceAgeSec = NaN(1,allocatedStepCount);
lastMeasurementTimestampSec = NaN(1,allocatedStepCount);
lastCommandSourceTimestampSec = NaN(1,allocatedStepCount);
controllerEvent = false(1,allocatedStepCount);
measurementPacketDelivered = false(1,allocatedStepCount);
commandPacketSent = false(1,allocatedStepCount);
commandPacketDropped = false(1,allocatedStepCount);
commandPacketDelivered = false(1,allocatedStepCount);
startupSafeActive = false(1,allocatedStepCount);
watchdogTimedOut = false(1,allocatedStepCount);
safeZeroActive = false(1,allocatedStepCount);
cancelled = false(1,allocatedStepCount);

% A queue slot is a virtual packet delivery event. Constant latency and a
% fixed controller period guarantee that two packets never share a slot.
sensorPacketQueued = false(1,allocatedStepCount);
sensorPacketPositionM = zeros(1,allocatedStepCount);
sensorPacketVelocityMPerSec = zeros(1,allocatedStepCount);
sensorPacketTimestampSec = zeros(1,allocatedStepCount);
commandPacketQueued = false(1,allocatedStepCount);
commandPacketForceN = zeros(1,allocatedStepCount);
commandPacketTimestampSec = zeros(1,allocatedStepCount);

hasMeasurement = false;
hasDeliveredCommand = false;
latestMeasuredPositionM = 0;
latestMeasuredVelocityMPerSec = 0;
latestMeasurementTimestampSec = 0;
latestControllerForceN = 0;
latestDeliveredForceN = 0;
latestCommandDeliveryTick = 0;
latestCommandSourceTimestampSec = 0;
commandSequence = 0;
queuesPurged = false;

for k = 1:allocatedStepCount
    currentTick = k-1;
    isCancelled = currentTick >= cancellationTick;
    cancelled(k) = isCancelled;

    if isCancelled
        % Cancellation invalidates queued work before any same-tick delivery.
        if ~queuesPurged
            sensorPacketQueued(k:end) = false;
            commandPacketQueued(k:end) = false;
            queuesPurged = true;
        end
    else
        if mod(currentTick,controllerPeriodTicks) == 0
            sensorDeliveryIndex = k+oneWayLatencyTicks;
            if sensorDeliveryIndex <= allocatedStepCount
                sensorPacketQueued(sensorDeliveryIndex) = true;
                sensorPacketPositionM(sensorDeliveryIndex) = positionM(k);
                sensorPacketVelocityMPerSec(sensorDeliveryIndex) = ...
                    velocityMPerSec(k);
                sensorPacketTimestampSec(sensorDeliveryIndex) = timeSec(k);
            end
        end

        if sensorPacketQueued(k)
            hasMeasurement = true;
            latestMeasuredPositionM = sensorPacketPositionM(k);
            latestMeasuredVelocityMPerSec = sensorPacketVelocityMPerSec(k);
            latestMeasurementTimestampSec = sensorPacketTimestampSec(k);
            measurementPacketDelivered(k) = true;
        end

        if mod(currentTick,controllerPeriodTicks) == 0
            controllerEvent(k) = true;
            if hasMeasurement
                rawForceN = positionGainNPerM*(referencePositionM(k)- ...
                    latestMeasuredPositionM)-velocityGainNPerMPerSec* ...
                    latestMeasuredVelocityMPerSec;
                latestControllerForceN = min(max(rawForceN, ...
                    -forceLimitN),forceLimitN);
                commandSequence = commandSequence+1;
                commandPacketSent(k) = true;
                shouldDrop = commandDropEveryN > 0 && ...
                    mod(commandSequence,commandDropEveryN) == 0;
                commandPacketDropped(k) = shouldDrop;
                if ~shouldDrop
                    commandDeliveryIndex = k+oneWayLatencyTicks;
                    if commandDeliveryIndex <= allocatedStepCount
                        commandPacketQueued(commandDeliveryIndex) = true;
                        commandPacketForceN(commandDeliveryIndex) = ...
                            latestControllerForceN;
                        commandPacketTimestampSec(commandDeliveryIndex) = ...
                            timeSec(k);
                    end
                end
            end
        end

        if commandPacketQueued(k)
            hasDeliveredCommand = true;
            latestDeliveredForceN = commandPacketForceN(k);
            latestCommandDeliveryTick = currentTick;
            latestCommandSourceTimestampSec = ...
                commandPacketTimestampSec(k);
            commandPacketDelivered(k) = true;
        end
    end

    controllerForceN(k) = latestControllerForceN;
    if hasMeasurement && ~isCancelled
        lastMeasuredPositionM(k) = latestMeasuredPositionM;
        lastMeasuredVelocityMPerSec(k) = latestMeasuredVelocityMPerSec;
        lastMeasurementTimestampSec(k) = latestMeasurementTimestampSec;
        measurementAgeSec(k) = timeSec(k)-latestMeasurementTimestampSec;
    end
    if hasDeliveredCommand && ~isCancelled
        commandAgeSec(k) = ...
            (currentTick-latestCommandDeliveryTick)*timeStepSec;
        lastCommandSourceTimestampSec(k) = ...
            latestCommandSourceTimestampSec;
        commandSourceAgeSec(k) = ...
            timeSec(k)-latestCommandSourceTimestampSec;
    end

    startupSafeActive(k) = ~isCancelled && ~hasDeliveredCommand;
    watchdogTimedOut(k) = ~isCancelled && hasDeliveredCommand && ...
        currentTick-latestCommandDeliveryTick >= watchdogTimeoutTicks;
    safeZeroActive(k) = isCancelled || startupSafeActive(k) || ...
        watchdogTimedOut(k);
    if safeZeroActive(k)
        appliedForceN(k) = 0;
    else
        appliedForceN(k) = latestDeliveredForceN;
    end

    if k < allocatedStepCount
        velocityMPerSec(k+1) = velocityDecay*velocityMPerSec(k)+ ...
            velocityFromForce*appliedForceN(k);
        positionM(k+1) = positionM(k)+ ...
            positionFromVelocity*velocityMPerSec(k)+ ...
            positionFromForce*appliedForceN(k);
        if ~isfinite(positionM(k+1)) || ~isfinite(velocityMPerSec(k+1)) || ...
                abs(positionM(k+1)) > positionBoundM || ...
                abs(velocityMPerSec(k+1)) > velocityBoundMPerSec
            error('P24:ResponseBound', ...
                'The virtual plant left the bounded learning view.');
        end
    end
end

trackingErrorM = referencePositionM-positionM;
finiteMeasurementAges = measurementAgeSec(isfinite(measurementAgeSec));
if isempty(finiteMeasurementAges)
    maximumMeasurementAgeSec = NaN;
else
    maximumMeasurementAgeSec = max(finiteMeasurementAges);
end
watchdogDurationSec = sum(watchdogTimedOut(1:end-1))*timeStepSec;
startupSafeDurationSec = sum(startupSafeActive(1:end-1))*timeStepSec;
safeZeroDurationSec = sum(safeZeroActive(1:end-1))*timeStepSec;
cancellationDurationSec = sum(cancelled(1:end-1))*timeStepSec;

result = struct( ...
    'controllerPeriodSec',controllerPeriodSec, ...
    'oneWayLatencySec',oneWayLatencySec, ...
    'roundTripLatencySec',2*oneWayLatencySec, ...
    'watchdogTimeoutSec',watchdogTimeoutSec, ...
    'commandDropEveryN',commandDropEveryN, ...
    'cancelAtSec',cancelAtSec, ...
    'plantMassKg',plantMassKg, ...
    'timeStepSec',timeStepSec, ...
    'durationSec',durationSec, ...
    'controllerPeriodTicks',controllerPeriodTicks, ...
    'oneWayLatencyTicks',oneWayLatencyTicks, ...
    'watchdogTimeoutTicks',watchdogTimeoutTicks, ...
    'minimumStepCount',minimumStepCount, ...
    'maximumStepCount',maximumStepCount, ...
    'allocatedStepCount',allocatedStepCount, ...
    'positionGainNPerM',positionGainNPerM, ...
    'velocityGainNPerMPerSec',velocityGainNPerMPerSec, ...
    'forceLimitN',forceLimitN, ...
    'plantDampingNPerMPerSec',plantDampingNPerMPerSec, ...
    'positionBoundM',positionBoundM, ...
    'velocityBoundMPerSec',velocityBoundMPerSec, ...
    'velocityDecay',velocityDecay, ...
    'velocityFromForce',velocityFromForce, ...
    'positionFromVelocity',positionFromVelocity, ...
    'positionFromForce',positionFromForce, ...
    'timeSec',timeSec, ...
    'referencePositionM',referencePositionM, ...
    'positionM',positionM, ...
    'velocityMPerSec',velocityMPerSec, ...
    'trackingErrorM',trackingErrorM, ...
    'controllerForceN',controllerForceN, ...
    'appliedForceN',appliedForceN, ...
    'lastMeasuredPositionM',lastMeasuredPositionM, ...
    'lastMeasuredVelocityMPerSec',lastMeasuredVelocityMPerSec, ...
    'measurementAgeSec',measurementAgeSec, ...
    'commandAgeSec',commandAgeSec, ...
    'commandSourceAgeSec',commandSourceAgeSec, ...
    'lastMeasurementTimestampSec',lastMeasurementTimestampSec, ...
    'lastCommandSourceTimestampSec',lastCommandSourceTimestampSec, ...
    'controllerEvent',controllerEvent, ...
    'measurementPacketDelivered',measurementPacketDelivered, ...
    'commandPacketSent',commandPacketSent, ...
    'commandPacketDropped',commandPacketDropped, ...
    'commandPacketDelivered',commandPacketDelivered, ...
    'startupSafeActive',startupSafeActive, ...
    'watchdogTimedOut',watchdogTimedOut, ...
    'safeZeroActive',safeZeroActive, ...
    'cancelled',cancelled, ...
    'trackingRmsM',sqrt(mean(trackingErrorM.^2)), ...
    'integratedAbsoluteErrorMSec', ...
    sum(abs(trackingErrorM(1:end-1)))*timeStepSec, ...
    'maximumMeasurementAgeSec',maximumMeasurementAgeSec, ...
    'watchdogDurationSec',watchdogDurationSec, ...
    'startupSafeDurationSec',startupSafeDurationSec, ...
    'safeZeroDurationSec',safeZeroDurationSec, ...
    'cancellationDurationSec',cancellationDurationSec, ...
    'peakAbsPositionM',max(abs(positionM)), ...
    'peakAbsVelocityMPerSec',max(abs(velocityMPerSec)), ...
    'peakAbsControllerForceN',max(abs(controllerForceN)), ...
    'peakAbsAppliedForceN',max(abs(appliedForceN)), ...
    'sensorPacketSentCount',sum(controllerEvent & ~cancelled), ...
    'measurementDeliveryCount',sum(measurementPacketDelivered), ...
    'commandPacketSentCount',sum(commandPacketSent), ...
    'commandPacketDroppedCount',sum(commandPacketDropped), ...
    'commandPacketDeliveredCount',sum(commandPacketDelivered), ...
    'finalTrackingErrorM',trackingErrorM(end));
end
