function run_checks
%RUN_CHECKS Verify P24 virtual protocol, plant, failure, and recovery rules.
tolerance = 5e-10;
baselineA = model(0.05,0.01,0.2,0,Inf,1.5,0.01,8);
baselineB = model(0.05,0.01,0.2,0,Inf,1.5,0.01,8);
assert(isequaln(baselineA,baselineB), ...
    'Repeated baseline calls must be exactly deterministic.');

% Reconstruct the fixed reference and exact mass-damper transition without
% trusting any summary metric from model.m.
expectedReferenceM = ones(size(baselineA.timeSec));
expectedReferenceM(baselineA.timeSec >= 4) = -0.5;
assert(isequal(baselineA.referencePositionM,expectedReferenceM), ...
    'The two-plateau reference must be exact.');
expectedDecay = exp(-baselineA.plantDampingNPerMPerSec* ...
    baselineA.timeStepSec/baselineA.plantMassKg);
expectedVelocityFromForce = (1-expectedDecay)/ ...
    baselineA.plantDampingNPerMPerSec;
expectedPositionFromVelocity = baselineA.plantMassKg/ ...
    baselineA.plantDampingNPerMPerSec*(1-expectedDecay);
expectedPositionFromForce = baselineA.timeStepSec/ ...
    baselineA.plantDampingNPerMPerSec-baselineA.plantMassKg/ ...
    baselineA.plantDampingNPerMPerSec^2*(1-expectedDecay);
assert(abs(baselineA.velocityDecay-expectedDecay) < tolerance && ...
    abs(baselineA.velocityFromForce-expectedVelocityFromForce) < ...
    tolerance && abs(baselineA.positionFromVelocity- ...
    expectedPositionFromVelocity) < tolerance && ...
    abs(baselineA.positionFromForce-expectedPositionFromForce) < ...
    tolerance, ...
    'The retained exact transition coefficients must match direct formulas.');
for k = 1:baselineA.allocatedStepCount-1
    expectedVelocity = expectedDecay*baselineA.velocityMPerSec(k)+ ...
        expectedVelocityFromForce*baselineA.appliedForceN(k);
    expectedPosition = baselineA.positionM(k)+ ...
        expectedPositionFromVelocity*baselineA.velocityMPerSec(k)+ ...
        expectedPositionFromForce*baselineA.appliedForceN(k);
    assert(abs(baselineA.velocityMPerSec(k+1)-expectedVelocity) < ...
        tolerance && abs(baselineA.positionM(k+1)-expectedPosition) < ...
        tolerance, ...
        'Every plant tick must satisfy the exact held-force transition.');
end

% Reconstruct every baseline release and fixed-latency delivery tick.
expectedControllerEvent = false(size(baselineA.timeSec));
expectedControllerEvent(1:baselineA.controllerPeriodTicks:end) = true;
expectedMeasurementDelivery = false(size(baselineA.timeSec));
measurementSourceIndices = find(expectedControllerEvent);
measurementDeliveryIndices = measurementSourceIndices+ ...
    baselineA.oneWayLatencyTicks;
measurementDeliveryIndices = measurementDeliveryIndices( ...
    measurementDeliveryIndices <= baselineA.allocatedStepCount);
expectedMeasurementDelivery(measurementDeliveryIndices) = true;
assert(isequal(baselineA.controllerEvent,expectedControllerEvent) && ...
    isequal(baselineA.measurementPacketDelivered, ...
    expectedMeasurementDelivery), ...
    'Controller releases and measurement deliveries must follow integer ticks.');
assert(baselineA.sensorPacketSentCount == 161 && ...
    baselineA.measurementDeliveryCount == 160 && ...
    baselineA.commandPacketSentCount == 160 && ...
    baselineA.commandPacketDroppedCount == 0 && ...
    baselineA.commandPacketDeliveredCount == 159, ...
    'Baseline packet attempt and bounded-horizon delivery counts must be exact.');

commandSendIndices = find(baselineA.commandPacketSent);
for k = commandSendIndices
    expectedRawForceN = baselineA.positionGainNPerM*( ...
        baselineA.referencePositionM(k)- ...
        baselineA.lastMeasuredPositionM(k))- ...
        baselineA.velocityGainNPerMPerSec* ...
        baselineA.lastMeasuredVelocityMPerSec(k);
    expectedControllerForceN = min(max(expectedRawForceN, ...
        -baselineA.forceLimitN),baselineA.forceLimitN);
    assert(abs(baselineA.controllerForceN(k)- ...
        expectedControllerForceN) < tolerance, ...
        'Every sent command must expose the bounded feedback law.');
end
firstCommandDeliveryIndex = find( ...
    baselineA.commandPacketDelivered,1,'first');
assert(abs(baselineA.timeSec(firstCommandDeliveryIndex)-0.06) < tolerance && ...
    baselineA.appliedForceN(firstCommandDeliveryIndex) == 18 && ...
    abs(baselineA.lastMeasurementTimestampSec( ...
    firstCommandDeliveryIndex)-0.05) < tolerance && ...
    abs(baselineA.measurementAgeSec(firstCommandDeliveryIndex)-0.01) < ...
    tolerance && abs(baselineA.lastCommandSourceTimestampSec( ...
    firstCommandDeliveryIndex)-0.05) < tolerance && ...
    abs(baselineA.commandSourceAgeSec(firstCommandDeliveryIndex)-0.01) < ...
    tolerance && ...
    baselineA.commandAgeSec(firstCommandDeliveryIndex) == 0, ...
    'Source timestamps, transport age, and arrival age must remain distinct.');
assert(abs(baselineA.startupSafeDurationSec-0.06) < tolerance && ...
    baselineA.watchdogDurationSec == 0 && ...
    baselineA.safeZeroDurationSec == 0.06 && ...
    ~any(baselineA.watchdogTimedOut), ...
    'Startup inhibit must not be mislabeled as a stale-command timeout.');
assert(max(abs(baselineA.controllerForceN)) <= 30 && ...
    max(abs(baselineA.appliedForceN)) <= 30 && ...
    max(abs(baselineA.positionM)) < 1.01 && ...
    max(abs(baselineA.velocityMPerSec)) < 2.8, ...
    'The baseline virtual loop must remain inside declared force and state bounds.');

% Independent retained baseline values from the same explicit event rules.
assert(abs(baselineA.trackingRmsM-0.35217805690329707) < tolerance && ...
    abs(baselineA.integratedAbsoluteErrorMSec- ...
    1.1527771702125116) < tolerance && ...
    abs(baselineA.maximumMeasurementAgeSec-0.05) < tolerance && ...
    abs(baselineA.peakAbsPositionM-0.9999993310787705) < tolerance && ...
    abs(baselineA.peakAbsVelocityMPerSec- ...
    2.78635714679453) < tolerance, ...
    'Baseline simulated metrics must remain deterministic.');

% Sweep one-way latency while holding every other input fixed.
latencyValuesSec = [0.01 0.02 0.04 0.06 0.08];
latencyAgeSec = zeros(size(latencyValuesSec));
latencyRmsM = zeros(size(latencyValuesSec));
latencyPeakVelocityMPerSec = zeros(size(latencyValuesSec));
for k = 1:numel(latencyValuesSec)
    changed = model(0.05,latencyValuesSec(k),0.2,0,Inf,1.5,0.01,8);
    assert(changed.controllerPeriodSec == 0.05 && ...
        changed.watchdogTimeoutSec == 0.2 && ...
        changed.commandDropEveryN == 0 && isinf(changed.cancelAtSec) && ...
        changed.plantMassKg == 1.5 && changed.timeStepSec == 0.01 && ...
        changed.durationSec == 8, ...
        'Latency sweep must reset every non-swept input.');
    latencyAgeSec(k) = changed.maximumMeasurementAgeSec;
    latencyRmsM(k) = changed.trackingRmsM;
    latencyPeakVelocityMPerSec(k) = changed.peakAbsVelocityMPerSec;
end
assert(all(diff(latencyAgeSec) > 0) && ...
    all(diff(latencyPeakVelocityMPerSec) > 0) && ...
    latencyRmsM(end) > latencyRmsM(1), ...
    'Latency must increase age and peak speed and degrade the high endpoint.');

% Sweep only controller release period; the plant tick stays fixed.
controllerPeriodValuesSec = [0.02 0.04 0.05 0.1 0.2];
periodAgeSec = zeros(size(controllerPeriodValuesSec));
periodRmsM = zeros(size(controllerPeriodValuesSec));
periodPeakVelocityMPerSec = zeros(size(controllerPeriodValuesSec));
periodCommandCount = zeros(size(controllerPeriodValuesSec));
for k = 1:numel(controllerPeriodValuesSec)
    changed = model(controllerPeriodValuesSec(k),0.01,0.2,0, ...
        Inf,1.5,0.01,8);
    assert(changed.oneWayLatencySec == 0.01 && ...
        changed.watchdogTimeoutSec == 0.2 && ...
        changed.commandDropEveryN == 0 && isinf(changed.cancelAtSec) && ...
        changed.plantMassKg == 1.5 && changed.timeStepSec == 0.01 && ...
        changed.durationSec == 8, ...
        'Period sweep must reset every non-swept input.');
    periodAgeSec(k) = changed.maximumMeasurementAgeSec;
    periodRmsM(k) = changed.trackingRmsM;
    periodPeakVelocityMPerSec(k) = changed.peakAbsVelocityMPerSec;
    periodCommandCount(k) = changed.commandPacketSentCount;
end
assert(all(diff(periodAgeSec) > 0) && ...
    all(diff(periodCommandCount) < 0) && ...
    all(diff(periodPeakVelocityMPerSec) > 0) && ...
    periodRmsM(end) > periodRmsM(1), ...
    'A slower controller must send less, hold older data, and degrade the endpoint.');

% Zero transport latency is the same-tick limiting case.
zeroLatency = model(0.05,0,0.2,0,Inf,1.5,0.01,8);
assert(zeroLatency.sensorPacketSentCount == 161 && ...
    zeroLatency.measurementDeliveryCount == 161 && ...
    zeroLatency.commandPacketSentCount == 161 && ...
    zeroLatency.commandPacketDeliveredCount == 161 && ...
    zeroLatency.appliedForceN(1) == 18 && ...
    zeroLatency.measurementAgeSec(1) == 0 && ...
    zeroLatency.commandSourceAgeSec(1) == 0 && ...
    zeroLatency.commandAgeSec(1) == 0 && ...
    zeroLatency.startupSafeDurationSec == 0 && ...
    zeroLatency.watchdogDurationSec == 0, ...
    'Zero latency must deliver both packets on the release tick.');

% Broken continuity, no-drop recovery, cancellation precedence, and isolation.
broken = model(0.1,0.04,0.12,2,Inf,1.5,0.01,8);
dropRecovered = model(0.1,0.04,0.12,0,Inf,1.5,0.01,8);
assert(broken.commandPacketSentCount == 80 && ...
    broken.commandPacketDroppedCount == 40 && ...
    broken.commandPacketDeliveredCount == 40 && ...
    broken.watchdogDurationSec > 3 && ...
    all(broken.appliedForceN(broken.watchdogTimedOut) == 0), ...
    'Alternate command loss must produce recurring stale-command timeouts.');
assert(dropRecovered.commandPacketDroppedCount == 0 && ...
    dropRecovered.commandPacketDeliveredCount == 79 && ...
    dropRecovered.watchdogDurationSec == 0 && ...
    ~any(dropRecovered.watchdogTimedOut), ...
    'Removing only command loss must restore continuous valid arrivals.');

% Pin the receiver's exact age boundary and same-tick recovery ordering.
firstDeliveryIndex = find(broken.commandPacketDelivered,1,'first');
firstTimeoutIndex = find(broken.watchdogTimedOut,1,'first');
recoveryDeliveryIndices = find(broken.commandPacketDelivered(2:end) & ...
    broken.watchdogTimedOut(1:end-1))+1;
assert(abs(broken.timeSec(firstTimeoutIndex)- ...
    (broken.timeSec(firstDeliveryIndex)+broken.watchdogTimeoutSec)) < ...
    tolerance && ~broken.watchdogTimedOut(firstTimeoutIndex-1) && ...
    broken.commandAgeSec(firstTimeoutIndex-1) < ...
    broken.watchdogTimeoutSec && ...
    broken.commandAgeSec(firstTimeoutIndex) == ...
    broken.watchdogTimeoutSec && ...
    broken.appliedForceN(firstTimeoutIndex-1) == ...
    broken.appliedForceN(firstDeliveryIndex) && ...
    broken.appliedForceN(firstTimeoutIndex) == 0, ...
    'Held force must stop exactly when arrival age reaches the timeout.');
assert(~isempty(recoveryDeliveryIndices) && ...
    all(broken.commandAgeSec(recoveryDeliveryIndices) == 0) && ...
    ~any(broken.watchdogTimedOut(recoveryDeliveryIndices)) && ...
    ~any(broken.safeZeroActive(recoveryDeliveryIndices)) && ...
    isequal(broken.safeZeroActive,broken.startupSafeActive | ...
    broken.watchdogTimedOut | broken.cancelled), ...
    'A fresh delivery must clear prior timeout before same-tick force selection.');

cancelAtZero = model(0.05,0.01,0.2,0,0,1.5,0.01,8);
cancelOnArrival = model(0.05,0.01,0.2,0,0.06,1.5,0.01,8);
cancelAtFour = model(0.05,0.01,0.2,0,4,1.5,0.01,8);
cancelIndex = find(cancelAtFour.cancelled,1,'first');
assert(cancelAtZero.commandPacketSentCount == 0 && ...
    cancelAtZero.commandPacketDeliveredCount == 0 && ...
    all(cancelAtZero.appliedForceN == 0) && ...
    all(cancelAtZero.positionM == 0) && ...
    cancelAtZero.watchdogDurationSec == 0, ...
    'Immediate cancellation must keep the entire virtual boundary safe-zero.');
assert(cancelOnArrival.commandPacketSentCount == 1 && ...
    cancelOnArrival.commandPacketDeliveredCount == 0 && ...
    all(cancelOnArrival.appliedForceN == 0), ...
    'Cancellation must purge a command due at the same virtual tick.');
assert(abs(cancelAtFour.timeSec(cancelIndex)-4) < tolerance && ...
    all(cancelAtFour.appliedForceN(cancelIndex:end) == 0) && ...
    ~any(cancelAtFour.commandPacketDelivered(cancelIndex:end)) && ...
    cancelAtFour.watchdogDurationSec == 0 && ...
    abs(cancelAtFour.cancellationDurationSec-4) < tolerance, ...
    'Cancellation must remain distinct from timeout and force later safe zero.');
freshAfterFailures = model(0.05,0.01,0.2,0,Inf,1.5,0.01,8);
assert(isequaln(freshAfterFailures,baselineA), ...
    'Broken and cancelled calls must not leak state into a fresh baseline.');

% Malformed inputs and resource bounds fail before history allocation.
assertAnyError(@() model(NaN,0.01,0.2,0,Inf,1.5,0.01,8), ...
    'A nonfinite controller period must be rejected.');
assertAnyError(@() model(0.05,[0.01 0.02],0.2,0,Inf,1.5,0.01,8), ...
    'A nonscalar latency must be rejected.');
assertAnyError(@() model(0.05,0.01,0.2,1.5,Inf,1.5,0.01,8), ...
    'A fractional drop cadence must be rejected.');
assertErrorId(@() model(0.01,0.01,0.2,0,Inf,1.5,0.01,8), ...
    'P24:ControllerPeriodRange','Too-fast controller period must fail.');
assertErrorId(@() model(0.21,0.01,0.2,0,Inf,1.5,0.01,8), ...
    'P24:ControllerPeriodRange','Too-slow controller period must fail.');
assertErrorId(@() model(0.05,0.21,0.2,0,Inf,1.5,0.01,8), ...
    'P24:LatencyRange','Excessive latency must fail.');
assertErrorId(@() model(0.05,0.01,0.04,0,Inf,1.5,0.01,8), ...
    'P24:WatchdogRange','Too-short watchdog must fail.');
assertErrorId(@() model(0.05,0.01,0.2,21,Inf,1.5,0.01,8), ...
    'P24:DropScheduleRange','Excessive drop cadence must fail.');
assertErrorId(@() model(0.05,0.01,0.2,0,-1,1.5,0.01,8), ...
    'P24:CancellationRange','Negative cancellation time must fail.');
assertErrorId(@() model(0.05,0.01,0.2,0,9,1.5,0.01,8), ...
    'P24:CancellationRange','Cancellation after the run must fail.');
assertErrorId(@() model(0.05,0.01,0.2,0,Inf,0.49,0.01,8), ...
    'P24:PlantMassRange','Too-small mass must fail.');
assertErrorId(@() model(0.05,0.01,0.2,0,Inf,5.01,0.01,8), ...
    'P24:PlantMassRange','Excessive mass must fail.');
assertErrorId(@() model(0.05,0.01,0.2,0,Inf,1.5,0.004,8), ...
    'P24:TimeStepRange','Too-small plant tick must fail.');
assertErrorId(@() model(0.05,0.01,0.2,0,Inf,1.5,0.021,8), ...
    'P24:TimeStepRange','Too-large plant tick must fail.');
assertErrorId(@() model(0.05,0.01,0.2,0,Inf,1.5,0.01,3.99), ...
    'P24:DurationRange','Too-short duration must fail.');
assertErrorId(@() model(0.05,0.01,0.2,0,Inf,1.5,0.01,20.01), ...
    'P24:DurationRange','Too-long duration must fail.');
assertErrorId(@() model(0.055,0.01,0.2,0,Inf,1.5,0.01,8), ...
    'P24:ControllerGridMismatch','Off-grid controller period must fail.');
assertErrorId(@() model(0.05,0.015,0.2,0,Inf,1.5,0.01,8), ...
    'P24:LatencyGridMismatch','Off-grid latency must fail.');
assertErrorId(@() model(0.05,0.01,0.125,0,Inf,1.5,0.01,8), ...
    'P24:WatchdogGridMismatch','Off-grid watchdog must fail.');
assertErrorId(@() model(0.05,0.01,0.2,0,0.065,1.5,0.01,8), ...
    'P24:CancellationGridMismatch','Off-grid cancellation must fail.');
assertErrorId(@() model(0.06,0,0.2,0,Inf,1.5,0.02,4.02), ...
    'P24:ReferenceGridMismatch','Off-grid reference reversal must fail.');

minimumHistory = model(0.02,0,1,0,Inf,5,0.02,4);
maximumHistory = model(0.02,0,1,0,Inf,5,0.005,20);
assert(minimumHistory.allocatedStepCount == 201 && ...
    maximumHistory.allocatedStepCount == 4001 && ...
    all(isfinite(maximumHistory.positionM)) && ...
    all(isfinite(maximumHistory.velocityMPerSec)), ...
    'Minimum and maximum accepted histories must remain finite and bounded.');
assertErrorId(@() model(0.2,0.2,0.5,2,Inf,0.5,0.01,4), ...
    'P24:ResponseBound','An extreme divergent view must stop at its bound.');
afterMalformedAndBounded = model(0.05,0.01,0.2,0,Inf,1.5,0.01,8);
assert(isequaln(afterMalformedAndBounded,baselineA), ...
    'Malformed, bounded, and response-bound calls must leave no hidden state.');

disp(['P24 checks passed: exact virtual protocol and plant transitions, ' ...
    'two isolated timing sweeps, zero latency, command-loss timeout, ' ...
    'cancellation precedence, malformed inputs, recovery, and bounds.']);
end

function assertAnyError(operation,message)
didError = false;
try
    operation();
catch
    didError = true;
end
assert(didError,message);
end

function assertErrorId(operation,expectedIdentifier,message)
actualIdentifier = '';
try
    operation();
catch exception
    actualIdentifier = exception.identifier;
end
assert(strcmp(actualIdentifier,expectedIdentifier),message);
end
