function out = model(proportionalGain,integralGain,derivativeGain, ...
    loadForceN,derivativeSign,tEnd,dt)
%MODEL Simulate a transparent PID position loop with a constant load.
%   A 1 kg carriage with viscous damping follows a 1 m reference:
%       m*x'' = u + Fload - b*x'
%       e = r-x,  q' = e
%       u = Kp*e + Ki*q + derivativeSign*Kd*x'.
%   derivativeSign = -1 is derivative-on-measurement damping because
%   de/dt = -x' for the constant reference. derivativeSign = +1 is the
%   deliberately broken case that feeds velocity back with the wrong sign.
arguments
    proportionalGain (1,1) double {mustBeReal,mustBeFinite,mustBeNonnegative} = 4
    integralGain (1,1) double {mustBeReal,mustBeFinite,mustBeNonnegative} = 1
    derivativeGain (1,1) double {mustBeReal,mustBeFinite,mustBeNonnegative} = 3
    loadForceN (1,1) double {mustBeReal,mustBeFinite} = -1
    derivativeSign (1,1) double {mustBeReal,mustBeFinite} = -1
    tEnd (1,1) double {mustBeReal,mustBeFinite,mustBePositive} = 20
    dt (1,1) double {mustBeReal,mustBeFinite,mustBePositive} = 0.01
end

if proportionalGain > 20
    error('P06:ProportionalGainRange', ...
        'proportionalGain must not exceed 20 N/m.');
end
if integralGain > 10
    error('P06:IntegralGainRange', ...
        'integralGain must not exceed 10 N/(m*s).');
end
if derivativeGain > 10
    error('P06:DerivativeGainRange', ...
        'derivativeGain must not exceed 10 N*s/m.');
end
if abs(loadForceN) > 10
    error('P06:LoadRange','loadForceN must have magnitude at most 10 N.');
end
if derivativeSign ~= -1 && derivativeSign ~= 1
    error('P06:DerivativeSign', ...
        'derivativeSign must be -1 for damping or +1 for the broken sign.');
end
if tEnd > 30
    error('P06:HorizonRange','tEnd must not exceed 30 s.');
end

massKg = 1;
dampingNPerMPerSec = 0.5;
referenceM = 1;
initialPositionM = 0;
initialVelocityMPerSec = 0;
initialIntegralErrorMSeconds = 0;

maxSamples = 20001;
intervalCount = floor(tEnd/dt);
lastRegularTime = intervalCount*dt;
timeTolerance = 8*eps(max(tEnd,dt));
appendEnd = intervalCount == 0 || tEnd-lastRegularTime > timeTolerance;
sampleCount = intervalCount + 1 + double(appendEnd);
if sampleCount > maxSamples
    error('P06:TooManySamples', ...
        'Requested %d samples; increase dt or shorten tEnd (maximum %d).', ...
        sampleCount,maxSamples);
end

t = (0:intervalCount)'*dt;
if appendEnd
    t(end+1,1) = tEnd;
else
    t(end) = tEnd;
end
maxInterval = max(diff(t));
characteristicRatePerSec = ...
    (dampingNPerMPerSec+derivativeGain)/massKg + ...
    sqrt(proportionalGain/massKg) + nthroot(integralGain/massKg,3);
maxDimensionlessStep = 0.15;
if characteristicRatePerSec*maxInterval > maxDimensionlessStep
    error('P06:TimeResolution', ...
        'Characteristic rate times maxInterval must not exceed %.2f.', ...
        maxDimensionlessStep);
end

positionM = zeros(sampleCount,1);
velocityMPerSec = zeros(sampleCount,1);
integralErrorMSeconds = zeros(sampleCount,1);
positionM(1) = initialPositionM;
velocityMPerSec(1) = initialVelocityMPerSec;
integralErrorMSeconds(1) = initialIntegralErrorMSeconds;
state = [initialPositionM;initialVelocityMPerSec;initialIntegralErrorMSeconds];
responseLimit = 1e6;
for k = 1:sampleCount-1
    step = t(k+1)-t(k);
    k1 = stateRate(state,proportionalGain,integralGain,derivativeGain, ...
        loadForceN,derivativeSign,massKg,dampingNPerMPerSec,referenceM);
    k2 = stateRate(state+0.5*step*k1,proportionalGain,integralGain, ...
        derivativeGain,loadForceN,derivativeSign,massKg, ...
        dampingNPerMPerSec,referenceM);
    k3 = stateRate(state+0.5*step*k2,proportionalGain,integralGain, ...
        derivativeGain,loadForceN,derivativeSign,massKg, ...
        dampingNPerMPerSec,referenceM);
    k4 = stateRate(state+step*k3,proportionalGain,integralGain, ...
        derivativeGain,loadForceN,derivativeSign,massKg, ...
        dampingNPerMPerSec,referenceM);
    state = state + step*(k1+2*k2+2*k3+k4)/6;
    if any(~isfinite(state)) || max(abs(state)) > responseLimit
        error('P06:ResponseBound', ...
            'The requested PID response exceeds the bounded learning view.');
    end
    positionM(k+1) = state(1);
    velocityMPerSec(k+1) = state(2);
    integralErrorMSeconds(k+1) = state(3);
end

trackingErrorM = referenceM-positionM;
errorDerivativeMPerSec = -velocityMPerSec;
proportionalControlN = proportionalGain*trackingErrorM;
integralControlN = integralGain*integralErrorMSeconds;
derivativeControlN = derivativeSign*derivativeGain*velocityMPerSec;
totalControlN = proportionalControlN+integralControlN+derivativeControlN;
accelerationMPerSec2 = (totalControlN+loadForceN- ...
    dampingNPerMPerSec*velocityMPerSec)/massKg;

absoluteErrorAreaMSeconds = sum(0.5*(abs(trackingErrorM(1:end-1))+ ...
    abs(trackingErrorM(2:end))).*diff(t));
overshootM = max(max(positionM-referenceM),0);
settlingBandM = 0.02;
outsideBand = find(abs(trackingErrorM) > settlingBandM);
if isempty(outsideBand)
    settlingTimeSec = 0;
elseif outsideBand(end) == sampleCount
    settlingTimeSec = Inf;
else
    settlingTimeSec = t(outsideBand(end)+1);
end

effectiveDampingNPerMPerSec = ...
    dampingNPerMPerSec-derivativeSign*derivativeGain;
positionLoopStable = proportionalGain > 0 && ...
    effectiveDampingNPerMPerSec > 0;
internalStateAsymptoticallyStable = integralGain > 0 && ...
    positionLoopStable && ...
    effectiveDampingNPerMPerSec*proportionalGain > massKg*integralGain;
closedLoopStable = internalStateAsymptoticallyStable;
if derivativeSign == -1
    derivativeLabel = 'damping: derivative opposes measured velocity';
else
    derivativeLabel = 'broken: derivative reinforces measured velocity';
end

out = struct( ...
    't',t, ...
    'positionM',positionM, ...
    'velocityMPerSec',velocityMPerSec, ...
    'accelerationMPerSec2',accelerationMPerSec2, ...
    'trackingErrorM',trackingErrorM, ...
    'errorDerivativeMPerSec',errorDerivativeMPerSec, ...
    'integralErrorMSeconds',integralErrorMSeconds, ...
    'proportionalControlN',proportionalControlN, ...
    'integralControlN',integralControlN, ...
    'derivativeControlN',derivativeControlN, ...
    'totalControlN',totalControlN, ...
    'proportionalGainNPerM',proportionalGain, ...
    'integralGainNPerMSecond',integralGain, ...
    'derivativeGainNSecondPerM',derivativeGain, ...
    'loadForceN',loadForceN, ...
    'derivativeSign',derivativeSign, ...
    'derivativeLabel',derivativeLabel, ...
    'massKg',massKg, ...
    'dampingNPerMPerSec',dampingNPerMPerSec, ...
    'effectiveDampingNPerMPerSec',effectiveDampingNPerMPerSec, ...
    'referenceM',referenceM, ...
    'initialPositionM',initialPositionM, ...
    'initialVelocityMPerSec',initialVelocityMPerSec, ...
    'positionLoopStable',positionLoopStable, ...
    'internalStateAsymptoticallyStable',internalStateAsymptoticallyStable, ...
    'closedLoopStable',closedLoopStable, ...
    'finalTrackingErrorM',trackingErrorM(end), ...
    'overshootM',overshootM, ...
    'settlingTimeSec',settlingTimeSec, ...
    'absoluteErrorAreaMSeconds',absoluteErrorAreaMSeconds, ...
    'maxAbsControlN',max(abs(totalControlN)), ...
    'maxAbsDerivativeControlN',max(abs(derivativeControlN)), ...
    'characteristicRatePerSec',characteristicRatePerSec, ...
    'maxDimensionlessStep',maxDimensionlessStep, ...
    'maxInterval',maxInterval, ...
    'sampleCount',sampleCount);
end

function rate = stateRate(state,proportionalGain,integralGain, ...
    derivativeGain,loadForceN,derivativeSign,massKg, ...
    dampingNPerMPerSec,referenceM)
positionM = state(1);
velocityMPerSec = state(2);
integralErrorMSeconds = state(3);
trackingErrorM = referenceM-positionM;
proportionalControlN = proportionalGain*trackingErrorM;
integralControlN = integralGain*integralErrorMSeconds;
derivativeControlN = derivativeSign*derivativeGain*velocityMPerSec;
totalControlN = proportionalControlN+integralControlN+derivativeControlN;
accelerationMPerSec2 = (totalControlN+loadForceN- ...
    dampingNPerMPerSec*velocityMPerSec)/massKg;
rate = [velocityMPerSec;accelerationMPerSec2;trackingErrorM];
end
