function run_checks
%RUN_CHECKS Independent PID identities, limits, failure, and recovery.
tolerance = 5e-10;

baselineA = model(4,1,3,-1,-1,20,0.01);
baselineB = model(4,1,3,-1,-1,20,0.01);
assert(isequaln(baselineA,baselineB), ...
    'Identical PID inputs must produce identical deterministic outputs.');
assert(baselineA.positionM(1) == 0 && baselineA.trackingErrorM(1) == 1, ...
    'The baseline must begin at rest one metre below the reference.');
assert(baselineA.proportionalControlN(1) == 4 && ...
    baselineA.integralControlN(1) == 0 && ...
    baselineA.derivativeControlN(1) == 0 && ...
    baselineA.accelerationMPerSec2(1) == 3, ...
    'At rest, only P acts initially and the -1 N load leaves 3 m/s^2.');

controllerResidual = baselineA.totalControlN-( ...
    baselineA.proportionalControlN+baselineA.integralControlN+ ...
    baselineA.derivativeControlN);
plantResidual = baselineA.massKg*baselineA.accelerationMPerSec2-( ...
    baselineA.totalControlN+baselineA.loadForceN- ...
    baselineA.dampingNPerMPerSec*baselineA.velocityMPerSec);
assert(max(abs(controllerResidual)) < tolerance, ...
    'The reported total force must equal the visible P+I+D terms.');
assert(max(abs(plantResidual)) < tolerance, ...
    'Every reported sample must satisfy the carriage force balance.');
assert(max(abs(baselineA.errorDerivativeMPerSec+ ...
    baselineA.velocityMPerSec)) < tolerance, ...
    'For a constant reference, error derivative must equal minus velocity.');
assert(abs(baselineA.finalTrackingErrorM) < 1e-3 && ...
    abs(baselineA.integralControlN(end)+baselineA.loadForceN) < 1e-3, ...
    'Integral action must remove offset and supply the steady load force.');
assert(baselineA.closedLoopStable && baselineA.overshootM < 0.02 && ...
    baselineA.maxAbsControlN == 4, ...
    'The baseline must be stable, lightly overshooting, and initially P-limited.');

% With Kp=11, Ki=6, and total damping b+Kd=6, the homogeneous
% characteristic polynomial is s^3+6*s^2+11*s+6=(s+1)*(s+2)*(s+3).
% A zero-load unit-reference response therefore has an independent exact
% trajectory that exercises position, velocity, and integral-error propagation.
factoredPoleCase = model(11,6,5.5,0,-1,1,0.002);
expectedFactoredPosition = 1+2.5*exp(-factoredPoleCase.t)- ...
    8*exp(-2*factoredPoleCase.t)+4.5*exp(-3*factoredPoleCase.t);
expectedFactoredVelocity = -2.5*exp(-factoredPoleCase.t)+ ...
    16*exp(-2*factoredPoleCase.t)-13.5*exp(-3*factoredPoleCase.t);
expectedFactoredIntegral = 2.5*exp(-factoredPoleCase.t)- ...
    4*exp(-2*factoredPoleCase.t)+1.5*exp(-3*factoredPoleCase.t);
trajectoryTolerance = 1e-10;
assert(max(abs(factoredPoleCase.positionM-expectedFactoredPosition)) < ...
    trajectoryTolerance && ...
    max(abs(factoredPoleCase.velocityMPerSec-expectedFactoredVelocity)) < ...
    trajectoryTolerance && ...
    max(abs(factoredPoleCase.integralErrorMSeconds- ...
    expectedFactoredIntegral)) < trajectoryTolerance, ...
    ['The coupled PID states must follow the independently factored ' ...
    'three-pole trajectory, not only satisfy samplewise force identities.']);

noIntegral = model(4,0,3,-1,-1,20,0.01);
moderateIntegral = model(4,0.5,3,-1,-1,20,0.01);
highIntegral = model(4,2,3,-1,-1,20,0.01);
assert(abs(noIntegral.positionM(end)-0.75) < 1e-9 && ...
    abs(noIntegral.finalTrackingErrorM-0.25) < 1e-9, ...
    'P+D alone must retain the independently predicted -Fload/Kp offset.');
assert(noIntegral.positionLoopStable && ...
    ~noIntegral.internalStateAsymptoticallyStable && ...
    ~noIntegral.closedLoopStable && ...
    noIntegral.integralErrorMSeconds(end) > 5, ...
    ['With Ki=0, position may settle while the visible unused error ' ...
    'accumulator keeps growing, so the full internal state is not asymptotically stable.']);
assert(abs(moderateIntegral.finalTrackingErrorM) < ...
    abs(noIntegral.finalTrackingErrorM) && ...
    abs(highIntegral.finalTrackingErrorM) < 1e-5, ...
    'Moving only Ki upward must remove constant-load offset.');
assert(highIntegral.overshootM > moderateIntegral.overshootM+0.1, ...
    'The same Ki sweep must expose the excess-integral overshoot tradeoff.');
assert(noIntegral.proportionalGainNPerM == highIntegral.proportionalGainNPerM && ...
    noIntegral.derivativeGainNSecondPerM == highIntegral.derivativeGainNSecondPerM && ...
    noIntegral.loadForceN == highIntegral.loadForceN && ...
    noIntegral.maxInterval == highIntegral.maxInterval, ...
    'The Ki sweep must preserve Kp, Kd, load, and calculation interval.');

noDerivative = model(4,1,0,-1,-1,20,0.01);
moderateDerivative = model(4,1,1.5,-1,-1,20,0.01);
baselineDerivative = model(4,1,3,-1,-1,20,0.01);
noDerivativeWrongSign = model(4,1,0,-1,1,20,0.01);
assert(noDerivative.overshootM > 0.4 && ...
    moderateDerivative.overshootM < noDerivative.overshootM && ...
    baselineDerivative.overshootM < moderateDerivative.overshootM, ...
    'Moving only Kd upward must visibly damp the position overshoot.');
assert(noDerivative.maxAbsDerivativeControlN == 0 && ...
    baselineDerivative.maxAbsDerivativeControlN > ...
    moderateDerivative.maxAbsDerivativeControlN, ...
    'The Kd lever must trade more derivative effort for more damping.');
assert(noDerivative.proportionalGainNPerM == ...
    baselineDerivative.proportionalGainNPerM && ...
    noDerivative.integralGainNPerMSecond == ...
    baselineDerivative.integralGainNPerMSecond && ...
    noDerivative.loadForceN == baselineDerivative.loadForceN && ...
    noDerivative.maxInterval == baselineDerivative.maxInterval, ...
    'The Kd sweep must preserve Kp, Ki, load, and calculation interval.');
assert(isequal(noDerivative.positionM,noDerivativeWrongSign.positionM) && ...
    isequal(noDerivative.totalControlN,noDerivativeWrongSign.totalControlN), ...
    'Derivative polarity must not alter the plant when Kd is exactly zero.');

zeroController = model(0,0,0,0,-1,3,0.01);
assert(all(zeroController.positionM == 0) && ...
    all(zeroController.velocityMPerSec == 0) && ...
    all(zeroController.totalControlN == 0), ...
    'Zero gains and zero load must leave the carriage at rest.');
assert(abs(zeroController.integralErrorMSeconds(end)-3) < tolerance, ...
    'The visible error integral may accumulate even when Ki is zero.');

broken = model(4,0.5,3,-1,1,4,0.01);
recovered = model(4,0.5,3,-1,-1,20,0.01);
assert(~broken.closedLoopStable && ...
    broken.effectiveDampingNPerMPerSec == -2.5 && ...
    max(abs(broken.positionM)) > 100, ...
    'The wrong derivative sign must create negative damping and growth.');
assert(max(abs(broken.derivativeControlN- ...
    3*broken.velocityMPerSec)) < tolerance, ...
    'The broken trajectory must visibly reinforce measured velocity.');
assert(recovered.closedLoopStable && recovered.maxAbsControlN <= 4 && ...
    abs(recovered.finalTrackingErrorM) < 0.02 && ...
    max(abs(recovered.positionM)) < 1, ...
    'Restoring derivative opposition must recover a bounded response.');

assertAnyError(@() model(NaN,1,3,-1,-1,20,0.01), ...
    'A nonfinite proportional gain must be rejected.');
assertAnyError(@() model(4,Inf,3,-1,-1,20,0.01), ...
    'A nonfinite integral gain must be rejected.');
assertAnyError(@() model(4,1,3+1i,-1,-1,20,0.01), ...
    'A nonreal derivative gain must be rejected.');
assertAnyError(@() model(4,1,3,[0 -1],-1,20,0.01), ...
    'A nonscalar load must be rejected.');
assertAnyError(@() model(-1,1,3,-1,-1,20,0.01), ...
    'A negative proportional gain must be rejected.');
assertAnyError(@() model(4,1,3,-1,-1,0,0.01), ...
    'A nonpositive duration must be rejected.');
assertAnyError(@() model(4,1,3,-1,-1,20,0), ...
    'A nonpositive interval must be rejected.');
assertErrorId(@() model(21,1,3,-1,-1,20,0.001), ...
    'P06:ProportionalGainRange','An excessive Kp must be rejected.');
assertErrorId(@() model(4,11,3,-1,-1,20,0.001), ...
    'P06:IntegralGainRange','An excessive Ki must be rejected.');
assertErrorId(@() model(4,1,11,-1,-1,20,0.001), ...
    'P06:DerivativeGainRange','An excessive Kd must be rejected.');
assertErrorId(@() model(4,1,3,-11,-1,20,0.01), ...
    'P06:LoadRange','An excessive load must be rejected.');
assertErrorId(@() model(4,1,3,-1,0,20,0.01), ...
    'P06:DerivativeSign','An ambiguous derivative sign must be rejected.');
assertErrorId(@() model(4,1,3,-1,-1,31,0.01), ...
    'P06:HorizonRange','An excessive horizon must be rejected.');
assertErrorId(@() model(20,10,10,-1,-1,1,0.05), ...
    'P06:TimeResolution','An under-resolved PID request must be rejected.');
assertErrorId(@() model(4,0.5,10,-1,1,20,0.001), ...
    'P06:ResponseBound','An excessive anti-damped response must be rejected.');

acceptedResolution = model(20,10,10,-1,-1,1,0.005);
assert(acceptedResolution.characteristicRatePerSec* ...
    acceptedResolution.maxInterval < ...
    acceptedResolution.maxDimensionlessStep && ...
    all(isfinite(acceptedResolution.positionM)), ...
    'A resolved upper-gain request must retain finite samples.');
coarse = model(4,1,3,-1,-1,5,0.02);
fine = model(4,1,3,-1,-1,5,0.01);
assert(abs(coarse.positionM(end)-fine.positionM(end)) < 1e-6 && ...
    abs(coarse.velocityMPerSec(end)-fine.velocityMPerSec(end)) < 1e-6, ...
    'Halving a resolved RK4 interval must preserve the endpoint response.');
nonIntegerGrid = model(4,1,3,-1,-1,0.033,0.011);
assert(nonIntegerGrid.sampleCount == 4 && ...
    all(diff(nonIntegerGrid.t) > 0) && nonIntegerGrid.t(end) == 0.033, ...
    'An integer interval ratio must not create a duplicate final timestamp.');
shortHorizon = model(4,1,3,-1,-1,0.02,0.05);
assert(shortHorizon.sampleCount == 2 && ...
    abs(shortHorizon.maxInterval-0.02) < tolerance, ...
    'A clipped endpoint interval must report the interval actually used.');
atResourceLimit = model(4,1,3,-1,-1,20,0.001);
assert(atResourceLimit.sampleCount == 20001, ...
    'The declared maximum calculation grid must remain accepted.');
assertErrorId(@() model(4,1,3,-1,-1,20.001,0.001), ...
    'P06:TooManySamples','An excessive calculation grid must be rejected.');

disp('P06 checks passed: PID terms, levers, limits, sign recovery, and bounds.');
end

function assertAnyError(operation,message)
didError = false;
try
    operation();
catch
    didError = true;
end
assert(didError,message);
end

function assertErrorId(operation,expectedIdentifier,message)
actualIdentifier = '';
try
    operation();
catch exception
    actualIdentifier = exception.identifier;
end
assert(strcmp(actualIdentifier,expectedIdentifier),message);
end
