function run_checks
%RUN_CHECKS Independent margin identities, limits, failure, and recovery.
tolerance = 5e-10;

baselineA = model(1,0.2,20,0.01);
baselineB = model(1,0.2,20,0.01);
assert(isequaln(baselineA,baselineB), ...
    'Identical inputs must produce identical time and frequency outputs.');
assert(baselineA.output(1) == 0 && baselineA.velocityPerSec(1) == 0 && ...
    baselineA.actuator(1) == 0 && baselineA.controllerCommand(1) == 1, ...
    'The lagged baseline starts at rest while its command steps to one.');

plantResidual = baselineA.accelerationPerSec2-( ...
    baselineA.actuator- ...
    baselineA.plantDampingRatePerSec*baselineA.velocityPerSec);
actuatorResidual = baselineA.actuatorRatePerSec-( ...
    baselineA.controllerCommand-baselineA.actuator)/0.2;
assert(max(abs(plantResidual)) < tolerance, ...
    'Every sample must satisfy y second = actuator minus y first.');
assert(max(abs(actuatorResidual)) < tolerance, ...
    'Every lagged sample must satisfy tau*a first = command-a.');
expectedMagnitude = 1./(baselineA.omegaRadPerSec.* ...
    sqrt(1+baselineA.omegaRadPerSec.^2).* ...
    sqrt(1+(0.2*baselineA.omegaRadPerSec).^2));
expectedPhase = -90-atan(baselineA.omegaRadPerSec)*180/pi- ...
    atan(0.2*baselineA.omegaRadPerSec)*180/pi;
assert(max(abs(baselineA.openLoopMagnitude-expectedMagnitude)) < tolerance && ...
    max(abs(baselineA.openLoopPhaseDeg-expectedPhase)) < tolerance, ...
    'The frequency arrays must equal the independently expanded factors.');
assert(abs(baselineA.gainCrossoverRadPerSec* ...
    sqrt(1+baselineA.gainCrossoverRadPerSec^2)* ...
    sqrt(1+(0.2*baselineA.gainCrossoverRadPerSec)^2)-1) < tolerance, ...
    'Magnitude must equal one at the reported gain crossover.');
assert(abs(baselineA.phaseMarginDeg-(180+ ...
    baselineA.phaseAtGainCrossoverDeg)) < tolerance, ...
    'Phase margin must be the angular distance to minus 180 degrees.');
assert(abs(baselineA.phaseCrossoverRadPerSec-sqrt(5)) < tolerance && ...
    abs(baselineA.criticalLoopGain-6) < tolerance && ...
    abs(baselineA.gainMarginRatio-6) < tolerance && ...
    abs(baselineA.gainMarginDb-20*log10(6)) < tolerance, ...
    'The baseline must satisfy exact phase-crossover and gain-margin identities.');
assert(baselineA.closedLoopStable && baselineA.phaseMarginDeg > 40 && ...
    baselineA.phaseMarginDeg < 45 && baselineA.overshoot > 0.2 && ...
    baselineA.overshoot < 0.3 && abs(baselineA.output(end)-1) < 1e-4, ...
    'The baseline must have positive reserve and a bounded decaying response.');

tinyGain = model(1e-30,0.2,1,0.01);
assert(abs(tinyGain.gainCrossoverRadPerSec/1e-30-1) < 1e-12 && ...
    tinyGain.phaseMarginDeg > 89.9 && tinyGain.closedLoopStable, ...
    'A tiny positive gain must retain a relative-accuracy crossover bracket.');

% With K=0.15 and tau=0.8, the normalized characteristic polynomial is
% s^3+2.25*s^2+1.25*s+0.1875=(s+0.25)*(s+0.5)*(s+1.5).
% Its exact unit-step response independently constrains all three propagated
% states, not merely the samplewise equations derived from those states.
factoredPoleCase = model(0.15,0.8,4,0.002);
expectedFactoredOutput = 1+1.5*exp(-0.5*factoredPoleCase.t)- ...
    0.1*exp(-1.5*factoredPoleCase.t)- ...
    2.4*exp(-0.25*factoredPoleCase.t);
expectedFactoredVelocity = -0.75*exp(-0.5*factoredPoleCase.t)+ ...
    0.15*exp(-1.5*factoredPoleCase.t)+ ...
    0.6*exp(-0.25*factoredPoleCase.t);
expectedFactoredActuator = -0.375*exp(-0.5*factoredPoleCase.t)- ...
    0.075*exp(-1.5*factoredPoleCase.t)+ ...
    0.45*exp(-0.25*factoredPoleCase.t);
trajectoryTolerance = 1e-11;
assert(max(abs(factoredPoleCase.output-expectedFactoredOutput)) < ...
    trajectoryTolerance && ...
    max(abs(factoredPoleCase.velocityPerSec-expectedFactoredVelocity)) < ...
    trajectoryTolerance && ...
    max(abs(factoredPoleCase.actuator-expectedFactoredActuator)) < ...
    trajectoryTolerance, ...
    ['The RK4 states must follow the independently factored three-pole ' ...
    'trajectory.']);

lowGain = model(0.5,0.2,30,0.01);
nominalGain = model(1,0.2,30,0.01);
highGain = model(5.5,0.2,30,0.01);
assert(lowGain.gainCrossoverRadPerSec < nominalGain.gainCrossoverRadPerSec && ...
    nominalGain.gainCrossoverRadPerSec < highGain.gainCrossoverRadPerSec, ...
    'Moving only gain upward must raise gain crossover.');
assert(lowGain.phaseMarginDeg > nominalGain.phaseMarginDeg && ...
    nominalGain.phaseMarginDeg > highGain.phaseMarginDeg && ...
    lowGain.overshoot < nominalGain.overshoot && ...
    nominalGain.overshoot < highGain.overshoot, ...
    'The isolated gain sweep must connect lost margin to larger overshoot.');
assert(lowGain.actuatorLagSec == highGain.actuatorLagSec && ...
    lowGain.maxInterval == highGain.maxInterval, ...
    'The gain sweep must preserve actuator lag and calculation interval.');

shortLag = model(1,0.05,30,0.004);
nominalLag = model(1,0.2,30,0.004);
longLag = model(1,0.8,30,0.004);
assert(shortLag.phaseMarginDeg > nominalLag.phaseMarginDeg && ...
    nominalLag.phaseMarginDeg > longLag.phaseMarginDeg && ...
    shortLag.gainMarginRatio > nominalLag.gainMarginRatio && ...
    nominalLag.gainMarginRatio > longLag.gainMarginRatio, ...
    'Moving only actuator lag upward must reduce phase and gain reserve.');
assert(shortLag.overshoot < nominalLag.overshoot && ...
    nominalLag.overshoot < longLag.overshoot, ...
    'The isolated lag sweep must expose increased time-domain ringing.');
assert(shortLag.loopGain == longLag.loopGain && ...
    shortLag.maxInterval == longLag.maxInterval, ...
    'The lag sweep must preserve loop gain and calculation interval.');

zeroGain = model(0,0.2,3,0.01);
assert(all(zeroGain.output == 0) && all(zeroGain.actuator == 0) && ...
    ~zeroGain.closedLoopStable && isinf(zeroGain.phaseMarginDeg), ...
    'Zero gain must leave the plant at rest with no meaningful crossover.');
zeroLag = model(4,0,20,0.005);
assert(zeroLag.closedLoopStable && isinf(zeroLag.criticalLoopGain) && ...
    isinf(zeroLag.gainMarginRatio) && ...
    max(abs(zeroLag.actuator-zeroLag.controllerCommand)) < tolerance && ...
    max(abs(zeroLag.output)) < 1.5, ...
    'The instantaneous-actuator limit must apply command directly and stay stable.');

critical = model(3,0.5,20,0.005);
assert(~critical.closedLoopStable && abs(critical.phaseMarginDeg) < tolerance && ...
    critical.gainMarginRatio == 1 && ...
    strcmp(critical.stabilityClass,'marginal: zero margin'), ...
    'K=(1+tau)/tau must be the zero-margin limiting case.');
broken = model(4,0.5,30,0.005);
recovered = model(1,0.5,30,0.005);
assert(~broken.closedLoopStable && broken.phaseMarginDeg < 0 && ...
    broken.gainMarginRatio < 1 && broken.maxAbsOutput > 10, ...
    'Omitted actuator lag must create negative margin and visible growth.');
assert(recovered.closedLoopStable && recovered.phaseMarginDeg > 30 && ...
    recovered.gainMarginRatio > 1 && recovered.maxAbsOutput < 1.5 && ...
    abs(recovered.output(end)-1) < 0.02, ...
    'Reducing gain below the lagged critical value must recover decay.');

assertAnyError(@() model(NaN,0.2,20,0.01), ...
    'A nonfinite loop gain must be rejected.');
assertAnyError(@() model(1,Inf,20,0.01), ...
    'A nonfinite actuator lag must be rejected.');
assertAnyError(@() model(1,0.2,[10 20],0.01), ...
    'A nonscalar duration must be rejected.');
assertAnyError(@() model(-1,0.2,20,0.01), ...
    'A negative loop gain must be rejected.');
assertAnyError(@() model(1,-0.2,20,0.01), ...
    'A negative actuator lag must be rejected.');
assertAnyError(@() model(1,0.2,0,0.01), ...
    'A nonpositive duration must be rejected.');
assertAnyError(@() model(1,0.2,20,0), ...
    'A nonpositive interval must be rejected.');
assertErrorId(@() model(26,0.2,20,0.005), ...
    'P07:LoopGainRange','An excessive loop gain must be rejected.');
assertErrorId(@() model(1,2.1,20,0.01), ...
    'P07:ActuatorLagRange','An excessive actuator lag must be rejected.');
assertErrorId(@() model(1,0.2,41,0.01), ...
    'P07:HorizonRange','An excessive horizon must be rejected.');
assertErrorId(@() model(1,0.05,20,0.01), ...
    'P07:TimeResolution','An under-resolved actuator request must be rejected.');
assertErrorId(@() model(25,2,40,0.005), ...
    'P07:ResponseBound','An excessive unstable response must be rejected.');

acceptedResolution = model(25,0.05,1,0.005);
assert(acceptedResolution.characteristicRatePerSec* ...
    acceptedResolution.maxInterval <= ...
    acceptedResolution.maxDimensionlessStep+1e-12 && ...
    all(isfinite(acceptedResolution.output)), ...
    'A resolved upper-rate request must retain finite samples.');
coarse = model(1,0.2,5,0.01);
fine = model(1,0.2,5,0.005);
assert(abs(coarse.output(end)-fine.output(end)) < 1e-7 && ...
    abs(coarse.velocityPerSec(end)-fine.velocityPerSec(end)) < 1e-7, ...
    'Halving a resolved RK4 interval must preserve the endpoint response.');
nonIntegerGrid = model(1,0.2,0.033,0.011);
assert(nonIntegerGrid.sampleCount == 4 && ...
    all(diff(nonIntegerGrid.t) > 0) && nonIntegerGrid.t(end) == 0.033, ...
    'An integer interval ratio must not duplicate the final timestamp.');
shortHorizon = model(1,0.2,0.02,0.05);
assert(shortHorizon.sampleCount == 2 && ...
    abs(shortHorizon.maxInterval-0.02) < tolerance, ...
    'A clipped endpoint interval must report the interval actually used.');
atResourceLimit = model(1,0.2,20,0.001);
assert(atResourceLimit.sampleCount == 20001, ...
    'The declared maximum calculation grid must remain accepted.');
assertErrorId(@() model(1,0.2,20.001,0.001), ...
    'P07:TooManySamples','An excessive calculation grid must be rejected.');

disp('P07 checks passed: margins, levers, limits, lag recovery, and bounds.');
end

function assertAnyError(operation,message)
didError = false;
try
    operation();
catch
    didError = true;
end
assert(didError,message);
end

function assertErrorId(operation,expectedIdentifier,message)
actualIdentifier = '';
try
    operation();
catch exception
    actualIdentifier = exception.identifier;
end
assert(strcmp(actualIdentifier,expectedIdentifier),message);
end
