function interactive
%INTERACTIVE Explore P22 line-of-sight guidance and acceleration authority.
modelFunction = @model;

window = uifigure('Name','P22 - Proportional navigation', ...
    'Position',[80 80 1220 780]);
geometryAxes = uiaxes(window,'Position',[45 525 730 210]);
losAxes = uiaxes(window,'Position',[45 285 730 190]);
accelerationAxes = uiaxes(window,'Position',[45 45 730 190]);

uilabel(window,'Position',[820 690 330 22], ...
    'Text','Navigation constant N (dimensionless)');
navigationSlider = uislider(window,'Position',[825 670 320 3], ...
    'Limits',[0 8],'Value',3,'MajorTicks',[0 1 2 3 4 5 6 7 8]);

uilabel(window,'Position',[820 615 210 22], ...
    'Text','Target crossing speed (m/s)');
crossingSpeedSpinner = uispinner(window,'Position',[1040 615 105 22], ...
    'Limits',[-150 150],'Step',5,'Value',60);

uilabel(window,'Position',[820 560 220 22], ...
    'Text','Acceleration limit (m/s^2)');
accelerationLimitSpinner = uispinner(window, ...
    'Position',[1040 560 105 22], ...
    'Limits',[5 120],'Step',5,'Value',80);

resetButton = uibutton(window,'push','Text','Reset PN baseline', ...
    'Position',[820 505 325 30]);
statusLabel = uilabel(window,'Position',[820 55 350 415], ...
    'VerticalAlignment','top','WordWrap','on','Text','');

navigationSlider.ValueChangingFcn = @(~,event) redraw(event.Value, ...
    crossingSpeedSpinner.Value,accelerationLimitSpinner.Value);
navigationSlider.ValueChangedFcn = @(~,~) redraw( ...
    navigationSlider.Value,crossingSpeedSpinner.Value, ...
    accelerationLimitSpinner.Value);
crossingSpeedSpinner.ValueChangedFcn = @(~,~) redraw( ...
    navigationSlider.Value,crossingSpeedSpinner.Value, ...
    accelerationLimitSpinner.Value);
accelerationLimitSpinner.ValueChangedFcn = @(~,~) redraw( ...
    navigationSlider.Value,crossingSpeedSpinner.Value, ...
    accelerationLimitSpinner.Value);
resetButton.ButtonPushedFcn = @(~,~) resetBaseline();

redraw(3,60,80);

function resetBaseline
    navigationSlider.Value = 3;
    crossingSpeedSpinner.Value = 60;
    accelerationLimitSpinner.Value = 80;
    redraw(3,60,80);
end

function redraw(navigationConstant,targetCrossingSpeed,accelerationLimit)
    result = modelFunction(navigationConstant,targetCrossingSpeed, ...
        accelerationLimit,0.02,25);

    cla(geometryAxes);
    plot(geometryAxes,result.interceptorXM,result.interceptorYM,'b-', ...
        'LineWidth',1.8,'DisplayName','Interceptor');
    hold(geometryAxes,'on');
    plot(geometryAxes,result.targetXM,result.targetYM,'m--', ...
        'LineWidth',1.8,'DisplayName','Target');
    plot(geometryAxes,result.interceptorXM(end), ...
        result.interceptorYM(end),'gx','LineWidth',2, ...
        'DisplayName','Terminal separation');
    hold(geometryAxes,'off'); axis(geometryAxes,'equal');
    grid(geometryAxes,'on');
    xlabel(geometryAxes,'Downrange x (m)');
    ylabel(geometryAxes,'Crossrange y (m)');
    title(geometryAxes,'Planar engagement geometry');
    legend(geometryAxes,'Location','best');

    cla(losAxes);
    yyaxis(losAxes,'left');
    plot(losAxes,result.timeSec,result.rangeM,'k-', ...
        'LineWidth',1.7);
    ylabel(losAxes,'Range (m)');
    yyaxis(losAxes,'right');
    plot(losAxes,result.timeSec, ...
        rad2deg(result.lineOfSightRateRadPerSec),'c-', ...
        'LineWidth',1.7);
    ylabel(losAxes,'LOS rate (deg/s)');
    grid(losAxes,'on'); xlabel(losAxes,'Time (s)');
    title(losAxes,'Decreasing range and constant-bearing evidence');

    cla(accelerationAxes);
    plot(accelerationAxes,result.timeSec, ...
        result.commandAccelerationMPerSec2,'m--','LineWidth',1.5, ...
        'DisplayName','Commanded acceleration');
    hold(accelerationAxes,'on');
    plot(accelerationAxes,result.timeSec, ...
        result.actualAccelerationMPerSec2,'b-','LineWidth',1.7, ...
        'DisplayName','Applied acceleration');
    yline(accelerationAxes,accelerationLimit,'r:', ...
        'Positive acceleration limit');
    yline(accelerationAxes,-accelerationLimit,'r:', ...
        'Negative acceleration limit');
    hold(accelerationAxes,'off'); grid(accelerationAxes,'on');
    xlabel(accelerationAxes,'Time (s)');
    ylabel(accelerationAxes,'Lateral acceleration (m/s^2)');
    title(accelerationAxes,'PN request versus available turn authority');
    legend(accelerationAxes,'Location','best');

    if result.intercepted && result.saturationDurationSec == 0
        interpretation = ['intercept: LOS rotation was suppressed while ' ...
            'range decreased, without acceleration clipping'];
    elseif result.intercepted
        interpretation = ['intercept despite clipping: acceleration ' ...
            'authority was active and margin should not be assumed'];
    elseif result.saturationDurationSec > 0
        interpretation = ['time-limit miss with clipping: applied turn ' ...
            'differed from the PN request; compare a higher limit before ' ...
            'attributing the miss to authority'];
    elseif navigationConstant == 0
        interpretation = ['time-limit miss: N=0 disables guidance, so the ' ...
            'initial LOS rotation is not corrected'];
    else
        interpretation = ['time-limit miss: the selected guidance response ' ...
            'did not enter the capture radius'];
    end
    statusLabel.Text = sprintf([ ...
        '%s\n\nN: %.2f\ntarget crossing speed: %.1f m/s\n' ...
        'acceleration limit: %.1f m/s^2\n\n' ...
        'closest range: %.3f m at %.3f s\n' ...
        'capture radius: %.1f m\n' ...
        'peak command: %.3f m/s^2\n' ...
        'peak applied: %.3f m/s^2\n' ...
        'saturation duration: %.3f s\n' ...
        'initial LOS rate: %.4f deg/s\n' ...
        'closest-sample LOS rate: %.4f deg/s\n\n%s'], ...
        upper(result.terminationReason),navigationConstant, ...
        targetCrossingSpeed,accelerationLimit, ...
        result.closestApproachDistanceM,result.closestApproachTimeSec, ...
        result.interceptRadiusM,result.peakCommandAccelerationMPerSec2, ...
        result.peakActualAccelerationMPerSec2, ...
        result.saturationDurationSec, ...
        rad2deg(result.initialLineOfSightRateRadPerSec), ...
        rad2deg(result.closestApproachLineOfSightRateRadPerSec), ...
        interpretation);
end
end
