function result = model(navigationConstant,targetCrossingSpeedMPerSec, ...
    maximumAccelerationMPerSec2,timeStepSec,maximumTimeSec)
%MODEL Simulate transparent planar proportional navigation with saturation.
arguments
    navigationConstant (1,1) double {mustBeReal,mustBeFinite} = 3
    targetCrossingSpeedMPerSec (1,1) double ...
        {mustBeReal,mustBeFinite} = 60
    maximumAccelerationMPerSec2 (1,1) double ...
        {mustBeReal,mustBeFinite,mustBePositive} = 80
    timeStepSec (1,1) double ...
        {mustBeReal,mustBeFinite,mustBePositive} = 0.02
    maximumTimeSec (1,1) double ...
        {mustBeReal,mustBeFinite,mustBePositive} = 25
end

if navigationConstant < 0 || navigationConstant > 8
    error('P22:NavigationConstantRange', ...
        'Navigation constant must be between 0 and 8.');
end
if abs(targetCrossingSpeedMPerSec) > 150
    error('P22:TargetCrossingSpeedRange', ...
        'Target crossing speed must be between -150 and 150 m/s.');
end
if maximumAccelerationMPerSec2 < 5 || ...
        maximumAccelerationMPerSec2 > 120
    error('P22:AccelerationLimitRange', ...
        'Maximum lateral acceleration must be between 5 and 120 m/s^2.');
end
if timeStepSec < 0.005 || timeStepSec > 0.1
    error('P22:TimeStepRange', ...
        'Time step must be between 0.005 and 0.1 seconds.');
end
if maximumTimeSec < 5 || maximumTimeSec > 40
    error('P22:MaximumTimeRange', ...
        'Maximum time must be between 5 and 40 seconds.');
end

stepRatio = maximumTimeSec/timeStepSec;
roundedStepRatio = round(stepRatio);
gridTolerance = 64*eps(max(1,abs(stepRatio)));
if abs(stepRatio-roundedStepRatio) > gridTolerance
    error('P22:TimeGridMismatch', ...
        'Maximum time must be an integer multiple of the time step.');
end
minimumStepCount = 51;
maximumStepCount = 5001;
allocatedStepCount = roundedStepRatio+1;
if allocatedStepCount < minimumStepCount || ...
        allocatedStepCount > maximumStepCount
    error('P22:StepCountRange', ...
        'The derived history must contain between 51 and 5001 samples.');
end

% Fixed educational geometry: interceptor begins at the origin on +x;
% the target begins downrange and crosses in +y at constant velocity.
interceptorSpeedMPerSec = 300;
targetAlongTrackSpeedMPerSec = 0;
initialInterceptorPositionM = [0 0];
initialTargetPositionM = [5000 600];
initialInterceptorHeadingRad = 0;
interceptRadiusM = 5;

% All resource bounds above run before allocating engagement histories.
timeSec = (0:roundedStepRatio)*timeStepSec;
interceptorXM = zeros(1,allocatedStepCount);
interceptorYM = zeros(1,allocatedStepCount);
targetXM = zeros(1,allocatedStepCount);
targetYM = zeros(1,allocatedStepCount);
interceptorHeadingRad = zeros(1,allocatedStepCount);
rangeM = zeros(1,allocatedStepCount);
lineOfSightAngleRad = zeros(1,allocatedStepCount);
lineOfSightRateRadPerSec = zeros(1,allocatedStepCount);
closingSpeedMPerSec = zeros(1,allocatedStepCount);
commandAccelerationMPerSec2 = zeros(1,allocatedStepCount);
actualAccelerationMPerSec2 = zeros(1,allocatedStepCount);
saturated = false(1,allocatedStepCount);

interceptorXM(1) = initialInterceptorPositionM(1);
interceptorYM(1) = initialInterceptorPositionM(2);
targetXM(1) = initialTargetPositionM(1);
targetYM(1) = initialTargetPositionM(2);
interceptorHeadingRad(1) = initialInterceptorHeadingRad;
usedStepCount = allocatedStepCount;
intercepted = false;
finalStepFraction = 1;
captureOnThisSample = false;

for k = 1:allocatedStepCount
    interceptorVelocityXMPerSec = interceptorSpeedMPerSec* ...
        cos(interceptorHeadingRad(k));
    interceptorVelocityYMPerSec = interceptorSpeedMPerSec* ...
        sin(interceptorHeadingRad(k));
    relativeXM = targetXM(k)-interceptorXM(k);
    relativeYM = targetYM(k)-interceptorYM(k);
    relativeVelocityXMPerSec = targetAlongTrackSpeedMPerSec- ...
        interceptorVelocityXMPerSec;
    relativeVelocityYMPerSec = targetCrossingSpeedMPerSec- ...
        interceptorVelocityYMPerSec;

    rangeSquaredM2 = relativeXM^2+relativeYM^2;
    rangeM(k) = sqrt(rangeSquaredM2);
    lineOfSightAngleRad(k) = atan2(relativeYM,relativeXM);
    closingSpeedMPerSec(k) = -(relativeXM*relativeVelocityXMPerSec+ ...
        relativeYM*relativeVelocityYMPerSec)/rangeM(k);
    lineOfSightRateRadPerSec(k) = ...
        (relativeXM*relativeVelocityYMPerSec- ...
        relativeYM*relativeVelocityXMPerSec)/rangeSquaredM2;

    positiveClosingSpeedMPerSec = max(closingSpeedMPerSec(k),0);
    commandAccelerationMPerSec2(k) = navigationConstant* ...
        positiveClosingSpeedMPerSec*lineOfSightRateRadPerSec(k);
    actualAccelerationMPerSec2(k) = min(max( ...
        commandAccelerationMPerSec2(k),-maximumAccelerationMPerSec2), ...
        maximumAccelerationMPerSec2);
    saturationTolerance = 64*eps(max([1 ...
        abs(commandAccelerationMPerSec2(k)) ...
        maximumAccelerationMPerSec2]));
    saturated(k) = abs(commandAccelerationMPerSec2(k)) > ...
        maximumAccelerationMPerSec2+saturationTolerance;

    if rangeM(k) <= interceptRadiusM || captureOnThisSample
        intercepted = true;
        usedStepCount = k;
        break;
    end
    if k == allocatedStepCount
        break;
    end

    % Semi-implicit fixed-step turn: acceleration is normal to the constant
    % speed velocity, so heading rate is a_n / speed.
    proposedHeadingRad = interceptorHeadingRad(k)+ ...
        actualAccelerationMPerSec2(k)/interceptorSpeedMPerSec*timeStepSec;
    proposedInterceptorXM = interceptorXM(k)+interceptorSpeedMPerSec* ...
        cos(proposedHeadingRad)*timeStepSec;
    proposedInterceptorYM = interceptorYM(k)+interceptorSpeedMPerSec* ...
        sin(proposedHeadingRad)*timeStepSec;
    proposedTargetXM = targetXM(k)+ ...
        targetAlongTrackSpeedMPerSec*timeStepSec;
    proposedTargetYM = targetYM(k)+ ...
        targetCrossingSpeedMPerSec*timeStepSec;

    % Resolve the first crossing of the capture circle along this discrete
    % step. This prevents a coarse sample grid from stepping over capture.
    nextRelativeXM = proposedTargetXM-proposedInterceptorXM;
    nextRelativeYM = proposedTargetYM-proposedInterceptorYM;
    deltaRelativeXM = nextRelativeXM-relativeXM;
    deltaRelativeYM = nextRelativeYM-relativeYM;
    segmentA = deltaRelativeXM^2+deltaRelativeYM^2;
    segmentB = 2*(relativeXM*deltaRelativeXM+ ...
        relativeYM*deltaRelativeYM);
    segmentC = rangeSquaredM2-interceptRadiusM^2;
    segmentDiscriminant = segmentB^2-4*segmentA*segmentC;
    crossingFraction = NaN;
    if segmentA > 0 && segmentDiscriminant >= 0
        candidateFraction = (-segmentB-sqrt(segmentDiscriminant))/(2*segmentA);
        if candidateFraction >= 0 && candidateFraction <= 1
            crossingFraction = candidateFraction;
        end
    end
    if isfinite(crossingFraction)
        captureOnThisSample = true;
        finalStepFraction = crossingFraction;
        timeSec(k+1) = timeSec(k)+crossingFraction*timeStepSec;
        interceptorHeadingRad(k+1) = interceptorHeadingRad(k)+ ...
            crossingFraction*(proposedHeadingRad-interceptorHeadingRad(k));
        interceptorXM(k+1) = interceptorXM(k)+crossingFraction* ...
            (proposedInterceptorXM-interceptorXM(k));
        interceptorYM(k+1) = interceptorYM(k)+crossingFraction* ...
            (proposedInterceptorYM-interceptorYM(k));
        targetXM(k+1) = targetXM(k)+crossingFraction* ...
            (proposedTargetXM-targetXM(k));
        targetYM(k+1) = targetYM(k)+crossingFraction* ...
            (proposedTargetYM-targetYM(k));
    else
        interceptorHeadingRad(k+1) = proposedHeadingRad;
        interceptorXM(k+1) = proposedInterceptorXM;
        interceptorYM(k+1) = proposedInterceptorYM;
        targetXM(k+1) = proposedTargetXM;
        targetYM(k+1) = proposedTargetYM;
    end
end

timeSec = timeSec(1:usedStepCount);
interceptorXM = interceptorXM(1:usedStepCount);
interceptorYM = interceptorYM(1:usedStepCount);
targetXM = targetXM(1:usedStepCount);
targetYM = targetYM(1:usedStepCount);
interceptorHeadingRad = interceptorHeadingRad(1:usedStepCount);
rangeM = rangeM(1:usedStepCount);
lineOfSightAngleRad = lineOfSightAngleRad(1:usedStepCount);
lineOfSightRateRadPerSec = lineOfSightRateRadPerSec(1:usedStepCount);
closingSpeedMPerSec = closingSpeedMPerSec(1:usedStepCount);
commandAccelerationMPerSec2 = ...
    commandAccelerationMPerSec2(1:usedStepCount);
actualAccelerationMPerSec2 = ...
    actualAccelerationMPerSec2(1:usedStepCount);
saturated = saturated(1:usedStepCount);

[sampledClosestApproachDistanceM,closestApproachIndex] = min(rangeM);
closestApproachDistanceM = sampledClosestApproachDistanceM;
closestApproachTimeSec = timeSec(closestApproachIndex);
% For a miss, retain the closest point on each piecewise-linear relative
% motion segment rather than only the closest retained sample.
for k = 1:usedStepCount-1
    relativeStartM = [targetXM(k)-interceptorXM(k) ...
        targetYM(k)-interceptorYM(k)];
    relativeEndM = [targetXM(k+1)-interceptorXM(k+1) ...
        targetYM(k+1)-interceptorYM(k+1)];
    relativeDeltaM = relativeEndM-relativeStartM;
    relativeDeltaSquaredM2 = sum(relativeDeltaM.^2);
    if relativeDeltaSquaredM2 > 0
        closestFraction = min(max( ...
            -sum(relativeStartM.*relativeDeltaM)/ ...
            relativeDeltaSquaredM2,0),1);
    else
        closestFraction = 0;
    end
    segmentClosestDistanceM = norm(relativeStartM+ ...
        closestFraction*relativeDeltaM);
    if segmentClosestDistanceM < closestApproachDistanceM
        closestApproachDistanceM = segmentClosestDistanceM;
        closestApproachTimeSec = timeSec(k)+closestFraction* ...
            (timeSec(k+1)-timeSec(k));
        if closestFraction <= 0.5
            closestApproachIndex = k;
        else
            closestApproachIndex = k+1;
        end
    end
end
peakCommandAccelerationMPerSec2 = ...
    max(abs(commandAccelerationMPerSec2));
peakActualAccelerationMPerSec2 = max(abs(actualAccelerationMPerSec2));
saturationSampleCount = sum(saturated);
if intercepted && usedStepCount > 1
    saturationDurationSec = sum(saturated(1:usedStepCount-2))*timeStepSec+ ...
        saturated(usedStepCount-1)*finalStepFraction*timeStepSec;
else
    saturationDurationSec = sum(saturated(1:max(usedStepCount-1,1)))* ...
        timeStepSec;
end
saturationFraction = saturationSampleCount/usedStepCount;
initialLineOfSightRateRadPerSec = lineOfSightRateRadPerSec(1);
closestApproachLineOfSightRateRadPerSec = ...
    lineOfSightRateRadPerSec(closestApproachIndex);
if initialLineOfSightRateRadPerSec == 0
    lineOfSightRateReductionRatio = 0;
else
    lineOfSightRateReductionRatio = ...
        abs(closestApproachLineOfSightRateRadPerSec)/ ...
        abs(initialLineOfSightRateRadPerSec);
end
if intercepted
    terminationReason = 'intercept';
else
    terminationReason = 'time-limit';
end

result = struct( ...
    'navigationConstant',navigationConstant, ...
    'targetCrossingSpeedMPerSec',targetCrossingSpeedMPerSec, ...
    'maximumAccelerationMPerSec2',maximumAccelerationMPerSec2, ...
    'timeStepSec',timeStepSec, ...
    'maximumTimeSec',maximumTimeSec, ...
    'minimumStepCount',minimumStepCount, ...
    'maximumStepCount',maximumStepCount, ...
    'allocatedStepCount',allocatedStepCount, ...
    'usedStepCount',usedStepCount, ...
    'finalStepFraction',finalStepFraction, ...
    'interceptorSpeedMPerSec',interceptorSpeedMPerSec, ...
    'targetAlongTrackSpeedMPerSec',targetAlongTrackSpeedMPerSec, ...
    'initialInterceptorPositionM',initialInterceptorPositionM, ...
    'initialTargetPositionM',initialTargetPositionM, ...
    'initialInterceptorHeadingRad',initialInterceptorHeadingRad, ...
    'interceptRadiusM',interceptRadiusM, ...
    'timeSec',timeSec, ...
    'interceptorXM',interceptorXM, ...
    'interceptorYM',interceptorYM, ...
    'targetXM',targetXM, ...
    'targetYM',targetYM, ...
    'interceptorHeadingRad',interceptorHeadingRad, ...
    'rangeM',rangeM, ...
    'lineOfSightAngleRad',lineOfSightAngleRad, ...
    'lineOfSightRateRadPerSec',lineOfSightRateRadPerSec, ...
    'closingSpeedMPerSec',closingSpeedMPerSec, ...
    'commandAccelerationMPerSec2',commandAccelerationMPerSec2, ...
    'actualAccelerationMPerSec2',actualAccelerationMPerSec2, ...
    'saturated',saturated, ...
    'intercepted',intercepted, ...
    'terminationReason',terminationReason, ...
    'closestApproachDistanceM',closestApproachDistanceM, ...
    'sampledClosestApproachDistanceM', ...
    sampledClosestApproachDistanceM, ...
    'closestApproachTimeSec',closestApproachTimeSec, ...
    'closestApproachIndex',closestApproachIndex, ...
    'peakCommandAccelerationMPerSec2', ...
    peakCommandAccelerationMPerSec2, ...
    'peakActualAccelerationMPerSec2',peakActualAccelerationMPerSec2, ...
    'saturationSampleCount',saturationSampleCount, ...
    'saturationDurationSec',saturationDurationSec, ...
    'saturationFraction',saturationFraction, ...
    'initialLineOfSightRateRadPerSec', ...
    initialLineOfSightRateRadPerSec, ...
    'closestApproachLineOfSightRateRadPerSec', ...
    closestApproachLineOfSightRateRadPerSec, ...
    'lineOfSightRateReductionRatio',lineOfSightRateReductionRatio);
end
