function run_checks
%RUN_CHECKS Verify P22 geometry, PN recurrence, events, limits, and failures.
tolerance = 2e-10;
baselineA = model(3,60,80,0.02,25);
baselineB = model(3,60,80,0.02,25);
assert(isequaln(baselineA,baselineB), ...
    'Repeated baseline calls must be exactly deterministic.');

% Independently reconstruct relative geometry and the PN law at every
% retained sample from positions and heading, not from summary fields.
relativeXM = baselineA.targetXM-baselineA.interceptorXM;
relativeYM = baselineA.targetYM-baselineA.interceptorYM;
interceptorVelocityXMPerSec = baselineA.interceptorSpeedMPerSec* ...
    cos(baselineA.interceptorHeadingRad);
interceptorVelocityYMPerSec = baselineA.interceptorSpeedMPerSec* ...
    sin(baselineA.interceptorHeadingRad);
relativeVelocityXMPerSec = baselineA.targetAlongTrackSpeedMPerSec- ...
    interceptorVelocityXMPerSec;
relativeVelocityYMPerSec = baselineA.targetCrossingSpeedMPerSec- ...
    interceptorVelocityYMPerSec;
expectedRangeM = sqrt(relativeXM.^2+relativeYM.^2);
expectedClosingSpeedMPerSec = -(relativeXM.*relativeVelocityXMPerSec+ ...
    relativeYM.*relativeVelocityYMPerSec)./expectedRangeM;
expectedLineOfSightRateRadPerSec = ...
    (relativeXM.*relativeVelocityYMPerSec- ...
    relativeYM.*relativeVelocityXMPerSec)./expectedRangeM.^2;
expectedCommandAccelerationMPerSec2 = baselineA.navigationConstant* ...
    max(expectedClosingSpeedMPerSec,0).* ...
    expectedLineOfSightRateRadPerSec;
expectedActualAccelerationMPerSec2 = min(max( ...
    expectedCommandAccelerationMPerSec2, ...
    -baselineA.maximumAccelerationMPerSec2), ...
    baselineA.maximumAccelerationMPerSec2);
assert(max(abs(baselineA.rangeM-expectedRangeM)) < tolerance && ...
    max(abs(baselineA.closingSpeedMPerSec- ...
    expectedClosingSpeedMPerSec)) < tolerance && ...
    max(abs(baselineA.lineOfSightRateRadPerSec- ...
    expectedLineOfSightRateRadPerSec)) < tolerance, ...
    'Range, closing speed, and LOS rate must match relative geometry.');
assert(max(abs(baselineA.commandAccelerationMPerSec2- ...
    expectedCommandAccelerationMPerSec2)) < tolerance && ...
    max(abs(baselineA.actualAccelerationMPerSec2- ...
    expectedActualAccelerationMPerSec2)) < tolerance, ...
    'Command and signed clipping must match the explicit PN law.');

% Every complete integration interval uses applied normal acceleration to
% update heading first, then moves the constant-speed interceptor.
fullStepEnd = baselineA.usedStepCount-2;
for k = 1:fullStepEnd
    expectedNextHeading = baselineA.interceptorHeadingRad(k)+ ...
        baselineA.actualAccelerationMPerSec2(k)/ ...
        baselineA.interceptorSpeedMPerSec*baselineA.timeStepSec;
    expectedNextXM = baselineA.interceptorXM(k)+ ...
        baselineA.interceptorSpeedMPerSec*cos(expectedNextHeading)* ...
        baselineA.timeStepSec;
    expectedNextYM = baselineA.interceptorYM(k)+ ...
        baselineA.interceptorSpeedMPerSec*sin(expectedNextHeading)* ...
        baselineA.timeStepSec;
    assert(abs(baselineA.interceptorHeadingRad(k+1)- ...
        expectedNextHeading) < tolerance && ...
        abs(baselineA.interceptorXM(k+1)-expectedNextXM) < tolerance && ...
        abs(baselineA.interceptorYM(k+1)-expectedNextYM) < tolerance, ...
        'The semi-implicit heading and position recurrence must be exact.');
end
assert(max(abs(baselineA.targetXM-5000)) < tolerance && ...
    max(abs(baselineA.targetYM-(600+60*baselineA.timeSec))) < ...
    tolerance,'The target must retain its declared constant velocity.');

% Independent initial arithmetic and retained baseline outcome.
initialRangeM = sqrt(5000^2+600^2);
initialClosingSpeedMPerSec = -([5000 600]*[-300;60])/initialRangeM;
initialLineOfSightRateRadPerSec = ...
    (5000*60-600*(-300))/initialRangeM^2;
initialCommandAccelerationMPerSec2 = 3* ...
    initialClosingSpeedMPerSec*initialLineOfSightRateRadPerSec;
assert(abs(baselineA.rangeM(1)-initialRangeM) < tolerance && ...
    abs(baselineA.closingSpeedMPerSec(1)- ...
    initialClosingSpeedMPerSec) < tolerance && ...
    abs(baselineA.lineOfSightRateRadPerSec(1)- ...
    initialLineOfSightRateRadPerSec) < tolerance && ...
    abs(baselineA.commandAccelerationMPerSec2(1)- ...
    initialCommandAccelerationMPerSec2) < tolerance, ...
    'Initial range, closing speed, LOS rate, and PN command must be exact.');
assert(abs(baselineA.rangeM(1)-5035.871324805668) < tolerance && ...
    abs(baselineA.closingSpeedMPerSec(1)-290.7143383089708) < ...
    tolerance && ...
    abs(baselineA.lineOfSightRateRadPerSec(1)- ...
    0.018927444794952685) < tolerance && ...
    abs(baselineA.commandAccelerationMPerSec2(1)- ...
    16.50743876833273) < tolerance, ...
    'Baseline initial reference metrics must remain deterministic.');
assert(baselineA.intercepted && ...
    strcmp(baselineA.terminationReason,'intercept') && ...
    abs(baselineA.closestApproachDistanceM-5) < 2e-9 && ...
    abs(baselineA.closestApproachTimeSec-17.72639209846985) < 2e-9 && ...
    baselineA.saturationDurationSec == 0 && ...
    baselineA.peakCommandAccelerationMPerSec2 < 80, ...
    'Baseline must enter the capture circle without saturation.');

% Segment/circle interpolation gives a fractional terminal interval and
% prevents a 0.1 s grid from stepping over capture.
assert(baselineA.finalStepFraction > 0 && ...
    baselineA.finalStepFraction < 1 && ...
    baselineA.timeSec(end)-baselineA.timeSec(end-1) < ...
    baselineA.timeStepSec && ...
    abs(baselineA.rangeM(end)-baselineA.interceptRadiusM) < 2e-9, ...
    'Baseline capture must terminate on a fractional capture-circle entry.');
coarse = model(3,60,80,0.1,25);
fine = model(3,60,80,0.005,25);
assert(coarse.intercepted && fine.intercepted && ...
    abs(coarse.closestApproachDistanceM-5) < 2e-9 && ...
    abs(fine.closestApproachDistanceM-5) < 2e-9 && ...
    abs(coarse.closestApproachTimeSec-fine.closestApproachTimeSec) < 0.01, ...
    'Coarse and fine grids must both detect interpolated capture.');

% Independent navigation-constant sweep: all non-swept values reset.
navigationConstantValues = [1 2 3 4 5];
expectedNavigationIntercepted = [false true true true true];
navigationMissDistanceM = zeros(size(navigationConstantValues));
for k = 1:numel(navigationConstantValues)
    changed = model(navigationConstantValues(k),60,80,0.02,25);
    assert(changed.targetCrossingSpeedMPerSec == 60 && ...
        changed.maximumAccelerationMPerSec2 == 80 && ...
        changed.timeStepSec == 0.02 && changed.maximumTimeSec == 25, ...
        'Navigation-constant sweep must reset non-swept inputs.');
    expectedInitialCommand = navigationConstantValues(k)* ...
        initialClosingSpeedMPerSec*initialLineOfSightRateRadPerSec;
    assert(abs(changed.commandAccelerationMPerSec2(1)- ...
        expectedInitialCommand) < tolerance && ...
        changed.intercepted == expectedNavigationIntercepted(k), ...
        'The N sweep must scale initial command and cross the intercept boundary.');
    navigationMissDistanceM(k) = changed.closestApproachDistanceM;
end
assert(navigationMissDistanceM(1) > 50 && ...
    all(abs(navigationMissDistanceM(2:5)-5) < 2e-9), ...
    'N=1 must miss while N=2 through N=5 enter the capture circle.');

% Independent acceleration-authority sweep and exact signed clipping.
accelerationLimitValuesMPerSec2 = [5 10 20 40 80];
expectedAuthorityIntercepted = [false false true true true];
for k = 1:numel(accelerationLimitValuesMPerSec2)
    changed = model(3,60,accelerationLimitValuesMPerSec2(k),0.02,25);
    assert(changed.navigationConstant == 3 && ...
        changed.targetCrossingSpeedMPerSec == 60 && ...
        changed.timeStepSec == 0.02 && changed.maximumTimeSec == 25, ...
        'Acceleration sweep must reset non-swept inputs.');
    assert(max(abs(changed.actualAccelerationMPerSec2)) <= ...
        accelerationLimitValuesMPerSec2(k)+tolerance && ...
        changed.intercepted == expectedAuthorityIntercepted(k), ...
        'Acceleration sweep must respect clipping and cross the intercept boundary.');
end
exactLimit = initialCommandAccelerationMPerSec2;
atLimit = model(3,60,exactLimit,0.02,25);
belowLimit = model(3,60,exactLimit-1e-6,0.02,25);
assert(~atLimit.saturated(1) && belowLimit.saturated(1) && ...
    abs(belowLimit.actualAccelerationMPerSec2(1)- ...
    (exactLimit-1e-6)) < tolerance, ...
    'The exact acceleration boundary must pass and a smaller limit must clip.');

% A negative LOS rate must reverse both the PN command and the applied turn;
% this guards the full signed crossing-speed control range.
negativeLineOfSight = model(3,-150,5,0.02,25);
expectedNegativeClosingSpeedMPerSec = ...
    -([5000 600]*[-300;-150])/initialRangeM;
expectedNegativeLineOfSightRateRadPerSec = ...
    (5000*(-150)-600*(-300))/initialRangeM^2;
expectedNegativeCommandAccelerationMPerSec2 = 3* ...
    expectedNegativeClosingSpeedMPerSec* ...
    expectedNegativeLineOfSightRateRadPerSec;
assert(expectedNegativeLineOfSightRateRadPerSec < 0 && ...
    abs(negativeLineOfSight.lineOfSightRateRadPerSec(1)- ...
    expectedNegativeLineOfSightRateRadPerSec) < tolerance && ...
    abs(negativeLineOfSight.commandAccelerationMPerSec2(1)- ...
    expectedNegativeCommandAccelerationMPerSec2) < tolerance && ...
    negativeLineOfSight.commandAccelerationMPerSec2(1) < -5 && ...
    negativeLineOfSight.actualAccelerationMPerSec2(1) == -5 && ...
    negativeLineOfSight.saturated(1) && ...
    abs(negativeLineOfSight.interceptorHeadingRad(2)- ...
    (-5/negativeLineOfSight.interceptorSpeedMPerSec* ...
    negativeLineOfSight.timeStepSec)) < tolerance, ...
    'Negative LOS motion must command, clip, and turn in the negative direction.');

% Constant-bearing collision course and disabled-guidance limiting case.
collisionCourse = model(3,-36,80,0.02,25);
assert(collisionCourse.intercepted && ...
    abs(collisionCourse.lineOfSightRateRadPerSec(1)) < tolerance && ...
    abs(collisionCourse.commandAccelerationMPerSec2(1)) < tolerance && ...
    max(abs(collisionCourse.commandAccelerationMPerSec2)) < 1e-8 && ...
    max(abs(collisionCourse.interceptorHeadingRad)) < 1e-10, ...
    'Constant bearing and decreasing range must capture without a turn.');
guidanceDisabled = model(0,60,80,0.02,25);
relativeVelocityNoGuidanceMPerSec = [-300 60];
analyticClosestTimeSec = -([5000 600]* ...
    relativeVelocityNoGuidanceMPerSec')/ ...
    sum(relativeVelocityNoGuidanceMPerSec.^2);
analyticClosestRelativeM = [5000 600]+ ...
    analyticClosestTimeSec*relativeVelocityNoGuidanceMPerSec;
analyticClosestDistanceM = norm(analyticClosestRelativeM);
assert(~guidanceDisabled.intercepted && ...
    strcmp(guidanceDisabled.terminationReason,'time-limit') && ...
    all(guidanceDisabled.commandAccelerationMPerSec2 == 0) && ...
    all(guidanceDisabled.actualAccelerationMPerSec2 == 0) && ...
    all(guidanceDisabled.interceptorHeadingRad == 0) && ...
    abs(guidanceDisabled.closestApproachTimeSec- ...
    analyticClosestTimeSec) < tolerance && ...
    abs(guidanceDisabled.closestApproachDistanceM- ...
    analyticClosestDistanceM) < tolerance, ...
    'N=0 must match the analytic straight-line miss.');

% Broken authority, opening-speed guard, bounded timeout, and recovery.
broken = model(3,60,5,0.02,25);
openingIndices = find(broken.closingSpeedMPerSec <= 0);
recovered = model(3,60,80,0.02,25);
shortHorizon = model(3,60,80,0.02,5);
assert(~broken.intercepted && ...
    strcmp(broken.terminationReason,'time-limit') && ...
    broken.closestApproachDistanceM > 900 && ...
    broken.saturationDurationSec > 17 && ...
    broken.peakActualAccelerationMPerSec2 == 5, ...
    'The broken actuator case must visibly saturate and miss.');
assert(~isempty(openingIndices) && ...
    all(broken.commandAccelerationMPerSec2(openingIndices) == 0), ...
    'Opening speed must command zero rather than abs(Vc) guidance.');
assert(~shortHorizon.intercepted && ...
    strcmp(shortHorizon.terminationReason,'time-limit') && ...
    shortHorizon.timeSec(end) == 5, ...
    'A bounded short horizon must return an explicit time-limit outcome.');
assert(isequaln(recovered,baselineA), ...
    'A valid call must exactly recover after broken and time-limit cases.');

% Malformed inputs and resource bounds fail before history allocation.
assertAnyError(@() model(NaN,60,80,0.02,25), ...
    'A nonfinite navigation constant must be rejected.');
assertAnyError(@() model([3 3],60,80,0.02,25), ...
    'A nonscalar navigation constant must be rejected.');
assertAnyError(@() model(3+1i,60,80,0.02,25), ...
    'A complex navigation constant must be rejected.');
assertAnyError(@() model(3,Inf,80,0.02,25), ...
    'A nonfinite crossing speed must be rejected.');
assertAnyError(@() model(3,60,NaN,0.02,25), ...
    'A nonfinite acceleration limit must be rejected.');
assertAnyError(@() model(3,60,80,0.02,NaN), ...
    'A nonfinite horizon must be rejected.');
assertErrorId(@() model(-0.01,60,80,0.02,25), ...
    'P22:NavigationConstantRange','Negative N must fail.');
assertErrorId(@() model(8.01,60,80,0.02,25), ...
    'P22:NavigationConstantRange','Excessive N must fail.');
assertErrorId(@() model(3,150.01,80,0.02,25), ...
    'P22:TargetCrossingSpeedRange','Excessive crossing speed must fail.');
assertErrorId(@() model(3,-150.01,80,0.02,25), ...
    'P22:TargetCrossingSpeedRange','Reverse crossing bound must fail.');
assertErrorId(@() model(3,60,4.99,0.02,25), ...
    'P22:AccelerationLimitRange','Too-small authority must fail.');
assertErrorId(@() model(3,60,120.01,0.02,25), ...
    'P22:AccelerationLimitRange','Excessive authority must fail.');
assertErrorId(@() model(3,60,80,0.0049,25), ...
    'P22:TimeStepRange','Too-small step must fail.');
assertErrorId(@() model(3,60,80,0.1001,25), ...
    'P22:TimeStepRange','Too-large step must fail.');
assertErrorId(@() model(3,60,80,0.02,4.99), ...
    'P22:MaximumTimeRange','Too-short horizon must fail.');
assertErrorId(@() model(3,60,80,0.02,40.01), ...
    'P22:MaximumTimeRange','Too-long horizon must fail.');
assertErrorId(@() model(3,60,80,0.03,25), ...
    'P22:TimeGridMismatch','A fractional time grid must fail.');
assertErrorId(@() model(3,60,80,0.005,40), ...
    'P22:StepCountRange','Oversized history must fail before allocation.');

boundedHistory = model(0,60,120,0.008,40);
afterBoundedHistory = model(3,60,80,0.02,25);
assert(boundedHistory.allocatedStepCount == 5001 && ...
    boundedHistory.usedStepCount == 5001 && ...
    numel(boundedHistory.timeSec) == 5001 && ...
    all(isfinite(boundedHistory.rangeM)) && ...
    all(isfinite(boundedHistory.lineOfSightRateRadPerSec)) && ...
    all(isfinite(boundedHistory.commandAccelerationMPerSec2)), ...
    'The largest accepted full history must remain finite and bounded.');
assert(isequaln(afterBoundedHistory,baselineA), ...
    'Maximum-history execution must not leak state into a fresh baseline.');

disp(['P22 checks passed: deterministic PN geometry, explicit recurrence, ' ...
    'segment capture, two isolated sweeps, limiting cases, saturation, ' ...
    'time limits, recovery, malformed inputs, and resource bounds.']);
end

function assertAnyError(operation,message)
didError = false;
try
    operation();
catch
    didError = true;
end
assert(didError,message);
end

function assertErrorId(operation,expectedIdentifier,message)
actualIdentifier = '';
try
    operation();
catch exception
    actualIdentifier = exception.identifier;
end
assert(strcmp(actualIdentifier,expectedIdentifier),message);
end
