function out = model(reference,controlLimit,tEnd,timeStepSec)
%MODEL Exact first-order plant motion under a clipped proportional command.
arguments
    reference (1,1) double {mustBeReal,mustBeFinite}
    controlLimit (1,1) double {mustBeReal,mustBeFinite,mustBePositive}
    tEnd (1,1) double {mustBeReal,mustBeFinite,mustBePositive}
    timeStepSec (1,1) double {mustBeReal,mustBeFinite,mustBePositive}
end

proportionalGain = 4;
plantTimeConstantSec = 1;
plantStaticGainOutputPerActuator = 1;
maxAbsReference = 5;
maxControlLimit = 10;
maxHorizonSec = 30;
maxTimeStepSec = 0.05;
maxSampleCount = 30001;
responseLimit = 100;

if abs(reference) > maxAbsReference
    error('P11:ReferenceRange', ...
        'Reference magnitude must not exceed 5 output units.');
end
if controlLimit > maxControlLimit
    error('P11:ControlLimitRange', ...
        'Control limit must not exceed 10 actuator units.');
end
if tEnd > maxHorizonSec
    error('P11:HorizonRange', ...
        'The learning horizon must not exceed 30 seconds.');
end
if timeStepSec > maxTimeStepSec
    error('P11:DisplayResolution', ...
        'Time step must not exceed 0.05 seconds.');
end

timeTolerance = 32*eps(max([1 tEnd timeStepSec]));
regularIntervalCount = floor(tEnd/timeStepSec);
projectedSampleCount = regularIntervalCount+1;
regularEndTime = regularIntervalCount*timeStepSec;
if regularIntervalCount == 0 || tEnd-regularEndTime > timeTolerance
    projectedSampleCount = projectedSampleCount+1;
end
if ~isfinite(projectedSampleCount) || projectedSampleCount > maxSampleCount
    error('P11:TooManySamples', ...
        'The requested grid exceeds 30001 samples.');
end

t = (0:regularIntervalCount)'*timeStepSec;
if regularIntervalCount == 0 || tEnd-t(end) > timeTolerance
    t = [t; tEnd];
else
    t(end) = tEnd;
end
sampleCount = numel(t);
intervalDurationSec = diff(t);

plantOutput = zeros(sampleCount,1);
unlimitedOutput = zeros(sampleCount,1);
requestedControl = zeros(sampleCount,1);
appliedControl = zeros(sampleCount,1);
saturationMask = false(sampleCount,1);
saturationTolerance = 64*eps(max([1 abs(reference) controlLimit]));

for k = 1:sampleCount
    requestedControl(k) = proportionalGain*(reference-plantOutput(k));
    appliedControl(k) = max(-controlLimit, ...
        min(controlLimit,requestedControl(k)));
    saturationMask(k) = abs(requestedControl(k)-appliedControl(k)) > ...
        saturationTolerance;
    if k < sampleCount
        plantDecay = exp(-intervalDurationSec(k)/plantTimeConstantSec);
        inputWeight = 1-plantDecay;
        plantOutput(k+1) = plantDecay*plantOutput(k)+ ...
            inputWeight*plantStaticGainOutputPerActuator*appliedControl(k);
        unlimitedRequestedControl = proportionalGain*( ...
            reference-unlimitedOutput(k));
        unlimitedOutput(k+1) = plantDecay*unlimitedOutput(k)+ ...
            inputWeight*plantStaticGainOutputPerActuator* ...
            unlimitedRequestedControl;
    end
end

if any(~isfinite(plantOutput)) || any(~isfinite(requestedControl)) || ...
        max(abs(plantOutput)) > responseLimit || ...
        max(abs(requestedControl)) > responseLimit
    error('P11:ResponseBound', ...
        'The requested response exceeds the bounded learning view.');
end

clippingGap = requestedControl-appliedControl;
trackingError = reference-plantOutput;
unlimitedGap = plantOutput-unlimitedOutput;
intervalSaturationMask = saturationMask(1:end-1);
allIntervalsSaturated = all(intervalSaturationMask);
saturationDurationSec = sum(intervalDurationSec.*double(intervalSaturationMask));
if allIntervalsSaturated
    saturationDurationSec = tEnd;
end
saturationFraction = saturationDurationSec/tEnd;
firstSaturationIndex = find(saturationMask(1:end-1),1,'first');
releaseIndex = find(saturationMask(1:end-1) & ...
    ~saturationMask(2:end),1,'first')+1;
if isempty(firstSaturationIndex)
    firstSaturationTimeSec = NaN;
else
    firstSaturationTimeSec = t(firstSaturationIndex);
end
if isempty(releaseIndex)
    releaseTimeSec = NaN;
else
    releaseTimeSec = t(releaseIndex);
end

loopGain = plantStaticGainOutputPerActuator*proportionalGain;
linearEquilibriumOutput = loopGain/(1+loopGain)*reference;
requiredLinearEquilibriumCommand = ...
    linearEquilibriumOutput/plantStaticGainOutputPerActuator;
persistentSaturation = reference ~= 0 && ...
    abs(requiredLinearEquilibriumCommand) >= controlLimit;
if reference == 0
    authorityRatio = Inf;
else
    authorityRatio = plantStaticGainOutputPerActuator* ...
        controlLimit/abs(reference);
end
integralAbsoluteError = sum(intervalDurationSec.*( ...
    abs(trackingError(1:end-1))+abs(trackingError(2:end)))/2);

out = struct( ...
    't',t, ...
    'reference',reference*ones(sampleCount,1), ...
    'plantOutput',plantOutput, ...
    'unlimitedOutput',unlimitedOutput, ...
    'trackingError',trackingError, ...
    'unlimitedGap',unlimitedGap, ...
    'requestedControl',requestedControl, ...
    'appliedControl',appliedControl, ...
    'clippingGap',clippingGap, ...
    'saturationMask',saturationMask, ...
    'controlUpperLimit',controlLimit*ones(sampleCount,1), ...
    'controlLowerLimit',-controlLimit*ones(sampleCount,1), ...
    'referenceValue',reference, ...
    'controlLimit',controlLimit, ...
    'proportionalGain',proportionalGain, ...
    'plantTimeConstantSec',plantTimeConstantSec, ...
    'plantStaticGainOutputPerActuator', ...
    plantStaticGainOutputPerActuator, ...
    'timeStepSec',timeStepSec, ...
    'horizonSec',tEnd, ...
    'linearEquilibriumOutput',linearEquilibriumOutput, ...
    'requiredLinearEquilibriumCommand', ...
    requiredLinearEquilibriumCommand, ...
    'linearEquilibriumExceedsActuatorLimit', ...
    abs(requiredLinearEquilibriumCommand) >= controlLimit, ...
    'authorityRatio',authorityRatio, ...
    'referenceExceedsActuatorAuthority', ...
    abs(reference) > plantStaticGainOutputPerActuator*controlLimit, ...
    'saturationDurationSec',saturationDurationSec, ...
    'saturationFraction',saturationFraction, ...
    'firstSaturationTimeSec',firstSaturationTimeSec, ...
    'releaseTimeSec',releaseTimeSec, ...
    'persistentSaturation',persistentSaturation, ...
    'saturatedThroughHorizon',saturationMask(end), ...
    'isSaturatedAtEnd',saturationMask(end), ...
    'maximumAbsRequestedControl',max(abs(requestedControl)), ...
    'maximumAbsAppliedControl',max(abs(appliedControl)), ...
    'maximumClippingGap',max(abs(clippingGap)), ...
    'maximumAbsUnlimitedGap',max(abs(unlimitedGap)), ...
    'finalTrackingError',trackingError(end), ...
    'integralAbsoluteError',integralAbsoluteError, ...
    'sampleCount',sampleCount, ...
    'maxSampleCount',maxSampleCount, ...
    'responseLimit',responseLimit);
end
