function run_checks
%RUN_CHECKS Independent clipping identities, limits, failure, and recovery.
tolerance = 2e-11;

baselineA = model(1,2,5,0.01);
baselineB = model(1,2,5,0.01);
assert(isequaln(baselineA,baselineB), ...
    'Identical inputs must produce identical trajectories and metrics.');
assert(baselineA.proportionalGain == 4 && ...
    baselineA.plantTimeConstantSec == 1 && ...
    baselineA.plantStaticGainOutputPerActuator == 1 && ...
    baselineA.linearEquilibriumOutput == 0.8, ...
    'The proportional law, plant, and unlimited equilibrium must stay fixed.');

expectedApplied = max(-baselineA.controlLimit, ...
    min(baselineA.controlLimit,baselineA.requestedControl));
assert(max(abs(baselineA.appliedControl-expectedApplied)) == 0, ...
    'Every applied command must equal the explicit symmetric clamp.');
assert(max(abs(baselineA.requestedControl-( ...
    4*(1-baselineA.plantOutput)))) < tolerance, ...
    'Every requested command must expose the proportional feedback law.');
assert(max(abs(baselineA.clippingGap-( ...
    baselineA.requestedControl-baselineA.appliedControl))) == 0, ...
    'Clipping gap must reveal exactly what the actuator could not apply.');
assert(all(abs(baselineA.appliedControl) <= ...
    baselineA.controlLimit+tolerance), ...
    'Applied control must never exceed the physical amplitude limit.');

intervalSec = diff(baselineA.t);
plantDecay = exp(-intervalSec);
plantResidual = baselineA.plantOutput(2:end)-( ...
    plantDecay.*baselineA.plantOutput(1:end-1)+(1-plantDecay).* ...
    baselineA.appliedControl(1:end-1));
assert(max(abs(plantResidual)) < tolerance, ...
    'Every plant interval must satisfy the exact held-command transition.');
unlimitedRequested = 4*(1-baselineA.unlimitedOutput(1:end-1));
unlimitedResidual = baselineA.unlimitedOutput(2:end)-( ...
    plantDecay.*baselineA.unlimitedOutput(1:end-1)+(1-plantDecay).* ...
    unlimitedRequested);
assert(max(abs(unlimitedResidual)) < tolerance, ...
    'The unlimited comparison must obey an independent proportional recurrence.');
assert(baselineA.requestedControl(1) == 4 && ...
    baselineA.appliedControl(1) == 2 && baselineA.saturationMask(1), ...
    'The baseline must visibly begin with a four-unit request clipped to two.');
assert(baselineA.saturationDurationSec > 0.28 && ...
    baselineA.saturationDurationSec < 0.31 && ...
    abs(baselineA.releaseTimeSec-0.29) < tolerance, ...
    'The baseline must release from saturation at the independently expected time.');
assert(~baselineA.persistentSaturation && ...
    ~baselineA.saturatedThroughHorizon && ...
    ~baselineA.isSaturatedAtEnd && baselineA.maximumClippingGap == 2, ...
    'Baseline clipping must be transient and its peak missing command explicit.');
assert(abs(baselineA.plantOutput(end)-0.8) < 1e-10 && ...
    abs(baselineA.unlimitedOutput(end)-0.8) < 1e-10, ...
    'After transient clipping, both paths must approach the P-only equilibrium.');

zeroReference = model(0,2,2,0.01);
assert(all(zeroReference.plantOutput == 0) && ...
    all(zeroReference.requestedControl == 0) && ...
    zeroReference.saturationDurationSec == 0, ...
    'Zero reference from zero state must remain the exact zero limiting case.');
unlimitedActuator = model(1,10,2,0.01);
assert(~any(unlimitedActuator.saturationMask) && ...
    max(abs(unlimitedActuator.plantOutput- ...
    unlimitedActuator.unlimitedOutput)) == 0, ...
    'A sufficiently large limit must recover the unlimited proportional loop.');
positive = model(1,1.2,3,0.01);
negative = model(-1,1.2,3,0.01);
assert(max(abs(positive.plantOutput+negative.plantOutput)) < tolerance && ...
    max(abs(positive.appliedControl+negative.appliedControl)) < tolerance && ...
    positive.saturationFraction == negative.saturationFraction, ...
    'Symmetric limits must produce sign-symmetric positive and negative steps.');

lowAuthority = model(1,0.4,3,0.01);
expectedLimitedOutput = 0.4*(1-exp(-lowAuthority.t));
assert(lowAuthority.persistentSaturation && ...
    lowAuthority.referenceExceedsActuatorAuthority && ...
    lowAuthority.linearEquilibriumExceedsActuatorLimit && ...
    max(abs(lowAuthority.plantOutput-expectedLimitedOutput)) < tolerance, ...
    'Persistent positive clipping must reduce to exact motion under u=0.4.');
assert(isnan(lowAuthority.releaseTimeSec) && ...
    lowAuthority.saturationFraction == 1 && ...
    lowAuthority.saturatedThroughHorizon && ...
    lowAuthority.maximumAbsAppliedControl == 0.4, ...
    'A persistently clipped case must have no release and full clipped duration.');

references = [0.25 0.5 1 1.5 2];
referenceFractions = zeros(size(references));
for k = 1:numel(references)
    changed = model(references(k),2,5,0.01);
    referenceFractions(k) = changed.saturationFraction;
    assert(changed.controlLimit == 2, ...
        'Reference sweep must preserve actuator limit.');
end
assert(all(diff(referenceFractions) >= 0) && ...
    referenceFractions(1) == 0 && referenceFractions(end) > 0.25, ...
    'Larger reference steps must not reduce clipped duration at fixed limit.');

limits = [0.4 0.6 0.8 1.2 2];
limitFractions = zeros(size(limits));
for k = 1:numel(limits)
    changed = model(1,limits(k),5,0.01);
    limitFractions(k) = changed.saturationFraction;
    assert(changed.referenceValue == 1, ...
        'Actuator-limit sweep must preserve reference.');
end
assert(all(diff(limitFractions) <= 0) && ...
    limitFractions(1) == 1 && limitFractions(end) < 0.1, ...
    'More actuator authority must not increase clipped duration.');

broken = model(1.5,0.6,5,0.01);
recovered = model(1.5,2,5,0.01);
assert(broken.referenceExceedsActuatorAuthority && ...
    broken.persistentSaturation && broken.saturationFraction == 1 && ...
    broken.finalTrackingError > 0.9, ...
    'A target beyond actuator authority must remain clipped with large error.');
assert(~recovered.referenceExceedsActuatorAuthority && ...
    ~recovered.persistentSaturation && ~isnan(recovered.releaseTimeSec) && ...
    recovered.finalTrackingError < 0.31, ...
    'Increasing only authority must release clipping and recover the P loop.');
assert(broken.referenceValue == recovered.referenceValue && ...
    broken.proportionalGain == recovered.proportionalGain && ...
    broken.plantTimeConstantSec == recovered.plantTimeConstantSec && ...
    broken.timeStepSec == recovered.timeStepSec && ...
    broken.horizonSec == recovered.horizonSec, ...
    'Recovery must change only the actuator limit.');
assert(recovered.integralAbsoluteError < broken.integralAbsoluteError && ...
    recovered.maximumAbsUnlimitedGap < broken.maximumAbsUnlimitedGap, ...
    'Recovered authority must reduce tracking error and the unlimited-path gap.');

partialGrid = model(1,2,0.097,0.03);
assert(partialGrid.t(end) == 0.097 && ...
    partialGrid.sampleCount == 5 && all(diff(partialGrid.t) > 0), ...
    'A noninteger horizon must retain one exact final partial interval.');
partialDt = partialGrid.t(end)-partialGrid.t(end-1);
expectedPartialOutput = exp(-partialDt)* ...
    partialGrid.plantOutput(end-1)+(1-exp(-partialDt))* ...
    partialGrid.appliedControl(end-1);
assert(abs(partialGrid.plantOutput(end)-expectedPartialOutput) < tolerance, ...
    'The final partial interval must use its actual duration exactly.');
releaseAtHorizon = model(1,2,0.29,0.01);
assert(releaseAtHorizon.saturationFraction == 1 && ...
    abs(releaseAtHorizon.releaseTimeSec-0.29) < tolerance && ...
    ~releaseAtHorizon.persistentSaturation && ...
    ~releaseAtHorizon.saturatedThroughHorizon, ...
    'Full clipped duration must not hide an exact-horizon release or imply persistence.');
eventualRelease = model(1,0.801,5,0.01);
assert(eventualRelease.saturatedThroughHorizon && ...
    ~eventualRelease.persistentSaturation && ...
    isnan(eventualRelease.releaseTimeSec), ...
    'Finite-view clipping must remain distinct from asymptotic persistent saturation.');
tinyHorizon = model(1,2,1e-16,0.01);
assert(tinyHorizon.sampleCount == 2 && tinyHorizon.t(1) == 0 && ...
    tinyHorizon.t(2) == 1e-16 && all(diff(tinyHorizon.t) > 0), ...
    'Every positive horizon must retain both its start and exact endpoint.');

assertAnyError(@() model(NaN,2,5,0.01), ...
    'A nonfinite reference must be rejected.');
assertAnyError(@() model(1,Inf,5,0.01), ...
    'A nonfinite actuator limit must be rejected.');
assertAnyError(@() model([1 2],2,5,0.01), ...
    'A nonscalar reference must be rejected.');
assertAnyError(@() model(1,0,5,0.01), ...
    'A zero actuator limit must be rejected.');
assertAnyError(@() model(1,-1,5,0.01), ...
    'A negative actuator limit must be rejected.');
assertErrorId(@() model(5.1,2,5,0.01), ...
    'P11:ReferenceRange','An excessive reference must be rejected explicitly.');
assertErrorId(@() model(1,10.1,5,0.01), ...
    'P11:ControlLimitRange','An excessive actuator limit must be rejected.');
assertErrorId(@() model(1,2,30.1,0.01), ...
    'P11:HorizonRange','An excessive horizon must be rejected.');
assertErrorId(@() model(1,2,5,0.051), ...
    'P11:DisplayResolution','An under-resolved time step must be rejected.');
assertErrorId(@() model(1,2,30,1e-12), ...
    'P11:TooManySamples', ...
    'A tiny time step must be rejected before allocating its grid.');
atSampleLimit = model(1,2,30,0.001);
assert(atSampleLimit.sampleCount == 30001 && ...
    all(isfinite(atSampleLimit.plantOutput)), ...
    'The declared maximum sample grid must remain accepted.');

disp(['P11 checks passed: exact clipping, independent levers, limits, ' ...
    'authority failure, one-limit recovery, and resource bounds.']);
end

function assertAnyError(operation,message)
didError = false;
try
    operation();
catch
    didError = true;
end
assert(didError,message);
end

function assertErrorId(operation,expectedIdentifier,message)
actualIdentifier = '';
try
    operation();
catch exception
    actualIdentifier = exception.identifier;
end
assert(strcmp(actualIdentifier,expectedIdentifier),message);
end
