function result = model(feedforwardScale,feedbackScale,feedforwardSign, ...
    planAmplitudeMPerSec2,disturbanceMagnitudeMPerSec2, ...
    simulationDurationSec,timeStepSec)
%MODEL Simulate transparent feedforward-plus-feedback tracking for P18.
arguments
    feedforwardScale (1,1) double {mustBeReal,mustBeFinite,mustBeNonnegative} = 1
    feedbackScale (1,1) double {mustBeReal,mustBeFinite,mustBeNonnegative} = 1
    feedforwardSign (1,1) double {mustBeReal,mustBeFinite} = 1
    planAmplitudeMPerSec2 (1,1) double ...
        {mustBeReal,mustBeFinite,mustBeNonnegative} = 0.6
    disturbanceMagnitudeMPerSec2 (1,1) double ...
        {mustBeReal,mustBeFinite,mustBeNonnegative} = 0.4
    simulationDurationSec (1,1) double ...
        {mustBeReal,mustBeFinite,mustBePositive} = 12
    timeStepSec (1,1) double {mustBeReal,mustBeFinite,mustBePositive} = 0.02
end

if feedforwardScale > 1.5
    error('P18:FeedforwardScaleRange', ...
        'Feedforward scale must be between 0 and 1.5.');
end
if feedbackScale > 2
    error('P18:FeedbackScaleRange', ...
        'Feedback scale must be between 0 and 2.');
end
if feedforwardSign ~= 1 && feedforwardSign ~= -1
    error('P18:FeedforwardSign', ...
        'Feedforward sign must be exactly +1 or -1.');
end
if planAmplitudeMPerSec2 > 1
    error('P18:PlanAmplitudeRange', ...
        'Plan amplitude must be between 0 and 1 m/s^2.');
end
if disturbanceMagnitudeMPerSec2 > 0.8
    error('P18:DisturbanceMagnitudeRange', ...
        'Disturbance magnitude must be between 0 and 0.8 m/s^2.');
end
if simulationDurationSec < 10 || simulationDurationSec > 20
    error('P18:DurationRange', ...
        'Simulation duration must be between 10 and 20 seconds.');
end
if timeStepSec > 0.05
    error('P18:DisplayResolution', ...
        'Time step must be at most 0.05 seconds.');
end

maximumStepCount = 5000;
rawStepCount = simulationDurationSec/timeStepSec;
if ~isfinite(rawStepCount) || rawStepCount > maximumStepCount+0.5
    error('P18:TooManySteps', ...
        'The requested time grid exceeds 5000 state transitions.');
end
stepCount = round(rawStepCount);
if abs(rawStepCount-stepCount) > 1e-10*max(1,rawStepCount)
    error('P18:GridAlignment', ...
        'Duration must contain an integer number of time steps.');
end

disturbanceStartSec = 4;
disturbanceEndSec = 5;
eventRatios = [disturbanceStartSec disturbanceEndSec]/timeStepSec;
if any(abs(eventRatios-round(eventRatios)) > ...
        1e-10*max(1,max(eventRatios)))
    error('P18:EventAlignment', ...
        'The 4 s and 5 s disturbance events must lie on the time grid.');
end

% Retain P17's damped cart and its dt=0.02 s baseline LQR gain. The gain is
% declared directly so P18 exposes the mixer rather than hiding it in a
% second Riccati calculation; it is held fixed when the display grid changes.
dampingPerSec = 0.5;
decay = exp(-dampingPerSec*timeStepSec);
positionFromRateSec = (1-decay)/dampingPerSec;
positionFromAccelerationSec2 = ...
    (timeStepSec-positionFromRateSec)/dampingPerSec;
discreteA = [1 positionFromRateSec;0 decay];
discreteB = [positionFromAccelerationSec2;positionFromRateSec];
feedbackGain = [1.9644942427723904 1.7703588392280174]; % [1/s^2, 1/s]
planFrequencyRadPerSec = 0.6;

sampleCount = stepCount+1;
timeSec = (0:stepCount)*timeStepSec;
plannedAccelerationMPerSec2 = ...
    planAmplitudeMPerSec2*sin(planFrequencyRadPerSec*timeSec);
disturbanceAccelerationMPerSec2 = zeros(1,sampleCount);
disturbanceActive = timeSec >= disturbanceStartSec & ...
    timeSec < disturbanceEndSec;
disturbanceAccelerationMPerSec2(disturbanceActive) = ...
    -disturbanceMagnitudeMPerSec2;

referenceState = zeros(2,sampleCount);
actualState = zeros(2,sampleCount);
trackingError = zeros(2,sampleCount);
feedforwardCommandMPerSec2 = zeros(1,sampleCount);
feedbackCommandMPerSec2 = zeros(1,sampleCount);
totalCommandMPerSec2 = zeros(1,sampleCount);

for k = 1:sampleCount
    trackingError(:,k) = referenceState(:,k)-actualState(:,k);
    feedforwardCommandMPerSec2(k) = feedforwardSign* ...
        feedforwardScale*plannedAccelerationMPerSec2(k);
    feedbackCommandMPerSec2(k) = feedbackScale*feedbackGain* ...
        trackingError(:,k);
    totalCommandMPerSec2(k) = feedforwardCommandMPerSec2(k)+ ...
        feedbackCommandMPerSec2(k);
    if k <= stepCount
        referenceState(:,k+1) = discreteA*referenceState(:,k)+ ...
            discreteB*plannedAccelerationMPerSec2(k);
        actualState(:,k+1) = discreteA*actualState(:,k)+ ...
            discreteB*(totalCommandMPerSec2(k)+ ...
            disturbanceAccelerationMPerSec2(k));
    end
end

effectiveFeedforwardScale = feedforwardSign*feedforwardScale;
errorClosedLoopA = discreteA-feedbackScale*discreteB*feedbackGain;
errorClosedLoopPoles = twoStatePoles(errorClosedLoopA);
errorSpectralRadius = max(abs(errorClosedLoopPoles));

positionErrorM = trackingError(1,:);
rateErrorMPerSec = trackingError(2,:);
positionErrorIntegralM2Sec = timeStepSec*sum(positionErrorM(1:end-1).^2);
rateErrorIntegralM2PerSec = timeStepSec*sum(rateErrorMPerSec(1:end-1).^2);
positionRmseM = sqrt(mean(positionErrorM.^2));
maximumAbsolutePositionErrorM = max(abs(positionErrorM));
feedforwardEffortIntegralM2PerSec3 = timeStepSec*sum( ...
    feedforwardCommandMPerSec2(1:end-1).^2);
feedbackEffortIntegralM2PerSec3 = timeStepSec*sum( ...
    feedbackCommandMPerSec2(1:end-1).^2);
totalCommandEffortIntegralM2PerSec3 = timeStepSec*sum( ...
    totalCommandMPerSec2(1:end-1).^2);
peakAbsoluteFeedbackCommandMPerSec2 = max(abs(feedbackCommandMPerSec2));
peakAbsoluteTotalCommandMPerSec2 = max(abs(totalCommandMPerSec2));

positionToleranceM = 0.02;
rateToleranceMPerSec = 0.02;
afterDisturbance = timeSec >= disturbanceEndSec;
outsideTolerance = abs(positionErrorM) > positionToleranceM | ...
    abs(rateErrorMPerSec) > rateToleranceMPerSec;
lastOutsideIndex = find(afterDisturbance & outsideTolerance,1,'last');
if isempty(lastOutsideIndex)
    recoveryTimeSec = 0;
elseif lastOutsideIndex == sampleCount
    recoveryTimeSec = Inf;
else
    recoveryTimeSec = timeSec(lastOutsideIndex+1)-disturbanceEndSec;
end
recoveredByEnd = isfinite(recoveryTimeSec);

referenceRecurrenceResidual = 0;
errorRecurrenceResidual = 0;
for k = 1:stepCount
    referenceResidual = referenceState(:,k+1)- ...
        (discreteA*referenceState(:,k)+ ...
        discreteB*plannedAccelerationMPerSec2(k));
    expectedErrorNext = errorClosedLoopA*trackingError(:,k)+ ...
        discreteB*((1-effectiveFeedforwardScale)* ...
        plannedAccelerationMPerSec2(k)- ...
        disturbanceAccelerationMPerSec2(k));
    referenceRecurrenceResidual = max(referenceRecurrenceResidual, ...
        max(abs(referenceResidual)));
    errorRecurrenceResidual = max(errorRecurrenceResidual, ...
        max(abs(trackingError(:,k+1)-expectedErrorNext)));
end
mixerResidualMPerSec2 = max(abs(totalCommandMPerSec2- ...
    feedforwardCommandMPerSec2-feedbackCommandMPerSec2));

result = struct( ...
    'feedforwardScale',feedforwardScale, ...
    'feedbackScale',feedbackScale, ...
    'feedforwardSign',feedforwardSign, ...
    'effectiveFeedforwardScale',effectiveFeedforwardScale, ...
    'planAmplitudeMPerSec2',planAmplitudeMPerSec2, ...
    'disturbanceMagnitudeMPerSec2',disturbanceMagnitudeMPerSec2, ...
    'planFrequencyRadPerSec',planFrequencyRadPerSec, ...
    'simulationDurationSec',simulationDurationSec, ...
    'timeStepSec',timeStepSec, ...
    'maximumStepCount',maximumStepCount, ...
    'stepCount',stepCount, ...
    'sampleCount',sampleCount, ...
    'dampingPerSec',dampingPerSec, ...
    'discreteA',discreteA, ...
    'discreteB',discreteB, ...
    'feedbackGain',feedbackGain, ...
    'errorClosedLoopA',errorClosedLoopA, ...
    'errorClosedLoopPoles',errorClosedLoopPoles, ...
    'errorSpectralRadius',errorSpectralRadius, ...
    'disturbanceStartSec',disturbanceStartSec, ...
    'disturbanceEndSec',disturbanceEndSec, ...
    'timeSec',timeSec, ...
    'plannedAccelerationMPerSec2',plannedAccelerationMPerSec2, ...
    'disturbanceAccelerationMPerSec2',disturbanceAccelerationMPerSec2, ...
    'referenceState',referenceState, ...
    'actualState',actualState, ...
    'trackingError',trackingError, ...
    'referencePositionM',referenceState(1,:), ...
    'referenceRateMPerSec',referenceState(2,:), ...
    'actualPositionM',actualState(1,:), ...
    'actualRateMPerSec',actualState(2,:), ...
    'positionErrorM',positionErrorM, ...
    'rateErrorMPerSec',rateErrorMPerSec, ...
    'feedforwardCommandMPerSec2',feedforwardCommandMPerSec2, ...
    'feedbackCommandMPerSec2',feedbackCommandMPerSec2, ...
    'totalCommandMPerSec2',totalCommandMPerSec2, ...
    'positionErrorIntegralM2Sec',positionErrorIntegralM2Sec, ...
    'rateErrorIntegralM2PerSec',rateErrorIntegralM2PerSec, ...
    'positionRmseM',positionRmseM, ...
    'maximumAbsolutePositionErrorM',maximumAbsolutePositionErrorM, ...
    'feedforwardEffortIntegralM2PerSec3', ...
    feedforwardEffortIntegralM2PerSec3, ...
    'feedbackEffortIntegralM2PerSec3',feedbackEffortIntegralM2PerSec3, ...
    'totalCommandEffortIntegralM2PerSec3', ...
    totalCommandEffortIntegralM2PerSec3, ...
    'peakAbsoluteFeedbackCommandMPerSec2', ...
    peakAbsoluteFeedbackCommandMPerSec2, ...
    'peakAbsoluteTotalCommandMPerSec2',peakAbsoluteTotalCommandMPerSec2, ...
    'positionToleranceM',positionToleranceM, ...
    'rateToleranceMPerSec',rateToleranceMPerSec, ...
    'recoveryTimeSec',recoveryTimeSec, ...
    'recoveredByEnd',recoveredByEnd, ...
    'referenceRecurrenceResidual',referenceRecurrenceResidual, ...
    'errorRecurrenceResidual',errorRecurrenceResidual, ...
    'mixerResidualMPerSec2',mixerResidualMPerSec2);
end

function poles = twoStatePoles(matrix)
traceValue = matrix(1,1)+matrix(2,2);
determinantValue = matrix(1,1)*matrix(2,2)-matrix(1,2)*matrix(2,1);
discriminant = complex(traceValue^2-4*determinantValue);
rootValue = sqrt(discriminant);
poles = [(traceValue+rootValue)/2;(traceValue-rootValue)/2];
end
