function run_checks
%RUN_CHECKS Verify P18 mixer, tracking, limits, recovery, and bounds.
tolerance = 5e-10;
baselineA = model(1,1,1,0.6,0.4,12,0.02);
baselineB = model(1,1,1,0.6,0.4,12,0.02);
assert(isequaln(baselineA,baselineB), ...
    'The deterministic baseline must repeat exactly.');

expectedDecay = exp(-0.5*0.02);
expectedPositionFromRate = (1-expectedDecay)/0.5;
expectedPositionFromAcceleration = ...
    (0.02-expectedPositionFromRate)/0.5;
expectedA = [1 expectedPositionFromRate;0 expectedDecay];
expectedB = [expectedPositionFromAcceleration;expectedPositionFromRate];
expectedGain = [1.9644942427723904 1.7703588392280174];
expectedErrorA = expectedA-expectedB*expectedGain;
assert(max(abs(baselineA.discreteA(:)-expectedA(:))) < tolerance && ...
    max(abs(baselineA.discreteB(:)-expectedB(:))) < tolerance, ...
    'The exact P17 held-input damped-cart matrices must be retained.');
assert(max(abs(baselineA.feedbackGain-expectedGain)) == 0 && ...
    max(abs(baselineA.errorClosedLoopA(:)-expectedErrorA(:))) < tolerance, ...
    'P18 must retain the declared P17 baseline state-feedback gain.');
assert(baselineA.errorSpectralRadius < 1 && ...
    baselineA.referenceRecurrenceResidual < tolerance && ...
    baselineA.errorRecurrenceResidual < tolerance && ...
    baselineA.mixerResidualMPerSec2 == 0, ...
    'The reference, error, and visible command mixer equations must agree.');

for k = 1:baselineA.stepCount
    expectedPlan = 0.6*sin(0.6*baselineA.timeSec(k));
    expectedError = baselineA.referenceState(:,k)-baselineA.actualState(:,k);
    expectedFeedforward = expectedPlan;
    expectedFeedback = expectedGain*expectedError;
    expectedTotal = expectedFeedforward+expectedFeedback;
    expectedReferenceNext = expectedA*baselineA.referenceState(:,k)+ ...
        expectedB*expectedPlan;
    expectedActualNext = expectedA*baselineA.actualState(:,k)+ ...
        expectedB*(expectedTotal+ ...
        baselineA.disturbanceAccelerationMPerSec2(k));
    assert(abs(baselineA.plannedAccelerationMPerSec2(k)-expectedPlan) < ...
        tolerance && max(abs(baselineA.trackingError(:,k)-expectedError)) < ...
        tolerance, ...
        'Every plan sample and error must follow its declared definition.');
    assert(abs(baselineA.feedforwardCommandMPerSec2(k)- ...
        expectedFeedforward) < tolerance && ...
        abs(baselineA.feedbackCommandMPerSec2(k)-expectedFeedback) < ...
        tolerance && abs(baselineA.totalCommandMPerSec2(k)-expectedTotal) < ...
        tolerance, ...
        'Every command must equal the visible feedforward-plus-feedback sum.');
    assert(max(abs(baselineA.referenceState(:,k+1)- ...
        expectedReferenceNext)) < tolerance && ...
        max(abs(baselineA.actualState(:,k+1)-expectedActualNext)) < ...
        tolerance, ...
        'Every state transition must follow the exact held-input recurrence.');
end

expectedPositionIse = 0.02*sum(baselineA.positionErrorM(1:end-1).^2);
expectedRateIse = 0.02*sum(baselineA.rateErrorMPerSec(1:end-1).^2);
expectedFeedforwardEffort = 0.02*sum( ...
    baselineA.feedforwardCommandMPerSec2(1:end-1).^2);
expectedFeedbackEffort = 0.02*sum( ...
    baselineA.feedbackCommandMPerSec2(1:end-1).^2);
expectedTotalEffort = 0.02*sum( ...
    baselineA.totalCommandMPerSec2(1:end-1).^2);
assert(abs(baselineA.positionErrorIntegralM2Sec-expectedPositionIse) < ...
    tolerance && abs(baselineA.rateErrorIntegralM2PerSec- ...
    expectedRateIse) < tolerance && ...
    abs(baselineA.feedforwardEffortIntegralM2PerSec3- ...
    expectedFeedforwardEffort) < tolerance && ...
    abs(baselineA.feedbackEffortIntegralM2PerSec3- ...
    expectedFeedbackEffort) < tolerance && ...
    abs(baselineA.totalCommandEffortIntegralM2PerSec3- ...
    expectedTotalEffort) < tolerance, ...
    'All retained integrals must be direct sums of their own histories.');
assert(abs(baselineA.positionErrorIntegralM2Sec-0.0161739933608727) < ...
    2e-12 && abs(baselineA.feedbackEffortIntegralM2PerSec3- ...
    0.11474509167732859) < 2e-12 && ...
    abs(baselineA.maximumAbsolutePositionErrorM- ...
    0.11172189006637057) < 2e-12 && ...
    abs(baselineA.recoveryTimeSec-2.6) < tolerance, ...
    'Baseline metrics must match independent reference arithmetic.');

% Behavioral architecture oracle: together must beat either single path on
% the same changing plan and disturbance.
feedbackOnly = model(0,1,1,0.6,0.4,12,0.02);
feedforwardOnly = model(1,0,1,0.6,0.4,12,0.02);
assert(baselineA.positionErrorIntegralM2Sec < ...
    feedbackOnly.positionErrorIntegralM2Sec && ...
    baselineA.positionErrorIntegralM2Sec < ...
    feedforwardOnly.positionErrorIntegralM2Sec, ...
    'Combined control must track this plan and disturbance better than either path alone.');

% Information-path oracle: an unplanned load must not rewrite the declared
% plan, feasible reference, or anticipatory command. It changes the plant
% first; only the resulting tracking error activates feedback.
undisturbedBaseline = model(1,1,1,0.6,0,12,0.02);
throughDisturbanceStart = baselineA.timeSec <= baselineA.disturbanceStartSec;
assert(isequal(baselineA.plannedAccelerationMPerSec2, ...
    undisturbedBaseline.plannedAccelerationMPerSec2) && ...
    isequal(baselineA.referenceState,undisturbedBaseline.referenceState) && ...
    isequal(baselineA.feedforwardCommandMPerSec2, ...
    undisturbedBaseline.feedforwardCommandMPerSec2), ...
    'Changing only the disturbance must not alter the plan or feedforward path.');
assert(isequal(baselineA.actualState(:,throughDisturbanceStart), ...
    undisturbedBaseline.actualState(:,throughDisturbanceStart)) && ...
    isequal(baselineA.feedbackCommandMPerSec2(throughDisturbanceStart), ...
    undisturbedBaseline.feedbackCommandMPerSec2(throughDisturbanceStart)) && ...
    max(abs(undisturbedBaseline.feedbackCommandMPerSec2)) == 0 && ...
    max(abs(baselineA.feedbackCommandMPerSec2)) > 0.3, ...
    'The unplanned load must affect the plant before error-driven feedback responds.');

% Sweep 1: with no disturbance, alpha=1 is an exact matched-plan limit.
feedforwardScaleValues = [0 0.5 1 1.5];
feedforwardIse = zeros(size(feedforwardScaleValues));
feedforwardCorrectionEffort = zeros(size(feedforwardScaleValues));
feedforwardRuns = cell(size(feedforwardScaleValues));
for k = 1:numel(feedforwardScaleValues)
    feedforwardRuns{k} = model(feedforwardScaleValues(k),1,1, ...
        0.6,0,12,0.02);
    changed = feedforwardRuns{k};
    feedforwardIse(k) = changed.positionErrorIntegralM2Sec;
    feedforwardCorrectionEffort(k) = ...
        changed.feedbackEffortIntegralM2PerSec3;
    assert(changed.feedbackScale == 1 && changed.feedforwardSign == 1 && ...
        changed.planAmplitudeMPerSec2 == 0.6 && ...
        changed.disturbanceMagnitudeMPerSec2 == 0 && ...
        changed.simulationDurationSec == 12 && changed.timeStepSec == 0.02 && ...
        max(abs(changed.discreteA(:)-baselineA.discreteA(:))) == 0, ...
        'The feedforward sweep must reset every non-swept input.');
end
matchedPlan = feedforwardRuns{3};
assert(max(abs(matchedPlan.trackingError(:))) == 0 && ...
    max(abs(matchedPlan.feedbackCommandMPerSec2)) == 0 && ...
    matchedPlan.positionErrorIntegralM2Sec == 0 && ...
    matchedPlan.feedbackEffortIntegralM2PerSec3 == 0, ...
    'Matched feedforward must be the exact zero-error nominal limit.');
assert(feedforwardIse(1) > feedforwardIse(2) && ...
    feedforwardIse(2) > feedforwardIse(3) && ...
    abs(feedforwardIse(2)-feedforwardIse(4)) < 5e-14 && ...
    abs(feedforwardCorrectionEffort(2)- ...
    feedforwardCorrectionEffort(4)) < 5e-14, ...
    'Feedforward mismatch must be symmetric about the matched scale.');

% Sweep 2: with matched feedforward, feedback removes the fixed load error.
feedbackScaleValues = [0 0.25 0.5 1 1.5 2];
feedbackIse = zeros(size(feedbackScaleValues));
feedbackCorrectionEffort = zeros(size(feedbackScaleValues));
feedbackRecovery = zeros(size(feedbackScaleValues));
feedbackRuns = cell(size(feedbackScaleValues));
for k = 1:numel(feedbackScaleValues)
    feedbackRuns{k} = model(1,feedbackScaleValues(k),1, ...
        0.6,0.4,12,0.02);
    changed = feedbackRuns{k};
    feedbackIse(k) = changed.positionErrorIntegralM2Sec;
    feedbackCorrectionEffort(k) = ...
        changed.feedbackEffortIntegralM2PerSec3;
    feedbackRecovery(k) = changed.recoveryTimeSec;
    assert(changed.feedforwardScale == 1 && changed.feedforwardSign == 1 && ...
        changed.planAmplitudeMPerSec2 == 0.6 && ...
        changed.disturbanceMagnitudeMPerSec2 == 0.4 && ...
        changed.simulationDurationSec == 12 && changed.timeStepSec == 0.02 && ...
        max(abs(changed.discreteB(:)-baselineA.discreteB(:))) == 0, ...
        'The feedback sweep must reset every non-swept input.');
end
assert(all(diff(feedbackIse) < 0) && ...
    all(diff(feedbackCorrectionEffort) > 0) && ...
    isinf(feedbackRecovery(1)) && all(diff(feedbackRecovery(2:end)) < 0), ...
    'More feedback authority must reduce load error and recovery time while using more correction.');
assert(abs(feedbackRuns{1}.positionErrorM(end)- ...
    0.7809892087462634) < 2e-12 && ...
    abs(feedbackRuns{1}.rateErrorMPerSec(end)- ...
    0.009505395626867573) < 2e-12 && ...
    abs(feedbackRuns{1}.errorSpectralRadius-1) < tolerance, ...
    'Feedforward alone must retain the analytic damped-pulse position offset.');

broken = model(1,1,-1,0.6,0.4,12,0.02);
recovered = model(1,1,1,0.6,0.4,12,0.02);
assert(broken.positionErrorIntegralM2Sec > 100* ...
    baselineA.positionErrorIntegralM2Sec && ...
    broken.feedbackEffortIntegralM2PerSec3 > 50* ...
    baselineA.feedbackEffortIntegralM2PerSec3 && ...
    broken.maximumAbsolutePositionErrorM > 0.5 && ...
    isinf(broken.recoveryTimeSec), ...
    'Wrong feedforward polarity must create large opposing correction and tracking error.');
assert(isequaln(recovered,baselineA), ...
    'A fresh correct-sign call must recover the exact baseline.');

zeroMotion = model(1,2,1,0,0,12,0.02);
assert(max(abs(zeroMotion.referenceState(:))) == 0 && ...
    max(abs(zeroMotion.actualState(:))) == 0 && ...
    max(abs(zeroMotion.totalCommandMPerSec2)) == 0 && ...
    zeroMotion.positionErrorIntegralM2Sec == 0, ...
    'Zero plan and zero disturbance must remain an exact equilibrium.');

assertAnyError(@() model(NaN,1,1,0.6,0.4,12,0.02), ...
    'A nonfinite feedforward scale must be rejected.');
assertAnyError(@() model([1 1],1,1,0.6,0.4,12,0.02), ...
    'A nonscalar feedforward scale must be rejected.');
assertAnyError(@() model(1,1+1i,1,0.6,0.4,12,0.02), ...
    'A complex feedback scale must be rejected.');
assertAnyError(@() model(-0.01,1,1,0.6,0.4,12,0.02), ...
    'A negative feedforward scale must be rejected.');
assertAnyError(@() model(1,-0.01,1,0.6,0.4,12,0.02), ...
    'A negative feedback scale must be rejected.');
assertAnyError(@() model(1,1,1,-0.01,0.4,12,0.02), ...
    'A negative plan amplitude must be rejected.');
assertAnyError(@() model(1,1,1,0.6,-0.01,12,0.02), ...
    'A negative disturbance magnitude must be rejected.');
assertAnyError(@() model(1,1,1,0.6,0.4,-12,0.02), ...
    'A negative duration must be rejected.');
assertAnyError(@() model(1,1,1,0.6,0.4,12,-0.02), ...
    'A negative time step must be rejected.');
assertErrorId(@() model(1.51,1,1,0.6,0.4,12,0.02), ...
    'P18:FeedforwardScaleRange','Excessive feedforward scale must be rejected.');
assertErrorId(@() model(1,2.01,1,0.6,0.4,12,0.02), ...
    'P18:FeedbackScaleRange','Excessive feedback scale must be rejected.');
assertErrorId(@() model(1,1,0,0.6,0.4,12,0.02), ...
    'P18:FeedforwardSign','Malformed feedforward sign must be rejected.');
assertErrorId(@() model(1,1,1,1.01,0.4,12,0.02), ...
    'P18:PlanAmplitudeRange','Excessive plan amplitude must be rejected.');
assertErrorId(@() model(1,1,1,0.6,0.81,12,0.02), ...
    'P18:DisturbanceMagnitudeRange', ...
    'Excessive disturbance magnitude must be rejected.');
assertErrorId(@() model(1,1,1,0.6,0.4,9.99,0.02), ...
    'P18:DurationRange','Too-short duration must be rejected.');
assertErrorId(@() model(1,1,1,0.6,0.4,20.01,0.02), ...
    'P18:DurationRange','Excessive duration must be rejected.');
assertErrorId(@() model(1,1,1,0.6,0.4,12,0.051), ...
    'P18:DisplayResolution','An under-resolved interval must be rejected.');
assertErrorId(@() model(1,1,1,0.6,0.4,12,0.031), ...
    'P18:GridAlignment','A partial final sample must be rejected.');
assertErrorId(@() model(1,1,1,0.6,0.4,12,0.03), ...
    'P18:EventAlignment','Off-grid disturbance events must be rejected.');
assertErrorId(@() model(1,1,1,0.6,0.4,20,0.003), ...
    'P18:TooManySteps','An oversized grid must be rejected before allocation.');
assertErrorId(@() model(1,1,1,0.6,0.4,20,realmin), ...
    'P18:TooManySteps','An overflowing grid ratio must be rejected.');
boundedGrid = model(1,2,1,1,0.8,20,0.004);
assert(boundedGrid.stepCount == 5000 && boundedGrid.sampleCount == 5001 && ...
    all(isfinite(boundedGrid.referenceState(:))) && ...
    all(isfinite(boundedGrid.actualState(:))) && ...
    all(isfinite(boundedGrid.totalCommandMPerSec2)) && ...
    boundedGrid.errorSpectralRadius < 1, ...
    'The largest accepted grid must contain only finite retained outputs.');

disp(['P18 checks passed: transparent command mixing, deterministic ' ...
    'tracking, two isolated sweeps, polarity recovery, malformed inputs, and bounds.']);
end

function assertAnyError(operation,message)
didError = false;
try
    operation();
catch
    didError = true;
end
assert(didError,message);
end

function assertErrorId(operation,expectedIdentifier,message)
actualIdentifier = '';
try
    operation();
catch exception
    actualIdentifier = exception.identifier;
end
assert(strcmp(actualIdentifier,expectedIdentifier),message);
end
