function interactive
%INTERACTIVE Explore P19 model error with bounded, immediate controls.
modelFunction = @model;

window = uifigure('Name','P19 - Sensitivity to model error', ...
    'Position',[100 100 1060 720]);
speedAxes = uiaxes(window,'Position',[55 360 620 315]);
gapAxes = uiaxes(window,'Position',[55 70 620 235]);

uilabel(window,'Position',[720 645 290 22], ...
    'Text','Actuator gain ratio (actual / nominal)');
gainSlider = uislider(window,'Position',[725 625 275 3], ...
    'Limits',[0.5 1.5],'Value',1, ...
    'MajorTicks',[0.5 0.75 1 1.25 1.5]);

uilabel(window,'Position',[720 570 290 22], ...
    'Text','Drag ratio (actual / nominal)');
dragSlider = uislider(window,'Position',[725 550 275 3], ...
    'Limits',[0.5 2],'Value',1, ...
    'MajorTicks',[0.5 1 1.5 2]);

uilabel(window,'Position',[720 495 220 22], ...
    'Text','Reference speed (m/s)');
referenceSpinner = uispinner(window,'Position',[900 495 100 22], ...
    'Limits',[0 2],'Step',0.1,'Value',1);

uilabel(window,'Position',[720 445 220 22], ...
    'Text','Actuator polarity');
signDropdown = uidropdown(window,'Position',[845 445 155 22], ...
    'Items',{'Correct sign','Reversed sign (broken)'}, ...
    'Value','Correct sign');

resetButton = uibutton(window,'push','Text','Reset baseline', ...
    'Position',[720 390 280 30]);
statusLabel = uilabel(window,'Position',[720 125 300 235], ...
    'VerticalAlignment','top','WordWrap','on','Text','');

gainSlider.ValueChangingFcn = @(~,event) redraw(event.Value, ...
    dragSlider.Value,referenceSpinner.Value,signDropdown.Value);
gainSlider.ValueChangedFcn = @(~,~) redraw(gainSlider.Value, ...
    dragSlider.Value,referenceSpinner.Value,signDropdown.Value);
dragSlider.ValueChangingFcn = @(~,event) redraw(gainSlider.Value, ...
    event.Value,referenceSpinner.Value,signDropdown.Value);
dragSlider.ValueChangedFcn = @(~,~) redraw(gainSlider.Value, ...
    dragSlider.Value,referenceSpinner.Value,signDropdown.Value);
referenceSpinner.ValueChangedFcn = @(~,~) redraw(gainSlider.Value, ...
    dragSlider.Value,referenceSpinner.Value,signDropdown.Value);
signDropdown.ValueChangedFcn = @(~,~) redraw(gainSlider.Value, ...
    dragSlider.Value,referenceSpinner.Value,signDropdown.Value);
resetButton.ButtonPushedFcn = @(~,~) resetBaseline();

redraw(1,1,1,'Correct sign');

function resetBaseline
    gainSlider.Value = 1;
    dragSlider.Value = 1;
    referenceSpinner.Value = 1;
    signDropdown.Value = 'Correct sign';
    redraw(1,1,1,'Correct sign');
end

function redraw(gainRatio,dragRatio,referenceSpeed,signChoice)
    if strcmp(signChoice,'Correct sign')
        actuatorSign = 1;
    else
        actuatorSign = -1;
    end
    result = modelFunction(gainRatio,dragRatio,actuatorSign, ...
        referenceSpeed,10,0.02);

    cla(speedAxes);
    plot(speedAxes,result.timeSec,result.referenceSpeed,'k:', ...
        'LineWidth',1.4,'DisplayName','Reference');
    hold(speedAxes,'on');
    plot(speedAxes,result.timeSec,result.predictedSpeedMPerSec,'b--', ...
        'LineWidth',1.7,'DisplayName','Nominal prediction');
    plot(speedAxes,result.timeSec,result.actualSpeedMPerSec,'m-', ...
        'LineWidth',1.7,'DisplayName','Actual speed');
    hold(speedAxes,'off'); grid(speedAxes,'on');
    xlabel(speedAxes,'Time (s)'); ylabel(speedAxes,'Speed (m/s)');
    title(speedAxes,'Nominal prediction versus actual plant');
    legend(speedAxes,'Location','best');

    cla(gapAxes);
    plot(gapAxes,result.timeSec,result.speedPredictionGapMPerSec,'r-', ...
        'LineWidth',1.7,'DisplayName','Actual minus predicted');
    hold(gapAxes,'on');
    yline(gapAxes,0,'k:','HandleVisibility','off');
    hold(gapAxes,'off'); grid(gapAxes,'on');
    xlabel(gapAxes,'Time (s)');
    ylabel(gapAxes,'Prediction gap (m/s)');
    title(gapAxes,'Observable consequence of model error');
    legend(gapAxes,'Location','best');

    if actuatorSign < 0
        interpretation = ['broken: reversed actuator polarity makes ' ...
            'feedback reinforce error instead of oppose it'];
        if result.actualClosedLoopStable
            sensitivityText = ['polarity is outside the positive-ratio ' ...
                'sensitivity sweeps'];
        else
            sensitivityText = 'steady sensitivities: undefined (unstable)';
        end
    elseif gainRatio == 1 && dragRatio == 1
        interpretation = ['matched limit: nominal and actual histories ' ...
            'coincide exactly'];
        sensitivityText = sprintf( ...
            'local gain/drag sensitivity: %+.3f / %+.3f m/s per fraction', ...
            result.actuatorGainSensitivityMPerSecPerFraction, ...
            result.dragSensitivityMPerSecPerFraction);
    elseif abs(gainRatio-1) >= abs(dragRatio-1)
        interpretation = ['actuator mismatch: gain error changes how much ' ...
            'speed each command produces'];
        sensitivityText = sprintf('local gain sensitivity: %+.3f m/s per fraction', ...
            result.actuatorGainSensitivityMPerSecPerFraction);
    else
        interpretation = ['drag mismatch: loss error changes the speed ' ...
            'needed to balance a fixed command'];
        sensitivityText = sprintf('local drag sensitivity: %+.3f m/s per fraction', ...
            result.dragSensitivityMPerSecPerFraction);
    end
    statusLabel.Text = sprintf([ ...
        'gain ratio: %.2f\ndrag ratio: %.2f\nactual pole: %.4f\n' ...
        'prediction-gap RMSE: %.4f m/s\npeak gap: %.4f m/s\n%s\n\n%s'], ...
        gainRatio,dragRatio,result.actualClosedLoopPole, ...
        result.predictionGapRmseMPerSec, ...
        result.maximumAbsolutePredictionGapMPerSec, ...
        sensitivityText,interpretation);
end
end
