function result = model(actuatorGainRatio,dragRatio,actuatorSign, ...
    referenceSpeedMPerSec,simulationDurationSec,timeStepSec)
%MODEL Compare nominal prediction with an uncertain closed-loop speed plant.
arguments
    actuatorGainRatio (1,1) double ...
        {mustBeReal,mustBeFinite,mustBePositive} = 1
    dragRatio (1,1) double {mustBeReal,mustBeFinite,mustBePositive} = 1
    actuatorSign (1,1) double {mustBeReal,mustBeFinite} = 1
    referenceSpeedMPerSec (1,1) double ...
        {mustBeReal,mustBeFinite,mustBeNonnegative} = 1
    simulationDurationSec (1,1) double ...
        {mustBeReal,mustBeFinite,mustBePositive} = 10
    timeStepSec (1,1) double ...
        {mustBeReal,mustBeFinite,mustBePositive} = 0.02
end

if actuatorGainRatio < 0.5 || actuatorGainRatio > 1.5
    error('P19:ActuatorGainRatioRange', ...
        'Actuator gain ratio must be between 0.5 and 1.5.');
end
if dragRatio < 0.5 || dragRatio > 2
    error('P19:DragRatioRange', ...
        'Drag ratio must be between 0.5 and 2.');
end
if actuatorSign ~= 1 && actuatorSign ~= -1
    error('P19:ActuatorSign', ...
        'Actuator sign must be exactly +1 or -1.');
end
if referenceSpeedMPerSec > 2
    error('P19:ReferenceSpeedRange', ...
        'Reference speed must be between 0 and 2 m/s.');
end
if simulationDurationSec < 6 || simulationDurationSec > 20
    error('P19:DurationRange', ...
        'Simulation duration must be between 6 and 20 seconds.');
end
if timeStepSec > 0.05
    error('P19:DisplayResolution', ...
        'Time step must be at most 0.05 seconds.');
end

maximumStepCount = 5000;
rawStepCount = simulationDurationSec/timeStepSec;
if ~isfinite(rawStepCount) || rawStepCount > maximumStepCount+0.5
    error('P19:TooManySteps', ...
        'The requested time grid exceeds 5000 state transitions.');
end
stepCount = round(rawStepCount);
if abs(rawStepCount-stepCount) > 1e-10*max(1,rawStepCount)
    error('P19:GridAlignment', ...
        'Duration must contain an integer number of time steps.');
end

referenceStepSec = 1;
eventRatio = referenceStepSec/timeStepSec;
if abs(eventRatio-round(eventRatio)) > 1e-10*max(1,eventRatio)
    error('P19:EventAlignment', ...
        'The 1 s reference event must lie on the time grid.');
end

% A first-order speed plant makes both uncertain coefficients visible:
%   dv/dt = -a*v + b*u.
% The controller retains P18's two roles, u[k]=(a0/b0)*r[k]+K*(r[k]-v[k]).
% That sampled command is held over one interval while the nominal predictor
% and actual plant close their own deterministic loops.
nominalDragPerSec = 1;
nominalActuatorGain = 1; % dimensionless command effectiveness
feedbackGainPerSec = 1.5;
actualDragPerSec = dragRatio*nominalDragPerSec;
actualActuatorGain = actuatorSign*actuatorGainRatio* ...
    nominalActuatorGain;

nominalDecay = exp(-nominalDragPerSec*timeStepSec);
nominalInputCoefficient = nominalActuatorGain/ ...
    nominalDragPerSec*(1-nominalDecay);
actualDecay = exp(-actualDragPerSec*timeStepSec);
actualInputCoefficient = actualActuatorGain/ ...
    actualDragPerSec*(1-actualDecay);
nominalClosedLoopPole = nominalDecay- ...
    nominalInputCoefficient*feedbackGainPerSec;
actualClosedLoopPole = actualDecay- ...
    actualInputCoefficient*feedbackGainPerSec;
actualClosedLoopStable = abs(actualClosedLoopPole) < 1;

sampleCount = stepCount+1;
timeSec = (0:stepCount)*timeStepSec;
referenceSpeed = zeros(1,sampleCount);
referenceSpeed(timeSec >= referenceStepSec) = referenceSpeedMPerSec;
predictedSpeedMPerSec = zeros(1,sampleCount);
actualSpeedMPerSec = zeros(1,sampleCount);
nominalFeedforwardCommandMPerSec2 = zeros(1,sampleCount);
nominalFeedbackCommandMPerSec2 = zeros(1,sampleCount);
nominalTotalCommandMPerSec2 = zeros(1,sampleCount);
actualFeedforwardCommandMPerSec2 = zeros(1,sampleCount);
actualFeedbackCommandMPerSec2 = zeros(1,sampleCount);
actualTotalCommandMPerSec2 = zeros(1,sampleCount);

for k = 1:sampleCount
    nominalFeedforwardCommandMPerSec2(k) = ...
        nominalDragPerSec/nominalActuatorGain*referenceSpeed(k);
    actualFeedforwardCommandMPerSec2(k) = ...
        nominalFeedforwardCommandMPerSec2(k);
    nominalFeedbackCommandMPerSec2(k) = feedbackGainPerSec* ...
        (referenceSpeed(k)-predictedSpeedMPerSec(k));
    actualFeedbackCommandMPerSec2(k) = feedbackGainPerSec* ...
        (referenceSpeed(k)-actualSpeedMPerSec(k));
    nominalTotalCommandMPerSec2(k) = ...
        nominalFeedforwardCommandMPerSec2(k)+ ...
        nominalFeedbackCommandMPerSec2(k);
    actualTotalCommandMPerSec2(k) = ...
        actualFeedforwardCommandMPerSec2(k)+ ...
        actualFeedbackCommandMPerSec2(k);
    if k <= stepCount
        predictedSpeedMPerSec(k+1) = nominalDecay* ...
            predictedSpeedMPerSec(k)+nominalInputCoefficient* ...
            nominalTotalCommandMPerSec2(k);
        actualSpeedMPerSec(k+1) = actualDecay*actualSpeedMPerSec(k)+ ...
            actualInputCoefficient*actualTotalCommandMPerSec2(k);
    end
end

speedPredictionGapMPerSec = actualSpeedMPerSec-predictedSpeedMPerSec;
actualTrackingErrorMPerSec = referenceSpeed-actualSpeedMPerSec;
predictionGapIntegralM2PerSec = timeStepSec*sum( ...
    speedPredictionGapMPerSec(1:end-1).^2);
predictionGapRmseMPerSec = sqrt(mean(speedPredictionGapMPerSec.^2));
maximumAbsolutePredictionGapMPerSec = max(abs(speedPredictionGapMPerSec));
actualTrackingIntegralM2PerSec = timeStepSec*sum( ...
    actualTrackingErrorMPerSec(1:end-1).^2);
actualFeedbackEffortIntegralM2PerSec3 = timeStepSec*sum( ...
    actualFeedbackCommandMPerSec2(1:end-1).^2);
peakAbsoluteActualCommandMPerSec2 = max(abs(actualTotalCommandMPerSec2));

% The equilibrium quotient is a transparent sensitivity measurement. For
% correct polarity, it predicts the long-run output and its local change per
% unit fractional error in actuator gain or drag.
steadyStateDenominatorPerSec = actualDragPerSec+ ...
    actualActuatorGain*feedbackGainPerSec;
if actualClosedLoopStable
    nominalSteadyStateSpeedMPerSec = referenceSpeedMPerSec;
    actualSteadyStateSpeedMPerSec = actualActuatorGain* ...
        (nominalDragPerSec/nominalActuatorGain+ ...
        feedbackGainPerSec)*referenceSpeedMPerSec/ ...
        steadyStateDenominatorPerSec;
    if actuatorSign > 0
        actuatorGainSensitivityMPerSecPerFraction = actuatorSign* ...
            nominalActuatorGain* ...
            (nominalDragPerSec/nominalActuatorGain+ ...
            feedbackGainPerSec)*referenceSpeedMPerSec*actualDragPerSec/ ...
            steadyStateDenominatorPerSec^2;
        dragSensitivityMPerSecPerFraction = -actualActuatorGain* ...
            (nominalDragPerSec/nominalActuatorGain+ ...
            feedbackGainPerSec)*referenceSpeedMPerSec*nominalDragPerSec/ ...
            steadyStateDenominatorPerSec^2;
    else
        actuatorGainSensitivityMPerSecPerFraction = NaN;
        dragSensitivityMPerSecPerFraction = NaN;
    end
else
    nominalSteadyStateSpeedMPerSec = referenceSpeedMPerSec;
    actualSteadyStateSpeedMPerSec = NaN;
    actuatorGainSensitivityMPerSecPerFraction = NaN;
    dragSensitivityMPerSecPerFraction = NaN;
end
steadyStatePredictionErrorMPerSec = actualSteadyStateSpeedMPerSec- ...
    nominalSteadyStateSpeedMPerSec;

nominalRecurrenceResidualMPerSec = 0;
actualRecurrenceResidualMPerSec = 0;
for k = 1:stepCount
    expectedPredictedNext = nominalDecay*predictedSpeedMPerSec(k)+ ...
        nominalInputCoefficient*nominalTotalCommandMPerSec2(k);
    expectedActualNext = actualDecay*actualSpeedMPerSec(k)+ ...
        actualInputCoefficient*actualTotalCommandMPerSec2(k);
    nominalRecurrenceResidualMPerSec = max( ...
        nominalRecurrenceResidualMPerSec, ...
        abs(predictedSpeedMPerSec(k+1)-expectedPredictedNext));
    actualRecurrenceResidualMPerSec = max( ...
        actualRecurrenceResidualMPerSec, ...
        abs(actualSpeedMPerSec(k+1)-expectedActualNext));
end

result = struct( ...
    'actuatorGainRatio',actuatorGainRatio, ...
    'dragRatio',dragRatio, ...
    'actuatorSign',actuatorSign, ...
    'relativeActuatorGainError',actuatorSign*actuatorGainRatio-1, ...
    'relativeDragError',dragRatio-1, ...
    'referenceSpeedMPerSec',referenceSpeedMPerSec, ...
    'simulationDurationSec',simulationDurationSec, ...
    'timeStepSec',timeStepSec, ...
    'referenceStepSec',referenceStepSec, ...
    'maximumStepCount',maximumStepCount, ...
    'stepCount',stepCount, ...
    'sampleCount',sampleCount, ...
    'nominalDragPerSec',nominalDragPerSec, ...
    'nominalActuatorGain',nominalActuatorGain, ...
    'feedbackGainPerSec',feedbackGainPerSec, ...
    'actualDragPerSec',actualDragPerSec, ...
    'actualActuatorGain',actualActuatorGain, ...
    'nominalDecay',nominalDecay, ...
    'nominalInputCoefficient',nominalInputCoefficient, ...
    'actualDecay',actualDecay, ...
    'actualInputCoefficient',actualInputCoefficient, ...
    'nominalClosedLoopPole',nominalClosedLoopPole, ...
    'actualClosedLoopPole',actualClosedLoopPole, ...
    'actualClosedLoopStable',actualClosedLoopStable, ...
    'timeSec',timeSec, ...
    'referenceSpeed',referenceSpeed, ...
    'predictedSpeedMPerSec',predictedSpeedMPerSec, ...
    'actualSpeedMPerSec',actualSpeedMPerSec, ...
    'speedPredictionGapMPerSec',speedPredictionGapMPerSec, ...
    'actualTrackingErrorMPerSec',actualTrackingErrorMPerSec, ...
    'nominalFeedforwardCommandMPerSec2', ...
    nominalFeedforwardCommandMPerSec2, ...
    'nominalFeedbackCommandMPerSec2',nominalFeedbackCommandMPerSec2, ...
    'nominalTotalCommandMPerSec2',nominalTotalCommandMPerSec2, ...
    'actualFeedforwardCommandMPerSec2',actualFeedforwardCommandMPerSec2, ...
    'actualFeedbackCommandMPerSec2',actualFeedbackCommandMPerSec2, ...
    'actualTotalCommandMPerSec2',actualTotalCommandMPerSec2, ...
    'predictionGapIntegralM2PerSec',predictionGapIntegralM2PerSec, ...
    'predictionGapRmseMPerSec',predictionGapRmseMPerSec, ...
    'maximumAbsolutePredictionGapMPerSec', ...
    maximumAbsolutePredictionGapMPerSec, ...
    'actualTrackingIntegralM2PerSec',actualTrackingIntegralM2PerSec, ...
    'actualFeedbackEffortIntegralM2PerSec3', ...
    actualFeedbackEffortIntegralM2PerSec3, ...
    'peakAbsoluteActualCommandMPerSec2', ...
    peakAbsoluteActualCommandMPerSec2, ...
    'nominalSteadyStateSpeedMPerSec',nominalSteadyStateSpeedMPerSec, ...
    'actualSteadyStateSpeedMPerSec',actualSteadyStateSpeedMPerSec, ...
    'steadyStatePredictionErrorMPerSec', ...
    steadyStatePredictionErrorMPerSec, ...
    'actuatorGainSensitivityMPerSecPerFraction', ...
    actuatorGainSensitivityMPerSecPerFraction, ...
    'dragSensitivityMPerSecPerFraction', ...
    dragSensitivityMPerSecPerFraction, ...
    'nominalRecurrenceResidualMPerSec', ...
    nominalRecurrenceResidualMPerSec, ...
    'actualRecurrenceResidualMPerSec',actualRecurrenceResidualMPerSec);
end
