function run_checks
%RUN_CHECKS Verify P19 prediction, sensitivity, limits, and bounds.
tolerance = 5e-12;
baselineA = model(1,1,1,1,10,0.02);
baselineB = model(1,1,1,1,10,0.02);
assert(isequaln(baselineA,baselineB), ...
    'The deterministic baseline must repeat exactly.');

expectedNominalDecay = exp(-0.02);
expectedNominalInput = 1-expectedNominalDecay;
expectedNominalPole = expectedNominalDecay-1.5*expectedNominalInput;
assert(abs(baselineA.nominalDecay-expectedNominalDecay) < tolerance && ...
    abs(baselineA.nominalInputCoefficient-expectedNominalInput) < ...
    tolerance && abs(baselineA.nominalClosedLoopPole- ...
    expectedNominalPole) < tolerance, ...
    'The nominal held-input coefficients and feedback pole must be exact.');
assert(baselineA.actualDragPerSec == 1 && ...
    baselineA.actualActuatorGain == 1 && ...
    baselineA.feedbackGainPerSec == 1.5 && ...
    baselineA.actualClosedLoopStable, ...
    'The baseline must use the declared stable nominal speed plant.');

for k = 1:baselineA.stepCount
    expectedReference = double(baselineA.timeSec(k) >= 1);
    expectedFeedforward = expectedReference;
    expectedNominalFeedback = 1.5*(expectedReference- ...
        baselineA.predictedSpeedMPerSec(k));
    expectedActualFeedback = 1.5*(expectedReference- ...
        baselineA.actualSpeedMPerSec(k));
    expectedNominalCommand = expectedFeedforward+expectedNominalFeedback;
    expectedActualCommand = expectedFeedforward+expectedActualFeedback;
    expectedPredictedNext = expectedNominalDecay* ...
        baselineA.predictedSpeedMPerSec(k)+expectedNominalInput* ...
        expectedNominalCommand;
    expectedActualNext = expectedNominalDecay* ...
        baselineA.actualSpeedMPerSec(k)+expectedNominalInput* ...
        expectedActualCommand;
    assert(baselineA.referenceSpeed(k) == expectedReference && ...
        abs(baselineA.nominalFeedforwardCommandMPerSec2(k)- ...
        expectedFeedforward) < tolerance, ...
        'The reference step and nominal feedforward must follow their definitions.');
    assert(abs(baselineA.nominalFeedbackCommandMPerSec2(k)- ...
        expectedNominalFeedback) < tolerance && ...
        abs(baselineA.actualFeedbackCommandMPerSec2(k)- ...
        expectedActualFeedback) < tolerance, ...
        'Each feedback command must use its own observable tracking error.');
    assert(abs(baselineA.nominalTotalCommandMPerSec2(k)- ...
        expectedNominalCommand) < tolerance && ...
        abs(baselineA.actualTotalCommandMPerSec2(k)- ...
        expectedActualCommand) < tolerance, ...
        'Each total command must equal feedforward plus feedback.');
    assert(abs(baselineA.predictedSpeedMPerSec(k+1)- ...
        expectedPredictedNext) < tolerance && ...
        abs(baselineA.actualSpeedMPerSec(k+1)-expectedActualNext) < ...
        tolerance, ...
        'Every baseline state must follow the exact held-input recurrence.');
end
assert(isequal(baselineA.predictedSpeedMPerSec, ...
    baselineA.actualSpeedMPerSec) && ...
    max(abs(baselineA.speedPredictionGapMPerSec)) == 0 && ...
    baselineA.predictionGapIntegralM2PerSec == 0 && ...
    baselineA.predictionGapRmseMPerSec == 0 && ...
    baselineA.maximumAbsolutePredictionGapMPerSec == 0, ...
    'Matched nominal and actual models must have an exact zero prediction gap.');
assert(abs(baselineA.actualSteadyStateSpeedMPerSec-1) < tolerance && ...
    abs(baselineA.actuatorGainSensitivityMPerSecPerFraction-0.4) < ...
    tolerance && abs(baselineA.dragSensitivityMPerSecPerFraction+0.4) < ...
    tolerance, ...
    'The matched equilibrium and analytic local sensitivities must be exact.');
assert(baselineA.nominalRecurrenceResidualMPerSec < tolerance && ...
    baselineA.actualRecurrenceResidualMPerSec < tolerance, ...
    'Retained recurrence residuals must remain at arithmetic roundoff.');

% Independent nonnominal oracle: derive held coefficients, every transition,
% metrics, equilibrium, and local derivatives without using retained fields.
weaker = model(0.8,1,1,1,10,0.02);
expectedActualDecay = exp(-0.02);
expectedActualInput = 0.8*(1-expectedActualDecay);
expectedActualPole = expectedActualDecay-1.5*expectedActualInput;
assert(abs(weaker.actualInputCoefficient-expectedActualInput) < ...
    tolerance && abs(weaker.actualClosedLoopPole-expectedActualPole) < ...
    tolerance, ...
    'Actuator error must change only the actual input coefficient and pole.');
for k = 1:weaker.stepCount
    expectedCommand = weaker.actualFeedforwardCommandMPerSec2(k)+ ...
        1.5*(weaker.referenceSpeed(k)-weaker.actualSpeedMPerSec(k));
    expectedNext = expectedActualDecay*weaker.actualSpeedMPerSec(k)+ ...
        expectedActualInput*expectedCommand;
    assert(abs(weaker.actualTotalCommandMPerSec2(k)-expectedCommand) < ...
        tolerance && abs(weaker.actualSpeedMPerSec(k+1)-expectedNext) < ...
        tolerance, ...
        'The nonnominal actual history must follow independent arithmetic.');
end
expectedGapIse = 0.02*sum(weaker.speedPredictionGapMPerSec(1:end-1).^2);
expectedGapRmse = sqrt(mean(weaker.speedPredictionGapMPerSec.^2));
assert(abs(weaker.predictionGapIntegralM2PerSec-expectedGapIse) < ...
    tolerance && abs(weaker.predictionGapRmseMPerSec-expectedGapRmse) < ...
    tolerance, ...
    'Prediction-gap metrics must be direct sums of the retained history.');
assert(abs(weaker.predictionGapIntegralM2PerSec- ...
    0.07788234685631548) < 5e-13 && ...
    abs(weaker.predictionGapRmseMPerSec-0.08825636091170849) < ...
    5e-13 && abs(weaker.maximumAbsolutePredictionGapMPerSec- ...
    0.11304306795345398) < 5e-13, ...
    'Nonnominal time metrics must match independent reference simulation.');
assert(abs(weaker.actualSteadyStateSpeedMPerSec-10/11) < tolerance && ...
    abs(weaker.actuatorGainSensitivityMPerSecPerFraction- ...
    0.5165289256198347) < tolerance && ...
    abs(weaker.dragSensitivityMPerSecPerFraction+ ...
    0.4132231404958677) < tolerance, ...
    'Nonnominal equilibrium sensitivities must match quotient derivatives.');

% Sweep 1: only positive actuator effectiveness changes.
actuatorGainRatioValues = [0.6 0.8 1 1.2 1.4];
actuatorSteadySpeed = zeros(size(actuatorGainRatioValues));
actuatorGapRmse = zeros(size(actuatorGainRatioValues));
actuatorRuns = cell(size(actuatorGainRatioValues));
for k = 1:numel(actuatorGainRatioValues)
    actuatorRuns{k} = model(actuatorGainRatioValues(k),1,1,1,10,0.02);
    changed = actuatorRuns{k};
    actuatorSteadySpeed(k) = changed.actualSteadyStateSpeedMPerSec;
    actuatorGapRmse(k) = changed.predictionGapRmseMPerSec;
    assert(changed.dragRatio == 1 && changed.actuatorSign == 1 && ...
        changed.referenceSpeedMPerSec == 1 && ...
        changed.simulationDurationSec == 10 && ...
        changed.timeStepSec == 0.02 && ...
        changed.actualClosedLoopStable, ...
        'The actuator sweep must reset every non-swept input.');
end
assert(all(diff(actuatorSteadySpeed) > 0) && ...
    actuatorGapRmse(3) == 0 && ...
    all(actuatorGapRmse([1 2 4 5]) > 0), ...
    'More positive actuator effectiveness must raise steady speed with a unique matched limit.');
assert(abs(actuatorSteadySpeed(1)-15/19) < tolerance && ...
    abs(actuatorSteadySpeed(5)-35/31) < tolerance, ...
    'Actuator-sweep endpoints must match independent equilibrium arithmetic.');

% Sweep 2: only positive drag changes.
dragRatioValues = [0.5 0.75 1 1.5 2];
dragSteadySpeed = zeros(size(dragRatioValues));
dragGapRmse = zeros(size(dragRatioValues));
dragRuns = cell(size(dragRatioValues));
for k = 1:numel(dragRatioValues)
    dragRuns{k} = model(1,dragRatioValues(k),1,1,10,0.02);
    changed = dragRuns{k};
    dragSteadySpeed(k) = changed.actualSteadyStateSpeedMPerSec;
    dragGapRmse(k) = changed.predictionGapRmseMPerSec;
    assert(changed.actuatorGainRatio == 1 && changed.actuatorSign == 1 && ...
        changed.referenceSpeedMPerSec == 1 && ...
        changed.simulationDurationSec == 10 && ...
        changed.timeStepSec == 0.02 && ...
        changed.actualClosedLoopStable, ...
        'The drag sweep must reset every non-swept input.');
end
assert(all(diff(dragSteadySpeed) < 0) && dragGapRmse(3) == 0 && ...
    all(dragGapRmse([1 2 4 5]) > 0), ...
    'More drag must lower steady speed with a unique matched limit.');
assert(abs(dragSteadySpeed(1)-1.25) < tolerance && ...
    abs(dragSteadySpeed(5)-5/7) < tolerance, ...
    'Drag-sweep endpoints must match independent equilibrium arithmetic.');

% Broken structure and recovery: feedback must oppose error, not reinforce it.
broken = model(1,1,-1,1,10,0.02);
recovered = model(1,1,1,1,10,0.02);
assert(~broken.actualClosedLoopStable && ...
    abs(broken.actualClosedLoopPole) > 1 && ...
    broken.maximumAbsolutePredictionGapMPerSec > 400 && ...
    broken.actualFeedbackEffortIntegralM2PerSec3 > 3e5 && ...
    isnan(broken.actualSteadyStateSpeedMPerSec) && ...
    isnan(broken.actuatorGainSensitivityMPerSecPerFraction) && ...
    isnan(broken.dragSensitivityMPerSecPerFraction), ...
    'Reversed actuator polarity must create an unstable pole and growing correction.');
assert(isequaln(recovered,baselineA), ...
    'A fresh correct-sign call must recover the exact baseline.');
stableReversed = model(0.5,2,-1,1,10,0.02);
assert(stableReversed.actualClosedLoopStable && ...
    abs(stableReversed.actualSteadyStateSpeedMPerSec+1) < tolerance && ...
    isnan(stableReversed.actuatorGainSensitivityMPerSecPerFraction) && ...
    isnan(stableReversed.dragSensitivityMPerSecPerFraction), ...
    'A stable reversed-sign loop remains outside the positive-ratio sensitivity family.');

zeroReference = model(1.5,2,1,0,10,0.02);
assert(max(abs(zeroReference.referenceSpeed)) == 0 && ...
    max(abs(zeroReference.predictedSpeedMPerSec)) == 0 && ...
    max(abs(zeroReference.actualSpeedMPerSec)) == 0 && ...
    max(abs(zeroReference.actualTotalCommandMPerSec2)) == 0 && ...
    zeroReference.predictionGapIntegralM2PerSec == 0 && ...
    zeroReference.actualSteadyStateSpeedMPerSec == 0, ...
    'Zero reference from rest must remain an exact equilibrium for any accepted positive model ratios.');

assertAnyError(@() model(NaN,1,1,1,10,0.02), ...
    'A nonfinite actuator ratio must be rejected.');
assertAnyError(@() model([1 1],1,1,1,10,0.02), ...
    'A nonscalar actuator ratio must be rejected.');
assertAnyError(@() model(1,1+1i,1,1,10,0.02), ...
    'A complex drag ratio must be rejected.');
assertAnyError(@() model(-1,1,1,1,10,0.02), ...
    'A negative actuator ratio must be rejected.');
assertAnyError(@() model(1,-1,1,1,10,0.02), ...
    'A negative drag ratio must be rejected.');
assertAnyError(@() model(1,1,1,-1,10,0.02), ...
    'A negative reference speed must be rejected.');
assertAnyError(@() model(1,1,1,1,-10,0.02), ...
    'A negative duration must be rejected.');
assertAnyError(@() model(1,1,1,1,10,-0.02), ...
    'A negative time step must be rejected.');
assertErrorId(@() model(0.49,1,1,1,10,0.02), ...
    'P19:ActuatorGainRatioRange','Too-small actuator ratio must be rejected.');
assertErrorId(@() model(1.51,1,1,1,10,0.02), ...
    'P19:ActuatorGainRatioRange','Excessive actuator ratio must be rejected.');
assertErrorId(@() model(1,0.49,1,1,10,0.02), ...
    'P19:DragRatioRange','Too-small drag ratio must be rejected.');
assertErrorId(@() model(1,2.01,1,1,10,0.02), ...
    'P19:DragRatioRange','Excessive drag ratio must be rejected.');
assertErrorId(@() model(1,1,0,1,10,0.02), ...
    'P19:ActuatorSign','Malformed actuator sign must be rejected.');
assertErrorId(@() model(1,1,1,2.01,10,0.02), ...
    'P19:ReferenceSpeedRange','Excessive reference speed must be rejected.');
assertErrorId(@() model(1,1,1,1,5.99,0.02), ...
    'P19:DurationRange','Too-short duration must be rejected.');
assertErrorId(@() model(1,1,1,1,20.01,0.02), ...
    'P19:DurationRange','Excessive duration must be rejected.');
assertErrorId(@() model(1,1,1,1,10,0.051), ...
    'P19:DisplayResolution','An under-resolved interval must be rejected.');
assertErrorId(@() model(1,1,1,1,10,0.03), ...
    'P19:GridAlignment','A partial final sample must be rejected.');
assertErrorId(@() model(1,1,1,1,6,0.024), ...
    'P19:EventAlignment','An off-grid reference event must be rejected.');
assertErrorId(@() model(1,1,1,1,20,0.003), ...
    'P19:TooManySteps','An oversized grid must be rejected before allocation.');
assertErrorId(@() model(1,1,1,1,20,realmin), ...
    'P19:TooManySteps','An overflowing grid ratio must be rejected.');

boundedGrid = model(1.5,2,1,2,20,0.004);
assert(boundedGrid.stepCount == 5000 && ...
    boundedGrid.sampleCount == 5001 && ...
    all(isfinite(boundedGrid.predictedSpeedMPerSec)) && ...
    all(isfinite(boundedGrid.actualSpeedMPerSec)) && ...
    all(isfinite(boundedGrid.actualTotalCommandMPerSec2)) && ...
    isfinite(boundedGrid.predictionGapIntegralM2PerSec) && ...
    boundedGrid.actualClosedLoopStable, ...
    'The largest accepted positive-polarity grid must retain only finite outputs.');

disp(['P19 checks passed: deterministic nominal/actual propagation, ' ...
    'analytic sensitivities, two isolated sweeps, polarity recovery, malformed inputs, and bounds.']);
end

function assertAnyError(operation,message)
didError = false;
try
    operation();
catch
    didError = true;
end
assert(didError,message);
end

function assertErrorId(operation,expectedIdentifier,message)
actualIdentifier = '';
try
    operation();
catch exception
    actualIdentifier = exception.identifier;
end
assert(strcmp(actualIdentifier,expectedIdentifier),message);
end
