function out = model(antiWindupGain,demandDurationSec,tEnd,timeStepSec,backCalculationSign)
%MODEL Compare PI windup with transparent back-calculation recovery.
arguments
    antiWindupGain (1,1) double {mustBeReal,mustBeFinite,mustBeNonnegative}
    demandDurationSec (1,1) double {mustBeReal,mustBeFinite,mustBePositive}
    tEnd (1,1) double {mustBeReal,mustBeFinite,mustBePositive}
    timeStepSec (1,1) double {mustBeReal,mustBeFinite,mustBePositive}
    backCalculationSign (1,1) double {mustBeReal,mustBeFinite} = 1
end

proportionalGain = 2;
integralGainPerSec = 1;
plantTimeConstantSec = 1;
plantStaticGainOutputPerActuator = 1;
controlLimit = 1;
highReference = 2;
recoveryReference = -0.5;
settlingBandOutput = 0.02;
maxAntiWindupGain = 10;
minDemandDurationSec = 0.25;
maxDemandDurationSec = 6;
maxHorizonSec = 20;
minRecoveryViewSec = 3;
maxTimeStepSec = 0.02;
maxSampleCount = 30001;
responseLimit = 500;

if antiWindupGain > maxAntiWindupGain
    error('P12:AntiWindupGainRange', ...
        'Anti-windup gain must not exceed 10 per second.');
end
if demandDurationSec < minDemandDurationSec || ...
        demandDurationSec > maxDemandDurationSec
    error('P12:DemandDurationRange', ...
        'High-demand duration must be between 0.25 and 6 seconds.');
end
if tEnd > maxHorizonSec || tEnd-demandDurationSec < minRecoveryViewSec
    error('P12:HorizonRange', ...
        'Horizon must be at most 20 seconds and show at least 3 recovery seconds.');
end
if timeStepSec > maxTimeStepSec
    error('P12:DisplayResolution', ...
        'Time step must not exceed 0.02 seconds.');
end
if backCalculationSign ~= 1 && backCalculationSign ~= -1
    error('P12:BackCalculationSign', ...
        'Back-calculation sign must be +1 (correct) or -1 (broken case).');
end

timeTolerance = 32*eps(max([1 tEnd demandDurationSec timeStepSec]));
regularIntervalCount = floor(tEnd/timeStepSec);
regularEndTime = regularIntervalCount*timeStepSec;
needsEndPoint = regularIntervalCount == 0 || ...
    tEnd-regularEndTime > timeTolerance;
eventIndex = round(demandDurationSec/timeStepSec);
eventOnRegularGrid = eventIndex <= regularIntervalCount && ...
    abs(eventIndex*timeStepSec-demandDurationSec) <= timeTolerance;
projectedSampleCount = regularIntervalCount+1+double(needsEndPoint)+ ...
    double(~eventOnRegularGrid);
if ~isfinite(projectedSampleCount) || projectedSampleCount > maxSampleCount
    error('P12:TooManySamples', ...
        'The requested event-aligned grid exceeds 30001 samples.');
end

t = (0:regularIntervalCount)'*timeStepSec;
if needsEndPoint
    t = [t; tEnd];
else
    t(end) = tEnd;
end
if eventOnRegularGrid
    t(eventIndex+1) = demandDurationSec;
else
    t = [t; demandDurationSec];
end
t = sort(t);
sampleCount = numel(t);
intervalDurationSec = diff(t);
reference = recoveryReference*ones(sampleCount,1);
reference(t < demandDurationSec) = highReference;

unprotected = simulatePath(false);
protected = simulatePath(true);
if any(~isfinite([unprotected.plantOutput; protected.plantOutput; ...
        unprotected.requestedControl; protected.requestedControl; ...
        unprotected.integralState; protected.integralState])) || ...
        max(abs([unprotected.requestedControl; ...
        protected.requestedControl; unprotected.integralState; ...
        protected.integralState])) > responseLimit
    error('P12:ResponseBound', ...
        'The requested response exceeds the bounded learning view.');
end

out = struct( ...
    't',t, ...
    'reference',reference, ...
    'unprotected',unprotected, ...
    'protected',protected, ...
    'antiWindupGainPerSec',antiWindupGain, ...
    'demandDurationSec',demandDurationSec, ...
    'horizonSec',tEnd, ...
    'timeStepSec',timeStepSec, ...
    'backCalculationSign',backCalculationSign, ...
    'proportionalGain',proportionalGain, ...
    'integralGainPerSec',integralGainPerSec, ...
    'plantTimeConstantSec',plantTimeConstantSec, ...
    'plantStaticGainOutputPerActuator',plantStaticGainOutputPerActuator, ...
    'controlLimit',controlLimit, ...
    'highReference',highReference, ...
    'recoveryReference',recoveryReference, ...
    'settlingBandOutput',settlingBandOutput, ...
    'controlUpperLimit',controlLimit*ones(sampleCount,1), ...
    'controlLowerLimit',-controlLimit*ones(sampleCount,1), ...
    'sampleCount',sampleCount, ...
    'maxSampleCount',maxSampleCount, ...
    'responseLimit',responseLimit);

    function path = simulatePath(useBackCalculation)
        plantOutput = zeros(sampleCount,1);
        trackingError = zeros(sampleCount,1);
        proportionalTerm = zeros(sampleCount,1);
        integralState = zeros(sampleCount,1);
        requestedControl = zeros(sampleCount,1);
        appliedControl = zeros(sampleCount,1);
        correctionTerm = zeros(sampleCount,1);
        saturationMask = false(sampleCount,1);
        saturationTolerance = 64*eps(max([1 controlLimit highReference]));

        for k = 1:sampleCount
            trackingError(k) = reference(k)-plantOutput(k);
            proportionalTerm(k) = proportionalGain*trackingError(k);
            requestedControl(k) = proportionalTerm(k)+integralState(k);
            appliedControl(k) = max(-controlLimit, ...
                min(controlLimit,requestedControl(k)));
            saturationMask(k) = abs(requestedControl(k)- ...
                appliedControl(k)) > saturationTolerance;
            if useBackCalculation
                correctionTerm(k) = backCalculationSign*antiWindupGain*( ...
                    appliedControl(k)-requestedControl(k));
            end
            if k < sampleCount
                plantDecay = exp(-intervalDurationSec(k)/ ...
                    plantTimeConstantSec);
                inputWeight = 1-plantDecay;
                plantOutput(k+1) = plantDecay*plantOutput(k)+ ...
                    inputWeight*plantStaticGainOutputPerActuator* ...
                    appliedControl(k);
                integratorDerivative = integralGainPerSec* ...
                    trackingError(k)+correctionTerm(k);
                integralState(k+1) = integralState(k)+ ...
                    intervalDurationSec(k)*integratorDerivative;
            end
        end

        commandGap = requestedControl-appliedControl;
        releaseSampleIndex = find(t == demandDurationSec,1,'first');
        recoveryIntervalMask = t(1:end-1) >= demandDurationSec;
        recoveryAbsoluteError = abs(trackingError);
        postReleaseIntegralAbsoluteError = sum(intervalDurationSec( ...
            recoveryIntervalMask).*(recoveryAbsoluteError( ...
            find(recoveryIntervalMask))+recoveryAbsoluteError( ...
            find(recoveryIntervalMask)+1))/2);
        reversalIndex = find(t >= demandDurationSec & ...
            appliedControl < -saturationTolerance,1,'first');
        if isempty(reversalIndex)
            reversalDelaySec = NaN;
        else
            reversalDelaySec = t(reversalIndex)-demandDurationSec;
        end
        tailMaximumError = zeros(sampleCount,1);
        tailMaximumError(end) = abs(plantOutput(end)-recoveryReference);
        for k = sampleCount-1:-1:1
            tailMaximumError(k) = max(abs(plantOutput(k)- ...
                recoveryReference),tailMaximumError(k+1));
        end
        settlingIndex = find(t >= demandDurationSec & ...
            tailMaximumError <= settlingBandOutput,1,'first');
        if isempty(settlingIndex)
            settlingTimeSec = NaN;
        else
            settlingTimeSec = t(settlingIndex)-demandDurationSec;
        end

        path = struct( ...
            'plantOutput',plantOutput, ...
            'trackingError',trackingError, ...
            'proportionalTerm',proportionalTerm, ...
            'integralState',integralState, ...
            'requestedControl',requestedControl, ...
            'appliedControl',appliedControl, ...
            'correctionTerm',correctionTerm, ...
            'commandGap',commandGap, ...
            'saturationMask',saturationMask, ...
            'integralStateAtRelease',integralState(releaseSampleIndex), ...
            'outputAtRelease',plantOutput(releaseSampleIndex), ...
            'reversalDelaySec',reversalDelaySec, ...
            'settlingTimeSec',settlingTimeSec, ...
            'postReleaseIntegralAbsoluteError', ...
            postReleaseIntegralAbsoluteError, ...
            'maximumAbsIntegralState',max(abs(integralState)), ...
            'maximumAbsCommandGap',max(abs(commandGap)), ...
            'finalTrackingError',trackingError(end), ...
            'isSaturatedAtEnd',saturationMask(end));
    end
end
