function run_checks
%RUN_CHECKS Independent windup identities, limits, failure, and recovery.
tolerance = 3e-11;

baselineA = model(1,3,12,0.01);
baselineB = model(1,3,12,0.01);
assert(isequaln(baselineA,baselineB), ...
    'Identical inputs must produce identical trajectories and metrics.');
assert(baselineA.proportionalGain == 2 && ...
    baselineA.integralGainPerSec == 1 && ...
    baselineA.plantTimeConstantSec == 1 && ...
    baselineA.plantStaticGainOutputPerActuator == 1 && ...
    baselineA.controlLimit == 1, ...
    'The PI law, plant, and actuator limit must remain explicit and fixed.');
maximumSteadyOutput = baselineA.plantStaticGainOutputPerActuator* ...
    baselineA.controlLimit;
assert(baselineA.highReference > maximumSteadyOutput && ...
    abs(baselineA.recoveryReference) < maximumSteadyOutput, ...
    'Plant gain and actuator authority must make only the high demand infeasible.');
assert(any(baselineA.t == baselineA.demandDurationSec) && ...
    baselineA.reference(find(baselineA.t == ...
    baselineA.demandDurationSec,1)) == baselineA.recoveryReference, ...
    'The exact demand event must use the recovery reference.');

paths = {baselineA.unprotected,baselineA.protected};
for pathIndex = 1:numel(paths)
    path = paths{pathIndex};
    expectedApplied = max(-baselineA.controlLimit, ...
        min(baselineA.controlLimit,path.requestedControl));
    assert(max(abs(path.appliedControl-expectedApplied)) == 0, ...
        'Every applied command must equal the explicit symmetric clamp.');
    assert(max(abs(path.requestedControl-(path.proportionalTerm+ ...
        path.integralState))) < tolerance, ...
        'Requested control must expose proportional plus integral effort.');
    assert(max(abs(path.proportionalTerm- ...
        baselineA.proportionalGain*path.trackingError)) < tolerance, ...
        'The proportional term must equal Kp times tracking error.');
    assert(max(abs(path.commandGap-(path.requestedControl- ...
        path.appliedControl))) == 0, ...
        'Command gap must equal requested minus applied effort.');
    assert(all(abs(path.appliedControl) <= ...
        baselineA.controlLimit+tolerance), ...
        'Anti-windup must never create actuator authority.');
end

intervalSec = diff(baselineA.t);
plantDecay = exp(-intervalSec/baselineA.plantTimeConstantSec);
unprotectedPlantResidual = baselineA.unprotected.plantOutput(2:end)-( ...
    plantDecay.*baselineA.unprotected.plantOutput(1:end-1)+(1-plantDecay).* ...
    baselineA.unprotected.appliedControl(1:end-1));
protectedPlantResidual = baselineA.protected.plantOutput(2:end)-( ...
    plantDecay.*baselineA.protected.plantOutput(1:end-1)+(1-plantDecay).* ...
    baselineA.protected.appliedControl(1:end-1));
assert(max(abs(unprotectedPlantResidual)) < tolerance && ...
    max(abs(protectedPlantResidual)) < tolerance, ...
    'Both paths must satisfy the exact held-command plant transition.');
unprotectedIntegralResidual = baselineA.unprotected.integralState(2:end)-( ...
    baselineA.unprotected.integralState(1:end-1)+intervalSec.* ...
    baselineA.integralGainPerSec.* ...
    baselineA.unprotected.trackingError(1:end-1));
protectedExpectedDerivative = baselineA.integralGainPerSec.* ...
    baselineA.protected.trackingError(1:end-1)+ ...
    baselineA.antiWindupGainPerSec.*( ...
    baselineA.protected.appliedControl(1:end-1)- ...
    baselineA.protected.requestedControl(1:end-1));
protectedIntegralResidual = baselineA.protected.integralState(2:end)-( ...
    baselineA.protected.integralState(1:end-1)+intervalSec.* ...
    protectedExpectedDerivative);
assert(max(abs(unprotectedIntegralResidual)) < tolerance && ...
    max(abs(protectedIntegralResidual)) < tolerance, ...
    'Both integral states must satisfy their transparent recurrences.');
assert(max(abs(baselineA.unprotected.correctionTerm)) == 0 && ...
    max(abs(baselineA.protected.correctionTerm-( ...
    baselineA.protected.appliedControl- ...
    baselineA.protected.requestedControl))) < tolerance, ...
    'Only the protected path may receive correctly signed gap feedback.');

highDemandMask = baselineA.t < baselineA.demandDurationSec;
assert(max(abs(baselineA.unprotected.plantOutput(highDemandMask)- ...
    baselineA.protected.plantOutput(highDemandMask))) == 0 && ...
    max(abs(baselineA.unprotected.appliedControl(highDemandMask)- ...
    baselineA.protected.appliedControl(highDemandMask))) == 0, ...
    'Protection must not change motion while both paths share the same clamp.');
assert(baselineA.unprotected.integralStateAtRelease > 3.9 && ...
    baselineA.protected.integralStateAtRelease < 0 && ...
    baselineA.protected.maximumAbsIntegralState < ...
    baselineA.unprotected.maximumAbsIntegralState, ...
    'Baseline gap feedback must reduce unavailable integral memory.');
assert(abs(baselineA.unprotected.reversalDelaySec-2.02) < 0.011 && ...
    baselineA.protected.reversalDelaySec == 0, ...
    'The protected baseline must reverse immediately instead of waiting 2.02 s.');
assert(baselineA.protected.postReleaseIntegralAbsoluteError < ...
    0.25*baselineA.unprotected.postReleaseIntegralAbsoluteError && ...
    ~isnan(baselineA.protected.settlingTimeSec) && ...
    isnan(baselineA.unprotected.settlingTimeSec), ...
    'Back-calculation must reduce recovery error and settling time.');

zeroGainCorrect = model(0,3,12,0.01,1);
zeroGainWrong = model(0,3,12,0.01,-1);
assert(isequaln(zeroGainCorrect.unprotected,zeroGainCorrect.protected) && ...
    isequaln(zeroGainCorrect.protected,zeroGainWrong.protected), ...
    'Kaw=0 must exactly recover plain PI and make polarity irrelevant.');

antiWindupGains = [0 0.25 0.5 1 2 4 8];
releaseIntegrals = zeros(size(antiWindupGains));
recoveryErrors = zeros(size(antiWindupGains));
for k = 1:numel(antiWindupGains)
    changed = model(antiWindupGains(k),3,12,0.01);
    releaseIntegrals(k) = changed.protected.integralStateAtRelease;
    recoveryErrors(k) = changed.protected.postReleaseIntegralAbsoluteError;
    assert(changed.demandDurationSec == 3 && ...
        changed.controlLimit == baselineA.controlLimit, ...
        'Gain sweep must preserve demand duration and actuator limit.');
end
assert(all(diff(releaseIntegrals) < 0) && ...
    recoveryErrors(4) == min(recoveryErrors), ...
    'More correction must drain release state, with moderate gain minimizing this recovery metric.');

demandDurationsSec = [1 2 3 4 5];
unprotectedReleaseIntegrals = zeros(size(demandDurationsSec));
unprotectedRecoveryErrors = zeros(size(demandDurationsSec));
protectedRecoveryErrors = zeros(size(demandDurationsSec));
for k = 1:numel(demandDurationsSec)
    changed = model(1,demandDurationsSec(k), ...
        demandDurationsSec(k)+9,0.01);
    unprotectedReleaseIntegrals(k) = ...
        changed.unprotected.integralStateAtRelease;
    unprotectedRecoveryErrors(k) = ...
        changed.unprotected.postReleaseIntegralAbsoluteError;
    protectedRecoveryErrors(k) = ...
        changed.protected.postReleaseIntegralAbsoluteError;
    assert(changed.antiWindupGainPerSec == 1 && ...
        changed.controlLimit == baselineA.controlLimit && ...
        changed.horizonSec-changed.demandDurationSec == 9 && ...
        changed.timeStepSec == baselineA.timeStepSec, ...
        'Duration sweep must preserve gain, limit, recovery window, and time step.');
end
assert(all(diff(unprotectedReleaseIntegrals) > 0) && ...
    all(diff(unprotectedRecoveryErrors) > 0), ...
    'Longer high demand must monotonically worsen unprotected windup.');
assert(max(protectedRecoveryErrors) < 1.1 && ...
    unprotectedRecoveryErrors(end) > 5*protectedRecoveryErrors(end), ...
    'Correct gap feedback must bound the duration-dependent recovery penalty.');

broken = model(0.5,3,8,0.01,-1);
recovered = model(0.5,3,8,0.01,1);
assert(isequaln(broken.unprotected,recovered.unprotected) && ...
    broken.backCalculationSign == -1 && recovered.backCalculationSign == 1, ...
    'Broken and recovered cases must change only correction polarity.');
assert(broken.protected.integralState(end) > 100 && ...
    broken.protected.appliedControl(end) == 1 && ...
    broken.protected.finalTrackingError < -1.4, ...
    'Wrong-sign feedback must expose runaway memory and wrong-direction actuation.');
assert(recovered.protected.maximumAbsIntegralState < 1 && ...
    recovered.protected.appliedControl(end) < 0 && ...
    abs(recovered.protected.finalTrackingError) < 0.06 && ...
    recovered.protected.postReleaseIntegralAbsoluteError < ...
    broken.protected.postReleaseIntegralAbsoluteError, ...
    'Restoring polarity must bound state and recover the feasible target.');

partialEvent = model(1,2.005,8.017,0.019);
eventIndex = find(partialEvent.t == 2.005,1,'first');
assert(~isempty(eventIndex) && partialEvent.t(end) == 8.017 && ...
    partialEvent.reference(eventIndex) == partialEvent.recoveryReference && ...
    all(diff(partialEvent.t) > 0), ...
    'Off-grid demand and horizon events must be inserted exactly and ordered.');
partialIntervalSec = diff(partialEvent.t);
partialDecay = exp(-partialIntervalSec);
partialPlantResidual = partialEvent.protected.plantOutput(2:end)-( ...
    partialDecay.*partialEvent.protected.plantOutput(1:end-1)+(1-partialDecay).* ...
    partialEvent.protected.appliedControl(1:end-1));
partialIntegralDerivative = partialEvent.protected.trackingError(1:end-1)+( ...
    partialEvent.protected.appliedControl(1:end-1)- ...
    partialEvent.protected.requestedControl(1:end-1));
partialIntegralResidual = partialEvent.protected.integralState(2:end)-( ...
    partialEvent.protected.integralState(1:end-1)+partialIntervalSec.* ...
    partialIntegralDerivative);
assert(max(abs(partialPlantResidual)) < tolerance && ...
    max(abs(partialIntegralResidual)) < tolerance, ...
    'Every inserted partial interval must use its actual duration.');
offGridEventExactHorizon = model(1,2.005,8.018,0.019);
assert(any(offGridEventExactHorizon.t == 2.005) && ...
    offGridEventExactHorizon.t(end) == 8.018 && ...
    numel(offGridEventExactHorizon.t) == numel(unique( ...
    offGridEventExactHorizon.t)), ...
    'An off-grid demand event must survive when the horizon is on-grid.');

assertAnyError(@() model(NaN,3,12,0.01), ...
    'A nonfinite gain must be rejected.');
assertAnyError(@() model([1 2],3,12,0.01), ...
    'A nonscalar gain must be rejected.');
assertAnyError(@() model(-1,3,12,0.01), ...
    'A negative gain must be rejected.');
assertAnyError(@() model(1,Inf,12,0.01), ...
    'A nonfinite duration must be rejected.');
assertAnyError(@() model(1,3,12,0), ...
    'A zero time step must be rejected.');
assertErrorId(@() model(10.1,3,12,0.01), ...
    'P12:AntiWindupGainRange','An excessive gain must be rejected.');
assertErrorId(@() model(1,0.2,12,0.01), ...
    'P12:DemandDurationRange','A too-short demand must be rejected.');
assertErrorId(@() model(1,6.1,12,0.01), ...
    'P12:DemandDurationRange','An excessive demand must be rejected.');
assertErrorId(@() model(1,3,5.9,0.01), ...
    'P12:HorizonRange','An insufficient recovery view must be rejected.');
assertErrorId(@() model(1,3,20.1,0.01), ...
    'P12:HorizonRange','An excessive horizon must be rejected.');
assertErrorId(@() model(1,3,12,0.021), ...
    'P12:DisplayResolution','An under-resolved time step must be rejected.');
assertErrorId(@() model(1,3,12,0.01,0), ...
    'P12:BackCalculationSign','An invalid correction polarity must be rejected.');
assertErrorId(@() model(1,3,20,1e-12), ...
    'P12:TooManySamples', ...
    'A tiny time step must be rejected before allocating its grid.');
assertErrorId(@() model(1,3,8,0.01,-1), ...
    'P12:ResponseBound', ...
    'Runaway wrong-sign state must stop at the declared response bound.');
boundedGrid = model(1,6,20,0.001);
assert(boundedGrid.sampleCount == 20001 && ...
    all(isfinite(boundedGrid.protected.plantOutput)), ...
    'A large grid below the declared sample cap must remain accepted.');

disp(['P12 checks passed: PI recurrences, independent levers, exact ' ...
    'events, windup failure, sign recovery, and resource bounds.']);
end

function assertAnyError(operation,message)
didError = false;
try
    operation();
catch
    didError = true;
end
assert(didError,message);
end

function assertErrorId(operation,expectedIdentifier,message)
actualIdentifier = '';
try
    operation();
catch exception
    actualIdentifier = exception.identifier;
end
assert(strcmp(actualIdentifier,expectedIdentifier),message);
end
