function out = model(samplePeriodSec,computationDelaySec,tEnd,displayStepSec)
%MODEL Expose how sampling and computation delay alter a feedback loop.
%   The normalized plant y'=-y+u is controlled by uComputed=Kp*(1-y)
%   at sample instants. During each interval the actuator first retains the
%   previous command for computationDelaySec, then applies the new command.
%   Both pieces use the exact constant-input plant transition.
arguments
    samplePeriodSec (1,1) double {mustBeReal,mustBeFinite,mustBePositive} = 0.05
    computationDelaySec (1,1) double {mustBeReal,mustBeFinite,mustBeNonnegative} = 0.01
    tEnd (1,1) double {mustBeReal,mustBeFinite,mustBePositive} = 4
    displayStepSec (1,1) double {mustBeReal,mustBeFinite,mustBePositive} = 0.005
end

if samplePeriodSec > 0.5
    error('P10:SamplePeriodRange','samplePeriodSec must not exceed 0.5 s.');
end
if computationDelaySec > samplePeriodSec
    error('P10:DelayRange', ...
        'computationDelaySec must lie between 0 and samplePeriodSec.');
end
if tEnd > 30
    error('P10:HorizonRange','tEnd must not exceed 30 s.');
end
if displayStepSec > samplePeriodSec
    error('P10:DisplayResolution', ...
        'displayStepSec must not exceed samplePeriodSec.');
end

maxControllerSamples = 10001;
maxDisplaySamples = 30001;
controllerIntervalCount = floor(tEnd/samplePeriodSec);
controllerSampleCount = controllerIntervalCount+1;
if ~isfinite(controllerSampleCount) || ...
        controllerSampleCount > maxControllerSamples
    error('P10:TooManyControllerSamples', ...
        'Requested %d controller samples; maximum is %d.', ...
        controllerSampleCount,maxControllerSamples);
end
displayIntervalCount = floor(tEnd/displayStepSec);
regularDisplaySampleCount = displayIntervalCount+1;
if ~isfinite(regularDisplaySampleCount) || ...
        regularDisplaySampleCount > maxDisplaySamples
    error('P10:TooManyDisplaySamples', ...
        'Requested at least %d display samples; maximum is %d.', ...
        regularDisplaySampleCount,maxDisplaySamples);
end
lastDisplayTime = displayIntervalCount*displayStepSec;
timeTolerance = 8*eps(max(tEnd,displayStepSec));
appendEnd = tEnd-lastDisplayTime > timeTolerance;
requestedRegularDisplaySampleCount = regularDisplaySampleCount+double(appendEnd);
if requestedRegularDisplaySampleCount > maxDisplaySamples
    error('P10:TooManyDisplaySamples', ...
        'Requested %d display samples; maximum is %d.', ...
        requestedRegularDisplaySampleCount,maxDisplaySamples);
end

sampleTimes = (0:controllerIntervalCount)'*samplePeriodSec;
sampleTimes(sampleTimes > tEnd & sampleTimes <= tEnd+timeTolerance) = tEnd;
t = (0:displayIntervalCount)'*displayStepSec;
if appendEnd
    t(end+1,1) = tEnd;
else
    t(end) = tEnd;
end
switchTimes = sampleTimes+computationDelaySec;
switchTimes = switchTimes(switchTimes <= tEnd+timeTolerance);
switchTimes(switchTimes > tEnd) = tEnd;
t = mergeEventTimes(t,[sampleTimes; switchTimes],timeTolerance);
displaySampleCount = numel(t);
if displaySampleCount > maxDisplaySamples
    error('P10:TooManyDisplaySamples', ...
        'Requested %d display samples after retaining timing events; maximum is %d.', ...
        displaySampleCount,maxDisplaySamples);
end

proportionalGain = 8;
plantTimeConstantSec = 1;
reference = 1;
equilibriumOutput = proportionalGain/(1+proportionalGain);
continuousClosedLoopRatePerSec = (1+proportionalGain)/plantTimeConstantSec;
continuousClosedLoopBandwidthRadPerSec = continuousClosedLoopRatePerSec;

oldCommandDecay = exp(-computationDelaySec/plantTimeConstantSec);
newCommandDurationSec = samplePeriodSec-computationDelaySec;
newCommandDecay = exp(-newCommandDurationSec/plantTimeConstantSec);
plantDecay = exp(-samplePeriodSec/plantTimeConstantSec);
previousCommandWeight = newCommandDecay*(1-oldCommandDecay);
newCommandWeight = 1-newCommandDecay;

% For deviations from equilibrium, x=[y-yEq; uPrevious-yEq].
stateA11 = plantDecay-newCommandWeight*proportionalGain;
stateA12 = previousCommandWeight;
stateMatrix = [stateA11 stateA12; -proportionalGain 0];
poleTrace = stateA11;
poleDeterminant = previousCommandWeight*proportionalGain;
poleDiscriminant = poleTrace^2-4*poleDeterminant;
closedLoopPoles = [ ...
    (poleTrace+sqrt(complex(poleDiscriminant)))/2; ...
    (poleTrace-sqrt(complex(poleDiscriminant)))/2];
spectralRadius = max(abs(closedLoopPoles));

outputSamples = zeros(controllerSampleCount,1);
computedCommandSamples = zeros(controllerSampleCount,1);
previousCommandSamples = zeros(controllerSampleCount,1);
previousCommand = 0;
responseLimit = 1000;
for k = 1:controllerSampleCount
    previousCommandSamples(k) = previousCommand;
    computedCommandSamples(k) = proportionalGain*( ...
        reference-outputSamples(k));
    if ~isfinite(computedCommandSamples(k)) || ...
            abs(computedCommandSamples(k)) > responseLimit
        error('P10:ResponseBound', ...
            'The requested computed command exceeds the bounded learning view.');
    end
    if k < controllerSampleCount
        outputSamples(k+1) = plantDecay*outputSamples(k)+ ...
            previousCommandWeight*previousCommand+ ...
            newCommandWeight*computedCommandSamples(k);
        if ~isfinite(outputSamples(k+1)) || ...
                abs(outputSamples(k+1)) > responseLimit
            error('P10:ResponseBound', ...
                'The requested plant response exceeds the bounded learning view.');
        end
    end
    previousCommand = computedCommandSamples(k);
end

sampledOutput = zeros(displaySampleCount,1);
appliedCommand = zeros(displaySampleCount,1);
computedCommand = zeros(displaySampleCount,1);
for k = 1:controllerSampleCount
    if k < controllerSampleCount
        active = t >= sampleTimes(k) & t < sampleTimes(k+1);
    else
        active = t >= sampleTimes(k);
    end
    elapsed = t(active)-sampleTimes(k);
    computedCommand(active) = computedCommandSamples(k);
    oldCommandActive = elapsed < computationDelaySec-timeTolerance;
    oldElapsed = elapsed(oldCommandActive);
    appliedCommand(active) = computedCommandSamples(k);
    activeIndices = find(active);
    oldIndices = activeIndices(oldCommandActive);
    appliedCommand(oldIndices) = previousCommandSamples(k);
    sampledOutput(oldIndices) = previousCommandSamples(k)+( ...
        outputSamples(k)-previousCommandSamples(k)).* ...
        exp(-oldElapsed/plantTimeConstantSec);

    newCommandActive = ~oldCommandActive;
    newElapsed = elapsed(newCommandActive)-computationDelaySec;
    switchOutput = previousCommandSamples(k)+( ...
        outputSamples(k)-previousCommandSamples(k))*oldCommandDecay;
    newIndices = activeIndices(newCommandActive);
    sampledOutput(newIndices) = computedCommandSamples(k)+( ...
        switchOutput-computedCommandSamples(k)).* ...
        exp(-newElapsed/plantTimeConstantSec);
end

continuousOutput = equilibriumOutput*( ...
    1-exp(-continuousClosedLoopRatePerSec*t));
continuousCommand = proportionalGain*(reference-continuousOutput);
trackingGap = sampledOutput-continuousOutput;
equilibriumDeviation = sampledOutput-equilibriumOutput;
outsideSettlingBand = find(abs(equilibriumDeviation) > ...
    0.02*abs(equilibriumOutput));
if isempty(outsideSettlingBand)
    settlingTimeSec = 0;
elseif outsideSettlingBand(end) == displaySampleCount
    settlingTimeSec = NaN;
else
    settlingTimeSec = t(outsideSettlingBand(end)+1);
end

sampleRateHz = 1/samplePeriodSec;
closedLoopBandwidthHz = continuousClosedLoopBandwidthRadPerSec/(2*pi);
nyquistRatio = sampleRateHz/(2*closedLoopBandwidthHz);
delayFraction = computationDelaySec/samplePeriodSec;
delayPhaseAtBandwidthDeg = 180/pi* ...
    continuousClosedLoopBandwidthRadPerSec*computationDelaySec;

out = struct( ...
    't',t, ...
    'reference',reference*ones(displaySampleCount,1), ...
    'sampledOutput',sampledOutput, ...
    'continuousOutput',continuousOutput, ...
    'appliedCommand',appliedCommand, ...
    'computedCommand',computedCommand, ...
    'continuousCommand',continuousCommand, ...
    'trackingGap',trackingGap, ...
    'sampleTimes',sampleTimes, ...
    'outputSamples',outputSamples, ...
    'computedCommandSamples',computedCommandSamples, ...
    'previousCommandSamples',previousCommandSamples, ...
    'samplePeriodSec',samplePeriodSec, ...
    'computationDelaySec',computationDelaySec, ...
    'delayFraction',delayFraction, ...
    'sampleRateHz',sampleRateHz, ...
    'proportionalGain',proportionalGain, ...
    'plantTimeConstantSec',plantTimeConstantSec, ...
    'equilibriumOutput',equilibriumOutput, ...
    'continuousClosedLoopRatePerSec',continuousClosedLoopRatePerSec, ...
    'continuousClosedLoopBandwidthRadPerSec', ...
    continuousClosedLoopBandwidthRadPerSec, ...
    'closedLoopBandwidthHz',closedLoopBandwidthHz, ...
    'nyquistRatio',nyquistRatio, ...
    'delayPhaseAtBandwidthDeg',delayPhaseAtBandwidthDeg, ...
    'oldCommandDecay',oldCommandDecay, ...
    'newCommandDecay',newCommandDecay, ...
    'plantDecay',plantDecay, ...
    'previousCommandWeight',previousCommandWeight, ...
    'newCommandWeight',newCommandWeight, ...
    'stateMatrix',stateMatrix, ...
    'poleTrace',poleTrace, ...
    'poleDeterminant',poleDeterminant, ...
    'poleDiscriminant',poleDiscriminant, ...
    'closedLoopPoles',closedLoopPoles, ...
    'spectralRadius',spectralRadius, ...
    'isStable',spectralRadius < 1, ...
    'maximumAbsTrackingGap',max(abs(trackingGap)), ...
    'rmsTrackingGap',sqrt(mean(trackingGap.^2)), ...
    'overshootPercent',100*max(0,max(sampledOutput)- ...
    equilibriumOutput)/equilibriumOutput, ...
    'finalEquilibriumDeviation',equilibriumDeviation(end), ...
    'settlingTimeSec',settlingTimeSec, ...
    'maximumAbsComputedCommand',max(abs(computedCommandSamples)), ...
    'controllerSampleCount',controllerSampleCount, ...
    'displaySampleCount',displaySampleCount, ...
    'maxControllerSamples',maxControllerSamples, ...
    'maxDisplaySamples',maxDisplaySamples, ...
    'responseLimit',responseLimit);
end

function mergedTimes = mergeEventTimes(regularTimes,eventTimes,timeTolerance)
% Keep exact controller events when a regular-grid point differs only by rounding.
candidateTimes = [regularTimes; eventTimes];
isEvent = [false(size(regularTimes)); true(size(eventTimes))];
[candidateTimes,order] = sort(candidateTimes);
isEvent = isEvent(order);
mergedTimes = zeros(size(candidateTimes));
mergedCount = 0;
candidateIndex = 1;
while candidateIndex <= numel(candidateTimes)
    clusterEnd = candidateIndex;
    while clusterEnd < numel(candidateTimes) && ...
            candidateTimes(clusterEnd+1)-candidateTimes(candidateIndex) <= ...
            timeTolerance
        clusterEnd = clusterEnd+1;
    end
    eventOffset = find(isEvent(candidateIndex:clusterEnd),1,'last');
    if isempty(eventOffset)
        selectedIndex = candidateIndex;
    else
        selectedIndex = candidateIndex+eventOffset-1;
    end
    mergedCount = mergedCount+1;
    mergedTimes(mergedCount) = candidateTimes(selectedIndex);
    candidateIndex = clusterEnd+1;
end
mergedTimes = mergedTimes(1:mergedCount);
end
