function run_checks
%RUN_CHECKS Independent timing identities, limits, failure, and recovery.
tolerance = 5e-12;

baselineA = model(0.05,0.01,4,0.005);
baselineB = model(0.05,0.01,4,0.005);
assert(isequaln(baselineA,baselineB), ...
    'Identical timing inputs must produce identical trajectories and metrics.');
assert(baselineA.proportionalGain == 8 && ...
    baselineA.plantTimeConstantSec == 1 && ...
    abs(baselineA.equilibriumOutput-8/9) < tolerance, ...
    'The plant, gain, and proportional equilibrium must remain fixed.');

expectedPlantDecay = exp(-0.05);
expectedOldDecay = exp(-0.01);
expectedNewDecay = exp(-0.04);
expectedPreviousWeight = expectedNewDecay*(1-expectedOldDecay);
expectedNewWeight = 1-expectedNewDecay;
assert(abs(baselineA.plantDecay-expectedPlantDecay) < tolerance && ...
    abs(baselineA.previousCommandWeight-expectedPreviousWeight) < tolerance && ...
    abs(baselineA.newCommandWeight-expectedNewWeight) < tolerance, ...
    'The two exact constant-command pieces must match independent exponentials.');
assert(abs(baselineA.plantDecay+baselineA.previousCommandWeight+ ...
    baselineA.newCommandWeight-1) < tolerance, ...
    'Plant, stale-command, and new-command weights must sum to one.');

sampleTransitionResidual = baselineA.outputSamples(2:end)-( ...
    baselineA.plantDecay*baselineA.outputSamples(1:end-1)+ ...
    baselineA.previousCommandWeight* ...
    baselineA.previousCommandSamples(1:end-1)+ ...
    baselineA.newCommandWeight* ...
    baselineA.computedCommandSamples(1:end-1));
assert(max(abs(sampleTransitionResidual)) < tolerance, ...
    'Every sample must satisfy the exact delayed-command plant transition.');
assert(max(abs(baselineA.computedCommandSamples-( ...
    8*(1-baselineA.outputSamples)))) < tolerance, ...
    'Every computed command must expose the proportional feedback law.');
assert(baselineA.previousCommandSamples(1) == 0 && ...
    max(abs(baselineA.previousCommandSamples(2:end)- ...
    baselineA.computedCommandSamples(1:end-1))) < tolerance, ...
    'The previous-command state must shift by exactly one controller update.');

displayedAtSamples = baselineA.sampledOutput(1:10:end);
assert(numel(displayedAtSamples) == numel(baselineA.outputSamples) && ...
    max(abs(displayedAtSamples-baselineA.outputSamples)) < tolerance, ...
    'The intersample reconstruction must meet every controller sample state.');
assert(all(baselineA.appliedCommand(1:2) == 0) && ...
    all(baselineA.computedCommand(1:2) == 8) && ...
    baselineA.appliedCommand(3) == 8, ...
    'The initial old command must persist until the exact delay switch.');
expectedPostSwitchOutput = 8*(1-exp(-0.005));
assert(baselineA.sampledOutput(3) == 0 && ...
    baselineA.appliedCommand(4) == 8 && ...
    abs(baselineA.sampledOutput(4)-expectedPostSwitchOutput) < tolerance, ...
    'Post-delay motion must begin at the switch and follow the exact new command.');

offGridTiming = model(0.033,0.011,0.08,0.01);
firstSwitchTime = offGridTiming.sampleTimes(1)+ ...
    offGridTiming.computationDelaySec;
secondSampleTime = offGridTiming.sampleTimes(2);
secondSwitchTime = secondSampleTime+offGridTiming.computationDelaySec;
firstSwitchIndex = find(offGridTiming.t == firstSwitchTime,1);
secondSampleIndex = find(offGridTiming.t == secondSampleTime,1);
secondSwitchIndex = find(offGridTiming.t == secondSwitchTime,1);
assert(~isempty(firstSwitchIndex) && ~isempty(secondSampleIndex) && ...
    ~isempty(secondSwitchIndex) && offGridTiming.displaySampleCount > 9, ...
    'Noncommensurate display grids must retain exact sample and delay-switch events.');
assert(offGridTiming.appliedCommand(firstSwitchIndex) == ...
    offGridTiming.computedCommandSamples(1) && ...
    offGridTiming.sampledOutput(firstSwitchIndex) == 0 && ...
    offGridTiming.sampledOutput(secondSampleIndex) == ...
    offGridTiming.outputSamples(2) && ...
    offGridTiming.computedCommand(secondSampleIndex) == ...
    offGridTiming.computedCommandSamples(2), ...
    'The first off-grid switch and next sample must expose their exact behavior.');
expectedSecondSwitchOutput = offGridTiming.previousCommandSamples(2)+( ...
    offGridTiming.outputSamples(2)-offGridTiming.previousCommandSamples(2))* ...
    exp(-offGridTiming.computationDelaySec);
assert(offGridTiming.appliedCommand(secondSwitchIndex) == ...
    offGridTiming.computedCommandSamples(2) && ...
    abs(offGridTiming.sampledOutput(secondSwitchIndex)- ...
    expectedSecondSwitchOutput) < tolerance, ...
    'The second off-grid delay event must switch command without moving the plant discontinuously.');

expectedA11 = expectedPlantDecay-8*expectedNewWeight;
expectedMatrix = [expectedA11 expectedPreviousWeight; -8 0];
assert(max(abs(baselineA.stateMatrix(:)-expectedMatrix(:))) < tolerance, ...
    'The explicit delayed-feedback state matrix must match direct expansion.');
poleResidual = baselineA.closedLoopPoles.^2- ...
    baselineA.poleTrace*baselineA.closedLoopPoles+ ...
    baselineA.poleDeterminant;
assert(max(abs(poleResidual)) < 1e-13 && ...
    abs(baselineA.spectralRadius-0.477315111987621) < 1e-12 && ...
    baselineA.isStable, ...
    'Reported poles must satisfy the independently expanded characteristic.');
assert(abs(baselineA.nyquistRatio-20*pi/9) < tolerance && ...
    abs(baselineA.delayPhaseAtBandwidthDeg- ...
    0.09*180/pi) < tolerance, ...
    'Sampling ratio and delay phase must retain their declared units.');

fineSampling = model(0.02,0,3,0.005);
mediumSampling = model(0.1,0,3,0.005);
coarseSampling = model(0.2,0,3,0.005);
assert(fineSampling.maximumAbsTrackingGap < ...
    mediumSampling.maximumAbsTrackingGap && ...
    mediumSampling.maximumAbsTrackingGap < ...
    coarseSampling.maximumAbsTrackingGap, ...
    'Moving only Ts upward must increase continuous-target gap.');
assert(fineSampling.sampleRateHz > mediumSampling.sampleRateHz && ...
    mediumSampling.sampleRateHz > coarseSampling.sampleRateHz && ...
    fineSampling.computationDelaySec == 0 && ...
    coarseSampling.computationDelaySec == 0, ...
    'The sample-period sweep must preserve zero delay while reducing sample rate.');

shortDelay = model(0.1,0.02,4,0.005);
mediumDelay = model(0.1,0.06,4,0.005);
fullDelay = model(0.1,0.1,4,0.005);
assert(shortDelay.previousCommandWeight < ...
    mediumDelay.previousCommandWeight && ...
    mediumDelay.previousCommandWeight < ...
    fullDelay.previousCommandWeight, ...
    'Moving only Td upward must increase stale-command weight.');
assert(shortDelay.spectralRadius < mediumDelay.spectralRadius && ...
    mediumDelay.spectralRadius < fullDelay.spectralRadius && ...
    shortDelay.samplePeriodSec == fullDelay.samplePeriodSec && ...
    shortDelay.sampleRateHz == fullDelay.sampleRateHz, ...
    'The delay sweep must isolate a visible loss of pole reserve.');
assert(shortDelay.overshootPercent < mediumDelay.overshootPercent && ...
    mediumDelay.overshootPercent < fullDelay.overshootPercent, ...
    'More delay at fixed Ts must increase overshoot in the declared sweep.');

zeroDelay = model(0.05,0,2,0.005);
oneSampleDelay = model(0.05,0.05,2,0.005);
assert(zeroDelay.previousCommandWeight == 0 && ...
    abs(zeroDelay.newCommandWeight-(1-exp(-0.05))) < tolerance, ...
    'Td=0 must apply the new command for the whole interval.');
assert(oneSampleDelay.newCommandWeight == 0 && ...
    abs(oneSampleDelay.previousCommandWeight-(1-exp(-0.05))) < tolerance && ...
    oneSampleDelay.outputSamples(2) == 0, ...
    'Td=Ts must apply only the previous command for the whole interval.');
smallTiming = model(0.005,0,2,0.005);
assert(smallTiming.maximumAbsTrackingGap < ...
    zeroDelay.maximumAbsTrackingGap && ...
    abs(smallTiming.sampledOutput(end)-8/9) < 1e-7, ...
    'As zero-delay sampling becomes fine, the model must approach the continuous target.');

broken = model(0.2,0.18,3,0.005);
recovered = model(0.2,0.02,3,0.005);
assert(broken.nyquistRatio > 1.7 && ...
    broken.spectralRadius > 1.13 && ~broken.isStable && ...
    abs(broken.finalEquilibriumDeviation) > 6, ...
    'Long sampling plus near-one-sample delay must fail despite Nyquist ratio above one.');
assert(recovered.spectralRadius < 0.37 && recovered.isStable && ...
    abs(recovered.finalEquilibriumDeviation) < 1e-5, ...
    'Reducing delay must restore pole reserve and convergence.');
assert(broken.samplePeriodSec == recovered.samplePeriodSec && ...
    broken.proportionalGain == recovered.proportionalGain && ...
    broken.plantTimeConstantSec == recovered.plantTimeConstantSec, ...
    'Recovery must change only computation delay.');

subDelayHorizon = model(0.05,0.01,0.007,0.001);
assert(subDelayHorizon.controllerSampleCount == 1 && ...
    all(subDelayHorizon.appliedCommand == 0) && ...
    all(subDelayHorizon.sampledOutput == 0), ...
    'A horizon shorter than Td must retain only the initial actuator command.');
nonIntegerGrid = model(0.03,0.01,0.097,0.005);
assert(nonIntegerGrid.sampleTimes(end) == 0.09 && ...
    nonIntegerGrid.t(end) == 0.097 && all(diff(nonIntegerGrid.t) > 0), ...
    'A noninteger horizon must append one exact, strictly increasing endpoint.');
lastDelayElapsedSec = nonIntegerGrid.t(end)- ...
    nonIntegerGrid.sampleTimes(end);
expectedFinalDelayedOutput = nonIntegerGrid.previousCommandSamples(end)+( ...
    nonIntegerGrid.outputSamples(end)- ...
    nonIntegerGrid.previousCommandSamples(end))* ...
    exp(-lastDelayElapsedSec/nonIntegerGrid.plantTimeConstantSec);
assert(nonIntegerGrid.appliedCommand(end) == ...
    nonIntegerGrid.previousCommandSamples(end) && ...
    abs(nonIntegerGrid.sampledOutput(end)- ...
    expectedFinalDelayedOutput) < tolerance, ...
    'The final partial delay must retain the previous command exactly.');

assertAnyError(@() model(NaN,0.01,4,0.005), ...
    'A nonfinite sample period must be rejected.');
assertAnyError(@() model(0.05,Inf,4,0.005), ...
    'A nonfinite delay must be rejected.');
assertAnyError(@() model(0.05,0.01,4,[0.005 0.01]), ...
    'A nonscalar display interval must be rejected.');
assertAnyError(@() model(0.05,-0.01,4,0.005), ...
    'A negative computation delay must be rejected.');
assertErrorId(@() model(0.05,0.051,4,0.005), ...
    'P10:DelayRange','A delay longer than Ts must be rejected explicitly.');
assertErrorId(@() model(0.51,0.01,4,0.005), ...
    'P10:SamplePeriodRange','An excessive sample period must be rejected.');
assertErrorId(@() model(0.05,0.01,30.1,0.005), ...
    'P10:HorizonRange','An excessive horizon must be rejected.');
assertErrorId(@() model(0.05,0.01,4,0.051), ...
    'P10:DisplayResolution','An under-resolved display request must be rejected.');
assertErrorId(@() model(0.0029,0,30,0.0029), ...
    'P10:TooManyControllerSamples','An excessive controller grid must be rejected.');
assertErrorId(@() model(1e-12,0,30,1e-12), ...
    'P10:TooManyControllerSamples', ...
    'A tiny Ts must be rejected before allocating the controller grid.');
assertErrorId(@() model(0.01,0,30,0.0009), ...
    'P10:TooManyDisplaySamples','An excessive display grid must be rejected.');
assertErrorId(@() model(0.01,0,30,1e-12), ...
    'P10:TooManyDisplaySamples', ...
    'A tiny display step must be rejected before allocating the display grid.');
assertErrorId(@() model(0.0031,0.0007,30,0.0011), ...
    'P10:TooManyDisplaySamples', ...
    'Exact sample and switch events must remain inside the final display cap.');
assertErrorId(@() model(0.5,0.5,5,0.005), ...
    'P10:ResponseBound','A divergent response must remain bounded.');

atControllerLimit = model(0.003,0,30,0.003);
assert(atControllerLimit.controllerSampleCount == 10001 && ...
    all(isfinite(atControllerLimit.sampledOutput)), ...
    'The declared maximum controller grid must remain accepted.');
atDisplayLimit = model(0.01,0,30,0.001);
assert(atDisplayLimit.displaySampleCount == 30001 && ...
    all(isfinite(atDisplayLimit.sampledOutput)), ...
    'The declared maximum display grid must remain accepted.');

disp(['P10 checks passed: exact command timing, independent levers, limits, ' ...
    'combined failure, same-Ts recovery, and resource bounds.']);
end

function assertAnyError(operation,message)
didError = false;
try
    operation();
catch
    didError = true;
end
assert(didError,message);
end

function assertErrorId(operation,expectedIdentifier,message)
actualIdentifier = '';
try
    operation();
catch exception
    actualIdentifier = exception.identifier;
end
assert(strcmp(actualIdentifier,expectedIdentifier),message);
end
