function run_checks
%RUN_CHECKS Independent pendulum invariants, limits, failures, and recovery.
tolerance = 2e-10;

baselineA = model(20,0,1,0.02,12,0.01);
baselineB = model(20,0,1,0.02,12,0.01);
assert(isequaln(baselineA,baselineB), ...
    'Identical inputs must produce identical deterministic outputs.');
assert(abs(baselineA.linearAngleDeg(1)-20) < tolerance && ...
    abs(baselineA.nonlinearAngleDeg(1)-20) < tolerance && ...
    abs(baselineA.linearRateRadPerSec(1)) < tolerance && ...
    abs(baselineA.nonlinearRateRadPerSec(1)) < tolerance, ...
    'Both models must preserve the shared release state.');

expectedNaturalFrequency = sqrt(9.81);
expectedSmallAnglePeriod = 2*pi/expectedNaturalFrequency;
assert(abs(baselineA.naturalFrequencyRadPerSec-expectedNaturalFrequency) < tolerance, ...
    'A one-metre pendulum must report wn=sqrt(g/L).');
assert(abs(baselineA.smallAnglePeriodSec-expectedSmallAnglePeriod) < tolerance, ...
    'The small-angle period must independently equal 2*pi*sqrt(L/g).');
poleResidual = baselineA.linearPolesPerSec.^2 + ...
    2*baselineA.dampingRatio*baselineA.naturalFrequencyRadPerSec* ...
    baselineA.linearPolesPerSec + baselineA.naturalFrequencyRadPerSec^2;
assert(max(abs(poleResidual)) < tolerance, ...
    'Reported linear poles must satisfy the P03 characteristic equation.');

initialAngleRad = 20*pi/180;
expectedLinearAcceleration = -9.81*initialAngleRad;
expectedNonlinearAcceleration = -9.81*sin(initialAngleRad);
assert(abs(baselineA.initialLinearAccelerationRadPerSec2- ...
    expectedLinearAcceleration) < tolerance, ...
    'Linear initial acceleration must use -(g/L)*theta.');
assert(abs(baselineA.initialNonlinearAccelerationRadPerSec2- ...
    expectedNonlinearAcceleration) < tolerance, ...
    'Nonlinear initial acceleration must use -(g/L)*sin(theta).');
assert(abs(expectedNonlinearAcceleration) < abs(expectedLinearAcceleration), ...
    'At nonzero release angle the nonlinear restoring magnitude must be weaker.');
assert(baselineA.nonlinearFirstZeroSec > baselineA.linearFirstZeroSec, ...
    'The weaker nonlinear restoring term must delay the first zero crossing.');
assert(all(diff(baselineA.linearSpecificEnergyJPerKg) <= 1e-8) && ...
    all(diff(baselineA.nonlinearSpecificEnergyJPerKg) <= 1e-8), ...
    'Positive damping must not create specific mechanical energy.');

smallRelease = model(5,0,1,0.02,12,0.01);
largeRelease = model(90,0,1,0.02,12,0.01);
assert(largeRelease.maxAbsErrorDeg > 20*smallRelease.maxAbsErrorDeg, ...
    'Moving only release angle outward must amplify model disagreement.');
assert(abs(largeRelease.smallAnglePeriodSec-smallRelease.smallAnglePeriodSec) < tolerance, ...
    'Changing only release angle must preserve the linear period scale.');

shortPendulum = model(20,0,0.5,0.02,12,0.01);
longPendulum = model(20,0,2,0.02,12,0.01);
assert(abs(longPendulum.smallAnglePeriodSec/shortPendulum.smallAnglePeriodSec-2) < tolerance, ...
    'Quadrupling length must double the small-angle period.');
assert(longPendulum.nonlinearFirstZeroSec > shortPendulum.nonlinearFirstZeroSec, ...
    'Moving only length upward must delay nonlinear motion.');
assert(abs(longPendulum.initialAngleDeg-shortPendulum.initialAngleDeg) < tolerance, ...
    'The length sweep must preserve release angle.');

tiny = model(0.01,0,1,0,4,0.002);
assert(tiny.maxAbsErrorDeg < 1e-7, ...
    'The linear and nonlinear models must agree in the tiny-angle limit.');
microscopic = model(1e-14,0,1,0,1,0.001);
assert(isfinite(microscopic.linearFirstZeroSec) && ...
    isfinite(microscopic.nonlinearFirstZeroSec), ...
    'Every accepted nonzero release must retain a measurable first crossing.');
zeroState = model(0,0,1,0.02,4,0.01);
assert(all(zeroState.linearAngleRad == 0) && ...
    all(zeroState.nonlinearAngleRad == 0) && ...
    isnan(zeroState.linearFirstZeroSec) && ...
    isnan(zeroState.nonlinearFirstZeroSec), ...
    'A zero release state must remain at equilibrium in both models.');
positiveState = model(30,15,1,0.02,4,0.01);
negativeState = model(-30,-15,1,0.02,4,0.01);
assert(max(abs(positiveState.linearAngleRad+negativeState.linearAngleRad)) < tolerance && ...
    max(abs(positiveState.nonlinearAngleRad+negativeState.nonlinearAngleRad)) < tolerance, ...
    'Both odd restoring laws must preserve sign symmetry.');
rateCase = model(0,30,1,0.1,1,0.005);
expectedInitialRate = pi/6;
expectedDampingAcceleration = -2*0.1*sqrt(9.81)*expectedInitialRate;
assert(abs(rateCase.linearRateRadPerSec(1)-expectedInitialRate) < tolerance && ...
    abs(rateCase.nonlinearRateRadPerSec(1)-expectedInitialRate) < tolerance, ...
    'Both models must preserve a nonzero initial angular rate.');
assert(abs(rateCase.initialLinearAccelerationRadPerSec2- ...
    expectedDampingAcceleration) < tolerance && ...
    abs(rateCase.initialNonlinearAccelerationRadPerSec2- ...
    expectedDampingAcceleration) < tolerance, ...
    'At zero angle both models must retain the same damping acceleration.');
velocityDriven = model(0,30,9.81,0,pi/2,pi/4000);
expectedQuarterAngle = pi/6;
assert(abs(velocityDriven.linearAngleRad(end)-expectedQuarterAngle) < tolerance && ...
    abs(velocityDriven.linearRateRadPerSec(end)) < tolerance, ...
    'A nonzero initial rate must propagate to the exact undamped quarter-cycle state.');
rateDriven = model(0,720,1,0.02,1,0.005);
simulatedAngleLimit = max([abs(rateDriven.linearAngleRad); ...
    abs(rateDriven.nonlinearAngleRad)]);
assert(max(abs(rateDriven.restoringAngleRad)) >= simulatedAngleLimit, ...
    'The restoring-law view must cover angular-rate-driven excursion.');

undamped = model(60,0,1,0,8,0.002);
assert(max(abs(undamped.linearSpecificEnergyJPerKg- ...
    undamped.linearSpecificEnergyJPerKg(1))) < 1e-8, ...
    'The undamped linear calculation must conserve quadratic specific energy.');
assert(max(abs(undamped.nonlinearSpecificEnergyJPerKg- ...
    undamped.nonlinearSpecificEnergyJPerKg(1))) < 1e-8, ...
    'The undamped nonlinear calculation must conserve physical specific energy.');
boundaryLengthM = 9.81*(0.01/0.074)^2;
acceptedResolution = model(5,0,boundaryLengthM,0,10,0.01);
expectedQuarterPeriod = pi/(2*acceptedResolution.naturalFrequencyRadPerSec);
assert(abs(acceptedResolution.linearFirstZeroSec-expectedQuarterPeriod) < 1e-5, ...
    'The accepted resolution boundary must retain linear quarter-period timing.');
assert(max(abs(acceptedResolution.linearSpecificEnergyJPerKg- ...
    acceptedResolution.linearSpecificEnergyJPerKg(1))) < 1e-6, ...
    'The accepted resolution boundary must bound artificial linear energy loss.');

broken = model(120,0,1,0.02,12,0.01);
recovered = model(5,0,1,0.02,12,0.01);
assert(broken.nonlinearZeroDelayPercent > 10 && broken.maxAbsErrorDeg > 60, ...
    'The 120-degree broken use must show delayed nonlinear motion and large error.');
assert(recovered.nonlinearZeroDelayPercent < 0.2 && ...
    recovered.maxAbsErrorDeg < 0.25, ...
    'Reducing release angle to five degrees must recover close agreement.');

assertAnyError(@() model(NaN,0,1,0.02,12,0.01), ...
    'A nonfinite release angle must be rejected.');
assertAnyError(@() model(20,Inf,1,0.02,12,0.01), ...
    'A nonfinite release rate must be rejected.');
assertAnyError(@() model(20,0,1+1i,0.02,12,0.01), ...
    'A nonreal length must be rejected.');
assertAnyError(@() model(20,0,1,-0.1,12,0.01), ...
    'A negative damping ratio must be rejected.');
assertAnyError(@() model([10 20],0,1,0.02,12,0.01), ...
    'A nonscalar release angle must be rejected.');
assertAnyError(@() model(20,0,1,0.02,0,0.01), ...
    'A nonpositive duration must be rejected.');
assertAnyError(@() model(20,0,1,0.02,12,0), ...
    'A nonpositive interval must be rejected.');
assertErrorId(@() model(180,0,1,0.02,12,0.01), ...
    'P04:InitialAngleRange','The ambiguous upright release must be rejected.');
assertErrorId(@() model(20,721,1,0.02,12,0.01), ...
    'P04:InitialRateRange','An excessive release rate must be rejected.');
assertErrorId(@() model(20,0,0.01,0.02,12,0.001), ...
    'P04:LengthRange','An out-of-contract length must be rejected.');
assertErrorId(@() model(20,0,1,2.1,12,0.01), ...
    'P04:DampingRange','An out-of-contract damping ratio must be rejected.');
assertErrorId(@() model(20,0,0.05,0.02,1,0.02), ...
    'P04:TimeResolution','An under-resolved calculation must be rejected.');

nonIntegerGrid = model(20,0,1,0.02,0.033,0.011);
assert(nonIntegerGrid.sampleCount == 4 && ...
    all(diff(nonIntegerGrid.t) > 0) && nonIntegerGrid.t(end) == 0.033, ...
    'An integer interval ratio must not create a duplicate final timestamp.');
shortHorizon = model(20,0,1,0.02,0.02,2);
assert(shortHorizon.sampleCount == 2 && ...
    abs(shortHorizon.maxInterval-0.02) < tolerance, ...
    'A clipped endpoint interval must report the interval actually used.');
atResourceLimit = model(20,0,1,0.02,20,0.001);
assert(atResourceLimit.sampleCount == 20001, ...
    'The declared maximum calculation grid must remain accepted.');
assertErrorId(@() model(20,0,1,0.02,20.001,0.001), ...
    'P04:TooManySamples','An excessive calculation grid must be rejected.');

disp('P04 checks passed: model invariants, limits, levers, broken recovery, and bounds.');
end

function assertAnyError(operation,message)
didError = false;
try
    operation();
catch
    didError = true;
end
assert(didError,message);
end

function assertErrorId(operation,expectedIdentifier,message)
actualIdentifier = '';
try
    operation();
catch exception
    actualIdentifier = exception.identifier;
end
assert(strcmp(actualIdentifier,expectedIdentifier),message);
end
