function out = model(sensorGain,observationWindowSec,timeStepSec, ...
    measurePosition,initialPositionM,initialRateMPerSec)
%MODEL Expose two-state observability with exact sampled free response.
arguments
    sensorGain (1,1) double {mustBeReal,mustBeFinite,mustBeNonnegative} = 1
    observationWindowSec (1,1) double ...
        {mustBeReal,mustBeFinite,mustBePositive} = 2
    timeStepSec (1,1) double {mustBeReal,mustBeFinite,mustBePositive} = 0.05
    measurePosition (1,1) logical = true
    initialPositionM (1,1) double {mustBeReal,mustBeFinite} = 0.8
    initialRateMPerSec (1,1) double {mustBeReal,mustBeFinite} = 0.6
end

minimumNonzeroSensorGain = 0.05;
maximumSensorGain = 2;
minimumObservationWindowSec = 0.1;
maximumObservationWindowSec = 5;
maximumTimeStepSec = 0.1;
maximumStepCount = 5000;
if sensorGain > maximumSensorGain || ...
        (sensorGain > 0 && sensorGain < minimumNonzeroSensorGain)
    error('P14:SensorGainRange', ...
        'Sensor gain must be zero or between 0.05 and 2.');
end
if observationWindowSec < minimumObservationWindowSec || ...
        observationWindowSec > maximumObservationWindowSec
    error('P14:WindowRange', ...
        'Observation window must be between 0.1 and 5 s.');
end
if timeStepSec > maximumTimeStepSec
    error('P14:DisplayResolution', ...
        'The sample interval must not exceed 0.1 s.');
end
if initialPositionM < -2 || initialPositionM > 2
    error('P14:InitialPositionRange', ...
        'Initial position must be between -2 and 2 m.');
end
if initialRateMPerSec < -2 || initialRateMPerSec > 2
    error('P14:InitialRateRange', ...
        'Initial rate must be between -2 and 2 m/s.');
end
stepRatio = observationWindowSec/timeStepSec;
if isinf(stepRatio)
    error('P14:TooManySteps', ...
        'Requested grid exceeds the 5000-step resource bound.');
end
stepCount = round(stepRatio);
alignmentTolerance = 64*eps(max(1,abs(stepRatio)));
if abs(stepRatio-stepCount) > alignmentTolerance
    error('P14:GridAlignment', ...
        'Observation window must be an integer multiple of the sample interval.');
end
if stepCount > maximumStepCount
    error('P14:TooManySteps', ...
        'Requested grid exceeds the 5000-step resource bound.');
end

dampingPerSec = 0.5;
positionScaleM = 1;
rateScaleMPerSec = 1;
stateScaling = diag([1/positionScaleM 1/rateScaleMPerSec]);
continuousA = [0 1;0 -dampingPerSec];
if measurePosition
    continuousC = [sensorGain 0];
    sensorMode = 'Position measurement';
    positionSensitivity = sensorGain;
    rateSensitivity = 0;
else
    continuousC = [0 sensorGain];
    sensorMode = 'Rate-only measurement (broken)';
    positionSensitivity = 0;
    rateSensitivity = sensorGain;
end
continuousObservabilityMatrix = [continuousC;continuousC*continuousA];
continuousObservabilityDeterminant = ...
    continuousObservabilityMatrix(1,1)* ...
    continuousObservabilityMatrix(2,2)- ...
    continuousObservabilityMatrix(1,2)* ...
    continuousObservabilityMatrix(2,1);

decay = exp(-dampingPerSec*timeStepSec);
positionFromRate = (1-decay)/dampingPerSec;
discreteA = [1 positionFromRate;0 decay];
sampleCount = stepCount+1;
timeSec = (0:stepCount)*timeStepSec;
observationMatrix = zeros(sampleCount,2);
stateTransition = eye(2);
for k = 1:sampleCount
    observationMatrix(k,:) = continuousC*stateTransition;
    stateTransition = discreteA*stateTransition;
end
physicalStateFromScaledState = diag([positionScaleM rateScaleMPerSec]);
scaledObservationMatrix = observationMatrix*physicalStateFromScaledState;
gramian = scaledObservationMatrix.'*scaledObservationMatrix;
g11 = gramian(1,1);
g12 = gramian(1,2);
g22 = gramian(2,2);
gramianTrace = g11+g22;
gramianDeterminant = g11*g22-g12*g12;
eigenvalueSpread = hypot(g11-g22,2*g12);
lambdaMaximum = max(0,0.5*(gramianTrace+eigenvalueSpread));
lambdaMinimum = max(0,0.5*(gramianTrace-eigenvalueSpread));
singularValues = [sqrt(lambdaMaximum);sqrt(lambdaMinimum)];
rankTolerance = 128*eps(max(gramianTrace,1));
if lambdaMaximum <= rankTolerance
    observabilityRank = 0;
elseif lambdaMinimum <= rankTolerance
    observabilityRank = 1;
else
    observabilityRank = 2;
end
if singularValues(2) == 0
    observabilityConditionNumber = Inf;
    worstCaseStateErrorGain = Inf;
else
    observabilityConditionNumber = singularValues(1)/singularValues(2);
    worstCaseStateErrorGain = 1/singularValues(2);
end

initialPhysicalState = [initialPositionM;initialRateMPerSec];
initialScaledState = stateScaling*initialPhysicalState;
alternativeInitialPhysicalState = initialPhysicalState+[1;0];
alternativeInitialScaledState = stateScaling*alternativeInitialPhysicalState;
stateTrajectory = zeros(2,sampleCount);
alternativeStateTrajectory = zeros(2,sampleCount);
stateTrajectory(:,1) = initialPhysicalState;
alternativeStateTrajectory(:,1) = alternativeInitialPhysicalState;
for k = 1:stepCount
    stateTrajectory(:,k+1) = discreteA*stateTrajectory(:,k);
    alternativeStateTrajectory(:,k+1) = ...
        discreteA*alternativeStateTrajectory(:,k);
end
measurementHistory = observationMatrix*initialPhysicalState;
alternativeMeasurementHistory = ...
    observationMatrix*alternativeInitialPhysicalState;
measurementDifference = ...
    alternativeMeasurementHistory-measurementHistory;
outputDifferenceRmsSensorUnits = sqrt(mean(measurementDifference.^2));
peakOutputDifferenceSensorUnits = max(abs(measurementDifference));

if observabilityRank == 2
    informationVector = scaledObservationMatrix.'*measurementHistory;
    estimatedScaledInitialState = [ ...
        (g22*informationVector(1)-g12*informationVector(2))/ ...
        gramianDeterminant; ...
        (-g12*informationVector(1)+g11*informationVector(2))/ ...
        gramianDeterminant];
    estimatedInitialPhysicalState = ...
        physicalStateFromScaledState*estimatedScaledInitialState;
    reconstructedMeasurementHistory = ...
        scaledObservationMatrix*estimatedScaledInitialState;
    reconstructionResidualNorm = ...
        norm(measurementHistory-reconstructedMeasurementHistory);
    initialStateErrorNorm = norm(initialScaledState-estimatedScaledInitialState);
    initialStateUnique = true;
else
    informationVector = scaledObservationMatrix.'*measurementHistory;
    estimatedScaledInitialState = [NaN;NaN];
    estimatedInitialPhysicalState = [NaN;NaN];
    reconstructedMeasurementHistory = NaN(sampleCount,1);
    reconstructionResidualNorm = Inf;
    initialStateErrorNorm = Inf;
    initialStateUnique = false;
end

out = struct( ...
    'sensorGain',sensorGain, ...
    'sensorMode',sensorMode, ...
    'measurePosition',measurePosition, ...
    'positionSensitivitySensorUnitsPerM',positionSensitivity, ...
    'rateSensitivitySensorUnitsPerMPerSec',rateSensitivity, ...
    'observationWindowSec',observationWindowSec, ...
    'timeStepSec',timeStepSec, ...
    'dampingPerSec',dampingPerSec, ...
    'positionScaleM',positionScaleM, ...
    'rateScaleMPerSec',rateScaleMPerSec, ...
    'stateScaling',stateScaling, ...
    'continuousA',continuousA, ...
    'continuousC',continuousC, ...
    'continuousObservabilityMatrix',continuousObservabilityMatrix, ...
    'continuousObservabilityDeterminant', ...
    continuousObservabilityDeterminant, ...
    'discreteA',discreteA, ...
    'observationMatrix',observationMatrix, ...
    'scaledObservationMatrix',scaledObservationMatrix, ...
    'gramian',gramian, ...
    'gramianTrace',gramianTrace, ...
    'gramianDeterminant',gramianDeterminant, ...
    'singularValues',singularValues, ...
    'minimumSingularValue',singularValues(2), ...
    'observabilityConditionNumber',observabilityConditionNumber, ...
    'worstCaseStateErrorGain',worstCaseStateErrorGain, ...
    'rankTolerance',rankTolerance, ...
    'observabilityRank',observabilityRank, ...
    'initialStateUnique',initialStateUnique, ...
    'initialPhysicalState',initialPhysicalState, ...
    'initialScaledState',initialScaledState, ...
    'alternativeInitialPhysicalState',alternativeInitialPhysicalState, ...
    'alternativeInitialScaledState',alternativeInitialScaledState, ...
    'estimatedScaledInitialState',estimatedScaledInitialState, ...
    'estimatedInitialPhysicalState',estimatedInitialPhysicalState, ...
    'informationVector',informationVector, ...
    'stateTrajectory',stateTrajectory, ...
    'alternativeStateTrajectory',alternativeStateTrajectory, ...
    'measurementHistory',measurementHistory, ...
    'alternativeMeasurementHistory',alternativeMeasurementHistory, ...
    'measurementDifference',measurementDifference, ...
    'reconstructedMeasurementHistory',reconstructedMeasurementHistory, ...
    'reconstructionResidualNorm',reconstructionResidualNorm, ...
    'initialStateErrorNorm',initialStateErrorNorm, ...
    'outputDifferenceRmsSensorUnits',outputDifferenceRmsSensorUnits, ...
    'peakOutputDifferenceSensorUnits',peakOutputDifferenceSensorUnits, ...
    'timeSec',timeSec, ...
    'stepCount',stepCount, ...
    'sampleCount',sampleCount, ...
    'maximumStepCount',maximumStepCount);
end
