function run_checks
%RUN_CHECKS Independent observability identities, limits, and recovery.
tolerance = 5e-11;

baselineA = model(1,2,0.05,true);
baselineB = model(1,2,0.05,true);
expectedStateScaling = eye(2);
assert(isequaln(baselineA,baselineB), ...
    'Identical inputs must produce identical matrices, states, and outputs.');
assert(baselineA.dampingPerSec == 0.5 && ...
    baselineA.positionScaleM == 1 && ...
    baselineA.rateScaleMPerSec == 1 && ...
    max(abs(baselineA.stateScaling(:)-expectedStateScaling(:))) == 0 && ...
    max(abs(baselineA.initialPhysicalState-[0.8;0.6])) == 0, ...
    'The damping, normalized state scales, and initial state must stay explicit.');

expectedA = [0 1;0 -0.5];
expectedC = [1 0];
expectedContinuousRows = [expectedC;expectedC*expectedA];
assert(max(abs(baselineA.continuousA(:)-expectedA(:))) == 0 && ...
    max(abs(baselineA.continuousC-expectedC)) == 0 && ...
    max(abs(baselineA.continuousObservabilityMatrix(:)- ...
    expectedContinuousRows(:))) == 0 && ...
    baselineA.continuousObservabilityDeterminant == 1, ...
    'The direct measurement and its dynamically revealed direction must be visible.');

decay = exp(-0.5*0.05);
expectedAd = [1 2*(1-decay);0 decay];
assert(max(abs(baselineA.discreteA(:)-expectedAd(:))) < tolerance, ...
    'The exact free-response transition must match independent scalar formulas.');
for k = 1:baselineA.sampleCount
    propagationCount = k-1;
    expectedRow = [1 2*(1-decay^propagationCount)];
    assert(max(abs(baselineA.observationMatrix(k,:)-expectedRow)) < ...
        tolerance, ...
        'Every observation row must match the independent closed form.');
end
expectedGramian = baselineA.scaledObservationMatrix.'* ...
    baselineA.scaledObservationMatrix;
assert(max(abs(baselineA.gramian(:)-expectedGramian(:))) < tolerance && ...
    baselineA.gramianDeterminant > 0 && ...
    baselineA.minimumSingularValue > 0 && ...
    baselineA.observabilityRank == 2, ...
    'The baseline observation Gramian must span both scaled state directions.');

reconstructedHistory = baselineA.scaledObservationMatrix* ...
    baselineA.estimatedScaledInitialState;
assert(max(abs(reconstructedHistory-baselineA.measurementHistory)) < ...
    tolerance && baselineA.initialStateUnique && ...
    baselineA.initialStateErrorNorm < tolerance && ...
    baselineA.reconstructionResidualNorm < tolerance, ...
    'The transparent two-by-two solve must reconstruct the initial state.');
for k = 1:baselineA.stepCount
    expectedNextState = baselineA.discreteA*baselineA.stateTrajectory(:,k);
    assert(max(abs(baselineA.stateTrajectory(:,k+1)- ...
        expectedNextState)) < tolerance, ...
        'Every state sample must satisfy the exact free-response recurrence.');
end
assert(max(abs(baselineA.measurementHistory- ...
    baselineA.observationMatrix*baselineA.initialPhysicalState)) == 0 && ...
    abs(baselineA.outputDifferenceRmsSensorUnits-1) < tolerance && ...
    abs(baselineA.peakOutputDifferenceSensorUnits-1) < tolerance, ...
    'Baseline output history and candidate separation must stay deterministic.');
assert(abs(baselineA.minimumSingularValue-1.88730671843965) < 1e-11 && ...
    abs(baselineA.observabilityConditionNumber-4.27628908064157) < 1e-11 && ...
    abs(baselineA.worstCaseStateErrorGain-0.529855582152942) < 1e-11, ...
    'Baseline scaled observability metrics must stay deterministic.');

sensorGains = [0.25 0.5 1 1.5 2];
gainSingularValues = zeros(size(sensorGains));
gainSeparations = zeros(size(sensorGains));
gainInverseNoise = zeros(size(sensorGains));
for k = 1:numel(sensorGains)
    changed = model(sensorGains(k),2,0.05,true);
    gainSingularValues(k) = changed.minimumSingularValue;
    gainSeparations(k) = changed.outputDifferenceRmsSensorUnits;
    gainInverseNoise(k) = changed.worstCaseStateErrorGain;
    assert(changed.observabilityRank == 2 && ...
        changed.measurePosition && changed.observationWindowSec == 2 && ...
        changed.timeStepSec == 0.05, ...
        'The sensitivity sweep must preserve sensor path, time, and rank.');
    assert(abs(gainSingularValues(k)-sensorGains(k)* ...
        baselineA.minimumSingularValue) < tolerance && ...
        abs(gainSeparations(k)-sensorGains(k)) < tolerance && ...
        abs(gainInverseNoise(k)-baselineA.worstCaseStateErrorGain/ ...
        sensorGains(k)) < tolerance, ...
        'Sensitivity must scale observation, separation, and inverse gain independently.');
end
assert(all(diff(gainSingularValues) > 0) && ...
    all(diff(gainSeparations) > 0) && all(diff(gainInverseNoise) < 0), ...
    'More sensitivity must improve separation and reduce inverse noise gain.');

observationWindowsSec = [0.1 0.25 0.5 1 2 4];
windowSingularValues = zeros(size(observationWindowsSec));
windowInverseNoise = zeros(size(observationWindowsSec));
for k = 1:numel(observationWindowsSec)
    changed = model(1,observationWindowsSec(k),0.05,true);
    windowSingularValues(k) = changed.minimumSingularValue;
    windowInverseNoise(k) = changed.worstCaseStateErrorGain;
    assert(changed.sensorGain == 1 && changed.measurePosition && ...
        changed.dampingPerSec == 0.5 && changed.timeStepSec == 0.05 && ...
        max(abs(changed.initialPhysicalState-[0.8;0.6])) == 0 && ...
        changed.observabilityRank == 2, ...
        'The window sweep must preserve sensor, dynamics, interval, state, and rank.');
end
assert(all(diff(windowSingularValues) > 0) && ...
    all(diff(windowInverseNoise) < 0) && ...
    windowInverseNoise(1) > 8*windowInverseNoise(5), ...
    'A longer observation window must strengthen the weakest visible direction.');

broken = model(1,2,0.05,false);
recovered = model(1,2,0.05,true);
assert(broken.observabilityRank == 1 && ...
    ~broken.initialStateUnique && ...
    broken.continuousObservabilityDeterminant == 0 && ...
    broken.minimumSingularValue == 0 && ...
    isinf(broken.observabilityConditionNumber), ...
    'Rate-only measurement must hide exactly one initial-state direction.');
assert(max(abs(broken.measurementHistory- ...
    broken.alternativeMeasurementHistory)) == 0 && ...
    max(abs(broken.stateTrajectory(1,:)- ...
    broken.alternativeStateTrajectory(1,:)+1)) < tolerance && ...
    max(abs(broken.stateTrajectory(2,:)- ...
    broken.alternativeStateTrajectory(2,:))) == 0 && ...
    all(isnan(broken.estimatedInitialPhysicalState)) && ...
    isinf(broken.initialStateErrorNorm), ...
    'Broken outputs must be identical while the hidden position offset remains.');
assert(recovered.observabilityRank == 2 && ...
    recovered.initialStateUnique && ...
    recovered.outputDifferenceRmsSensorUnits == 1 && ...
    recovered.initialStateErrorNorm < tolerance, ...
    'Restoring position measurement must recover separation and reconstruction.');

noSensor = model(0,2,0.05,true);
assert(noSensor.observabilityRank == 0 && ...
    ~noSensor.initialStateUnique && ...
    max(abs(noSensor.measurementHistory)) == 0 && ...
    max(abs(noSensor.alternativeMeasurementHistory)) == 0, ...
    'Zero sensitivity must produce no information and rank zero.');
shortWindow = model(1,0.1,0.05,true);
assert(shortWindow.sampleCount == 3 && shortWindow.observabilityRank == 2 && ...
    shortWindow.minimumSingularValue < baselineA.minimumSingularValue, ...
    'The shortest accepted window must be full rank but weakly informative.');
zeroRate = model(1,2,0.05,true,0.8,0);
assert(max(abs(zeroRate.stateTrajectory(2,:))) == 0 && ...
    max(abs(zeroRate.stateTrajectory(1,:)-0.8)) == 0 && ...
    zeroRate.observabilityRank == 2 && zeroRate.initialStateErrorNorm < tolerance, ...
    'A zero-rate trajectory must remain constant without changing structural observability.');

assertAnyError(@() model(NaN,2,0.05,true), ...
    'A nonfinite sensor gain must be rejected.');
assertAnyError(@() model([1 2],2,0.05,true), ...
    'A nonscalar sensor gain must be rejected.');
assertAnyError(@() model(1+1i,2,0.05,true), ...
    'A complex sensor gain must be rejected.');
assertAnyError(@() model(1,2,0.05,'position'), ...
    'A malformed measurement selector must be rejected.');
assertErrorId(@() model(0.01,2,0.05,true), ...
    'P14:SensorGainRange','A misleading tiny sensor gain must be rejected.');
assertErrorId(@() model(2.1,2,0.05,true), ...
    'P14:SensorGainRange','Excessive sensor gain must be rejected.');
assertErrorId(@() model(1,0.09,0.05,true), ...
    'P14:WindowRange','A too-short observation window must be rejected.');
assertErrorId(@() model(1,5.1,0.05,true), ...
    'P14:WindowRange','An excessive observation window must be rejected.');
assertErrorId(@() model(1,2,0.11,true), ...
    'P14:DisplayResolution','An under-resolved sample interval must be rejected.');
assertErrorId(@() model(1,2,0.03,true), ...
    'P14:GridAlignment','A partial sample interval must be rejected.');
assertErrorId(@() model(1,2,0.05,true,-2.1,0.6), ...
    'P14:InitialPositionRange','An excessive negative position must be rejected.');
assertErrorId(@() model(1,2,0.05,true,0.8,2.1), ...
    'P14:InitialRateRange','An excessive rate must be rejected.');
assertErrorId(@() model(1,5,1e-6,true), ...
    'P14:TooManySteps','An oversized grid must be rejected before allocation.');
boundedGrid = model(1,5,0.001,true);
assert(boundedGrid.stepCount == 5000 && ...
    all(isfinite(boundedGrid.stateTrajectory(:))) && ...
    all(isfinite(boundedGrid.measurementHistory)) && ...
    boundedGrid.initialStateErrorNorm < tolerance, ...
    'The largest accepted grid must remain finite and reconstruct the state.');

disp(['P14 checks passed: exact observation rows, two isolated levers, ' ...
    'hidden position, recovery, malformed inputs, and bounds.']);
end

function assertAnyError(operation,message)
didError = false;
try
    operation();
catch
    didError = true;
end
assert(didError,message);
end

function assertErrorId(operation,expectedIdentifier,message)
actualIdentifier = '';
try
    operation();
catch exception
    actualIdentifier = exception.identifier;
end
assert(strcmp(actualIdentifier,expectedIdentifier),message);
end
