function out = model(observerPoleSpeedPerSec,interferenceAmplitudeM, ...
    sensorBiasM,commandAccelerationMPerSec2,simulationDurationSec, ...
    timeStepSec,initialEstimatePositionM,initialEstimateRateMPerSec)
%MODEL Simulate an exact sampled plant and a transparent state observer.
arguments
    observerPoleSpeedPerSec (1,1) double ...
        {mustBeReal,mustBeFinite,mustBePositive} = 2
    interferenceAmplitudeM (1,1) double ...
        {mustBeReal,mustBeFinite,mustBeNonnegative} = 0
    sensorBiasM (1,1) double {mustBeReal,mustBeFinite} = 0
    commandAccelerationMPerSec2 (1,1) double ...
        {mustBeReal,mustBeFinite,mustBeNonnegative} = 0.4
    simulationDurationSec (1,1) double ...
        {mustBeReal,mustBeFinite,mustBePositive} = 8
    timeStepSec (1,1) double ...
        {mustBeReal,mustBeFinite,mustBePositive} = 0.02
    initialEstimatePositionM (1,1) double ...
        {mustBeReal,mustBeFinite} = -0.4
    initialEstimateRateMPerSec (1,1) double ...
        {mustBeReal,mustBeFinite} = 0.4
end

minimumObserverPoleSpeedPerSec = 1;
maximumObserverPoleSpeedPerSec = 5;
maximumInterferenceAmplitudeM = 0.05;
maximumSensorBiasMagnitudeM = 0.25;
maximumCommandAccelerationMPerSec2 = 1;
minimumSimulationDurationSec = 2;
maximumSimulationDurationSec = 10;
maximumTimeStepSec = 0.05;
maximumStepCount = 5000;
if observerPoleSpeedPerSec < minimumObserverPoleSpeedPerSec || ...
        observerPoleSpeedPerSec > maximumObserverPoleSpeedPerSec
    error('P15:ObserverSpeedRange', ...
        'Observer pole speed must be between 1 and 5 1/s.');
end
if interferenceAmplitudeM > maximumInterferenceAmplitudeM
    error('P15:InterferenceRange', ...
        'Measurement interference amplitude must be between 0 and 0.05 m.');
end
if abs(sensorBiasM) > maximumSensorBiasMagnitudeM
    error('P15:SensorBiasRange', ...
        'Sensor bias magnitude must not exceed 0.25 m.');
end
if commandAccelerationMPerSec2 > maximumCommandAccelerationMPerSec2
    error('P15:CommandRange', ...
        'Command acceleration must be between 0 and 1 m/s^2.');
end
if simulationDurationSec < minimumSimulationDurationSec || ...
        simulationDurationSec > maximumSimulationDurationSec
    error('P15:DurationRange', ...
        'Simulation duration must be between 2 and 10 s.');
end
if timeStepSec > maximumTimeStepSec
    error('P15:DisplayResolution', ...
        'The sample interval must not exceed 0.05 s.');
end
if initialEstimatePositionM < -2 || initialEstimatePositionM > 2
    error('P15:InitialEstimatePositionRange', ...
        'Initial estimated position must be between -2 and 2 m.');
end
if initialEstimateRateMPerSec < -2 || initialEstimateRateMPerSec > 2
    error('P15:InitialEstimateRateRange', ...
        'Initial estimated rate must be between -2 and 2 m/s.');
end

stepRatio = simulationDurationSec/timeStepSec;
if isinf(stepRatio)
    error('P15:TooManySteps', ...
        'Requested grid exceeds the 5000-step resource bound.');
end
stepCount = round(stepRatio);
alignmentTolerance = 64*eps(max(1,abs(stepRatio)));
if abs(stepRatio-stepCount) > alignmentTolerance
    error('P15:GridAlignment', ...
        'Simulation duration must be an integer multiple of the sample interval.');
end
if stepCount > maximumStepCount
    error('P15:TooManySteps', ...
        'Requested grid exceeds the 5000-step resource bound.');
end

% The P14 plant is observable from position: p_dot=v, v_dot=-d*v+u.
dampingPerSec = 0.5;
continuousA = [0 1;0 -dampingPerSec];
continuousB = [0;1];
measurementRow = [1 0];
positionScaleM = 1;
rateScaleMPerSec = 1;
measurementScaleM = 1;
decay = exp(-dampingPerSec*timeStepSec);
positionFromRateSec = (1-decay)/dampingPerSec;
positionFromAccelerationSec2 = ...
    (timeStepSec-positionFromRateSec)/dampingPerSec;
discreteA = [1 positionFromRateSec;0 decay];
discreteB = [positionFromAccelerationSec2;positionFromRateSec];

% Derive a repeated sampled error pole at q without opaque placement helpers.
desiredErrorPole = exp(-observerPoleSpeedPerSec*timeStepSec);
observerGainPosition = 1+decay-2*desiredErrorPole;
observerGainRatePerSec = ...
    (desiredErrorPole-decay)^2/positionFromRateSec;
observerGain = [observerGainPosition;observerGainRatePerSec];
normalizedObserverGain = [ ...
    observerGainPosition*measurementScaleM/positionScaleM; ...
    observerGainRatePerSec*measurementScaleM/rateScaleMPerSec];
errorTransition = discreteA-observerGain*measurementRow;
errorTransitionTrace = errorTransition(1,1)+errorTransition(2,2);
errorTransitionDeterminant = ...
    errorTransition(1,1)*errorTransition(2,2)- ...
    errorTransition(1,2)*errorTransition(2,1);

sampleCount = stepCount+1;
timeSec = (0:stepCount)*timeStepSec;
commandAcceleration = commandAccelerationMPerSec2*double(timeSec >= 0.5);
interferenceShape = sin(2*pi*2.5*timeSec);
measurementInterferenceM = interferenceAmplitudeM*interferenceShape;
trueState = zeros(2,sampleCount);
estimatedState = zeros(2,sampleCount);
measurementM = zeros(1,sampleCount);
innovationM = zeros(1,sampleCount);
trueState(:,1) = [0.8;-0.3];
estimatedState(:,1) = ...
    [initialEstimatePositionM;initialEstimateRateMPerSec];

for k = 1:sampleCount
    measurementM(k) = measurementRow*trueState(:,k)+ ...
        sensorBiasM+measurementInterferenceM(k);
    innovationM(k) = measurementM(k)-measurementRow*estimatedState(:,k);
    if k <= stepCount
        trueState(:,k+1) = discreteA*trueState(:,k)+ ...
            discreteB*commandAcceleration(k);
        estimatedState(:,k+1) = discreteA*estimatedState(:,k)+ ...
            discreteB*commandAcceleration(k)+observerGain*innovationM(k);
    end
end

estimationError = trueState-estimatedState;
normalizedError = [estimationError(1,:)/positionScaleM; ...
    estimationError(2,:)/rateScaleMPerSec];
normalizedErrorNorm = sqrt(sum(normalizedError.^2,1));
tailMask = timeSec >= simulationDurationSec-1;
positionErrorRmsTailM = sqrt(mean(estimationError(1,tailMask).^2));
rateErrorRmsTailMPerSec = sqrt(mean(estimationError(2,tailMask).^2));
initialErrorNorm = normalizedErrorNorm(1);
settlingThreshold = 0.02*initialErrorNorm;
settlingTimeSec = Inf;
suffixMaximum = 0;
for k = sampleCount:-1:1
    suffixMaximum = max(suffixMaximum,normalizedErrorNorm(k));
    if suffixMaximum <= settlingThreshold
        settlingTimeSec = timeSec(k);
    end
end

out = struct( ...
    'observerPoleSpeedPerSec',observerPoleSpeedPerSec, ...
    'interferenceAmplitudeM',interferenceAmplitudeM, ...
    'sensorBiasM',sensorBiasM, ...
    'commandAccelerationMPerSec2',commandAccelerationMPerSec2, ...
    'simulationDurationSec',simulationDurationSec, ...
    'timeStepSec',timeStepSec, ...
    'dampingPerSec',dampingPerSec, ...
    'continuousA',continuousA, ...
    'continuousB',continuousB, ...
    'measurementRow',measurementRow, ...
    'discreteA',discreteA, ...
    'discreteB',discreteB, ...
    'decay',decay, ...
    'positionFromRateSec',positionFromRateSec, ...
    'positionFromAccelerationSec2',positionFromAccelerationSec2, ...
    'desiredErrorPole',desiredErrorPole, ...
    'observerGain',observerGain, ...
    'observerGainPosition',observerGainPosition, ...
    'observerGainRatePerSec',observerGainRatePerSec, ...
    'normalizedObserverGain',normalizedObserverGain, ...
    'errorTransition',errorTransition, ...
    'errorTransitionTrace',errorTransitionTrace, ...
    'errorTransitionDeterminant',errorTransitionDeterminant, ...
    'timeSec',timeSec, ...
    'commandAcceleration',commandAcceleration, ...
    'interferenceShape',interferenceShape, ...
    'measurementInterferenceM',measurementInterferenceM, ...
    'measurementM',measurementM, ...
    'innovationM',innovationM, ...
    'trueState',trueState, ...
    'estimatedState',estimatedState, ...
    'estimationError',estimationError, ...
    'positionScaleM',positionScaleM, ...
    'rateScaleMPerSec',rateScaleMPerSec, ...
    'measurementScaleM',measurementScaleM, ...
    'normalizedError',normalizedError, ...
    'normalizedErrorNorm',normalizedErrorNorm, ...
    'initialErrorNorm',initialErrorNorm, ...
    'settlingThreshold',settlingThreshold, ...
    'settlingTimeSec',settlingTimeSec, ...
    'positionErrorRmsTailM',positionErrorRmsTailM, ...
    'rateErrorRmsTailMPerSec',rateErrorRmsTailMPerSec, ...
    'peakInnovationM',max(abs(innovationM)), ...
    'finalNormalizedError',normalizedErrorNorm(end), ...
    'stepCount',stepCount, ...
    'sampleCount',sampleCount, ...
    'maximumStepCount',maximumStepCount);
end
