function run_checks
%RUN_CHECKS Verify P15 observer invariants without presentation code.
tolerance = 2e-11;
baselineA = model(2,0,0,0.4,8,0.02);
baselineB = model(2,0,0,0.4,8,0.02);
assert(isequaln(baselineA,baselineB), ...
    'The deterministic baseline must repeat exactly.');

expectedDecay = exp(-0.5*0.02);
expectedPositionFromRate = (1-expectedDecay)/0.5;
expectedPositionFromAcceleration = ...
    (0.02-expectedPositionFromRate)/0.5;
expectedA = [1 expectedPositionFromRate;0 expectedDecay];
expectedB = [expectedPositionFromAcceleration;expectedPositionFromRate];
expectedPole = exp(-2*0.02);
expectedGain = [1+expectedDecay-2*expectedPole; ...
    (expectedPole-expectedDecay)^2/expectedPositionFromRate];
expectedErrorTransition = expectedA-expectedGain*[1 0];
assert(max(abs(baselineA.discreteA(:)-expectedA(:))) < tolerance && ...
    max(abs(baselineA.discreteB(:)-expectedB(:))) < tolerance, ...
    'Exact zero-order-hold plant matrices must match independent formulas.');
assert(max(abs(baselineA.observerGain-expectedGain)) < tolerance && ...
    max(abs(baselineA.errorTransition(:)- ...
    expectedErrorTransition(:))) < tolerance, ...
    'Observer gain and error transition must match the visible pole design.');
assert(abs(baselineA.errorTransitionTrace-2*expectedPole) < tolerance && ...
    abs(baselineA.errorTransitionDeterminant-expectedPole^2) < tolerance, ...
    'Error-transition trace and determinant must place the repeated pole.');
jordanResidual = ...
    (baselineA.errorTransition-expectedPole*eye(2))^2;
assert(max(abs(jordanResidual(:))) < tolerance, ...
    'The repeated-pole Jordan identity must hold without an opaque eig call.');

for k = 1:baselineA.stepCount
    expectedTrue = baselineA.discreteA*baselineA.trueState(:,k)+ ...
        baselineA.discreteB*baselineA.commandAcceleration(k);
    expectedEstimate = ...
        baselineA.discreteA*baselineA.estimatedState(:,k)+ ...
        baselineA.discreteB*baselineA.commandAcceleration(k)+ ...
        baselineA.observerGain*baselineA.innovationM(k);
    expectedError = ...
        baselineA.errorTransition*baselineA.estimationError(:,k);
    assert(max(abs(baselineA.trueState(:,k+1)-expectedTrue)) < tolerance && ...
        max(abs(baselineA.estimatedState(:,k+1)-expectedEstimate)) < tolerance, ...
        'Every plant and observer sample must follow the governing recurrence.');
    assert(max(abs(baselineA.estimationError(:,k+1)-expectedError)) < tolerance, ...
        'Known plant input must cancel from the noise-free error recurrence.');
end
assert(baselineA.finalNormalizedError < 1e-5 && ...
    baselineA.positionErrorRmsTailM < 1e-5 && ...
    baselineA.rateErrorRmsTailMPerSec < 2e-5, ...
    'The matched noise-free baseline must converge from a wrong initial guess.');

exactStart = model(2,0,0,0.4,8,0.02,0.8,-0.3);
assert(max(abs(exactStart.estimationError(:))) < tolerance && ...
    max(abs(exactStart.innovationM)) < tolerance && ...
    exactStart.settlingTimeSec == 0, ...
    'An exact initial estimate must remain exact under the shared known input.');
commandFree = model(2,0,0,0,8,0.02);
assert(max(abs(commandFree.estimationError(:)- ...
    baselineA.estimationError(:))) < tolerance, ...
    'Changing a command known to plant and observer must not change estimation error.');

observerPoleSpeedsPerSec = [1 2 3 4];
speedFinalErrors = zeros(size(observerPoleSpeedsPerSec));
speedPoles = zeros(size(observerPoleSpeedsPerSec));
speedGainNorms = zeros(size(observerPoleSpeedsPerSec));
for k = 1:numel(observerPoleSpeedsPerSec)
    changed = model(observerPoleSpeedsPerSec(k),0,0,0.4,8,0.02);
    speedFinalErrors(k) = changed.finalNormalizedError;
    speedPoles(k) = changed.desiredErrorPole;
    speedGainNorms(k) = norm(changed.normalizedObserverGain);
    assert(changed.interferenceAmplitudeM == 0 && ...
        changed.sensorBiasM == 0 && ...
        changed.commandAccelerationMPerSec2 == 0.4 && ...
        changed.simulationDurationSec == 8 && changed.timeStepSec == 0.02, ...
        'The pole-speed sweep must hold every other input fixed.');
end
assert(all(diff(speedPoles) < 0) && all(diff(speedGainNorms) > 0) && ...
    all(diff(speedFinalErrors) < 0) && speedFinalErrors(end) < 1e-10, ...
    'This fixed-horizon sweep must show faster poles, stronger gain, and less final error.');

interferenceAmplitudesM = [0 0.005 0.02 0.05];
interferenceRuns = cell(size(interferenceAmplitudesM));
positionRms = zeros(size(interferenceAmplitudesM));
rateRms = zeros(size(interferenceAmplitudesM));
for k = 1:numel(interferenceAmplitudesM)
    interferenceRuns{k} = model(2,interferenceAmplitudesM(k),0,0.4,8,0.02);
    changed = interferenceRuns{k};
    positionRms(k) = changed.positionErrorRmsTailM;
    rateRms(k) = changed.rateErrorRmsTailMPerSec;
    assert(changed.observerPoleSpeedPerSec == 2 && ...
        changed.sensorBiasM == 0 && ...
        changed.commandAccelerationMPerSec2 == 0.4 && ...
        max(abs(changed.trueState(:)-baselineA.trueState(:))) == 0, ...
        'The interference sweep must preserve observer, input, and truth.');
end
unitImpact = (interferenceRuns{2}.estimatedState- ...
    interferenceRuns{1}.estimatedState)/interferenceAmplitudesM(2);
for k = 3:numel(interferenceAmplitudesM)
    changedImpact = (interferenceRuns{k}.estimatedState- ...
        interferenceRuns{1}.estimatedState)/interferenceAmplitudesM(k);
    assert(max(abs(changedImpact(:)-unitImpact(:))) < 2e-10, ...
        'Deterministic interference response must scale linearly with amplitude.');
end
assert(all(diff(positionRms) > 0) && all(diff(rateRms) > 0), ...
    'More measurement interference must increase both late state-error RMS values.');

broken = model(2,0,0.15,0.4,8,0.02);
recovered = model(2,0,0,0.4,8,0.02);
assert(max(abs(broken.trueState(:)-recovered.trueState(:))) == 0 && ...
    max(abs(broken.commandAcceleration-recovered.commandAcceleration)) == 0 && ...
    max(abs((broken.measurementM-recovered.measurementM)-0.15)) < tolerance, ...
    'The broken case must change only the named sensor calibration assumption.');
assert(abs(broken.estimationError(1,end)+0.15) < 1e-4 && ...
    abs(broken.estimationError(2,end)) < 1e-4 && ...
    abs(broken.innovationM(end)) < 1e-4 && ...
    broken.positionErrorRmsTailM > 0.14, ...
    'Positive bias must hide a high position estimate behind a quiet innovation.');
assert(isequaln(recovered,baselineA), ...
    'A fresh zero-bias call must recover the exact deterministic baseline.');

assertAnyError(@() model(NaN,0,0,0.4,8,0.02), ...
    'A nonfinite observer speed must be rejected.');
assertAnyError(@() model([1 2],0,0,0.4,8,0.02), ...
    'A nonscalar observer speed must be rejected.');
assertAnyError(@() model(2+1i,0,0,0.4,8,0.02), ...
    'A complex observer speed must be rejected.');
assertAnyError(@() model(2,-0.01,0,0.4,8,0.02), ...
    'A negative interference amplitude must be rejected.');
assertAnyError(@() model(2,0,0,-0.1,8,0.02), ...
    'A negative command acceleration must be rejected.');
assertErrorId(@() model(0.9,0,0,0.4,8,0.02), ...
    'P15:ObserverSpeedRange','A too-slow observer setting must be rejected.');
assertErrorId(@() model(5.1,0,0,0.4,8,0.02), ...
    'P15:ObserverSpeedRange','An excessive observer setting must be rejected.');
assertErrorId(@() model(2,0.051,0,0.4,8,0.02), ...
    'P15:InterferenceRange','Excessive interference must be rejected.');
assertErrorId(@() model(2,0,0.251,0.4,8,0.02), ...
    'P15:SensorBiasRange','Excessive sensor bias must be rejected.');
assertErrorId(@() model(2,0,0,1.01,8,0.02), ...
    'P15:CommandRange','Excessive command acceleration must be rejected.');
assertErrorId(@() model(2,0,0,0.4,1.9,0.02), ...
    'P15:DurationRange','A too-short duration must be rejected.');
assertErrorId(@() model(2,0,0,0.4,10.1,0.02), ...
    'P15:DurationRange','An excessive duration must be rejected.');
assertErrorId(@() model(2,0,0,0.4,8,0.051), ...
    'P15:DisplayResolution','An under-resolved sample interval must be rejected.');
assertErrorId(@() model(2,0,0,0.4,8,0.03), ...
    'P15:GridAlignment','A partial final sample must be rejected.');
assertErrorId(@() model(2,0,0,0.4,8,0.02,-2.1,0.4), ...
    'P15:InitialEstimatePositionRange','An excessive initial position estimate must be rejected.');
assertErrorId(@() model(2,0,0,0.4,8,0.02,-0.4,2.1), ...
    'P15:InitialEstimateRateRange','An excessive initial rate estimate must be rejected.');
assertErrorId(@() model(2,0,0,0.4,10,1e-6), ...
    'P15:TooManySteps','An oversized grid must be rejected before allocation.');
boundedGrid = model(2,0,0,0.4,10,0.002);
assert(boundedGrid.stepCount == 5000 && boundedGrid.sampleCount == 5001 && ...
    all(isfinite(boundedGrid.trueState(:))) && ...
    all(isfinite(boundedGrid.estimatedState(:))) && ...
    all(isfinite(boundedGrid.innovationM)) && ...
    boundedGrid.finalNormalizedError < 1e-7, ...
    'The largest accepted grid must remain finite and convergent.');

disp(['P15 checks passed: exact observer poles, error recurrence, two ' ...
    'isolated levers, hidden bias, recovery, malformed inputs, and bounds.']);
end

function assertAnyError(operation,message)
didError = false;
try
    operation();
catch
    didError = true;
end
assert(didError,message);
end

function assertErrorId(operation,expectedIdentifier,message)
actualIdentifier = '';
try
    operation();
catch exception
    actualIdentifier = exception.identifier;
end
assert(strcmp(actualIdentifier,expectedIdentifier),message);
end
