function out = model(samplePeriodSec,discretizationMethod,tEnd,displayStepSec)
%MODEL Compare a digital PI realization with its continuous target.
%   The normalized plant y'=-y+u has an exact zero-order-hold transition
%       y[k+1] = a*y[k] + (1-a)*u[k],  a = exp(-samplePeriodSec).
%   The continuous PI target is u=Kp*e+Ki*integral(e dt), e=1-y,
%   with Kp=2 and Ki=4 1/s. The two transparent discrete integral rules are
%   forward Euler (previous error) and backward Euler (current error).
arguments
    samplePeriodSec (1,1) double {mustBeReal,mustBeFinite,mustBePositive} = 0.05
    discretizationMethod (1,:) char = 'backward-euler'
    tEnd (1,1) double {mustBeReal,mustBeFinite,mustBePositive} = 12
    displayStepSec (1,1) double {mustBeReal,mustBeFinite,mustBePositive} = 0.01
end

validMethods = {'forward-euler','backward-euler'};
if ~any(strcmp(discretizationMethod,validMethods))
    error('P09:UnknownMethod', ...
        'discretizationMethod must be forward-euler or backward-euler.');
end
if samplePeriodSec > 1
    error('P09:SamplePeriodRange','samplePeriodSec must not exceed 1 s.');
end
if tEnd > 60
    error('P09:HorizonRange','tEnd must not exceed 60 s.');
end
if displayStepSec > samplePeriodSec
    error('P09:DisplayResolution', ...
        'displayStepSec must not exceed samplePeriodSec.');
end

maxControllerSamples = 10001;
maxDisplaySamples = 20001;
controllerIntervalCount = floor(tEnd/samplePeriodSec);
controllerSampleCount = controllerIntervalCount+1;
if ~isfinite(controllerSampleCount) || ...
        controllerSampleCount > maxControllerSamples
    error('P09:TooManyControllerSamples', ...
        'Requested %d controller samples; maximum is %d.', ...
        controllerSampleCount,maxControllerSamples);
end
sampleTimes = (0:controllerIntervalCount)'*samplePeriodSec;
displayIntervalCount = floor(tEnd/displayStepSec);
regularDisplaySampleCount = displayIntervalCount+1;
if ~isfinite(regularDisplaySampleCount) || ...
        regularDisplaySampleCount > maxDisplaySamples
    error('P09:TooManyDisplaySamples', ...
        'Requested at least %d display samples; maximum is %d.', ...
        regularDisplaySampleCount,maxDisplaySamples);
end
lastDisplayTime = displayIntervalCount*displayStepSec;
timeTolerance = 8*eps(max(tEnd,displayStepSec));
appendEnd = tEnd-lastDisplayTime > timeTolerance;
displaySampleCount = regularDisplaySampleCount+double(appendEnd);
if displaySampleCount > maxDisplaySamples
    error('P09:TooManyDisplaySamples', ...
        'Requested %d display samples; maximum is %d.', ...
        displaySampleCount,maxDisplaySamples);
end
t = (0:displayIntervalCount)'*displayStepSec;
if appendEnd
    t(end+1,1) = tEnd;
else
    t(end) = tEnd;
end

proportionalGain = 2;
integralGainPerSec = 4;
plantTimeConstantSec = 1;
reference = 1;
plantDecay = exp(-samplePeriodSec/plantTimeConstantSec);
plantInputWeight = 1-plantDecay;

% Form the exact two-state closed-loop update for pole calculations.
stateA11 = plantDecay-plantInputWeight*proportionalGain;
if strcmp(discretizationMethod,'backward-euler')
    stateA11 = stateA11- ...
        plantInputWeight*integralGainPerSec*samplePeriodSec;
end
stateA12 = plantInputWeight*integralGainPerSec;
stateA21 = -samplePeriodSec;
stateA22 = 1;
poleTrace = stateA11+stateA22;
poleDeterminant = stateA11*stateA22-stateA12*stateA21;
poleDiscriminant = poleTrace^2-4*poleDeterminant;
discretePoles = [ ...
    (poleTrace+sqrt(complex(poleDiscriminant)))/2; ...
    (poleTrace-sqrt(complex(poleDiscriminant)))/2];
spectralRadius = max(abs(discretePoles));

digitalOutputSamples = zeros(controllerSampleCount,1);
errorSamples = zeros(controllerSampleCount,1);
integralStateSamples = zeros(controllerSampleCount,1);
controlSamples = zeros(controllerSampleCount,1);
integralState = 0;
responseLimit = 1000;
for k = 1:controllerSampleCount
    errorSamples(k) = reference-digitalOutputSamples(k);
    if strcmp(discretizationMethod,'backward-euler')
        integralState = integralState+samplePeriodSec*errorSamples(k);
    end
    integralStateSamples(k) = integralState;
    controlSamples(k) = proportionalGain*errorSamples(k)+ ...
        integralGainPerSec*integralStateSamples(k);
    if ~isfinite(controlSamples(k)) || abs(controlSamples(k)) > responseLimit
        error('P09:ResponseBound', ...
            'The requested controller effort exceeds the bounded learning view.');
    end
    if strcmp(discretizationMethod,'forward-euler')
        integralState = integralState+samplePeriodSec*errorSamples(k);
    end
    if k < controllerSampleCount
        digitalOutputSamples(k+1) = plantDecay*digitalOutputSamples(k)+ ...
            plantInputWeight*controlSamples(k);
        if ~isfinite(digitalOutputSamples(k+1)) || ...
                abs(digitalOutputSamples(k+1)) > responseLimit
            error('P09:ResponseBound', ...
                'The requested plant response exceeds the bounded learning view.');
        end
    end
end

% Reconstruct the exact continuous plant motion under each held command.
digitalOutput = zeros(displaySampleCount,1);
heldControl = zeros(displaySampleCount,1);
for k = 1:controllerSampleCount
    if k < controllerSampleCount
        active = t >= sampleTimes(k) & t < sampleTimes(k+1);
    else
        active = t >= sampleTimes(k);
    end
    elapsed = t(active)-sampleTimes(k);
    heldControl(active) = controlSamples(k);
    digitalOutput(active) = controlSamples(k)+( ...
        digitalOutputSamples(k)-controlSamples(k)).* ...
        exp(-elapsed/plantTimeConstantSec);
end

% Independent closed-form continuous PI target for the fixed gains.
continuousDecayRatePerSec = (1+proportionalGain)/2;
continuousDampedFrequencyRadPerSec = sqrt( ...
    4*integralGainPerSec-(1+proportionalGain)^2)/2;
continuousSineWeight = (proportionalGain- ...
    continuousDecayRatePerSec)/continuousDampedFrequencyRadPerSec;
decayingEnvelope = exp(-continuousDecayRatePerSec*t);
continuousOutput = reference+decayingEnvelope.*( ...
    -cos(continuousDampedFrequencyRadPerSec*t)+ ...
    continuousSineWeight*sin(continuousDampedFrequencyRadPerSec*t));
continuousDerivative = decayingEnvelope.*( ...
    (continuousDecayRatePerSec+continuousSineWeight* ...
    continuousDampedFrequencyRadPerSec)* ...
    cos(continuousDampedFrequencyRadPerSec*t)+( ...
    continuousDampedFrequencyRadPerSec-continuousDecayRatePerSec* ...
    continuousSineWeight)*sin(continuousDampedFrequencyRadPerSec*t));
continuousControl = continuousOutput+continuousDerivative;

trackingGap = digitalOutput-continuousOutput;
digitalError = reference-digitalOutput;
continuousNaturalFrequencyRadPerSec = sqrt(integralGainPerSec);
samplesPerNaturalPeriod = 2*pi/( ...
    continuousNaturalFrequencyRadPerSec*samplePeriodSec);
outsideSettlingBand = find(abs(digitalError) > 0.02*abs(reference));
if isempty(outsideSettlingBand)
    settlingTimeSec = 0;
elseif outsideSettlingBand(end) == displaySampleCount
    settlingTimeSec = NaN;
else
    settlingTimeSec = t(outsideSettlingBand(end)+1);
end

out = struct( ...
    't',t, ...
    'reference',reference*ones(displaySampleCount,1), ...
    'digitalOutput',digitalOutput, ...
    'continuousOutput',continuousOutput, ...
    'heldControl',heldControl, ...
    'continuousControl',continuousControl, ...
    'trackingGap',trackingGap, ...
    'sampleTimes',sampleTimes, ...
    'digitalOutputSamples',digitalOutputSamples, ...
    'errorSamples',errorSamples, ...
    'integralStateSamples',integralStateSamples, ...
    'controlSamples',controlSamples, ...
    'samplePeriodSec',samplePeriodSec, ...
    'discretizationMethod',discretizationMethod, ...
    'proportionalGain',proportionalGain, ...
    'integralGainPerSec',integralGainPerSec, ...
    'plantTimeConstantSec',plantTimeConstantSec, ...
    'plantDecay',plantDecay, ...
    'plantInputWeight',plantInputWeight, ...
    'stateMatrix',[stateA11 stateA12; stateA21 stateA22], ...
    'poleTrace',poleTrace, ...
    'poleDeterminant',poleDeterminant, ...
    'poleDiscriminant',poleDiscriminant, ...
    'discretePoles',discretePoles, ...
    'spectralRadius',spectralRadius, ...
    'isStable',spectralRadius < 1, ...
    'continuousDecayRatePerSec',continuousDecayRatePerSec, ...
    'continuousDampedFrequencyRadPerSec', ...
    continuousDampedFrequencyRadPerSec, ...
    'continuousNaturalFrequencyRadPerSec', ...
    continuousNaturalFrequencyRadPerSec, ...
    'samplesPerNaturalPeriod',samplesPerNaturalPeriod, ...
    'maximumAbsTrackingGap',max(abs(trackingGap)), ...
    'rmsTrackingGap',sqrt(mean(trackingGap.^2)), ...
    'overshootPercent',100*max(0,max(digitalOutput)-reference), ...
    'finalError',digitalError(end), ...
    'settlingTimeSec',settlingTimeSec, ...
    'controllerSampleCount',controllerSampleCount, ...
    'displaySampleCount',displaySampleCount, ...
    'maxControllerSamples',maxControllerSamples, ...
    'maxDisplaySamples',maxDisplaySamples, ...
    'responseLimit',responseLimit);
end
