function run_checks
%RUN_CHECKS Independent sampled-data identities, limits, failure, and recovery.
tolerance = 5e-12;

baselineA = model(0.05,'backward-euler',12,0.01);
baselineB = model(0.05,'backward-euler',12,0.01);
assert(isequaln(baselineA,baselineB), ...
    'Identical inputs must produce identical trajectories, poles, and metrics.');
assert(baselineA.proportionalGain == 2 && ...
    baselineA.integralGainPerSec == 4 && ...
    baselineA.plantTimeConstantSec == 1, ...
    'The continuous controller and plant identity must remain fixed.');
assert(abs(baselineA.plantDecay-exp(-0.05)) < tolerance && ...
    abs(baselineA.plantInputWeight-(1-exp(-0.05))) < tolerance, ...
    'The exact held-plant weights must equal their independent exponential values.');

sampleTransitionResidual = baselineA.digitalOutputSamples(2:end)-( ...
    baselineA.plantDecay*baselineA.digitalOutputSamples(1:end-1)+ ...
    baselineA.plantInputWeight*baselineA.controlSamples(1:end-1));
assert(max(abs(sampleTransitionResidual)) < tolerance, ...
    'Every sample must satisfy the exact zero-order-hold plant transition.');
assert(max(abs(baselineA.errorSamples-( ...
    1-baselineA.digitalOutputSamples))) < tolerance, ...
    'Every sampled error must equal reference minus sampled plant output.');
expectedBackwardIntegral = 0.05*cumsum(baselineA.errorSamples);
assert(max(abs(baselineA.integralStateSamples- ...
    expectedBackwardIntegral)) < tolerance, ...
    'Backward Euler memory must include the current sampled error.');
assert(max(abs(baselineA.controlSamples-( ...
    2*baselineA.errorSamples+4*baselineA.integralStateSamples))) < ...
    tolerance, ...
    'Every held command must expose proportional plus integral action.');

displayedAtSamples = baselineA.digitalOutput(1:5:end);
assert(numel(displayedAtSamples) == numel(baselineA.digitalOutputSamples) && ...
    max(abs(displayedAtSamples-baselineA.digitalOutputSamples)) < tolerance, ...
    'The exact held response must meet every controller sample state.');
assert(baselineA.continuousOutput(1) == 0 && ...
    abs(baselineA.continuousControl(1)-2) < tolerance && ...
    abs(baselineA.continuousOutput(end)-1) < 1e-7, ...
    'The independent continuous PI target must start and settle correctly.');

expectedA11 = exp(-0.05)-(1-exp(-0.05))*(2+4*0.05);
expectedA12 = (1-exp(-0.05))*4;
expectedMatrix = [expectedA11 expectedA12; -0.05 1];
assert(max(abs(baselineA.stateMatrix(:)-expectedMatrix(:))) < tolerance, ...
    'The backward-Euler closed-loop state matrix must match direct expansion.');
poleResidual = baselineA.discretePoles.^2- ...
    baselineA.poleTrace*baselineA.discretePoles+ ...
    baselineA.poleDeterminant;
assert(max(abs(poleResidual)) < 1e-13 && ...
    abs(baselineA.spectralRadius-0.923952527731886) < 1e-12 && ...
    baselineA.isStable, ...
    'Reported poles must satisfy the independently expanded characteristic equation.');
assert(abs(baselineA.samplesPerNaturalPeriod-20*pi) < tolerance, ...
    'Ts=0.05 s with natural frequency 2 rad/s must give 20*pi samples per period.');

fastSampling = model(0.02,'backward-euler',8,0.01);
mediumSampling = model(0.1,'backward-euler',8,0.01);
coarseSampling = model(0.4,'backward-euler',8,0.01);
assert(fastSampling.maximumAbsTrackingGap < ...
    mediumSampling.maximumAbsTrackingGap && ...
    mediumSampling.maximumAbsTrackingGap < ...
    coarseSampling.maximumAbsTrackingGap, ...
    'Moving only Ts upward must increase the continuous-target gap in the sweep.');
assert(fastSampling.samplesPerNaturalPeriod > ...
    mediumSampling.samplesPerNaturalPeriod && ...
    mediumSampling.samplesPerNaturalPeriod > ...
    coarseSampling.samplesPerNaturalPeriod, ...
    'Moving only Ts upward must reduce samples per natural period.');
assert(strcmp(fastSampling.discretizationMethod, ...
    coarseSampling.discretizationMethod) && ...
    fastSampling.proportionalGain == coarseSampling.proportionalGain && ...
    fastSampling.integralGainPerSec == coarseSampling.integralGainPerSec, ...
    'The sample-period sweep must preserve rule and continuous gains.');

forwardCase = model(0.05,'forward-euler',8,0.01);
backwardCase = model(0.05,'backward-euler',8,0.01);
assert(forwardCase.controlSamples(1) == 2 && ...
    abs(backwardCase.controlSamples(1)-2.2) < tolerance, ...
    'Forward and backward Euler must use previous and current error respectively.');
expectedForwardIntegral = [0; 0.05*cumsum( ...
    forwardCase.errorSamples(1:end-1))];
assert(max(abs(forwardCase.integralStateSamples- ...
    expectedForwardIntegral)) < tolerance, ...
    'Forward Euler memory used by u[k] must stop at the previous error.');
assert(forwardCase.samplePeriodSec == backwardCase.samplePeriodSec && ...
    forwardCase.proportionalGain == backwardCase.proportionalGain && ...
    forwardCase.integralGainPerSec == backwardCase.integralGainPerSec && ...
    max(abs(forwardCase.digitalOutput- ...
    backwardCase.digitalOutput)) > 0.01, ...
    'The rule sweep must isolate a visible current-versus-previous error effect.');

smallForward = model(0.005,'forward-euler',4,0.005);
smallBackward = model(0.005,'backward-euler',4,0.005);
baselineForward = model(0.05,'forward-euler',4,0.01);
assert(smallForward.maximumAbsTrackingGap < ...
    baselineForward.maximumAbsTrackingGap && ...
    smallBackward.maximumAbsTrackingGap < ...
    baselineA.maximumAbsTrackingGap && ...
    max(abs(smallForward.digitalOutput-smallBackward.digitalOutput)) < 0.007, ...
    'Both Euler rules must approach one another and the continuous target as Ts shrinks.');

broken = model(0.8,'forward-euler',12,0.01);
recovered = model(0.05,'forward-euler',12,0.01);
assert(broken.spectralRadius > 1.05 && ~broken.isStable && ...
    abs(broken.finalError) > 1.7 && ...
    broken.maximumAbsTrackingGap > 1.9, ...
    'The coarse forward-Euler case must expose pole growth and tracking failure.');
assert(recovered.spectralRadius < 1 && recovered.isStable && ...
    abs(recovered.finalError) < 1e-6 && ...
    recovered.maximumAbsTrackingGap < 0.03, ...
    'Reducing Ts must put poles inside the unit circle and recover convergence.');
assert(broken.proportionalGain == recovered.proportionalGain && ...
    broken.integralGainPerSec == recovered.integralGainPerSec && ...
    strcmp(broken.discretizationMethod,recovered.discretizationMethod), ...
    'Recovery must change timing only, not controller gains or realization.');

zeroHorizonView = model(0.05,'forward-euler',0.02,0.01);
assert(zeroHorizonView.controllerSampleCount == 1 && ...
    all(zeroHorizonView.digitalOutput >= 0) && ...
    zeroHorizonView.digitalOutput(end) > 0, ...
    'A horizon shorter than Ts must retain one command and exact held motion.');
nonIntegerGrid = model(0.03,'forward-euler',0.1,0.01);
assert(nonIntegerGrid.sampleTimes(end) == 0.09 && ...
    nonIntegerGrid.t(end) == 0.1 && all(diff(nonIntegerGrid.t) > 0), ...
    'A noninteger horizon must hold the last command through one exact endpoint.');
lastHoldElapsedSec = nonIntegerGrid.t(end)- ...
    nonIntegerGrid.sampleTimes(end);
expectedFinalHeldOutput = nonIntegerGrid.controlSamples(end)+( ...
    nonIntegerGrid.digitalOutputSamples(end)- ...
    nonIntegerGrid.controlSamples(end))*exp(-lastHoldElapsedSec/ ...
    nonIntegerGrid.plantTimeConstantSec);
lastHold = nonIntegerGrid.t >= nonIntegerGrid.sampleTimes(end);
assert(all(nonIntegerGrid.heldControl(lastHold) == ...
    nonIntegerGrid.controlSamples(end)) && ...
    abs(nonIntegerGrid.digitalOutput(end)-expectedFinalHeldOutput) < tolerance, ...
    'The final partial interval must retain its command and exact plant motion.');

assertAnyError(@() model(NaN,'forward-euler',12,0.01), ...
    'A nonfinite sample period must be rejected.');
assertAnyError(@() model(0.05,'forward-euler',Inf,0.01), ...
    'A nonfinite horizon must be rejected.');
assertAnyError(@() model(0.05,'forward-euler',12,[0.01 0.02]), ...
    'A nonscalar display interval must be rejected.');
assertAnyError(@() model(-0.05,'forward-euler',12,0.01), ...
    'A negative sample period must be rejected.');
assertAnyError(@() model(0.05,7,12,0.01), ...
    'A malformed method type must be rejected.');
assertErrorId(@() model(0.05,'tustin',12,0.01), ...
    'P09:UnknownMethod','An unsupported rule must be rejected explicitly.');
assertErrorId(@() model(1.01,'forward-euler',12,0.01), ...
    'P09:SamplePeriodRange','An excessive sample period must be rejected.');
assertErrorId(@() model(0.05,'forward-euler',60.1,0.01), ...
    'P09:HorizonRange','An excessive horizon must be rejected.');
assertErrorId(@() model(0.05,'forward-euler',12,0.051), ...
    'P09:DisplayResolution','An under-resolved display request must be rejected.');
assertErrorId(@() model(0.005,'forward-euler',60,0.005), ...
    'P09:TooManyControllerSamples', ...
    'An excessive controller grid must be rejected.');
assertErrorId(@() model(1e-12,'forward-euler',60,1e-12), ...
    'P09:TooManyControllerSamples', ...
    'A tiny period must be rejected before allocating its controller grid.');
assertErrorId(@() model(0.03,'forward-euler',60,0.002), ...
    'P09:TooManyDisplaySamples','An excessive display grid must be rejected.');
assertErrorId(@() model(0.05,'forward-euler',60,1e-12), ...
    'P09:TooManyDisplaySamples', ...
    'A tiny display step must be rejected before allocating its display grid.');
assertErrorId(@() model(0.8,'backward-euler',12,0.01), ...
    'P09:ResponseBound','An excessive unstable response must be bounded.');

atControllerLimit = model(0.006,'forward-euler',60,0.006);
assert(atControllerLimit.controllerSampleCount == 10001 && ...
    all(isfinite(atControllerLimit.digitalOutput)), ...
    'The declared maximum controller grid must remain accepted.');
atDisplayLimit = model(0.03,'forward-euler',60,0.003);
assert(atDisplayLimit.displaySampleCount == 20001 && ...
    all(isfinite(atDisplayLimit.digitalOutput)), ...
    'The declared maximum display grid must remain accepted.');

disp(['P09 checks passed: held-plant identity, timing levers, limits, ' ...
    'coarse-sample failure, recovery, and bounds.']);
end

function assertAnyError(operation,message)
didError = false;
try
    operation();
catch
    didError = true;
end
assert(didError,message);
end

function assertErrorId(operation,expectedIdentifier,message)
actualIdentifier = '';
try
    operation();
catch exception
    actualIdentifier = exception.identifier;
end
assert(strcmp(actualIdentifier,expectedIdentifier),message);
end
