function out = model(feedbackGain,disturbanceAmplitude, ...
    disturbanceFrequencyRadPerSec,sensorBias,tEnd,dt)
%MODEL Evaluate disturbance rejection in a transparent first-order loop.
%   The normalized plant and proportional controller are
%       tau*y' = -y + u + d,  u = -K*(y+bias),  tau = 1 s.
%   Disturbance and bias begin at t=1 s. Frequency zero selects a step;
%   positive frequency selects a sine wave with zero phase at its start.
arguments
    feedbackGain (1,1) double {mustBeReal,mustBeFinite,mustBeNonnegative} = 4
    disturbanceAmplitude (1,1) double {mustBeReal,mustBeFinite} = 1
    disturbanceFrequencyRadPerSec (1,1) double ...
        {mustBeReal,mustBeFinite,mustBeNonnegative} = 0
    sensorBias (1,1) double {mustBeReal,mustBeFinite} = 0
    tEnd (1,1) double {mustBeReal,mustBeFinite,mustBePositive} = 12
    dt (1,1) double {mustBeReal,mustBeFinite,mustBePositive} = 0.01
end

if feedbackGain > 20
    error('P08:FeedbackGainRange', ...
        'feedbackGain must not exceed 20.');
end
if abs(disturbanceAmplitude) > 10
    error('P08:DisturbanceAmplitudeRange', ...
        'abs(disturbanceAmplitude) must not exceed 10 output units.');
end
if disturbanceFrequencyRadPerSec > 40
    error('P08:DisturbanceFrequencyRange', ...
        'disturbanceFrequencyRadPerSec must not exceed 40 rad/s.');
end
if abs(sensorBias) > 10
    error('P08:SensorBiasRange', ...
        'abs(sensorBias) must not exceed 10 output units.');
end
if tEnd > 60
    error('P08:HorizonRange','tEnd must not exceed 60 s.');
end

maxSamples = 20001;
intervalCount = floor(tEnd/dt);
lastRegularTime = intervalCount*dt;
timeTolerance = 8*eps(max(tEnd,dt));
appendEnd = intervalCount == 0 || tEnd-lastRegularTime > timeTolerance;
sampleCount = intervalCount + 1 + double(appendEnd);
if sampleCount > maxSamples
    error('P08:TooManySamples', ...
        'Requested %d samples; increase dt or shorten tEnd (maximum %d).', ...
        sampleCount,maxSamples);
end
t = (0:intervalCount)'*dt;
if appendEnd
    t(end+1,1) = tEnd;
else
    t(end) = tEnd;
end
maxInterval = max(diff(t));

plantTimeConstantSec = 1;
disturbanceStartSec = 1;
closedLoopRatePerSec = (1+feedbackGain)/plantTimeConstantSec;
characteristicRatePerSec = max(closedLoopRatePerSec, ...
    disturbanceFrequencyRadPerSec);
maxDimensionlessStep = 0.1;
if characteristicRatePerSec*maxInterval > ...
        maxDimensionlessStep+16*eps(maxDimensionlessStep)
    error('P08:TimeResolution', ...
        'Characteristic rate times maxInterval must not exceed %.2f.', ...
        maxDimensionlessStep);
end

trueOutput = zeros(sampleCount,1);
state = 0;
responseLimit = 9;
for k = 1:sampleCount-1
    intervalStart = t(k);
    intervalEnd = t(k+1);
    if intervalEnd <= disturbanceStartSec
        trueOutput(k+1) = state;
        continue;
    end
    integrationStart = max(intervalStart,disturbanceStartSec);
    step = intervalEnd-integrationStart;
    k1 = stateRate(integrationStart,state,feedbackGain,disturbanceAmplitude, ...
        disturbanceFrequencyRadPerSec,sensorBias, ...
        disturbanceStartSec,plantTimeConstantSec);
    k2 = stateRate(integrationStart+0.5*step,state+0.5*step*k1,feedbackGain, ...
        disturbanceAmplitude,disturbanceFrequencyRadPerSec,sensorBias, ...
        disturbanceStartSec,plantTimeConstantSec);
    k3 = stateRate(integrationStart+0.5*step,state+0.5*step*k2,feedbackGain, ...
        disturbanceAmplitude,disturbanceFrequencyRadPerSec,sensorBias, ...
        disturbanceStartSec,plantTimeConstantSec);
    k4 = stateRate(integrationStart+step,state+step*k3,feedbackGain, ...
        disturbanceAmplitude,disturbanceFrequencyRadPerSec,sensorBias, ...
        disturbanceStartSec,plantTimeConstantSec);
    state = state + step*(k1+2*k2+2*k3+k4)/6;
    if ~isfinite(state) || abs(state) > responseLimit
        error('P08:ResponseBound', ...
            'The requested response exceeds the bounded learning view.');
    end
    trueOutput(k+1) = state;
end

active = t >= disturbanceStartSec;
phase = disturbanceFrequencyRadPerSec*(t-disturbanceStartSec);
if disturbanceFrequencyRadPerSec == 0
    disturbanceInput = disturbanceAmplitude*double(active);
else
    disturbanceInput = disturbanceAmplitude*sin(phase).*double(active);
end
sensorBiasSignal = sensorBias*double(active);
measuredOutput = trueOutput+sensorBiasSignal;
controlEffort = -feedbackGain*measuredOutput;
stateDerivativePerSec = (-trueOutput+controlEffort+disturbanceInput)/ ...
    plantTimeConstantSec;

omegaRadPerSec = logspace(-2,2,401)';
openLoopDisturbanceMagnitude = 1./sqrt(1+ ...
    (plantTimeConstantSec*omegaRadPerSec).^2);
closedLoopDisturbanceMagnitude = 1./sqrt((1+feedbackGain)^2+ ...
    (plantTimeConstantSec*omegaRadPerSec).^2);
feedbackRejectionRatio = sqrt(1+ ...
    (plantTimeConstantSec*disturbanceFrequencyRadPerSec)^2)/ ...
    sqrt((1+feedbackGain)^2+ ...
    (plantTimeConstantSec*disturbanceFrequencyRadPerSec)^2);
additionalAttenuationDb = -20*log10(feedbackRejectionRatio);
theoreticalOutputAmplitude = abs(disturbanceAmplitude)/ ...
    sqrt((1+feedbackGain)^2+ ...
    (plantTimeConstantSec*disturbanceFrequencyRadPerSec)^2);
openLoopOutputAmplitude = abs(disturbanceAmplitude)/ ...
    sqrt(1+(plantTimeConstantSec*disturbanceFrequencyRadPerSec)^2);
disturbancePhaseLagDeg = -atan2( ...
    plantTimeConstantSec*disturbanceFrequencyRadPerSec,1+feedbackGain)*180/pi;
closedLoopTimeConstantSec = plantTimeConstantSec/(1+feedbackGain);

disturbanceDcTrueOutput = disturbanceAmplitude/(1+feedbackGain);
biasTrueOffset = -feedbackGain*sensorBias/(1+feedbackGain);
biasMeasuredOffset = sensorBias/(1+feedbackGain);
stepTrueOutput = disturbanceDcTrueOutput+biasTrueOffset;
stepMeasuredOutput = stepTrueOutput+sensorBias;
stepControlEffort = -feedbackGain*stepMeasuredOutput;

out = struct( ...
    't',t, ...
    'trueOutput',trueOutput, ...
    'measuredOutput',measuredOutput, ...
    'controlEffort',controlEffort, ...
    'disturbanceInput',disturbanceInput, ...
    'sensorBiasSignal',sensorBiasSignal, ...
    'stateDerivativePerSec',stateDerivativePerSec, ...
    'feedbackGain',feedbackGain, ...
    'disturbanceAmplitude',disturbanceAmplitude, ...
    'disturbanceFrequencyRadPerSec',disturbanceFrequencyRadPerSec, ...
    'sensorBias',sensorBias, ...
    'plantTimeConstantSec',plantTimeConstantSec, ...
    'disturbanceStartSec',disturbanceStartSec, ...
    'omegaRadPerSec',omegaRadPerSec, ...
    'openLoopDisturbanceMagnitude',openLoopDisturbanceMagnitude, ...
    'closedLoopDisturbanceMagnitude',closedLoopDisturbanceMagnitude, ...
    'feedbackRejectionRatio',feedbackRejectionRatio, ...
    'additionalAttenuationDb',additionalAttenuationDb, ...
    'theoreticalOutputAmplitude',theoreticalOutputAmplitude, ...
    'openLoopOutputAmplitude',openLoopOutputAmplitude, ...
    'disturbancePhaseLagDeg',disturbancePhaseLagDeg, ...
    'closedLoopTimeConstantSec',closedLoopTimeConstantSec, ...
    'disturbanceDcTrueOutput',disturbanceDcTrueOutput, ...
    'biasTrueOffset',biasTrueOffset, ...
    'biasMeasuredOffset',biasMeasuredOffset, ...
    'stepTrueOutput',stepTrueOutput, ...
    'stepMeasuredOutput',stepMeasuredOutput, ...
    'stepControlEffort',stepControlEffort, ...
    'peakAbsTrueOutput',max(abs(trueOutput)), ...
    'peakAbsMeasuredOutput',max(abs(measuredOutput)), ...
    'peakAbsControlEffort',max(abs(controlEffort)), ...
    'finalTrueOutput',trueOutput(end), ...
    'finalMeasuredOutput',measuredOutput(end), ...
    'finalControlEffort',controlEffort(end), ...
    'closedLoopRatePerSec',closedLoopRatePerSec, ...
    'characteristicRatePerSec',characteristicRatePerSec, ...
    'maxDimensionlessStep',maxDimensionlessStep, ...
    'maxInterval',maxInterval, ...
    'sampleCount',sampleCount);
end

function rate = stateRate(time,trueOutput,feedbackGain, ...
    disturbanceAmplitude,disturbanceFrequencyRadPerSec,sensorBias, ...
    disturbanceStartSec,plantTimeConstantSec)
if time < disturbanceStartSec
    disturbance = 0;
    bias = 0;
elseif disturbanceFrequencyRadPerSec == 0
    disturbance = disturbanceAmplitude;
    bias = sensorBias;
else
    disturbance = disturbanceAmplitude*sin( ...
        disturbanceFrequencyRadPerSec*(time-disturbanceStartSec));
    bias = sensorBias;
end
measuredOutput = trueOutput+bias;
controlEffort = -feedbackGain*measuredOutput;
rate = (-trueOutput+controlEffort+disturbance)/plantTimeConstantSec;
end
