function run_checks
%RUN_CHECKS Independent disturbance identities, limits, failure, and recovery.
tolerance = 5e-10;

baselineA = model(4,1,0,0,12,0.01);
baselineB = model(4,1,0,0,12,0.01);
assert(isequaln(baselineA,baselineB), ...
    'Identical inputs must produce identical time and frequency outputs.');
assert(all(baselineA.trueOutput(baselineA.t <= 1) == 0) && ...
    baselineA.disturbanceInput(1) == 0 && ...
    baselineA.controlEffort(1) == 0, ...
    'The baseline must remain at rest until the disturbance begins.');

plantResidual = baselineA.stateDerivativePerSec-( ...
    -baselineA.trueOutput+baselineA.controlEffort+ ...
    baselineA.disturbanceInput)/baselineA.plantTimeConstantSec;
assert(max(abs(plantResidual)) < tolerance, ...
    'Every reported sample must satisfy tau*y first=-y+u+d.');
assert(max(abs(baselineA.measuredOutput-(baselineA.trueOutput+ ...
    baselineA.sensorBiasSignal))) < tolerance, ...
    'Measured output must equal true output plus sensor bias.');
assert(max(abs(baselineA.controlEffort+ ...
    baselineA.feedbackGain*baselineA.measuredOutput)) < tolerance, ...
    'Control effort must be negative gain times measured output.');

expectedOpenMagnitude = 1./sqrt(1+baselineA.omegaRadPerSec.^2);
expectedClosedMagnitude = 1./sqrt(25+baselineA.omegaRadPerSec.^2);
assert(max(abs(baselineA.openLoopDisturbanceMagnitude- ...
    expectedOpenMagnitude)) < tolerance && ...
    max(abs(baselineA.closedLoopDisturbanceMagnitude- ...
    expectedClosedMagnitude)) < tolerance, ...
    'Frequency arrays must equal the independently expanded plant factors.');
assert(abs(baselineA.feedbackRejectionRatio-0.2) < tolerance && ...
    abs(baselineA.additionalAttenuationDb-20*log10(5)) < tolerance, ...
    'The DC feedback ratio must be 1/(1+K).');
assert(abs(baselineA.stepTrueOutput-0.2) < tolerance && ...
    abs(baselineA.stepMeasuredOutput-0.2) < tolerance && ...
    abs(baselineA.stepControlEffort+0.8) < tolerance && ...
    abs(baselineA.closedLoopTimeConstantSec-0.2) < tolerance, ...
    'The baseline must satisfy exact constant-load equilibrium identities.');

expectedStepOutput = zeros(size(baselineA.t));
afterStart = baselineA.t > baselineA.disturbanceStartSec;
expectedStepOutput(afterStart) = 0.2*(1-exp( ...
    -5*(baselineA.t(afterStart)-baselineA.disturbanceStartSec)));
assert(max(abs(baselineA.trueOutput-expectedStepOutput)) < 2e-7, ...
    'RK4 must match the independent closed-form step trajectory.');

noFeedback = model(0,1,0,0,8,0.01);
lowGain = model(1,1,0,0,8,0.01);
highGain = model(9,1,0,0,8,0.005);
assert(noFeedback.stepTrueOutput == 1 && ...
    lowGain.stepTrueOutput == 0.5 && ...
    highGain.stepTrueOutput == 0.1, ...
    'The gain sweep must preserve exact 1/(1+K) constant-load offsets.');
assert(noFeedback.closedLoopTimeConstantSec > ...
    lowGain.closedLoopTimeConstantSec && ...
    lowGain.closedLoopTimeConstantSec > ...
    highGain.closedLoopTimeConstantSec, ...
    'Moving only gain upward must shorten the loop time constant.');
assert(abs(noFeedback.stepControlEffort) < tolerance && ...
    abs(lowGain.stepControlEffort) < abs(highGain.stepControlEffort), ...
    'Moving only gain upward must spend more steady opposing effort.');
assert(noFeedback.disturbanceAmplitude == highGain.disturbanceAmplitude && ...
    noFeedback.disturbanceFrequencyRadPerSec == ...
    highGain.disturbanceFrequencyRadPerSec && ...
    noFeedback.sensorBias == highGain.sensorBias, ...
    'The gain sweep must preserve load amplitude, frequency, and location.');

slowLoad = model(4,1,0.2,0,16,0.005);
mediumLoad = model(4,1,1,0,16,0.005);
fastLoad = model(4,1,15,0,16,0.005);
assert(slowLoad.theoreticalOutputAmplitude > ...
    mediumLoad.theoreticalOutputAmplitude && ...
    mediumLoad.theoreticalOutputAmplitude > ...
    fastLoad.theoreticalOutputAmplitude, ...
    'Moving only frequency upward must reduce absolute plant output amplitude.');
assert(slowLoad.feedbackRejectionRatio < ...
    mediumLoad.feedbackRejectionRatio && ...
    mediumLoad.feedbackRejectionRatio < fastLoad.feedbackRejectionRatio, ...
    'Feedback additional rejection must weaken toward high frequency.');
assert(slowLoad.feedbackGain == fastLoad.feedbackGain && ...
    slowLoad.disturbanceAmplitude == fastLoad.disturbanceAmplitude && ...
    slowLoad.sensorBias == fastLoad.sensorBias, ...
    'The frequency sweep must preserve gain, load amplitude, and sensor honesty.');
expectedFastAmplitude = 1/sqrt(25+15^2);
expectedFastRatio = sqrt(1+15^2)/sqrt(25+15^2);
assert(abs(fastLoad.theoreticalOutputAmplitude-expectedFastAmplitude) < ...
    tolerance && abs(fastLoad.feedbackRejectionRatio-expectedFastRatio) < ...
    tolerance, ...
    'The high-frequency case must retain independent amplitude and ratio values.');

sineBehavior = model(4,1,1,0,4,0.005);
sineElapsed = sineBehavior.t-sineBehavior.disturbanceStartSec;
sineActive = sineElapsed >= 0;
expectedSineOutput = zeros(size(sineBehavior.t));
expectedSineOutput(sineActive) = ( ...
    5*sin(sineElapsed(sineActive))-cos(sineElapsed(sineActive))+ ...
    exp(-5*sineElapsed(sineActive)))/26;
assert(max(abs(sineBehavior.trueOutput-expectedSineOutput)) < 1e-9, ...
    ['The sinusoidal time history must match the independent transient ' ...
    'solution, not only its frequency metrics.']);

zeroAmplitude = model(4,0,3,0,4,0.01);
negativeLoad = model(4,-1,0,0,8,0.01);
assert(all(zeroAmplitude.trueOutput == 0) && ...
    zeroAmplitude.theoreticalOutputAmplitude == 0 && ...
    abs(zeroAmplitude.feedbackRejectionRatio- ...
    sqrt(10)/sqrt(34)) < tolerance, ...
    'Zero load must leave zero output while the system rejection ratio stays defined.');
assert(abs(negativeLoad.stepTrueOutput+0.2) < tolerance && ...
    negativeLoad.finalTrueOutput < 0, ...
    'A negative constant load must reverse the output and effort directions.');
assert(max(abs(noFeedback.closedLoopDisturbanceMagnitude- ...
    noFeedback.openLoopDisturbanceMagnitude)) < tolerance && ...
    noFeedback.feedbackRejectionRatio == 1, ...
    'Zero feedback is the exact open-loop limiting case.');

broken = model(9,0,0,0.5,8,0.005);
recovered = model(9,0,0,0,8,0.005);
assert(abs(broken.stepTrueOutput+0.45) < tolerance && ...
    abs(broken.stepMeasuredOutput-0.05) < tolerance && ...
    abs(broken.stepControlEffort+0.45) < tolerance, ...
    'Sensor bias must create large true motion while measured error looks small.');
assert(abs(broken.finalTrueOutput-broken.stepTrueOutput) < 1e-6 && ...
    abs(broken.finalMeasuredOutput-broken.stepMeasuredOutput) < 1e-6, ...
    'The broken trajectory must approach its independently derived equilibrium.');
assert(all(recovered.trueOutput == 0) && ...
    all(recovered.measuredOutput == 0) && ...
    all(recovered.controlEffort == 0), ...
    'Removing validated sensor bias must recover the zero-output condition.');
largeGainBias = model(20,0,0,0.5,4,0.004);
assert(abs(largeGainBias.biasTrueOffset) > abs(broken.biasTrueOffset) && ...
    abs(largeGainBias.biasMeasuredOffset) < ...
    abs(broken.biasMeasuredOffset), ...
    'More gain must worsen hidden true motion while shrinking biased measurement.');

assertAnyError(@() model(NaN,1,0,0,12,0.01), ...
    'A nonfinite gain must be rejected.');
assertAnyError(@() model(4,Inf,0,0,12,0.01), ...
    'A nonfinite disturbance amplitude must be rejected.');
assertAnyError(@() model(4,1,0,0,[10 12],0.01), ...
    'A nonscalar duration must be rejected.');
assertAnyError(@() model(-1,1,0,0,12,0.01), ...
    'A negative gain must be rejected.');
assertAnyError(@() model(4,1,-1,0,12,0.01), ...
    'A negative disturbance frequency must be rejected.');
assertAnyError(@() model(4,1,0,0,0,0.01), ...
    'A nonpositive duration must be rejected.');
assertAnyError(@() model(4,1,0,0,12,0), ...
    'A nonpositive interval must be rejected.');
assertErrorId(@() model(21,1,0,0,2,0.004), ...
    'P08:FeedbackGainRange','Excessive feedback gain must be rejected.');
assertErrorId(@() model(4,10.1,0,0,2,0.01), ...
    'P08:DisturbanceAmplitudeRange','Excessive load amplitude must be rejected.');
assertErrorId(@() model(4,1,40.1,0,2,0.002), ...
    'P08:DisturbanceFrequencyRange','Excessive load frequency must be rejected.');
assertErrorId(@() model(4,1,0,10.1,2,0.01), ...
    'P08:SensorBiasRange','Excessive sensor bias must be rejected.');
assertErrorId(@() model(4,1,0,0,60.1,0.01), ...
    'P08:HorizonRange','Excessive horizon must be rejected.');
assertErrorId(@() model(4,1,0,0,2,0.03), ...
    'P08:TimeResolution','An under-resolved loop request must be rejected.');
assertErrorId(@() model(20,0,0,10,3,0.004), ...
    'P08:ResponseBound','An excessive biased response must be bounded.');

acceptedResolution = model(20,1,0,0,2,0.004);
assert(acceptedResolution.characteristicRatePerSec* ...
    acceptedResolution.maxInterval <= ...
    acceptedResolution.maxDimensionlessStep+1e-12 && ...
    all(isfinite(acceptedResolution.trueOutput)), ...
    'A resolved upper-rate request must retain finite samples.');
coarse = model(4,1,0,0,4,0.01);
fine = model(4,1,0,0,4,0.005);
assert(abs(coarse.finalTrueOutput-fine.finalTrueOutput) < 1e-7, ...
    'Halving a resolved RK4 interval must preserve the endpoint response.');
crossingGrid = model(4,1,0,0,1.008,0.018);
expectedCrossingOutput = 0.2*(1-exp(-5*0.008));
assert(all(crossingGrid.trueOutput(crossingGrid.t <= 1) == 0) && ...
    abs(crossingGrid.finalTrueOutput-expectedCrossingOutput) < 1e-6, ...
    'A grid crossing disturbance onset must split the event and preserve timing.');
nonIntegerGrid = model(4,1,0,0,1.033,0.01);
assert(all(diff(nonIntegerGrid.t) > 0) && ...
    nonIntegerGrid.t(end) == 1.033 && ...
    nonIntegerGrid.maxInterval <= 0.01+eps, ...
    'A noninteger interval ratio must append one strictly increasing endpoint.');
shortHorizon = model(4,1,0,0,0.02,0.05);
assert(shortHorizon.sampleCount == 2 && ...
    abs(shortHorizon.maxInterval-0.02) < tolerance && ...
    all(shortHorizon.trueOutput == 0), ...
    'A clipped pre-disturbance horizon must report its actual interval.');
atResourceLimit = model(0,0,0,0,20,0.001);
assert(atResourceLimit.sampleCount == 20001, ...
    'The declared maximum calculation grid must remain accepted.');
assertErrorId(@() model(0,0,0,0,20.001,0.001), ...
    'P08:TooManySamples','An excessive calculation grid must be rejected.');

disp(['P08 checks passed: disturbance paths, levers, limits, bias recovery, ' ...
    'and bounds.']);
end

function assertAnyError(operation,message)
didError = false;
try
    operation();
catch
    didError = true;
end
assert(didError,message);
end

function assertErrorId(operation,expectedIdentifier,message)
actualIdentifier = '';
try
    operation();
catch exception
    actualIdentifier = exception.identifier;
end
assert(strcmp(actualIdentifier,expectedIdentifier),message);
end
