function run_checks
%RUN_CHECKS Independent pole, motion, limit, and input checks for P03.
tolerance = 2e-11;

baselineA = model(-0.5,2,1,0,12,0.01);
baselineB = model(-0.5,2,1,0,12,0.01);
assert(isequaln(baselineA,baselineB), ...
    'Identical inputs must produce identical deterministic outputs.');
assert(abs(baselineA.position(1)-1) < tolerance && ...
    abs(baselineA.velocity(1)) < tolerance, ...
    'The exact response must preserve both initial conditions.');
assert(max(abs(baselineA.position)-baselineA.envelope) < tolerance, ...
    'Motion must remain inside the analytic exponential envelope.');

poleResidual = baselineA.poles.^2 - ...
    2*baselineA.poleReal*baselineA.poles + ...
    baselineA.naturalFrequency^2;
assert(max(abs(poleResidual)) < tolerance, ...
    'Both reported poles must satisfy the governing characteristic equation.');
assert(max(abs(baselineA.acceleration - ...
    (2*baselineA.poleReal*baselineA.velocity - ...
    baselineA.naturalFrequency^2*baselineA.position))) < tolerance, ...
    'Acceleration must independently satisfy the second-order equation.');
assert(all(diff(baselineA.energy) <= tolerance), ...
    'Left-half-plane motion must not gain unit-mass mechanical energy.');

onePeriod = model(-0.5,2,1,0,pi,pi/1000);
expectedScale = exp(-0.5*pi);
assert(abs(onePeriod.position(end)-expectedScale) < tolerance && ...
    abs(onePeriod.velocity(end)) < tolerance, ...
    'After one period, the state must repeat scaled by exp(sigma*T).');
assert(abs(baselineA.oscillationPeriod-pi) < tolerance, ...
    'omega=2 rad/s must independently give a pi-second period.');
assert(abs(baselineA.envelopeTimeConstant-2) < tolerance, ...
    'sigma=-0.5 1/s must independently give a two-second envelope constant.');

phaseCase = model(-0.5,2,1.25,-0.75,pi/4,pi/4000);
expectedPhaseScale = exp(-pi/8);
expectedQuarterPosition = -0.0625*expectedPhaseScale;
expectedQuarterVelocity = -2.46875*expectedPhaseScale;
assert(abs(phaseCase.position(1)-1.25) < tolerance && ...
    abs(phaseCase.velocity(1)+0.75) < tolerance, ...
    'An oscillatory response must preserve a nonzero initial velocity.');
assert(abs(phaseCase.position(end)-expectedQuarterPosition) < tolerance && ...
    abs(phaseCase.velocity(end)-expectedQuarterVelocity) < tolerance, ...
    'A quarter-cycle state must reflect the initial-condition phase coefficient.');

fastDecay = model(-1,2,1,0,12,0.01);
slowDecay = model(-0.2,2,1,0,12,0.01);
assert(abs(fastDecay.oscillationPeriod-slowDecay.oscillationPeriod) < tolerance, ...
    'Changing only pole real part must preserve cycle spacing.');
assert(fastDecay.exponentialScaleRatio < slowDecay.exponentialScaleRatio, ...
    'A more-negative real part must shrink the envelope faster.');
slowOscillation = model(-0.5,1,1,0,12,0.01);
fastOscillation = model(-0.5,4,1,0,12,0.01);
assert(fastOscillation.oscillationPeriod < slowOscillation.oscillationPeriod, ...
    'A larger imaginary magnitude must shorten the oscillation period.');
assert(abs(fastOscillation.exponentialScaleRatio- ...
    slowOscillation.exponentialScaleRatio) < tolerance, ...
    'Changing only imaginary magnitude must preserve envelope decay ratio.');

marginal = model(0,2,1,0,4*pi,pi/1000);
assert(max(abs(marginal.envelope-marginal.envelope(1))) < tolerance, ...
    'Imaginary-axis poles must preserve their motion envelope.');
assert(max(abs(marginal.energy-marginal.energy(1))) < tolerance, ...
    'Undamped unit-mass motion must conserve mechanical energy.');
repeated = model(-0.5,0,1,0,2,0.01);
expectedRepeatedFinal = 2*exp(-1);
assert(abs(repeated.position(end)-expectedRepeatedFinal) < tolerance && ...
    isinf(repeated.oscillationPeriod), ...
    'The zero-imaginary limiting case must match the repeated-pole solution.');
doubleZero = model(0,0,1,3,4,0.01);
assert(abs(doubleZero.position(end)-13) < tolerance && ...
    abs(doubleZero.velocity(end)-3) < tolerance, ...
    'Two zero poles must recover the constant-velocity integrator limit from P02.');
zeroState = model(-0.5,2,0,0,12,0.01);
assert(all(zeroState.position == 0) && all(zeroState.velocity == 0), ...
    'Zero initial state must remain a zero-motion limiting case.');

broken = model(0.25,2,1,0,12,0.01);
recovered = model(-0.25,2,1,0,12,0.01);
assert(all(real(broken.poles) > 0) && broken.exponentialScaleRatio > 20, ...
    'The broken case must place both poles in the right half-plane and grow.');
assert(all(diff(broken.energy) >= -tolerance) && ...
    broken.finalEnergy > broken.initialEnergy, ...
    'Right-half-plane motion must show outward energy growth.');
assert(all(real(recovered.poles) < 0) && ...
    abs(recovered.exponentialScaleRatio-exp(-3)) < tolerance && ...
    recovered.exponentialScaleRatio < 0.1, ...
    'Restoring the same poles to the left half-plane must recover decay.');

assertAnyError(@() model(NaN,2,1,0,12,0.01), ...
    'A nonfinite real part must be rejected.');
assertAnyError(@() model(-0.5,Inf,1,0,12,0.01), ...
    'A nonfinite imaginary magnitude must be rejected.');
assertAnyError(@() model(-0.5,-1,1,0,12,0.01), ...
    'A negative imaginary magnitude must be rejected.');
assertAnyError(@() model(-0.5,2,1+1i,0,12,0.01), ...
    'A nonreal initial position must be rejected.');
assertAnyError(@() model(-0.5,2,1,Inf,12,0.01), ...
    'A nonfinite initial velocity must be rejected.');
assertAnyError(@() model(-0.5,2,1,[0 1],12,0.01), ...
    'A nonscalar initial velocity must be rejected.');
assertAnyError(@() model([-0.5 -1],2,1,0,12,0.01), ...
    'A nonscalar real part must be rejected.');
assertAnyError(@() model(-0.5,2,1,0,0,0.01), ...
    'A nonpositive duration must be rejected.');
assertAnyError(@() model(-0.5,2,1,0,12,0), ...
    'A nonpositive interval must be rejected.');
assertErrorId(@() model(100,2,1,0,4,0.01), ...
    'P03:ExponentRange','An excessive exponential range must be rejected.');
assertErrorId(@() model(-100,2,1,0,4,0.01), ...
    'P03:ExponentRange','Excessive exponential underflow must be rejected.');
assertErrorId(@() model(-0.5,2,realmax,0,1,0.01), ...
    'P03:NonfiniteOutput','A state that overflows energy must be rejected.');

nonIntegerGrid = model(-0.5,2,1,0,0.033,0.011);
assert(nonIntegerGrid.sampleCount == 4 && ...
    all(diff(nonIntegerGrid.t) > 0) && nonIntegerGrid.t(end) == 0.033, ...
    'An integer interval ratio must not create a duplicate final timestamp.');
shortHorizon = model(-0.5,2,1,0,0.5,2);
assert(shortHorizon.sampleCount == 2 && ...
    abs(shortHorizon.maxInterval-0.5) < tolerance, ...
    'A clipped endpoint interval must report the interval actually used.');
atResourceLimit = model(-0.5,2,1,0,20,0.001);
assert(atResourceLimit.sampleCount == 20001, ...
    'The declared maximum calculation grid must remain accepted.');
assertErrorId(@() model(-0.5,2,1,0,100,0.001), ...
    'P03:TooManySamples','An excessive calculation grid must be rejected.');

disp('P03 checks passed: pole invariants, limits, levers, broken recovery, and input bounds.');
end

function assertAnyError(operation,message)
didError = false;
try
    operation();
catch
    didError = true;
end
assert(didError,message);
end

function assertErrorId(operation,expectedIdentifier,message)
actualIdentifier = '';
try
    operation();
catch exception
    actualIdentifier = exception.identifier;
end
assert(strcmp(actualIdentifier,expectedIdentifier),message);
end
